### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by rogah** [jsforce/jsforce#1]
How can I setup a HTTP proxy to access the salesforce login url from within a company organization? I'm currently getting the following:

_Error: connect ETIMEDOUT_

Example:

```
var jsforce = require('jsforce');
var conn = new jsforce.Connection({
    proxy: 'http://proxy_ur:port'
});
```

**Comment by jayfresh** [comment]
:+1: for releasing an update to npm :)
