### ISSUE TITLE
INVALID_SESSION_ID Error

### ISSUE THREAD

**Issue by handlerda** [jsforce/jsforce#1003]
I am building an SFDC backend express application using JSForce. When making SOQL queries I am getting a INVALID_SESSION_ID error.

I can authenticate using oauth2 without any issues.
I have access to accessToken, URI info, refreshToken information. They are stored in req.session.
I have relaxed all IP settings in my custom app and ensured I have API access in my profile.
I am able to execute the REST API request using Workbench.
Is anyone else experiencing this error?

`
const express = require("express");
const router = express.Router();
const oauth2 = require("../jsforce/jsforce");
const jsforce = require("jsforce");

router.get("/", function (req, res) {
  // if no authentication, redirect to index
  if (!req.session.accessToken || !req.session.instanceUrl) {
    console.log("not authenticated must redirect");
    res.redirect("/auth");
  }

  //sample SOQL Query
  let q = "SELECT Id, Name FROM account LIMIT 10";

  //init new connection
  let conn = new jsforce.Connection({
    oauth2: { oauth2 },
    accessToken: req.session.accessToken,
    instanceUrl: req.session.instanceUrl,
  });

  let records = [];
  let query = conn
    .query(q)
    .on("record", function (record) {
      records.push(record);
    })
    .on("end", function () {
      console.log("total in database : " + query.totalSize);
      console.log("total fetched : " + query.totalFetched);
      res.json(records);
    })
    .on("error", function (err) {
      console.error(err);
      res.json({
        "err status": err.name,
        "err message": err.message,
      });
    })
    .run({ autoFetch: true, maxFetch: 4000 });
});

module.exports = router;

**Comment by kharatps02** [comment]
Check whether access token and instance are valid or not?
