### ISSUE TITLE
Best practice to store Refresh token and access token

### ISSUE THREAD

**Issue by bhuvaneswary** [jsforce/jsforce#1004]
I am new to jsforce
I am trying to set up access/refresh token flow as per the document.
Refresh token and access token is getting generated successfully and able to use them to subscribe platform events. How to ensure I have valid connection through out my application since I have to use the connection object for multiple actions like subscribing platform events sending email task etc.

I have added script like this

		createConn(): Promise<any> {
			try {
			  var conn = new jsforce.Connection({
				oauth2 : {
				  clientId : <SF_CLIENT_ID>,
				  clientSecret : <SF_CLIENT_SECRET_ID>,
				  redirectUri : <SF_REDIRECT_URL>
				},
				instanceUrl : <SF_INSTANCE_URL>,
				accessToken : <SF_ACCESS_TOKEN>,
				refreshToken : <SF_REFRESH_TOKEN>
			  });
			  conn.on("refresh", function(accessToken, res) {
				console.log('Access token refreshed');
				// Refresh event will be fired when renewed access token
				// to store it in your storage for next request
		});
               logger.info('Connection to salesforce established successfully');
               return conn;
         }
When and how jsforce will execute conn.on("refresh", function(accessToken, res)  to refresh accesstoken?
What is best practice to store tokens for next use?
Do we need to make sure we have valid connection? Because it is not throwing any exception when I just use connection object with invalid tokens. 
Can you please help me on these?
@stomita
Thanks in Advance!

**Comment by bhuvaneswary** [comment]
refresh is happening when I do sobject query.
For testing purpose I just added below code:
`let conn: Connection ;
try {

  let oauth2 = new jsforce.OAuth2({
    loginUrl : process.env.SF_LOGIN_URL,
    clientId : process.env.SF_CLIENT_ID,
    clientSecret : process.env.SF_CLIENT_SECRET_ID,
    redirectUri : 'http://localhost:3000/getAccessToken'
  });
  app.get('/oauth2/auth', function(req, res) {
    res.redirect(oauth2.getAuthorizationUrl({ scope : 'api id web refresh_token' }));
  });

  app.get('/getAccessToken', function(req, res) {
    conn = new jsforce.Connection({ oauth2 : oauth2 });
    const code = req.param('code');
    conn.authorize(code, function(err, userInfo) {
      if (err) { return console.error(err); }
      // Save them to establish connection next time.
      logger.info(conn.accessToken);
      logger.info(conn.instanceUrl);
      logger.info(conn.refreshToken);
      logger.info("User ID: " + userInfo.id);
      logger.info("Org ID: " + userInfo.organizationId);
      res.send('success');

      conn.on("refresh", function(accessToken, res) {
        logger.info('New accessToken');
        // Refresh event will be fired when renewed access token
        // to store it in your storage for next request
      });
    });
    
  });

  app.get('/query', async function(req, res) {
    if(conn){
      logger.info(conn.accessToken);
      const recs = conn.sobject('Opportunity').find({
        Id: '0060p000005F0kHAAS'
      });
      for (const rec of await recs) {
        console.log(rec.Id);
      }
    }
    res.send('success');
  });
 } catch (error) {
  logger.error(error.message);
}`

Here after I revoke the accesstoken and try to hit http://localhost:3000/query refresh is happening.

So is there any limitation in streaming api? We are stuck with the implementation.
@stomita can you please help me on this?

**Comment by favio41** [comment]
This ticket contains a little more information about the auth flow: [https://github.com/jsforce/jsforce/issues/824](https://github.com/jsforce/jsforce/issues/824)
By that answer, the whole accessToken is managed by JSForce, and you only have to worry about invalidation of refreshToken.
