### ISSUE TITLE
allOrNone is not a supported option under RestApiOptions

### ISSUE THREAD

**Issue by AnanyaJha** [jsforce/jsforce#1005]
I'm trying to use the tooling api to create records in bulk with the following code 
`myConnection.tooling.update('AuraDefinition', listOfRecordsToUpdate)`

from the documentation, it looks like I should be able to specify the `allOrNone` option to ensure that all records are rolled back once an error is found as such: 

`myConnection.tooling.update('AuraDefinition', listOfRecordsToUpdate, {allOrNone: true})`

but I keep getting the following error: 
`(property) allOrNone: boolean
Argument of type '{ allOrNone: boolean; }' is not assignable to parameter of type 'RestApiOptions'.
  Object literal may only specify known properties, and 'allOrNone' does not exist in type 'RestApiOptions' `

Is this option no longer supported?

**Comment by bhuvaneswary** [comment]
Have you got this fixed? I am facing same issue.

**Comment by AnanyaJha** [comment]
Nope, haven’t gotten a solution yet

**Comment by tx-paola** [comment]
maybe a PR would be good I'm having the issue when trying to pass `allowRecursive: true`

**Comment by jonathanwiesel** [comment]
If you're referring to the typescript definitions, it has been contributed and updated DefinitelyTyped/DefinitelyTyped/pull/48101

**Comment by lms15** [comment]
Ok thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cristiand391** [comment]
triaging old issues...

types in jsforce v3 are correct for this ✅

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
