### ISSUE TITLE
Unable to create "Task" for an "Account"

### ISSUE THREAD

**Issue by DiptimanBadajena** [jsforce/jsforce#1006]
I'm trying to create task "Contact", "Lead" and "Account" using `jsforce@1.9.3`. Tasks for "Contact" and "Lead" works fine; however, for "Account" it fails with following error message:
```
      "errors": [
        {
          "fields": [
            "WhoId"
          ],
          "message": "Name ID: id value of incorrect type: 0015w000029KTYHAA4",
          "statusCode": "FIELD_INTEGRITY_EXCEPTION"
        }
      ],
```

Sample code
```javascript
conn.sobject('Task').create({
          WhoId: <<account id>>,
          TaskSubtype: 'Task',
          Subject: 'Some name here',
          Description: <<some url here>>
        },{},function(err, ret) {
          if (err || !ret.success) {
            return console.error(err, ret);
          }
          console.log('Updated Successfully : ', ret);
          // ...
        });
```

**Comment by cristiand391** [comment]
triaging old issues...

docs says `WhoId` represents a human such as a lead or a contact, you ƒor accounts you need to pass `WhatId`:

> The WhatId represents nonhuman objects such as accounts, opportunities, campaigns, cases, or custom objects.

https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_task.htm
