### ISSUE TITLE
Faye library needs update

### ISSUE THREAD

**Issue by MattBrooke30** [jsforce/jsforce#1009]
Hi,

According to Snyk, the version of Faye currently used by jsforce has a vulnerability: https://app.snyk.io/vuln/SNYK-JS-FAYE-567757

Latest version of Faye appears to just include the security update, so it should be an easy fix.

Thanks!

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
