### ISSUE TITLE
When will the Bulk API V2 be supported?

### ISSUE THREAD

**Issue by s4mli** [jsforce/jsforce#1014]
- Background
At the moment, I believe JSForce is always on bulk API v1 regardless which version has been specified when constructing a connection.
And yes, we actually can use `connection.request()` to hit the RESTful endpoint.

- Why
But given Bulk API v2 is asking for a local text/csv file, this doesn't fit serverless architecture.
It would be more handy that JSForce can add some sort of abstractions to support both bulk api v1 and v2, so developers can use the same bulk object to load data, via a stream for instance, consistently and transparently.

**Comment by khjuan** [comment]
+1 for Bulk API v2 support. Just ran into a use-case need to query MetadataComponentDependency.

**Comment by davidbrowaeys** [comment]
Yeah definitely +1 here

**Comment by nvuillam** [comment]
+1 here too :)

**Comment by jmsfez** [comment]
+= 1 🤪

**Comment by gdemarcosSFDC** [comment]
+1

**Comment by steakin** [comment]
+1 :)

**Comment by colincasey** [comment]
is anyone actively working on this?  if not, my team needs Bulk API V2 support in jsforce and would be interested in adding it.

**Comment by Asafkbalink** [comment]
+1. Is this being worked on?

**Comment by colincasey** [comment]
@Asafkbalink #1251 was merged into the [jsforce:2.0](https://github.com/jsforce/jsforce/tree/2.0) branch

**Comment by jacobrr** [comment]
Hi all! great work!! any idea or estimation of when will be in a stable version?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
