### ISSUE TITLE
Creating ContentVersion error "No such column 'type' ..."

### ISSUE THREAD

**Issue by grjkz** [jsforce/jsforce#1016]
`INVALID_FIELD: No such column 'type' on sobject of type ContentVersion`

I'm getting the above error when attempting to upload a document/file from my local computer using the following code:

`conn.sobject('ContentVersion').create({
    'Title': fileName,
    'VersionData': fileBuffer,
    'FirstPublishLocationId': entityId,
    'IsLatest': true,
    'PathOnClient': fileName,
    'IsMajorVersion': true
  }, function(err, res) {
    console.log('err', err);
    console.log('res', res);
    if (err || !res.success) {
      return err;
    }
    return res;
  });`

As you can see, I never used the field `type` in my map. I did a describe on the object and it didn't return any field with the name `type`. I don't know what's causing the issue.

**Comment by sumitk39** [comment]
I'm also getting the same error, while creating ContentVersion record from Integromat scenario using "Create a record in an object" module. I'm not querying any field name called "type" in contentVersion object and can't see any field with name/api name as "type".
![1](https://user-images.githubusercontent.com/24607835/93967262-72196a00-fd84-11ea-9363-1e466ff40b6c.PNG)
![2](https://user-images.githubusercontent.com/24607835/93967275-7a71a500-fd84-11ea-95ce-95aa4578f7e0.PNG)
![3](https://user-images.githubusercontent.com/24607835/93967289-82314980-fd84-11ea-994b-10c00fad0336.PNG)

**Comment by kkarkos** [comment]
I got the same error for uploading `sf.conn.sobject("Attachment").create ` - depending on how you handle your data (e.g. form-data) you might have to create a base64 buffer `fileBuffer = Buffer.from(yourdata).toString("base64")` before you pass it it the `Attachment.Body` or in your case `VersionData`.

**Comment by messified** [comment]
> I got the same error for uploading `sf.conn.sobject("Attachment").create ` - depending on how you handle your data (e.g. form-data) you might have to create a base64 buffer `fileBuffer = Buffer.from(yourdata).toString("base64")` before you pass it it the `Attachment.Body` or in your case `VersionData`.

@kkarkos Thank you! `Buffer.from(yourdata).toString("base64")` worked for me

**Comment by vinaykumar612** [comment]
Hi All,

Its throwing INVALID_FIELD: No such column 'ContentData' on sobject of type FeedItem

But in Metadata I'm having the ContentData field of type base 64.

Can you please help me to resolve this.

Same is column getting inserted using other integration technology.(TIBCO)
```js
const regularfeedItem = {
          ParentId: Id,
          Body: `${InternalNotes.trim().length > 10000
            ? InternalNotes.trim().substr(0, 10000) : InternalNotes}`,
          ContentData: InternalNotes.length > 0 ? Buffer.from(InternalNotes.substr(0, 10000 + 1)).toString('base64') : '',
          ContentFileName: InternalNotes.length > 0
            ? `${serviceRequestor.concat('-').concat(CaseNumber)
              .concat('-').concat(moment().format('MMDDYYYYHHmmss')).concat('.txt')}` : '',
          Visibility: 'AllUsers',
 };
const feedres = await conn.sobject('FeedItem').create(regularfeedItem);
```

**Comment by cristiand391** [comment]
triaging old issues...

this is the suggested solution:
https://github.com/jsforce/jsforce/issues/1016#issuecomment-768019861

you should always check the docs for the object, most mention they expect a base64-encoded content.
