### ISSUE TITLE
Limit of records in set in Bulk API

### ISSUE THREAD

**Issue by tx-paola** [jsforce/jsforce#1017]
Is there a maximum of records in a set that Bulk API supports? Our goal is to insert 20'000 records.

**Comment by cristiand391** [comment]
triaging old issues...

20K records should be fine, docs for reference:
https://developer.salesforce.com/docs/atlas.en-us.250.0.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm
