### ISSUE TITLE
UNABLE_TO_LOCK_ROW unable to obtain exclusive access to this record or 1 records

### ISSUE THREAD

**Issue by justlester** [jsforce/jsforce#1018]
Hi! When I try to update a record in an object and at the same time someone also updates on it. This error will show. 

I found a solution adding "FOR UPDATE" in the query but this is applicable in apex class controller (refer:https://salesforce.stackexchange.com/questions/20921/can-anybody-explain-the-unable-to-lock-row-error)

Is there any workaround for this for jsForce? I didn't find in the documentation regarding to this when multiple users is accessing a record.

My current code is:
```
sfConn.sobject('My_Custom_Object__c')
.update({
                //fields to be updated
}).then((res)=>{
                //success
}).catch((err)=>{
               //error
});
```

Thanks!

**Comment by trueter** [comment]
What we do is keep retrying using Bluebird.retry until it succeeds, but I would also appreciate a better solution.

**Comment by sridh-ar** [comment]
I am facing the same issue. Did you find anything on how to do it from jsforce?

**Comment by trueter** [comment]
No. Retry is still your best bet.
You can try changing the automation inside your org to reduce post-update/insert side effects, but even then you might never be able to completely avoid the possibility of facing a locked row. While annoying, it's not an issue related to jsfoce, but inherent to the environment your developing in.

**Comment by vahahavronsky** [comment]
Hey, do you have an idea how to implement a retry on this error?
