### ISSUE TITLE
Support for Lightning Web Components (from JavaScript in a VF Page)

### ISSUE THREAD

**Issue by LWCGUY** [jsforce/jsforce#1021]
Wondering if you guys have support for Lightning Web Components from JS code. I tried describing **LightningComponentBundle** resource from JavaScript (from with-in a Visualforce Page), and I am getting this error :

**_NOT_FOUND: The requested resource does not exist_**

Wondering how can I correct this issue?

**Comment by paustint** [comment]
There are a couple of reasons why you might run into this:
1. your API version is not recent, LWC was introduced at some point and older api version would not have access
2. The core describe call does not support `LightningComponentBundle`, you will need to use `tooling.describe` to get this particular type

Also, you can use the metadata apis list/read to interact with `LightningComponentBundle`

**Comment by LWCGUY** [comment]
Thank a ton @paustint - you are the savior -**_Thank You  Sir!._** I can now proceed with my work, appreciate  your prompt guidance.
