### ISSUE TITLE
sharingModel for sobject in describe call

### ISSUE THREAD

**Issue by tanumaydas** [jsforce/jsforce#1022]
Hi There, i need to use the sharingModel of a Sobject but cant find it in sobject.describe() or describe(sobject,func). Am i doing something silly or it is indeed not supported

Regards
Tanumay (A fan of jsforce)

**Comment by jon-freed** [comment]
Try the [Metadata API](https://jsforce.github.io/document/#metadata-api).  

Salesforce just doesn't have a simple, straightforward way of getting all the information about an SObject in one place.  For example, the following code will help you get each SObject's sharing model and fields, but it won't get you every field's type. 

After you get a JSForce connection (e.g. "conn" below), then you can try the following code:

```
var metadataSObjectNames = ['Account', 'Contact', 'Quote'];
conn.metadata.read('CustomObject', metadataSObjectNames, function(err, metadata) {
    if (err) {
        console.error(err);
    }
    for (var i = 0; i < metadata.length; i++) {
        console.log('\nFull Name: ' + metadata[i].fullName);
        console.log('Sharing Model: ' + metadata[i].sharingModel);
        console.log('Fields count: ' + metadata[i].fields.length);
        console.log('Fields: ' + JSON.stringify(metadata[i].fields,null,4));
        // types include Lookup (e.g. for Contact.AccountId) and MasterDetail (e.g. for Quote.AccountId),
        // but when the field is a standard field, other type info is missing.  E.g. for Contact.Title field
    }
});
```
