### ISSUE TITLE
Inserting a new record with related objects in one request

### ISSUE THREAD

**Issue by jgmullor** [jsforce/jsforce#1031]
Hello!!

I was trying to insert a new object related with another one already created, but I only know the External ID for the related one, is there any way I could call insert without making two calls? (Asking for ID for the related object and then inserting the new object).

I have found this comment (But it is using **upsert**): https://github.com/jsforce/jsforce/issues/673#issuecomment-373824396

Thank you!! :)

**Comment by paustint** [comment]
Insert/update/upsert should all work the same. This is a Salesforce feature, not a JSForce feature - so you can refer to the SFDC docs for examples.

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm

In addition, if for some reason you can't get the insert working, you should be able to specify an "upsert" and use "Id" of the record as the upsert id (External id) so that it will insert records every time.

**Comment by jgmullor** [comment]
Hi @paustint! Thank you for your reply. I found that article, but the ID I am trying to use is for the related object.

I have tried something like this, but I am getting a `JSON_PARSER_ERROR: Cannot deserialize instance of <unknown> from FIELD_NAME value type or request may be missing a required field`

```js
conn.sobject('leads__c').create({
    "Name":"John",
    "source__c":"test",
    "campaign__r":{
        "type":"campaign__c",
        "reference__c":"campn-summer-20-details"
    }
})
```

**Comment by paustint** [comment]
I just tried this on the JSforce console and it worked without problems.

```json
conn.sobject('Contact').create({
    "FirstName":"John",
    "LastName":"Smith",
    "Account":{
        "My_Ext_Id__c":"test-123"
    }
})
```

![image](https://user-images.githubusercontent.com/5461649/85414811-d16ba200-b529-11ea-9522-a2bbef4a9637.png)

![image](https://user-images.githubusercontent.com/5461649/85414883-e6483580-b529-11ea-86e3-fa3145babd1a.png)

**Comment by jgmullor** [comment]
Hello @paustint! Thank you again for your answer. :)
I have tried again and does not work, maybe it is only compatible with native Salesforce objects?

**Request 1:**
```js
conn.sobject('Request__c').create({
    "Development__c":{
        "External_Property_ID__c":"TAAD44"
    },
    "User__c":"0030X00002g2LCAQA2"
})
```
I get: `JSON_PARSER_ERROR: Cannot deserialize instance of reference from START_OBJECT value { or request may be missing a required field at [line:1, column:2]`.


**Request 2:**
```js
conn.sobject('Request__c').create({
    "Development__c":"a0O0X00000YKSxPUAX",
    "User__c":"0030X00002g2LCAQA2"
})
```
Request works: `{ id: 'a0Q0X00000HLTgfUAH', success: true, errors: [] }`

The field External_Property_ID__c is marked as an External ID for my `Development__c` object:

<img width="900" alt="Screenshot 2020-06-23 at 18 31 53" src="https://user-images.githubusercontent.com/1301633/85430062-eb37d400-b57f-11ea-847e-f5ae588d4fb6.png">

Thank you!

**Comment by jgmullor** [comment]
Okay... I found it, I was using the field (`Development__c`) instead of the relationship (`Development_r`), now it works as expected.

Many thanks @paustint =)
