### ISSUE TITLE
Refreshing Visualforce Session ID on INVALID_SESSION_ID error

### ISSUE THREAD

**Issue by justlester** [jsforce/jsforce#1033]
Hi! I have a Visualforce page that I use with JS force 
`var conn = new jsforce.Connection({ accessToken: '{!$API.Session_Id}' });`

After a long duration of API calls with JSforce, I got an error:
`{"name":"INVALID_SESSION_ID","errorCode":"INVALID_SESSION_ID"}`

I can't proceed to another API request and still need to refresh in order to log in and get another session id. 

Is there a way that I can get a new session id by not refreshing the visualforce page? 
Like refreshing access tokens. I can't find in the documentation about authenticating expired session ids.

A little help would be appreciated. Thanks!

**Comment by cristiand391** [comment]
triaging old issues...

for reference:
jsforce refreshes expired access tokens when using oauth:
https://jsforce.github.io/document/#access-token-with-refresh-token

`Connection` also takes a `refreshFn` function that you could use to set a new valid AT (if it's something you can do in visualforce:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html#__type.refreshFn
