### ISSUE TITLE
Important: Not able to authorize the code returned from the Salesforce either it is expired or invalid

### ISSUE THREAD

**Issue by shaharyar-shamshi** [jsforce/jsforce#1036]
I am using OAuth2 to authorize the user I generate the URL at the backend send the url to the frontend (which is in VUE ) which open it in the new window the callback url is one of the route of the frontend which collect the Code from the query param and send it to the Backend but when I Authorize it in the Backend it give error that code is invalid I am attaching my code sample for your reference . I will be highly thankful for the help

const oauth2 = new jsforce.OAuth2({
    clientId: salesforceCredentials.clientId,
    clientSecret: salesforceCredentials.clientSecret,
    redirectUri: 'http://localhost:8080/salesforceAuth',
});
/**
 * To get teh Authorization credetials for Salesforce
 * @param {*} req
 * @param {*} res
 */
async function getAuthorizationInfo(req, res) {
    const conn =
       new jsforce.Connection({ oauth2: oauth2 });
    const code = req.query.code;
    console.log(code)
    //console.log(req)
    conn.authorize(code, function (err, userInfo) {
        if (err) {
            console.log("hello word")
            return console.error(err);
        }
        console.log("hello word2")
        // Now you can get the access token, refresh token, and instance URL information.
        // Save them to establish connection next time.
        console.log(userInfo.state)
        console.log(conn.accessToken);
        console.log(conn.refreshToken);
        console.log(conn.instanceUrl);
        //console.log("User ID: " + userInfo.id);
        //console.log("Org ID: " + userInfo.organizationId);
        // ...
        res.send('success'); // or your desired response
    });
}
//
// Get authorization url and redirect to it.
//
router.get('/salesforce/oAuth2', function (req, res) {
    res.send(oauth2.getAuthorizationUrl({ scope: 'api' }));
});
router.get('/salesforce/oAuth2Response', getAuthorizationInfo)

**Comment by shaharyar-shamshi** [comment]
I will be highly Thankful for help

**Comment by shaharyar-shamshi** [comment]
@stomita can you kindly help me in it I will be highly thankful to you

**Comment by cristiand391** [comment]
triaging old issues...

Not sure how the oauth object was being created, if anyone finds a similar please open a new issue.
