### ISSUE TITLE
Unable to use bulk api

### ISSUE THREAD

**Issue by mpdeglau** [jsforce/jsforce#1037]
When I try to create a bulk job, I get the following error `TypeError: Cannot read property 'createJob' of undefined`.
```
const conn = new jsforce.Connection({
        // you can change loginUrl to connect to sandbox or prerelease env.
        loginUrl : 'https://test.salesforce.com'
});
conn.login(username, pw).then((userInfo)=>{
     const job = conn.bulk.createJob('Account', 'insert');
}).catch((ex)=>{console.log(ex)});
```

**Comment by lozdog** [comment]
Same. None of the Bulk-related methods seem to be working on the most recent version. They were all returning undefined. 
```
conn.bulk
conn.sobject().bulkload()
conn.sobject().insertBulk()
```
I tried downgrading to 1.9.3 and they work now. Spend way too many hours figuring that out!

**Comment by stomita** [comment]
Sorry it was my mistake the 2.0 alpha version was published as latest. I've fixed it.
