### ISSUE TITLE
Issue with JSForce Login - origin 'http://localhost:3001' has been blocked by CORS policy 

### ISSUE THREAD

**Issue by anilshivaraj** [jsforce/jsforce#1039]
When i try to use the username password flow to authenticate with a salesforce org, i get a CORS error 

`Access to XMLHttpRequest at 'https://login.salesforce.com/services/Soap/u/43.0' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have used a straight out lwc.dev code and added the authentication piece of code to it, i have also added the localhost url to the CORS whitelist and Remote site setting too but still getting the CORS error. I am also curious that the when i see the salesforce [demos](https://youtu.be/GCbO3HAuwbg) they use exact similar code but don't face the cors issue, how is that? Below is the code which i am using 

```
import {
    createElement
} from 'lwc';
import MyApp from 'my/app';

const jsforce = require('jsforce');
const conn = new jsforce.Connection({
    // you can change loginUrl to connect to sandbox or prerelease env.
    loginUrl: 'https://login.salesforce.com'
});

const username = 'XXXXXX';
const password = 'XXXXXX';
conn.login(username, password, function (err, userInfo) {
    if (err) {
        return console.error(err);
    }
    // Now you can get the access token and instance URL information.
    // Save them to establish connection next time.
    console.log(conn.accessToken);
    console.log(conn.instanceUrl);
    // logged in user property
    console.log("User ID: " + userInfo.id);
    console.log("Org ID: " + userInfo.organizationId);
    // ...
});
```
![hY98T](https://user-images.githubusercontent.com/5904682/86656602-35e83000-c005-11ea-814d-845c18d8692b.jpg)

**Comment by alex-huang-dc** [comment]
Do you have any solution?  I faced this issue too

**Comment by thaka** [comment]
@alex-huang-dc  
Salesforce does not allow to add CORS with unsecured url with HTTP://domainURL therefore could not be able to add http://localhost:3001.
The workaround I did was setting up HTTPS Local Server https://localhost:3001. Then add https://localhost:3001 on Salesforce CORS Setup. 
Here are details and an example on setting up HTTPS Local Server https://github.com/sagardere/set-up-SSL-in-nodejs.

Hope this help.

**Comment by aman-11** [comment]
I am also stuck in this where the cors is failing for thr http://localhost:3000. Please let me know if amy workaround is there

**Comment by cristiand391** [comment]
triaging old issues...

see: https://github.com/jsforce/jsforce/issues/1172#issuecomment-2142721406
