### ISSUE TITLE
Trying to implement jsforce with React Native 

### ISSUE THREAD

**Issue by NishaLodhi** [jsforce/jsforce#1043]
Hi, 

I am trying to use jsforce with react native, I have installed all the dependency regarding this library but it didn't work.

Please let me know if you are going to provide jsforce support for react native. 

I really want to use this awesome library with my react project

**Comment by Muhammad-zain-rehman** [comment]
Following

**Comment by cristiand391** [comment]
triaging old issues...

Officially jsforce only works on node and the browser but I think some people got it working on react native. Next time please add more details of the failure, jsforce version, logs, etc.
