### ISSUE TITLE
Metadata API read not returning full list of fields

### ISSUE THREAD

**Issue by pavankumarananta** [jsforce/jsforce#1047]
The metadata api for objects is not returning complete list of fields which is causing our test cases to fail.
It is was working fine few weeks back and suddenly now the api doesn't return all the fields.

Few objects like CaseComment comes back as undefined.

For objects like Accounts the few fields are missing. We check the permissions the user has permissions to see the fields and also appears in Objectmanager of salesforce and in https://workbench.developerforce.com/

**Comment by cristiand391** [comment]
Triaging old issues...

I'm going to close this one, if anyone can repro this using jsforce v3 please file a new issues and a repro/debug logs.
