### ISSUE TITLE
Bypass duplicate rules to update account in Salesforce

### ISSUE THREAD

**Issue by tanvo-agilityio** [jsforce/jsforce#1055]
Currently, I want to update an account in Salesforce via JSforce but I got the **DUPLICATES_DETECTED - (These look like they might be dupes.  Do you want to use one of these records?)** error. Although I set **Allow** in Duplicate rule setting of the Salesforce page and we can edit successfully this account on it, It cannot be done by JSforce from my end. 

```
const jsforce = require('jsforce');

   /* Update to Salesforce */
   update: function (updateObject, callback) {
     this.getSObject().update(updateObject, callback);
   }
```

Some documents suggest setting **allowSave** to **true** in header of request via API soap like [this](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_header_duplicateruleheader.htm) but I don't don't know how to set **duplicateruleheader** for the connection in JSforce. I also found the PR in this repo about adding DuplicateRuleHeader with SOAP API [here](https://github.com/jsforce/jsforce/pull/668/commits) but it was closed.

Is this possible to bypass Duplicate Management via JSforce without disabling these rules?

**Comment by rajkopodinic** [comment]
Hello,

I have tried following a similar pattern when creating a Lead record but when inlcuding the headers ass mentioned above, im still getting the error.

Creating the record the first time works perfectly but when entering the same details a second time, i get a DUPLICTAES_DETECTED error. Is there any way to bypass this?

I saw something about this being available in API version 52.0 and later. Not sure which version JSForce uses?

**My code:**
`conn.login(username, password, function (err, userInfo) {
    if (err) {
      return console.error(err);
    }
    // Now you can get the access token and instance URL information.
    // Save them to establish connection next time.
    console.log(conn.accessToken);
    console.log(conn.instanceUrl);
    // logged in user property
    console.log("User ID: " + userInfo.id);
    console.log("Org ID: " + userInfo.organizationId);
    // ...
    conn.sobject("Lead").create(
      {
        FirstName: body.fname,
        LastName: body.lname,
        Company: body.company,
        Email: body.email,
        MobilePhone: body.mobile,
        Message__c: body.message
      },
      function (err, ret) {
        if (err || !ret.success) {
          return console.error(err, ret);
        }
        console.log("Created record id : " + ret.id);
        // ...
      },
      
    );
  });`

**Error:**
DUPLICATES_DETECTED: Use one of these records?
    at HttpApi.getError (/Users/rajkopodinic/Documents/nextjs/sendgrid-email/node_modules/jsforce/lib/http-api.js:250:13)
    at /Users/rajkopodinic/Documents/nextjs/sendgrid-email/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/Users/rajkopodinic/Documents/nextjs/sendgrid-email/node_modules/promise/lib/core.js:37:12)
    at /Users/rajkopodinic/Documents/nextjs/sendgrid-email/node_modules/promise/lib/core.js:123:15
    at flush (/Users/rajkopodinic/Documents/nextjs/sendgrid-email/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  duplicateResut: {
    allowSave: true,
    duplicateRule: 'Standard_Lead_Duplicate_Rule',
    duplicateRuleEntityType: 'Lead',
    errorMessage: 'Use one of these records?',
    matchResults: [ [Object] ]
  },
  errorCode: 'DUPLICATES_DETECTED'
} undefined

**Comment by cristiand391** [comment]
adding `docs` label to document the `options.header` feature (I just learned about it ❗ )

**Comment by cristiand391** [comment]
ref: https://jsforce.github.io/document/#http-headers
