### ISSUE TITLE
Add Support for the User Interface API

### ISSUE THREAD

**Issue by jmsfez** [jsforce/jsforce#1056]
Salesforce introduces the **[User Interface API](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_get_started.htm)** to simplify building web and mobile apps that need to deal with both data and metadata (for integrity constraints), as well as page layouts, translation and others correlated subjects.
I would like to suggest to **add support for the UI API**.
Thanks in advance

**Comment by lms15** [comment]
I do not know coding so I was trying to delete the account
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cristiand391** [comment]
closing this in favor of: https://github.com/jsforce/jsforce/discussions/1474
