### ISSUE TITLE
Platform Event topic subscription not firing when using Access Token on a Scratch Org

### ISSUE THREAD

**Issue by bpetty-formfast** [jsforce/jsforce#1058]
We are using the latest 1.9.3 build of jsforce and connecting to a Scratch Org.
When we subscribe to a Platform Event topic after calling login(...) with user credentials, the messages are captured.
When we connect by Access token or Access with Refresh (this includes the oauth2 section for the connection), it does not trigger.

I have tried using access tokens returned by the username/password flow without luck (both soap and oauth), as well as access tokens generated by an Authorization flow, as well as access tokens obtained by manually refreshing with a refresh token.

A number of people I work with have reproduce this issue.
It can be demonstrated with the following code:

```js
// Connecting with an access token will not pick up the platform event
const conn = new jsforce.Connection({
    instanceUrl: "https://business-java-1786-dev-ed.cs95.my.salesforce.com/",
    accessToken: "<access token>",
    version: "40.0"
});

conn.query("SELECT Id, FirstName, LastName FROM contact")
.then(result => {
    console.dir(result); // Shows that we have authenticated and are authorized
});

const event = "<namespace>__<event>__e";
conn.streaming.topic("/event/${event}").subscribe(async function (message) {
    console.log("access-token message:", message); // Will never see this
}); 

// Connecting with a username/pwd+token will pick up the event
const conn2 = new jsforce.Connection({
    loginUrl : "https://CS95.salesforce.com"
});

conn2.login("test-utervmrp3pog@example.com", "<password><securitytoken>", function(err, res) {
    if (err) { return console.error(err); }

    conn2.streaming.topic("/event/${event}").subscribe(async function (message) {
        console.log("user-pwd message:", message); // This will work
    }); 
});
```

**Comment by cristiand391** [comment]
could someone check if this happens wit jsforce v3? We do have e2e tests for the streaming wrapper and are flaky sometimes, wonder if it's related to this.
