### ISSUE TITLE
Documentation Issue. Specific instance URLs no longer recommended.

### ISSUE THREAD

**Issue by deckblad** [jsforce/jsforce#1059]
Correct me if I'm wrong. But, as I recall, we're supposed to be using https://login.salesforce.com for all API connections to prod.

The documentation here ( https://jsforce.github.io/document/#query ) may be slightly misleading by having a suggestion to use "na1.salesforce.com"

Thanks

**Comment by cristiand391** [comment]
closing this, `na1.salesforce.com` is mentioned as an example of an actual instance URL.
We recommend always passing the My Domain URL.
