### ISSUE TITLE
Unable to get binary response from apex call

### ISSUE THREAD

**Issue by AdrianTudC** [jsforce/jsforce#1072]
I'm using the apex API to make a GET request which gives me a PDF file.

The request looks like this: `const result = await conn.apex.get('path', options);`. In `options` I'm only allowed to provide headers.

The Apex class that I'm using is returning a PDF file with `Content-Type: application/octet-stream`. The type of `result` after that call is a string with loss of data (it's not in utf8 and a lot of characters are broken)

Example how it should be:
```
%PDF-1.4
%âãÏÓ
4 0 obj <</Filter/FlateDecode/Alternate/DeviceCMYK/Length 484774/N 4>>stream
xœ¬¶PUÑÛÿ*)‚"%( JI·Jˆt( X !Ò*)yº»»ç8‡î’F@ÅÀn±
```
and how the string I receive looks like:
```
%PDF-1.4
%����
4 0 obj <</Filter/FlateDecode/Alternate/DeviceCMYK/Length 484774/N 4>>stream
x���PU���*)�"%( JI�J�t( X !�*)y����8��F@��n�
```

If I do this request with axios, It works as it should:
```
const result = await axios.get('path',
                {
                    headers: {
                        Authorization: 'Bearer ' + accessToken,
                    },
                    responseType: 'arraybuffer',
                },
            );
```

The most important thing being `responseType:'arraybuffer'` which gives me binary data instead of a string.

I took a dive into jsforce codebase and it seems like the only response types that are checked are via `contentType` header and even that is chcked only for `csv`, `xml` or `json`. There should be a binary option available. What I couldn't understand exactly is at which point is the response stringified.

Is there any solution for me to get binary data from an `apex.get` request ?

**Comment by stefanzepeda** [comment]
Hey @AdrianTudC were able to resolve this within JSforce? I am having the same issue and will probably end up having to write an Axios fetch for this.

**Comment by jimmatthews** [comment]
I was able to work around this issue by patching jsforce 1.11.0 (using [patch-package](https://www.npmjs.com/package/patch-package)) to pass an `encoding` option through to the request package to specify a binary download:

```
diff --git a/node_modules/jsforce/lib/api/apex.js b/node_modules/jsforce/lib/api/apex.js
index 0fe[2](https://bitbucket.org/trello/provisioner/pull-requests/524#Lpatches/jsforce+1.11.0.patchT2)629..dc060b5 100644
--- a/node_modules/jsforce/lib/api/apex.js
+++ b/node_modules/jsforce/lib/api/apex.js
@@ -[4](https://bitbucket.org/trello/provisioner/pull-requests/524#Lpatches/jsforce+1.11.0.patchT4)8,6 +48,9 @@ Apex.prototype._createRequestParams = function(method, path, body, options) {
       params.body = body;
     }
   }
+  if (options && options.encoding === null) {
+    params.encoding = null;
+  }
   return params;
 };
```

and calling the apex endpoint with:

```
      const pdfBuffer = await client.apex.get(`/v1/my-getpdf-endpoint`, {
        // This call relies on a patched copy of jsforce 1.11.0, which passes
        // the encoding option through to the request module.
        // An encoding value of null indicates that binary data is expected,
        // see https://www.npmjs.com/package/request .
        encoding: null,
      });
```

**Comment by om-mani-padme-hum** [comment]
+1 Same issue with when trying to download an attached content document.

**Comment by om-mani-padme-hum** [comment]
@jimmatthews did you open a pull request for this?  Wondering why this hasn't been addressed yet.
@AdrianTudC Are you able to add a label like triage or something to this issue to get the attention of the development team?

**Comment by om-mani-padme-hum** [comment]
For my case, I finally got the solution after several hours:

```javascript
let i = 1;

for ( const attachment of record.AttachedContentDocuments.records ) {
  console.log(`Attachment #${i} found.  Requesting the version data...`);

  const result = await conn.sobject(`ContentVersion`)
    .select(`*, ContentVersion.*`)
    .where(`ContentDocumentId = '${attachment.ContentDocumentId}'`)
    .execute().then();

  let j = 1;

  for ( const version of result ) {
    console.log(`Found version #${j++}!  Requesting the attachment...`);

    const result = await conn.request({ url: version.VersionData, encoding: null });

    console.log(`Received attachment, saving as ${version.PathOnClient}`);
    
    fs.writeFileSync(path.resolve(__dirname + `/${version.PathOnClient}`), Buffer.from(result, `binary`));
  }
}
```

The critical ingredient was to use an object form request with the `encoding: null` in the config.  This does not seem very well documented, but I dug through the code to find that the object form request goes straight through to the request library.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
