### ISSUE TITLE
INVALID_FIELD: No such column 'type' on sobject of type Attachment

### ISSUE THREAD

**Issue by ppetitto1** [jsforce/jsforce#1074]
Hello, after scouring the dark recesses of stack exchange, I'm at a loss of what I'm doing wrong. I fear the problem isn't with my code.
```
var jsforce = require('jsforce');
var conn = new jsforce.Connection();
const fs = require('fs')
require('dotenv').config()
let deal = 'a5Id0000001Hr3d'
let project = 'a2m3o000001vDXwAAM'
conn.login(process.env.USER, process.env.PASS, function(err, res) {
    if (err) { return console.error(err); }
    conn.sobject('Attachment__c').create({
        Project__c: project,
        Type__c: 'Feasibility Analysis',
        State__c: 'CT'
    }, (err, res)=>{
        if(err){console.log(err)}
        console.log(res)
        let image = fs.readFileSync('test.PNG')
        let base64data = Buffer.from(image, 'base64')
    conn.sobject('Attachment').create({
        ParentId: res.id,
        Name: 'test.PNG',
        Body: base64data,
        ContentType: 'image/png'
    },function(err,res){
      if(err){console.log(err)}
      console.log(res)
       })
    })
})
```

This returns:

PS D:\JSForce Test> node index.js
{ id: 'a2b3o00000EmCYoAAN', success: true, errors: [] }
INVALID_FIELD: No such column 'type' on sobject of type Attachment
    at HttpApi.getError (D:\JSForce Test\node_modules\jsforce\lib\http-api.js:250:13)
    at D:\JSForce Test\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (D:\JSForce Test\node_modules\promise\lib\core.js:37:12)
    at D:\JSForce Test\node_modules\promise\lib\core.js:123:15
    at flush (D:\JSForce Test\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  name: 'INVALID_FIELD',
  errorCode: 'INVALID_FIELD'
}
undefined

I'm stumped by the "No such column 'type' on sobject of type Attachment" error. There is no 'type' field in my object, so I don't understand why it's giving me this error. I am running JSForce 1.10.0

**Comment by paustint** [comment]
@ppetitto1 - I tried this out and an attachment was created without any problems for me, so I don't have any advice on fixing your issue, but here is the code that I used with success:

```javascript
var jsforce = require('jsforce');
const fs = require('fs');
require('dotenv').config();

async function start() {
  try {
    const conn = new jsforce.Connection({});
    await conn.login(process.env.SFDC_USERNAME, process.env.SFDC_PASSWORD);

    const base64data = fs.readFileSync('test.png', { encoding: 'base64' });
    const results = await conn.sobject('Attachment').create({
      ParentId: 'a006g00000ELWoHAAX',
      Name: 'test.png',
      Body: base64data,
      ContentType: 'image/png',
    });
    console.log(results);
  } catch (ex) {
    console.log('[ERROR]', ex);
  }
}

start();
```

**Results**: `{ id: '00P6g000007Bzn3EAC', success: true, errors: [] }` - I confirmed the attachment was created successfully.

**Comment by ppetitto1** [comment]
Holy guacamole you are my hero you beautiful man. Turns out using the buffer function was messing it up. When I tried your method, just simply setting encoding to base64 in the readfilesync, it worked like a charm. Thank you so much!
