### ISSUE TITLE
AccessToken undefined in React Outlook Add Ins

### ISSUE THREAD

**Issue by sundariragavan** [jsforce/jsforce#1075]
Hi, 
 I have implemented salesforce login in react project using jsforce.  Its working fine and returning the value (access token)
 ` jsforce.browser.init({
      clientId: "client id",
      redirectUri: "https://localhost:3000/salesforce",
    });
   jsforce.browser.login();
   jsforce.browser.on("connect", function(conn) {
   // access token
    });`

But i want to implement the salesforce login in outlook Add Ins ( React ). Unable to get the access token.  
`jsforce.browser.init({
      clientId: "client id",
      redirectUri: "https://localhost:3000/taskpane.html",
    });
    jsforce.browser.login();
    jsforce.browser.on("connect", function(conn) {
    // access token
    });`
In outlook react add ins unable to get the data. Please help me to solve the issue
Thanks

**Comment by cristiand391** [comment]
I'm not sure what outlook ad ins is, please re-open if this is still a problem.
