### ISSUE TITLE
Composite requests

### ISSUE THREAD

**Issue by TNelen** [jsforce/jsforce#1080]
Is there a possibility to do composite requests using the connector? 

I saw the `requestPost()` method mentioned in another issue, but i do not have that method. I'm on version 1.9.20".

It seems the documentation does not mention anything about composite request, would it be possible to provide and example? 

Many thanks!

**Comment by paustint** [comment]
Yes, you can make calls to the composite API using this library. Here is a thread with some additional detail on how to form your request: https://github.com/jsforce/jsforce/issues/934

These methods have existed for a long time, they do work on your version. Here are the versions I am using:

"jsforce": "^1.9.3",
"@types/jsforce": "^1.9.25",

**Comment by TNelen** [comment]
Thanks a lot. I think I know sufficient to move forward. 

This issue can be closed.
