### ISSUE TITLE
Instance url being returned by jsforce is incorrect

### ISSUE THREAD

**Issue by GittBUB** [jsforce/jsforce#1096]
I'm getting a 404 from a proxy request. After looking into it the problem appears to be `this._conn.instanceUrl`.

To be more specific `this._conn.instanceUrl` is providing the instance name "company--stage--c.visualforce.com" and this causes a 404.

When I mock a request using "company--stage--my.salesforce.com" I get a 200, which confirms the problem.

**Comment by cristiand391** [comment]
triaging old issues...

the `instanceUrl` should be passed when creating the connection:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html

jsforce shouldn't change the instanceURL internally, please file a new issue if it's reproducible
