### ISSUE TITLE
Can't see version 1.10.1 in the repo

### ISSUE THREAD

**Issue by papandreou** [jsforce/jsforce#1100]
@stomita, did you forget to push the commit that bumps the version to 1.10.1?

**Comment by papandreou** [comment]
Ping @stomita, should be a quick little thing to fix?

**Comment by cristiand391** [comment]
closing this since v1 isn't getting updates, see pinned issue about jsforce v3

**Comment by papandreou** [comment]
I don’t really care anymore, but I don’t understand why you don’t feel it’s important to have these basic hygiene factors in place.

**Comment by cristiand391** [comment]
oh, we do care about this, that's why we automated the release process in the v3 branch:
https://github.com/jsforce/jsforce/tree/3.0/.github/workflows

for each release you get a commit bump in the repo + GH release that triggers the npm publish.
https://github.com/jsforce/jsforce/releases

**Comment by papandreou** [comment]
But why not get it in order for older releases as well? It looks like two tags are missing:

```
[jsforce]$ diff <(npm info jsforce --json | jq -r .versions[] | grep '^1\.' | sort -n) <(git tag | grep '^1\.' | sort -n)
26d25
< 1.8.2
35d33
< 1.10.1
```
