### ISSUE TITLE
LocalStorage functionality broken in Chrome 87

### ISSUE THREAD

**Issue by jordancue** [jsforce/jsforce#1106]
In https://jsforce.github.io/jsforce/doc/browser_client.js.html , localStorage is intended to be used synchronously to remove the `jsforce_state` stored value before closing the authentication popup. However, in modern browsers such as Chrome, localStorage can run asynchronously. This results in the stored value not being removed before the window closes.

Here's the relevant code:

```javascript
function handleCallbackResponse() {
  var res = checkCallbackResponse();
  var state = localStorage.getItem('jsforce_state');
  if (res && state && res.body.state === state) {
    localStorage.removeItem('jsforce_state');
    var states = state.split('.');
    var prefix = states[0], promptType = states[1];
    var cli = new Client(prefix);
    if (res.success) {
      cli._storeTokens(res.body);
      location.hash = '';
    } else {
      cli._storeError(res.body);
    }
    if (promptType === 'popup') { window.close(); }
    return true;
  }
}
```

**Comment by cristiand391** [comment]
triaging old issues...

I don't see docs pointing localstorage methods can run async, please this code will stay the same in jsforce v3.
