### ISSUE TITLE
How do i set the scope for oAuth2 in browser based authentication

### ISSUE THREAD

**Issue by gunish** [jsforce/jsforce#111]
e.g. https://jsforce.github.io/jsforce/doc/OAuth2.html#getAuthorizationUrl

this method when called from Node / Express accepts scope parameters. 

Where as in Browser, we call #init and #login methods 
I tried passing the scope as a parameter in both of them, but could am unable to set it.

Basically i am trying to get a refresh token in the response when authenticating via browser / oauth2 !

**Comment by cristiand391** [comment]
triaging old issues...

in jsforce v3 you can pass that set the scope when calling `login` in the options obj. it takes:
https://jsforce.github.io/jsforce/types/browser_client.LoginOptions.html
