### ISSUE TITLE
how to use query method chain (json/mongo-style) with OR, AND? 

### ISSUE THREAD

**Issue by techieshark** [jsforce/jsforce#1112]
Hi, thanks for this very useful library. I have a question about the MongoDB style queries:

Taking as a start the example query from [the docs](https://jsforce.github.io/document/#using-query-method-chain):
```
conn.sobject("Contact")
  .find(
    // conditions in JSON object
    { LastName : { $like : 'A%' },
      CreatedDate: { $gte : jsforce.Date.YESTERDAY },
      'Account.Name' : 'Sony, Inc.' },
    ...
```

How would we modify this to include a more complex query involving nested AND/OR operators?

I'd guess it should look like:
```
conn.sobject("Contact")
  .find(
    // conditions in JSON object 
    { LastName : { 
       $or: [
       { $like : 'A%' },
       { $like: 'B%' },
      ]
    },
    ...
```

I'd expect that to result in:
```
SELECT ... FROM Contact WHERE LastName LIKE 'A%' OR Lastname LIKE 'B%' 
```
but jsforce seems to just drop those LIKE parts entirely, presumably because it isn't understand what I'm passing to it.

I've looked at the `soql-builder.test.js` and see it seems it should work, but the code/examples there aren't directly transferrable since they use a `conditions: { }` object passed to `SOQL.Builder.createSOQL` rather than calling `find()` directly.

Thanks!

**Comment by techieshark** [comment]
For extra context, I also wrote another test for `soql-builder.test.js` that tests the full complexity of a query similar in structure to what I want, and it passed. So I think the issue may be in translation between `find()` and `SOQLBuilder.createSOQL()`. 

```
describe("Query with nested AND/OR operators using like and exists", function () {
    var soql = SOQLBuilder.createSOQL({
      table: "Contact",
      conditions: {
        $and: [
          { 'Contact.Name': { $exists: true } },
          {
            $or: [
              { 'Contact.Name': { $like: 'Jack%' } },
              { 'Contact.Name': { $like: 'Jill%' } }
            ]
          }
        ]
      }
    });

    it("should equal to soql", function () {
      console.log(soql);
      assert.ok(soql ===
        "SELECT Id FROM Contact " +
        "WHERE Contact.Name != null AND (Contact.Name LIKE 'Jack%' OR Contact.Name LIKE 'Jill%')"
      );
    });
  });
```

**Comment by cristiand391** [comment]
triaging old issues...

the conditionals array expect each operator to be paired with the field it acts on, here's an example:

```ts
const soqlQuery = await conn.sobject('Contact').find(
    {
      $or: [{ LastName: { $like : 'A%' }}, { LastName: { $like : 'B%'} }]
    },
    {
      Name: 1,
    }
  ).toSOQL()
```

that returns:
```soql
SELECT Name FROM Contact WHERE LastName LIKE 'A%' OR LastName LIKE 'B%'
```

I'll add an example about this in the docs.

**Comment by cristiand391** [comment]
added a `Conditionals` section here to cover this:
https://jsforce.github.io/document/#using-query-method-chain
