### ISSUE TITLE
INVALID_FIELD from Query using SOQL for Birthdate, FinServ custom field on contact object

### ISSUE THREAD

**Issue by s0up2up** [jsforce/jsforce#1114]
Hi there,

I'm coming across an issue where we are generating a SOQL query and it is erroring with an INVALID_FIELD code. The field that we are trying to query is both the standard Birthdate and a custom Financial Services Cloud field on the contact sObject. 

The same query works as expected utilizing the Developer Console within SF and also the browser implementation on the Documentation site, so seems a local node jsforce issue? Has anyone come across anything similar and how did they resolve it?

Code sample below:
<pre><code>conn.query(`SELECT Id, FirstName, MiddleName, LastName, Email, Birthdate, FinServ__Occupation__c, MailingStreet, MailingPostalCode, MailingCity, MailingCountry FROM contact WHERE Id IN ('redacted_contactId')`</code></pre>

Any questions let me know.

Kind regards,

**Comment by paustint** [comment]
There are usually two reasons why this could happen:
1. You are using a different user with JSForce than you are logged in on the developer console and the user does not have permissions to those fields.
2. You are using a different API version when initializing in Node vs the other places, where those fields don't exist with that api version.

This works fine for me on the node version, so this must be something with your configuration.

**Example**: these are returned using API version 49.0 using the https://getjetstream.app/ platform, which uses the jsforce node api:

![image](https://user-images.githubusercontent.com/5461649/104962142-a98fd000-598c-11eb-8d69-f60eb9baf4b7.png)

**Comment by s0up2up** [comment]
@paustint yup that totally is it. Now to trouble shoot a more basic FLS issue, thanks for the heads up.
