### ISSUE TITLE
Is JWT Bearer flow available

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [jsforce/jsforce#1116]
Hi
I have been taking a look at the code and I was wondering if JWT Bearer flow was available. This is an important flow when SalesForce APIs are access from the backend. Thanks

**Comment by anner-emed** [comment]
No there is a PR here https://github.com/jsforce/jsforce/pull/1053

that has not been merged and it has been asked since 2016!!

**Comment by cristiand391** [comment]
triaging old issues...

docs: https://jsforce.github.io/document/#jwt-bearer-flow-oauth-2-0-jwt-bearer-flow-
