### ISSUE TITLE
NodeJS specific NPM listing

### ISSUE THREAD

**Issue by lcampos** [jsforce/jsforce#1117]
This library is used for multiple purposes which the current NPM listing accounts for. However, in a scenario where the library is used as part of a NodeJS project a lot of the code being installed is not used (e.g. everything under the `build` folder). We currently have to add post install steps to remove all the unused code. Would the maintainers be open to having an additional NPM listing which is specific for this scenarios and exclusively ships the code under `lib` ?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
