### ISSUE TITLE
retrieve multiple ids

### ISSUE THREAD

**Issue by spoon16** [jsforce/jsforce#112]
There is a retrieve call that takes multiple ids (I think).  Anyway to get jsforce to support this call?  I'm trying to use the synchronization API (getUpdated, getDeleted).  For getUpdated I need to get the list of updated ID's and then retrieve each ID.  Using queries doesn't work well because the query length limit is quickly exceeded.

Can jsforce be updated to use the retrieve version that takes a list of id's instead of a single id?

http://www.salesforce.com/us/developer/docs/api/index_Left.htm#CSHID=sforce_api_calls_retrieve.htm|StartTopic=Content%2Fsforce_api_calls_retrieve.htm|SkinName=webhelp

**Comment by cristiand391** [comment]
closing this, should be supported in v3:
https://jsforce.github.io/jsforce/classes/sobject.SObject.html#retrieve
