### ISSUE TITLE
String literals as params not working

### ISSUE THREAD

**Issue by AlanGreyjoy** [jsforce/jsforce#1123]
I can not use string literals in the params below. Nothing works!

**Only this works**
``` .find({ Phone: '‪(222) 222-2222‬' })```

**Not this**
```.find({ Phone: `${req.query.phoneNumber}` })```

**Not this**
```.find({ Phone: "'"+req.query.phoneNumber+"'" })```

**Not even this**
```.find({ Phone: req.query.phoneNumber })```

**I also tried to assign the string before hand**
```const pn = req.query.phoneNumber```
and then used
```.find({ Phone: pn })```

**Nothing.**

What could I be doing wrong??

```
exports.FindContact = async (req, res)=>{
    let conn = new jsForce.Connection();
    conn.login('XXXXXXXXXX','XXXXXXXXXX').then((auth)=>{
        conn.sobject("Contact")
            .find({ Phone: '‪(222) 222-2222‬' }) // THIS IS THE PROBLEM
            .execute(function(err, records) {
                if (err) { return console.error(err); }
                console.log(records);
            });
    }).catch(error=>{console.error(error)})
}
```

![](https://cdn.discordapp.com/attachments/348054624256786434/814516799843467301/unknown.png)

![](https://cdn.discordapp.com/attachments/348054624256786434/814516896333430866/unknown.png)

![](https://cdn.discordapp.com/attachments/348054624256786434/814517232792371210/unknown.png)

**Comment by cristiand391** [comment]
triaging old issues...

I can't repro this:
```
  const contact = conn.sobject('Contact');

  const john = await contact.find({
    Phone: '(222) 222-2222',
  },['Name', 'Id', 'Phone'])

  console.log(john)

```

⬇️ 

```
[
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v60.0/sobjects/Contact/0038N00000Jn47aQAB'
    },
    Name: 'John McApple',
    Id: '0038N00000Jn47aQAB',
    Phone: '(222) 222-2222'
  }
]
```

> I can not use string literals in the params below

jsforce takes a string, so any of those scenarios is valid code.

**Comment by AlanGreyjoy** [comment]
lol? You can't come at me with an issue I wrote 3 years ago 😂
It could have been fixed by now.

**Comment by cristiand391** [comment]
> lol? You can't come at me with an issue I wrote 3 years ago 😂
It could have been fixed by now.

I know, I know 😄 .I'm helping triaging old issues so we don't miss bugs in latest versions.
