### ISSUE TITLE
Adding a logging interceptor to the connection

### ISSUE THREAD

**Issue by azakordonets** [jsforce/jsforce#1128]
Hi, 

I was wondering if it's possible to log http request/response details to the Salesforce from the library, so that it would be a less black box during debug. Right now it's only possible to catch errors and guess what kind of payload and what url was used to make a request to Salesforce. 

Something like this - https://github.com/new10com/axios-logger ?

**Comment by cristiand391** [comment]
triaging old issues...

you can set a logLevel when creating the connection, that will log requests details:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html
