### ISSUE TITLE
Web browser access

### ISSUE THREAD

**Issue by RobinBarnwell** [jsforce/jsforce#1129]
The examples on https://jsforce.github.io/document/ run just fine on my dev org.  But when I run in web browser I can get a connection but the query fails with a 404.  But it looks wrong as its trying to get from the localhost rather than Salesforce instance.  What am I doing wrong? 

GET https://localhost:8000/services/data/v42.0/query?q=SELECT%20Id%2C%20Name%20FROM%20Account 404 (Not Found)

<!DOCTYPE html><html><head>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jsforce/1.9.1/jsforce.min.js"></script>
<script>
    var conn = new jsforce.Connection();
    conn.login("robin.barnwell@curious-goat-XXX.com", "XXXXXXXLk7USQ4ooibjwNYgJNeH0V7", function(err, userInfo) {    if (err) { return console.error(err); }    });

    var records = [];
    conn.query("SELECT Id, Name FROM Account", function(err, result) {     if (err) { return console.error(err); }    });
</script>
</head><body>Hello</body></html>

**Comment by RobinBarnwell** [comment]
It's OK I worked it out. You need to set-up oAuth then it works.  There is a need to a full tutorial here for people like me who are only just getting it and having to read lots of manuals and watch Youtube to figure out what it all means.

**Comment by cristiand391** [comment]
triaging old issues...

there are a few examples here:
https://jsforce.github.io/document/

for this specific error, the instance URL was being set to localhost when it should always be your "my domain" instance URL.
