### ISSUE TITLE
Cannot download XML files

### ISSUE THREAD

**Issue by gvoss-mavens** [jsforce/jsforce#1131]
Retrieving XML files from salesforce using HTTPS request, returns JSON object instead of XML data

Using the connectAPI getRequest to retrieve the file contents of an XML file, the content that is returned in the response was a JSON object. I should be getting the XML text returned so that I can write the response to a new XML file, instead I am getting a JSON object which prevents me from writing to the new file

**Comment by paustint** [comment]
You may find this post helpful as it explains how to opt-out of having JSForce parse your response as JSON: https://github.com/jsforce/jsforce/issues/934#issuecomment-546714813
