### ISSUE TITLE
Error is ERROR_HTTP_414: <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre> on query all the fields with wild card

### ISSUE THREAD

**Issue by goldjmj** [jsforce/jsforce#1134]
for example the below code returns the error:
```
conn.sobject("Contact")
      .select('Account.*')
      // .limit(1)
      // .offset(20)
          .execute(function (err, records) {
            console.log(err);
        insertData(records);
          }).catch((error) => {
        console.log('Error is ' + error);
      });
```

**Comment by pardhav** [comment]
```
await conn
            .sobject('Contact')
            .select('Account.*')
            .limit(1)
            .execute()
            .then((data) => {
                res.status(200).json({data});
            })
            .catch((error) => {
                console.log('Error is ' + error);
            });
```

I tried your snippet in express js, It works fine for me. 
Developer Org, API version 50.0

**Comment by goldwinVonage** [comment]
My org has about 675 fields. I am getting same error.

**Comment by goldwinVonage** [comment]
I think it is the limit from salesforce.

**Comment by cristiand391** [comment]
triaging old issues

jsforce transform that code into a soql query that's executed via the REST API and specified as an URL parameter, that's likely why you hit the [414 URI Too Long error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414).

AFAIK, the API doesn't allow to pass the soql query in the request body so there's little jsforce can do.

**Comment by cristiand391** [comment]
triaging old issues

jsforce transform that code into a soql query that's executed via the REST API and specified as an URL parameter, that's likely why you hit the [414 URI Too Long error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414).

AFAIK, the API doesn't allow to pass the soql query in the request body so there's little jsforce can do.
