### ISSUE TITLE
V2 Status

### ISSUE THREAD

**Issue by amphro** [jsforce/jsforce#1137]
Shinichi Tomita announced [v2](https://github.com/jsforce/jsforce/issues/889) in 2019. He’s made significant progress since then and published a few beta releases. This post outlines the remaining work to take it from beta to GA. We’d love your help with reporting issues, keeping this list up-to-date, and submitting PRs to the [v2 branch](https://github.com/jsforce/jsforce/tree/2.0). Please include “[v2]” in the issue or PR description. 

**Remaining work:** 
- [x] Change request to node-fetch (#1136) (#1090).
- [x] Export more types for fewer breaking changes between v1 → v2. (In progress #1142)
- [ ] Documentation equivalent to the current jsforce.github.io (http://jsforce.github.io/).
- [ ] Annotations to the code for API references.
- [ ] Bonus - a node-specific release (without dist folder) (follow-up issue explaining this).

[open PRs to 2.0 branch](https://github.com/jsforce/jsforce/pulls?q=is%3Apr+is%3Aopen+base%3A2.0)

**Comment by qbert-007** [comment]
Is there any ETA for jsforce stable version 2? When should we expect the official release? Could you please let us know whether the release is within the next couple months so we can plan the library upgrade accordingly?

**Comment by catalandres** [comment]
Should we have separate issues to track each of the points that are blocking GA?

**Comment by amphro** [comment]
Separate issues sound fine to me. If you @catalandres want to create them and start conversations around them, I can add links to this issue. This will probably need more community help to get across the line.

I've moved on to other projects and am no longer a maintainer on jsforce. I'm happy to help with opinions, conversations, or reviews when mentioned, but I don't have time for more than that. I know the other maintainers are super busy but they may be able to provide guidance too. @mshanemc @stomita

**Comment by overclocked47** [comment]
> Is there any ETA for jsforce stable version 2? When should we expect the official release? Could you please let us know whether the release is within the next couple months so we can plan the library upgrade accordingly?

Do we have a potential release date for version 2?

**Comment by cristiand391** [comment]
Closing this in favor of https://github.com/jsforce/jsforce/issues/1360
