### ISSUE TITLE
OAuth with node.js 

### ISSUE THREAD

**Issue by rokadeamol** [jsforce/jsforce#1144]
`Hi,`

I am new to JSForce. I am trying to run the OAuth snippet found here on Node.js using VS code

https://jsforce.github.io/document/#authorization-request

My code is below. When I run this on the express server, I would expect to the redircted to the Salesforce login page but that is not happening. Can you please help me with this?

var express        = require('express');
var jsforce        = require('jsforce');
var app            = express();

PORT = 3001

var oauth2 = new jsforce.OAuth2({
  // you can change loginUrl to connect to sandbox or prerelease env.
  loginUrl : 'https://login.salesforce.com',
  clientId : 'client id',
  clientSecret : 'client secret',
  redirectUri : 'http://localhost:3001/oauth/callback'
});
///

app.get('/oauth2/auth', function(req, res) {
    res.redirect(oauth2.getAuthorizationUrl({ scope : 'api id web' }));
  });
//
// Pass received authorization code and get access token
//
app.get('/oauth2/callback', function(req, res) {
    var conn = new jsforce.Connection({ oauth2 : oauth2 });
    var code = req.param('code');
    conn.authorize(code, function(err, userInfo) {
      if (err) { return console.error(err); }
      // Now you can get the access token, refresh token, and instance URL information.
      // Save them to establish connection next time.
      console.log(conn.accessToken);
      console.log(conn.refreshToken);
      console.log(conn.instanceUrl);
      console.log("User ID: " + userInfo.id);
      console.log("Org ID: " + userInfo.organizationId);
      // ...
      res.send('success'); // or your desired response
    });
  });

  app.listen(PORT, function () {
	console.log('Example app listening on port !');
});

when I tested in browser with below URL
http://localhost:3001/ I am getting 'Cannot GET / ' error

In connected APP I have added http://localhost:3001/oauth/callback callback URL also

**Comment by paustint** [comment]
Your configured url is GET `http://localhost:3001/oauth2/auth` based on the route path you chose to define here `app.get('/oauth2/auth', function(req, res) {`

You don't appear to have anything configured at `/`

**Comment by rokadeamol** [comment]
I didn’t get your point could you plz explain what changes i need to do to fix it

> Your configured url is GET `http://localhost:3001/oauth2/auth` based on the route path you chose you defined here `app.get('/oauth2/auth', function(req, res) {`
> 
> You don't appear to have anything configured at `/`
I didn’t get your point could you plz explain what changes i need to do to fix it

**Comment by paustint** [comment]
You do not need to make any changes to your code. You need to change the URL you are visiting.

1. start your application (I would explain this in more detail if you had filenames - but for the sake of argument, let's assume you are able to start a node program)
2. Open your web browser
3. Type in URL `http://localhost:3001/oauth2/auth` (**NOT** `http://localhost:3001` and **NOT** `http://localhost:3001/`)
4. You will be redirected to the login page assuming that you have correctly configured your `clientId` and `clientSecret`

On a side note, if you do want  `http://localhost:3001` to start the authentication flow, then you would change `app.get('/oauth2/auth', function(req, res) {` to `app.get('/', function(req, res) {`

I would encourage you go learn about how `express` works before attempting to `express` for an authentication flow.

**Comment by rokadeamol** [comment]
> You do not need to make any changes to your code. You need to change the URL you are visiting.
> 
> 1. start your application (I would explain this in more detail if you had filenames - but for the sake of argument, let's assume you are able to start a node program)
> 2. Open your web browser
> 3. Type in URL `http://localhost:3001/oauth2/auth` (**NOT** `http://localhost:3001` and **NOT** `http://localhost:3001/`)
> 4. You will be redirected to the SFDC login page assuming that you have correctly configured your `clientId` and `clientSecret`
>    
>    * If you did not configure your connected app correctly, then  you will be presented with a Salesforce webpage with the following: `error=invalid_client_id&error_description=client%20identifier%20invalid`
> 
> On a side note, if you do want `http://localhost:3001` to start the authentication flow, then you would change `app.get('/oauth2/auth', function(req, res) {` to `app.get('/', function(req, res) {`
> 
> I would encourage you go learn about how `express` works before attempting to `express` for an authentication flow.

Thanks a lot @paustint its worked
