### ISSUE TITLE
npm has beta version as latest

### ISSUE THREAD

**Issue by etienne-detrace** [jsforce/jsforce#1149]
I reported this same issue a month or two ago and it was fixed. npm has the latest as 2.0.0-beta.4 while this repo shows 1.10.0 as the latest. This is causing our Jenkins deployments to fail unless we specifically set our npm install to the specific version which is not desirable.

Great package, issues with packaging deployments to npm.

**Comment by stomita** [comment]
Sorry, I fixed it.
