### ISSUE TITLE
Login popup doesn't close after receiving access token 

### ISSUE THREAD

**Issue by ghost** [jsforce/jsforce#115]
The login popup work perfectly but it dont close and so the browser.on event doesn't work.

I am doing this in a visualforce page as the page will be on site and user might not be loggedin.

< apex:page showHeader="false" standardStylesheets="false">
< html>
< head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.3.1/jsforce.min.js"></script>
< script>
jsforce.browser.init({
  clientId: '3MVG9Y6d_Btp4xp7mLm_Hzhxc2gM.QMsZhKWDrFhNZ8zSJHS1rGKyuXrTR_XCDSknzUW_xA6mXSVtss9buDF',
  redirectUri: 'https://c.ap1.visual.force.com/apex/JSForce_authrization' 
});

jsforce.browser.on('connect', function(conn) { 
    alert();
});

</ script>
</ head>
< body>
  < button onclick="jsforce.browser.login();">Login</button>
</ body>
</ html>
</ apex:page>

**Comment by seemas-grazitti** [comment]
I am still facing same issue. I have added proxyUrl and disabled developement mode.

**Comment by BhavikThakkar** [comment]
I am facing same issue with one more problem when pop up displays salesforce login page, main page also get redirected to salesforce login page.

**Comment by rodrigoEclipsa** [comment]
Does anyone know how this is resolved?
