### ISSUE TITLE
Connection with access_token not working in v2?

### ISSUE THREAD

**Issue by pogilvie** [jsforce/jsforce#1151]
The program below works in v 1.10.1 but fails on any of the version 2.0.0.beta.x versions.   Symptom:  does not block on describe function just completes without error which status 0.

this is on MacOS 11.4 (ARM and Intel)

```javascript
const jsforce = require('jsforce');
const conn = new jsforce.Connection({
  instanceUrl : 'https://myorg.my.salesforce.com',
  accessToken : 'my-access-tokenx'
});

conn.sobject("Account").describe(function(err, meta) {
  if (err) { return console.error(err); }
  console.log('Label : ' + meta.label);
  console.log('Num of Fields : ' + meta.fields.length);
});

```

**Comment by stomita** [comment]
The callback style invocation will be removed in 2.0 and will be replaced in promise style.

```javascript
conn.sobject("Account").describe().then(function(meta) {
  console.log('Label : ' + meta.label);
  console.log('Num of Fields : ' + meta.fields.length);
}).catch(function(err) {
  console.error(err);
});
```

**Comment by pogilvie** [comment]
Thank you.  My existing project pulled in 2.0 and broke when I nom installed.   I've changed my package.json to specify v1 latest.   Good to know the root cause.
