### ISSUE TITLE
Upsert with Multiple Objects generates Individual requests to Salesforce

### ISSUE THREAD

**Issue by redwarewolf** [jsforce/jsforce#1156]
When using the method `upsert ` from connection with an array of Objects, JsForce does individual requests to Salesforce instead of Upserting chunks of `maxObjects`
For example, if you use upsert with 200 objects, It performs 200 API Requests to Salesforce thus causing huge costs in Salesforce licenses.
Method create instead uses createMany thus not presenting this issue

This issue is present in: 
https://github.com/jsforce/jsforce/blob/master/lib/connection.js

and

https://github.com/jsforce/jsforce/blob/2.0/src/connection.ts

**Comment by redwarewolf** [comment]
This issue is present in: 
https://github.com/jsforce/jsforce/blob/master/lib/connection.js

and

https://github.com/jsforce/jsforce/blob/2.0/src/connection.ts

**Comment by stomita** [comment]
We've introduced [collection API](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_sobjects_collections.htm) to handle multiple records in insert/update/delete operation request, which supports up to 200 records at one request. But [till 49.0 there was no for upsert in collection API](https://developer.salesforce.com/docs/atlas.en-us.224.0.api_rest.meta/api_rest/resources_composite_sobjects_collections.htm). That is why we use parallel call for upsert request at the time of implementation. We may add the support in 2.0.
