### ISSUE TITLE
REDACTED

### ISSUE THREAD

**Issue by mikallojjus** [jsforce/jsforce#1161]
No longer applicable, please delete this issue. Thanks!

**Comment by paustint** [comment]
*.lightning.force.com is not a proxy for the login service. In your
browser, it ends up redirecting to the login service, but that is very much
different than a proxy. In addition, it is not even on the same domain (
force.com vs salesforce.com).


IMO there are a couple of improvements that could be made.

Based on the response code (e.x. 405) jsforce could provide a custom error
message back explaining the url is not valid for logging in.

Second, and maybe better, is to make sure that the documentation for the
login process clearly states which url to use to login (or link to sfdc
documentation if it exists)
