### ISSUE TITLE
Relationship Query - Lookup to User Not Working

### ISSUE THREAD

**Issue by jkk4999** [jsforce/jsforce#1163]
Hello,

I am not seeing the expected result when using a relationship query to User.   

For example, when using a Contact query with a relationship to Account, the query produces a correct result which contains the fields of the lookup relationship and the Contact fields (see image 2),

When using a Contact query with a relationship to User, no User fields are returned (see image 1).

Here is example code:

// sobject  =  'Contact'
// selectClause =  '\*, User.*'

await conn
        .sobject(objName)
        .select(selectClause)
        .execute(
          { autoFetch: true, maxFetch: 100000 },
          function (err, records) {
            for (var i = 0; i < records.length; i++) {
              var record = records[i];
             // process results ...
            }
            results = records;
          }
        );

return results;

<img width="715" alt="Contact with User Lookup" src="https://user-images.githubusercontent.com/59376742/126200088-099ed620-0ddd-43b6-ac18-0731db8d377d.png">

// sobject = 'Contact'
// selectClause = '\*, Account.*'

<img width="722" alt="Contact with Account Lookup" src="https://user-images.githubusercontent.com/59376742/126201981-75f84cc6-7e66-464f-bb73-1e5713d9b121.png">

Your assistance would be appreciated.  Thanks!

**Comment by cristiand391** [comment]
triaging old issues...

with the `User.*` clause, jsforce looks for `Contact` fields that have `relationshipName` === `User`, I don't see that being populated in the response: 

```
sf sobject describe --sobject Contact --json | jq '.result.fields | .[] | .relationshipName | select(. != null)'
"MasterRecord"
"Account"
"ReportsTo"
"Owner"
"CreatedBy"
"LastModifiedBy"
"JigsawContact"
"Individual"
"User__r"
```

`User__r` is included because I created a relationship to users manually, so:

```ts
const res = await conn.sobject('Contact').select('*, User__r.*').toSOQL()
```
expands user fields correctly.
