### ISSUE TITLE
Login Popup Window Doesn't Close

### ISSUE THREAD

**Issue by steveFormica** [jsforce/jsforce#1164]
There was another issue entered for this same problem, but had no answers on it. When I click the button to Login from my external webpage, the Login window opens and I am able to login to Salesforce, but then the new window stays open and in that window I am redirected back to my external webpage, which is what I set my redirect URL to.

Is this because I don't have the proxy server set up? I don't have Developer Mode selected on my profile in Salesforce. What am I missing or doing wrong?

**Comment by paustint** [comment]
If you opened the window using javascript, then you are in charge of the lifecycle of that window.

You have a couple of options to solve this:
1. don't open a new window, but instead redirect the user in the main browser tab you are using for your application
2. use window.postMessage to communicate between browser windows so that after the redirect you can post the information back to the previously open browser tab (this is a bit more complicated, but was the only good way I found to do it for the project I am working on - http://getjetstream.app/)

With `#2` the page on your redirect url would need to handle initiating the message to the window that opened it.

Here is a rough example:

**Open the new window and listen for message event**
```javascript
let windowRef;

function handleWindowEvent(event) {
  if (isString(event.data)) {
    try {
      const org = JSON.parse(event.data);
      // TODO: ensure message is from your origin (see MDN docs for examples)
      if (windowRef) {
        windowRef.close();
      }
    } catch (ex) {
      // TODO: tell user there was a problem
    }
  }
}

windowRef = window.open(url, 'Add Salesforce Org', strWindowFeatures);
window.addEventListener('message', handleWindowEvent, false);
```

**Javascript used on the page at the redirect URL**

```javascipt
function parseQuery(queryString) {
  var query = {};
  var pairs = (queryString[0] === '?' ? queryString.substr(1) : queryString).split('&');
  for (var i = 0; i < pairs.length; i++) {
    var pair = pairs[i].split('=');
    query[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1] || '');
  }
  return query;
}

window.addEventListener('load', function () {
  var params = parseQuery(window.location.search);

  if (params.error) {
    document.getElementById('status').innerText = params.message + ' ' + params.error || '';
  } else {
    if (window.opener) {
      // send them to the opening window
     // TODO: replace targetOrigin with specific origin, or '*'
    // docs: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage 
      window.opener.postMessage(JSON.stringify(params), targetOrigin);
      // window.close(); // TODO: add this back in after testing
    } else {
      // ERROR! TODO:
      console.error('ERROR - window.opener is not defined');
    }
  }
});
```

**Comment by steveFormica** [comment]
Thanks Paustint. So it seems it is my lack of knowledge of Javascript that is the problem and not my setup. I will give both options a try. 

My follow up question is after I've established a connection to Salesforce, how do I then run an SOQL query on a button click?

Below code is how I would expect to do this. The problem is that the connection "conn" is not recognized here. How do I access/use the connection that has been established?

$('#getCompID').on('click', function(){
        var records = [];
	conn.query("SELECT Id, Name FROM Account", function(err, result) {
		if (err) { return console.error(err); }
		console.log("total : " + result.totalSize);
		console.log("fetched : " + result.records.length);
		for (var i = 0; i < result.records.length; i++) {
			console.log(result.records[i]);
		}
	});
});

**Comment by paustint** [comment]
@steveFormica - I would have to see more of your code to know for sure, it all depends on how you instantiated the variable that will determine on how it is scoped to various functions.

I shudder to say this, but if you store `conn` as a global variable (e.x. var conn = ....`) then it would be considered global. This is not at all a best practice, but it should work.  If you initialized conn inside of another function using let or const then conn would be scoped just to that function.

You can put in a breakpoint in your browser and can look at the variables that you have in scope and play around in the developer console REPL while the code execution is paused - that should help give you an idea.

**Comment by steveFormica** [comment]
I have a solution that I will share in case anyone else ever wants to call the Salesforce API using client side Javascript. Please critique it if I'm doing something dumb. I went with the solution to login to salesforce in the same window instead of popping up a different window. I used the jquery.cookie.js library to query the jsforce0_loggedin cookie to determine if the user is logged in and connected to Salesforce. I only show/hide the login and logout of Salesforce buttons based on this cookie value. I had to initialize the connection variable with global scope. Not sure if this is a bad idea or not. My external program/webpage is only accessible by users who I specifically give access to so I figure it is not much of a risk if that is the only concern doing it this way. 

**I made 2 changes to the jsforce.js file.** 

First, in the popupWin function, instead of opening a new window like this:

return window.open(url, null, 'location=yes,toolbar=no,status=no,menubar=no,width='+w+',height='+h+',top='+top+',left='+left);

I set the href to the url like this:

window.location.href = url;

Then I changed the init function to pass the connection as a parameter instead of passing the config as a parameter. Here is the function before I changed it:

Client.prototype.init = function(config) {
  if (handleCallbackResponse()) { return; }
  this.config = config;
  this.connection = new Connection(config);
  var tokens = this._getTokens();
  if (tokens) {
    this.connection.initialize(tokens);
    var self = this;
    setTimeout(function() {
      self.emit('connect', self.connection);
    }, 10);
  }
};

Here is the function after I changed it:

Client.prototype.init = function(salesforceConn) {
  if (handleCallbackResponse()) { return; }									   
  var tokens = this._getTokens();
  if (tokens) {
    salesforceConn.initialize(tokens);
    var self = this;
    setTimeout(function() {
      self.emit('connect', salesforceConn);
    }, 10);
  }
};


**Here is my personal JS file:**

$(function() {  
	var config = {
		clientId: 'exampleclientidAn8DFoi5gsexampleclientidxqdio23SDfgexampleclientid4s5J6OPagh',
		loginUrl: 'https://mysaleforceinstance.my.salesforce.com',
		redirectUri: 'https://myExternalProgramURL'
	};
	
	var salesforceConnection = new jsforce.Connection(config);
	
	jsforce.browser.init(salesforceConnection);
	
	if ($.cookie("jsforce0_loggedin")) {
		$('#logoutSF').removeClass("hide");
		$('#sendSF').removeClass("hide");
	} else {
		$('#loginSF').removeClass("hide");
	}

	$('#loginSF').on('click', function(){
		// Make sure jsForceConn is set and that we're logged in.
		if (jsforce.browser.isLoggedIn() === false || jsForceConn === null) {
			jsforce.browser.login(config,"");
		}
	});
	
	$('#logoutSF').on('click', function(){
		jsforce.browser.logout(salesforceConnection);
		location.reload();
	});
	
	$('#sendSF').on('click', function(){
		jsforce.browser.init(salesforceConnection);
		custIdent = "exampleID";

		records = [];
		salesforceConnection.query("SELECT Id FROM Account Where Company_Number__c = '" + custIdent + "'", function(err, result) {
			if (err) { return console.error(err); }
			
			// Loop through results and call SF api to update flag to true
			for (var i = 0; i < result.records.length; i++) {
				updSendFlag(result.records[i].Id, true);
			}
		});
		
		location.reload();
	});
	
	function updSendFlag(accountId, updValue) {
		salesforceConnection.sobject("Account").update({ 
			Id : accountId,
			Send_Comms__c : updValue
		}, function(err, ret) {
			if (err || !ret.success) { return console.error(err, ret); }
			console.log('Updated Successfully : ' + ret.id);
		});
	}
});

Here's a barebones version of my HTML:

<!DOCTYPE html>
<html>
  <head>    
    <script src="/b2b/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="/b2b/js/jsforce_custom.js" type="text/javascript"></script>
    <script src="/b2b/js/myExternalProgram.js" type="text/javascript"></script>
  </head>
  <body>
	<div>
	  <a href="#" class="hide" id="loginSF"><span key="">Login to Salesforce</span></a>
	  <a href="#" class="hide" id="sendSF"><span key="">Send to Salesforce</span></a>
	  <a href="#" class="hide" id="logoutSF"><span key="">Log out of Salesforce</span></a>
	</div>
  </body>
</html>

In this example, I am working with the Account object. First I am querying the Account object to get the Id of any records that match. Then I'm looping through the matching records and using the single record Update API to update that record. 

The jsforce library is super easy to work with once I figured out how to use it via client side JS. Thanks to whoever wrote and maintains it.
