### ISSUE TITLE
Intermittent invalid_grant error when trying to refresh accessToken

### ISSUE THREAD

**Issue by bhavyama** [jsforce/jsforce#1170]
We are initialising jsforce object with the following code:
```js
self.sfconn = new jsforce.Connection({
    oauth2: {
        clientId: clientId,
        clientSecret: clientSecret,
        redirectUri: redirectUri,
        loginUrl: instanceUrl
    },
    instanceUrl: instanceUrl,
    accessToken: accessToken,
    refreshToken: refreshToken,
    logLevel: 'ERROR',
    version: apiVersion
})
```
The apiVersion is set to "51.0". 

We are using [REST based API ](https://developer.salesforce.com/docs/atlas.en-us.230.0.chatterapi.meta/chatterapi/connect_resources_files_information.htm)and passing the accessToken like this:
```js
headers: {
    Accept: 'application/json',
    Authorization: `Bearer ${sfconn.accessToken}`
}
```

If we get a 401 statusCode from the endpoint call then we refresh the **accessToken** using
```js
sfconn.oauth2.refreshToken(sfconn.refreshToken, (refreshTokenErr, results) => {
    if (refreshTokenErr) {
        // Logic to add this in our application's logs
    } else {
        sfconn.accessToken = results.access_token
        // retry the request with new access token
        req.headers.Authorization = `Bearer ${sfconn.accessToken}`
        // Other processing logic that will retry the endpoint call
    }
})
```

However, **intermittentently** we get the following error:

``` json
{
	"message": "expired access/refresh token",
	"stack": "invalid_grant: expired access/refresh token\n at /home/vcap/deps/0/node_modules/jsforce/lib/oauth2.js:198:19\n at tryCallOne (/home/vcap/deps/0/node_modules/promise/lib/core.js:37:12)\n at /home/vcap/deps/0/node_modules/promise/lib/core.js:123:15\n at flush (/home/vcap/deps/0/node_modules/asap/raw.js:50:29)\n at /home/vcap/deps/0/node_modules/async-listener/glue.js:188:31\n at processTicksAndRejections (internal/process/task_queues.js:75:11)",
	"name": "invalid_grant"
}
``` 
We were not able to reproduce this considering this is intermittent behaviour. 

From https://jsforce.github.io/document/ link we know that `If a refresh token is provided in the constructor, the connection will automatically refresh the access token when it has expired.` Since we are maintaining the connection why are we getting this error?

**Comment by theteladras** [comment]
This sounds like a known issue where salesforce will only allow 5 active oAuthed applications. Which means that for every additional connection it will invalidate previous connection credentials.

> A given user may only have 5 access tokens authorized for a given connected app. Since each refresh token can potentially issue an access token, they are counted in that total. The way to think about this is that only the most recent 5 authorizations are valid. When the user goes through login the sixth time, the oldest authorization is invalidated and that refresh token will no longer work.

Referenced from [here](https://salesforce.stackexchange.com/questions/65590/connected-app-avoiding-a-limit-on-a-number-of-issued-tokens-token-expiration#:~:text=A%20given%20user,no%20longer%20work.).
