### ISSUE TITLE
Does JSForce support upsert with Bulk API?

### ISSUE THREAD

**Issue by dicksonstephen** [jsforce/jsforce#1171]
I found an old issue from 2015 that was closed without comment, and the documentation still doesn't mention upsert with Bulk API.

**Comment by RBee9** [comment]
Also looking for that answer

**Comment by paustint** [comment]
Yes, upsert is supported with the bulk API.

More information can be found in the JSForce api documentation: https://jsforce.github.io/jsforce/doc/Bulk.html#load

**Comment by RBee9** [comment]
I found that you need to specify it in the following way:
```
[
  {
    Project_Series__c: line.ProjectSeries,
    Staff_Code__c: line.StaffCode,
    'Budget__r.Name': line.BudgetCode, // 'relationshipName__r.externalIDField'
  },
  { ... },
  ...
]
```

**Comment by paustint** [comment]
What you are showing is extremely useful, but  it is not an upsert.
An upsert is where you create or insert a record.

What you are showing is how to create a lookup to a related record by using an external Id - documentation is here: https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/datafiles_csv_rel_field_header_row.htm

**Comment by RBee9** [comment]
@paustint Thats true. It's not complete. I got stuck when I tried to find out how to specify lookup fields for a bulk upsert. 

Here is how you would do it:
```
var job = conn.bulk.createJob("Account", "upsert", { extIdField: 'CUSTOMERID__c' });
job.createBatch().execute([
  {
    Project_Series__c: line.ProjectSeries,
    CUSTOMERID__c: line.CustomerID,
    'Budget__r.Name': line.BudgetCode, // 'relationshipName__r.externalIDField'
  }
]
)
```

**Comment by JonathanHemnes** [comment]
@paustint I have it working as follows:

```
      this.connection.sobject("Opportunity").upsertBulk(proposalDTO, "ProposalOrderId__c", (err, result) => {
        salesforceUpsertLogger.duration("Proposal upsert timing:", Date.now() - start);
        if (err) {
          salesforceUpsertLogger.error("Failed to upload proposals to Salesforce", err);
          return reject("Failed to upload proposals");
        }
        return resolve(result);
      });
```

I am struggling with a problem where the job wont close reliably, however, once the upload is complete.

**Comment by cristiand391** [comment]
Closing this as jsforce >= v1 supports bulk upserts.
