### ISSUE TITLE
CORS Issue with local React app

### ISSUE THREAD

**Issue by alechko** [jsforce/jsforce#1172]
Hi, I'm trying to use jsforce with a local React app but it seems to be blocked by CORS issue:

```
Access to XMLHttpRequest at 'https://login.salesforce.com/services/Soap/u/42.0' from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

request.js:35 POST https://login.salesforce.com/services/Soap/u/42.0 net::ERR_FAILED

Error: Access Declined
    at connection.js:1552
```

I'm using the following code to test jsforce:

```
...
import jsforce from 'jsforce'

useEffect(() => {
    var conn = new jsforce.Connection();
    conn.login('USERNAME', 'PASSWORD', function(err, res) {
      if (err) { return console.error('login', err); } // <-- fails here
      conn.query('SELECT Id, Name FROM Account', function(err, res) {
        if (err) { return console.error(err); }
        console.log(res);
      });
    })
  return () => {
  }
}, [])
...
```

I have added `https://localhost:3000` to CORS settings in the org:
![image](https://user-images.githubusercontent.com/1391846/129887733-ae0b0ad3-4d63-4229-aff4-b46fbcdf725a.png)

The USERNAME and PASSWORD are correct and I've tested them with the cli version of jsforce, but the React app fails to login.

Any idea what's wrong with my setup and how can I overcome this?

**Comment by stomita** [comment]
CORS setting is not applied to the login, you need to get the access token by OAuth2 or something.

**Comment by alechko** [comment]
thanks for the reply @stomita, just verify, [the official node.js docs](https://jsforce.github.io/document/#connection) states that:
```
When you have a Salesforce username and password (and maybe security token, if required), you can use Connection#login(username, password) to establish a connection to Salesforce.
```

So this basically is not possible and I have to register my local app as a Connected App and use the OAuth2?

**Comment by cristiand391** [comment]
triaging old issues..

The CORS allowlist doesn't support the SOAP API:
https://help.salesforce.com/s/articleView?id=sf.extend_code_cors.htm&type=5tria

you need to use a CORS proxy like: https://github.com/jsforce/jsforce-ajax-proxy/
