### ISSUE TITLE
Concurrency limitations when accessing Lead with sobjects?

### ISSUE THREAD

**Issue by jamesliupenn** [jsforce/jsforce#1177]
Hi folks, I am running this code that uses `jsforce` to interact with Salesforce Lead objects. In two different steps, one upserts into the Leads collection, and the next step would require finding the Lead again. I'm failing to trigger the 2nd step occasionally, and according to my logs in these failure cases, the 2nd step triggered before the 1st step (upsert) responded. I'm suspecting that Salesforce isn't allowing me to read that Lead when another operation is concurrently updating it. Is this an expected behavior?

**Comment by cristiand391** [comment]
triaging old issues...

not sure what error exactly you were getting, will close for now but if anyone finds something simliar please post the full error message and how the upserts are done.
