### ISSUE TITLE
Exceeded max limit of concurrent call in Multiple record retrieval

### ISSUE THREAD

**Issue by haani104** [jsforce/jsforce#118]
Hi,

I am using sandbox account.

Whenever I try to fetch records data through CRUD Multiple record retrieve I get **Exceeded max limit of concurrent call**

I looked into retrieve method in connection.js from where the error was coming.

The check which throws this response is 
 if (ids.length > self.maxRequest) {

on watching these, self.maxRequest comes out as **10**, however my ids.length comes as 19. Where 19 is the number of records I am trying to fetch.(Array containing 19 Lead Id)

I am sure that self.maxRequest is **Concurrent API Request Limit**.

What should one do if he/she needs to fetch data for suppose 100 or 1k leads?

**Comment by sohoki6508** [comment]
I am using jsforce API and retrieving data from Salesforce and I have the same issues regarding "Exceeded max limit of concurrent call". But sometimes the number of limit is changed. So i cannot control it. Is there any solution for this problem?

**Comment by stomita** [comment]
Use bulk API if the records number exceeds the max limit

**Comment by HoangSonTran** [comment]
Thanks @stomita.I am the ghost above. I have deleted my account yesterday and created new one.So i will use bulk API in the link below, is it right?
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_quickstart_set_up_org.htm

**Comment by stomita** [comment]
@HoangSonTran Yes. We also have a wrapper to access the API.
You can call `SObject#insertBulk(records)` instead of `SObject#create(records)`.

**Comment by HoangSonTran** [comment]
I am trying.My main issue is export data from Salesforce into csv file. I am using jsforce, I followed you guide that insert maxRequest to connection. But It doesnt work well. I am not good at  bulk API  :( that is a bad new

**Comment by yinmaster** [comment]
I am using the Bulk API and I am still getting the limit error. Any suggestions on overriding this?
