### ISSUE TITLE
🚨 `conn.describe ("PermissionSet")` Bug : It doesn't return the description of the 'Type' field

### ISSUE THREAD

**Issue by jmsfez** [jsforce/jsforce#1181]
Hi,
When running the following code in a Node.js app, I get the description of all `PermissionSet` fields except the `Type` field.
```
let permissionSetDescribe = await conn.describe ("PermissionSet") ;
console.log (JSON.stringify (permissionSetDescribe, null, 4)) ;
```
I should have the same result as invoking `GET {{instanceURL}}/services/data/{{version}}/sobjects/permissionset/describe` which returns the description of all fields, including the `Type` field?
Can you help me please?
Thanks in advance

**Comment by jmsfez** [comment]
Hi,
😔 It's worse than I thought: it's also impossible to query the `Type` column of the `PermissionSet` object.
When running the following code in a Node.js app, I get the `No such column 'Type' on entity 'PermissionSet'` error.
```
        let query = "SELECT Type, Id FROM PermissionSet" ;
        let queryResponse = await conn.query (query) ;
```
I should have the same result as invoking `GET {{instanceURL}}/services/data/{{version}}/query?q=SELECT Type, Id FROM PermissionSet` which correctly returns the raws, including the `Type` column.

**Comment by paustint** [comment]
@jmsfez - It probably is not a bug, since SFDC is returning the response.

The `Type` field was introduces in version `46.0`, so you are probably using an API version lower than this.

When you are initializing your connection, make sure to explicitly set the version otherwise jsforce will default to a really old API version.

**Comment by jmsfez** [comment]
Ok, thank you @paustint 😉

For those that are interested, it's possible to configure the API version using the Connection constructor like below:
```
        const conn = new jsforce.Connection ({
            instanceUrl: jwtResponse.instance_url,
            accessToken: jwtResponse.access_token,
            version: '52.0' // 🟢 Explicitly define an API Version without the 'v' character prefix
        }) ;
        console.log (`conn.version: ${conn.version}`) ; // 🟢 Display 52.0

```
However, I don't understand why it's not possible to configure the API version using the initialize method like below
```
        const conn = new jsforce.Connection () ;
        conn.initialize ({
            instanceUrl: jwtResponse.instance_url,
            accessToken: jwtResponse.access_token,
            version: '52.0' // 🔴 This doesn't work
        }) ;
        console.log (`conn.version: ${conn.version}`) ; // 🔴 Display 42.0

```
I'll open a case on that 😉
