### ISSUE TITLE
issue when trying to delete records using tooling api

### ISSUE THREAD

**Issue by explorerInfinite** [jsforce/jsforce#1182]
TypeError: Cannot read property '_toRecordResult' of undefined
>      at C:\Users\12063\node_modules\jsforce\lib\connection.js:1115:21
>      at tryCallOne (C:\Users\12063\node_modules\promise\lib\core.js:37:12)
>      at C:\Users\12063\node_modules\promise\lib\core.js:123:15
>      at flush (C:\Users\12063\node_modules\asap\raw.js:50:29)
>      at processTicksAndRejections (internal/process/task_queues.js:75:11) undefined

I have tried:
conn.tooling.delete("traceFlag", recToDelete,{ allOrNone: false }, function(err, ret) {
          if (err || !ret.success) { return console.error(err, ret); });

Also,

conn.tooling.sobject("traceFlag").delete(recToDelete,{ allOrNone: false }, function(err, ret) {
          if (err || !ret.success) { return console.error(err, ret); });

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
