### ISSUE TITLE
Updating SFDC records triggers lead assignment rules - how to prevent it?

### ISSUE THREAD

**Issue by ph07** [jsforce/jsforce#119]
We have the following problem – when updating custom account fields in SFDC using jsforce library, for some reason it triggers Lead Assignment Rule, but not Workflow rules. Our updates are not relevant to Lead Assignment or Workflow rules,  so can you please suggest the way to prevent triggering Lead Assignment rule (better) or making sure Workflow Rules are triggered as well? We have single default lead assignment rule and multiple workflow rules.

We use 'conn.sobject(type).update(data, function(err, rets)` which calls:

/**
- Update records
  *
- @param {Record|Array.<Record>} records - A record or array of records to update
- @param {Callback.<RecordResult|Array.<RecordResult>>} [callback] - Callback function
- @returns {Promise.<RecordResult|Array.<RecordResult>>}
  */

SObject.prototype.update = function(records, callback) {
  return this._conn.update(this.type, records, callback);
};

When calling the `update` methods (which takes in multiple records), it triggers the lead assignment rules.

**Comment by vishal-grazitti** [comment]
Hi @ph07 

I am trying it with following syntax. But, my default assignment rue is still firing in Salesforce. Can you please help:

conn.sobject("case").update({ 
  Id : '50020000010wwiXAAQ'
}, "Sforce-Auto-Assign: 'FALSE'", function(err, ret) {
  if (err || !ret.success) { return console.error(err, ret); }
  console.log('Updated Successfully : ' + ret.id);
  // ...
});

**Comment by vishal-grazitti** [comment]
Seems like I could make it work. Following should be the right way:

var optionHeader =  {headers: {'SForce-Auto-Assign': 'FALSE'}};

conn.sobject("case").update({ 
  Id : '50020000010wwiXAAQ'
}, optionHeader, function(err, ret) {
  if (err || !ret.success) { return console.error(err, ret); }
  console.log('Updated Successfully : ' + ret.id);
  // ...
});

Thanks.
