### ISSUE TITLE
Query call freezes on expired password error

### ISSUE THREAD

**Issue by matthewsouther** [jsforce/jsforce#1199]
I'm testing a basic JSforce use case in Node.js. I'm able to connect to Salesforce, but for some reason, I'm unable to run a basic query.  The terminal freezes indefinitely as soon as I make a call to `conn.query`.

* Node version: v16.13.0
* jsforce version: 1.10.1
* OS: Windows 10 Enterprise version 1909

Repro code:

```js
import jsforce from "jsforce";
import dotenv from "dotenv";
let SF_USERNAME, SF_PASSWORD;

const runTest = async () => {
  dotenv.config();
  ({ SF_USERNAME, SF_PASSWORD } = process.env);

  // Outputs my username correctly
  console.log("SF_USERNAME: " + SF_USERNAME);

  const config = { loginUrl: "https://test.salesforce.com" };
  const conn = new jsforce.Connection(config);
  await conn.login(SF_USERNAME, SF_PASSWORD);

  // Outputs my user ID correctly
  console.log("Authenticated User ID: " + conn.userInfo.id);

  // When I uncomment the 3 lines below, my terminal freezes indefinitely
  // const { totalSize, records } = await conn.query(
  //  "SELECT Id, Name FROM Account LIMIT 3"
  // );
};

runTest();
```

I'm using `$ node src/test.js` in Git Bash to execute this. I have also tried using the old CommonJS syntax (i.e. `const jsforce = require("jsforce");`) and running the code as a CommonJS script, with the same results.

It all seems straightforward enough. What is the problem here?

  [1]: https://jsforce.github.io/

**Comment by matthewsouther** [comment]
OK, I found the root cause -- **my Salesforce password had expired**.  _Ughhhh..._

I guess if there's an issue here, it's that expired password errors arguably aren't handled that well in `jsforce`.

**Comment by cristiand391** [comment]
closing this...

requests using expired/wrong passwords usually return `Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.` from the server, which jsforce catches as 4xx and throw.
Please file a new issue if you can repro this issue on jsforce v3.
