### ISSUE TITLE
Metadata-AsyncResultLocator#complete() no being called after successful operation

### ISSUE THREAD

**Issue by ArtturiSipila** [jsforce/jsforce#12]
Metadata-AsyncResultLocator#complete() is not being after custom field has been successfully created.

```
 conn.metadata.create('CustomField', customFields).complete(err, res) {
console.log("I will be never called");
}
```

If I check the status with metadata.checkStatus I can clearly see that all the operations have been finished successfully.

**Comment by ssshake** [comment]
totally unrelated but grasping at straws here, there's no documentation on how to create custom fields. The only reference on google is this ticket with the example code above, can anyone help me figure this out? I'm trying to create a customer object and then create custom fields within it.

Thanks,

**Comment by muchavie** [comment]
This took me a day to figure out.   This is a very cool module!   But some documentation here would be helpful.

http://stackoverflow.com/questions/34961032/how-to-add-customfields-in-salesforce-object-using-jsforce-module-using-the-m/36961852#36961852

**Comment by stomita** [comment]
@muchavie The custom fields are created using 'CustomField' metadata type, not 'CustomObject'. The document is to be official Salesforce Metadata API document as JSforce metadata simply wraps it.

**Comment by muchavie** [comment]
The only way I've been able to create new custom fields is via create CustomObject with a fields: element.    I get errors that look like this:

soapenv:Client: Element {http://soap.sforce.com/2006/04/metadata}type invalid at this location in type Picklist


From ...

    let newPicklist = {
              type: 'Picklist',
          fullName: 'Hunting_with_Dogs__c',
       description: 'Subjective Hunting Performance Measure',
        externalId: 'false',
             label: 'Hunting with Dogs',
          picklist:  {
                     sorted: 'false',
             picklistValues:
            [   { default: 'true',  fullName: '0 - No Data' },
                { default: 'false', fullName: '1 - Attacks dogs' },
                { default: 'false', fullName: '2 -' },
                 { default: 'false', fullName: '3 - Attacks some dogs but not others' },
                { default: 'false', fullName: '4 -' },
                { default: 'false', fullName: '5 - Has never attacked even a small dog chasing a rabbit' } ],
             trackTrending: 'false'
        }
  };

    let newField = {
          fullName: 'Hawk__c.dogs__c',
              label: 'Hunting with Dogs',
               type: 'Picklist',
           picklist: newPicklist,
        description: 'Subjective Hunting Performance Measure',
    inlineHelpText: 'Subjectinve measure of how well this bird hunts with dogs.',
    };

In any case examples would be appreciated.  I suspect some people might give up on this interface because they aren't successful at creating fields.

**Comment by muchavie** [comment]
Ah!  Got 'CustomField' to work!

    let newField = {
          fullName: 'Hawk__c.Hunting_with_Dogs__c',
              type: 'Picklist',
       description: 'Subjective Hunting Performance Measure',
         externalId: 'false',
              label: 'Hunting with Dogs',
            picklist:  {
                     sorted: 'false',
             picklistValues:
           [     { default: 'true',  fullName: '0 - No Data' },
                 { default: 'false', fullName: '1 - Attacks dogs' },
                 { default: 'false', fullName: '2 -' },
                 { default: 'false', fullName: '3 - Attacks some dogs but not others' },
                 { default: 'false', fullName: '4 -' },
                 { default: 'false', fullName: '5 - Has never attacked even a small dog chasing a rabbit' } ]
          }
    };

....
    c.metadata.create('CustomField', newField, function(err, result) {
`
