### ISSUE TITLE
Invalid type error when querying Calendar Object

### ISSUE THREAD

**Issue by jkk4999** [jsforce/jsforce#1201]
jsforce throws an error when querying the Calendar object.  Anyone else experiencing this?

var records = [];
conn.query("SELECT Id, Name FROM Calendar", function(err, result) {
  if (err) { return console.error(err); }
  console.log("total : " + result.totalSize);
  console.log("fetched : " + result.records.length);
});

INVALID_TYPE: sObject type 'Calendar' is not supported.
    at h.getError (https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.9.1/jsforce.min.js:3:6245)
    at https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.9.1/jsforce.min.js:3:4595
    at o (https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.9.1/jsforce.min.js:7:20504)
    at https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.9.1/jsforce.min.js:7:21281
    at MutationObserver.r (https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.9.1/jsforce.min.js:4:6460)

**Comment by paustint** [comment]
Calendars were added in api version `45.0` - if you are not specifying an explicit version when you setup jsforce connection then it will default to a much older API version, in which case the error message is correct because `Calendar` does not exist.

**Comment by jkk4999** [comment]
Thank you so much!  Appreciate your help.
