### ISSUE TITLE
How to use the Oauth Refresh token flow

### ISSUE THREAD

**Issue by hollaugo** [jsforce/jsforce#1203]
Hi, 

I am building an app using jsforce, I am trying to implement the refresh token flow but I am not sure it is working for me. Please can you provide an example that explains how to use and store the refresh token back to a database? I am using the example provided in the documentation and it does not work for me. I am using a Postgres database to store the tokens. Even after implementing this, I still get an error after the access token is expired. 

**Error**
`invalid_grant: token validity expired`

Here is my code below 

**Initialization**

```
 let conn = new jsforce.Connection({ 
      logLevel: 'debug',
      oauth2: sfoauth2,
      instanceUrl:'https://na163.salesforce.com/',
      accessToken: sfToken.dataValues.sfAccessToken,
      refreshToken: sfToken.dataValues.sfRefreshToken
    });
```

**Refresh Event and Store Token**

```
 conn.on('refresh', async (accessToken, res) => {
      await console.log('Access token refreshed');
      await console.log(accessToken)

 await Users.upsert({
        userId: user.id,
        sfRefreshToken: res.refreshToken,
        sfAccessToken: res.accessToken
      });
  
      });
```

**Comment by paustint** [comment]
I found that `res` did not have the data that the docs claimed and I think refreshToken will be missing from that (at least is was for me!).

The refreshToken does not change when it is refreshed, so you can keep that as-is in the DB and continue to use it in the future.

Give this a try and let me know if it works.

```diff
 conn.on('refresh', async (accessToken, res) => {
     console.log('Access token refreshed');
     console.log(accessToken)
     console.log(res)

 await Users.upsert({
        userId: user.id,
-        sfRefreshToken: res.refreshToken,
-        sfAccessToken: res.accessToken
+        sfAccessToken: accessToken
      });
  
      });
```
