### ISSUE TITLE
🚨 `conn.metadata.read()` doesn't support 'GlobalValueSetTranslation', and 'StandardValueSetTranslation'

### ISSUE THREAD

**Issue by jmsfez** [jsforce/jsforce#1207]
Hi,
When considering the 'ApexClass' metadata type, I observed the following:
• `conn.metadata.describe()` returns the 'GlobalValueSetTranslation' as a correct org's metadata type.
• `conn.metadata.list([{ type: 'GlobalValueSetTranslation', folder: null }])` returns the correct collection of existing GlobalValueSetTranslation.
However...
• `conn.metadata.read('GlobalValueSetTranslation', ['AnyGlobalValueSetTranslationFullName'])` always throws the following exception
    **soapenv:Client: The content of elements must consist of well-formed character data or markup**
Notice that I observed exactly the same issue with the **'StandardValueSetTranslation'** metadata types.
Is it a known issue?
Thank in advance for your help

**Comment by paustint** [comment]
Works fine for me.

Have you confirmed that you setup your connection with at least API version `38.0` or later as specified as the version when this type was made available?
(versions must be specified as a string in this format when initializing jsforce `52.0`)

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_globalvaluesettranslation.htm

**Comment by jmsfez** [comment]
Yes, `conn.version` returns **"52.0"**.
Do you call it like me, I mean with the `fullName` in the second parameter?

**Comment by paustint** [comment]
yeah, I think I was calling it the same way when I tested it out.

**Comment by jmsfez** [comment]
Ok, I don't know why but it doesn't work for me using the Metadata API with CRUD-Based Calls.
However, It work for me using the Metadata API with File-Based Calls.
Thanks a lot for your help @paustint 😉
