### ISSUE TITLE
🚨 `conn.metadata.read()` doesn't support 'Settings'

### ISSUE THREAD

**Issue by jmsfez** [jsforce/jsforce#1208]
Hi,
When considering the 'Settings' metadata type, I observed the following:
• `conn.metadata.describe()` returns the 'Settings' as a correct org's metadata type.
• `conn.metadata.list([{ type: 'Settings', folder: null }])` returns the correct collection of existing GlobalValueSetTranslation.
However...
• `conn.metadata.read('Settings', ['AnySettingFullName'])` always throws the following exception
    **sf:UNKNOWN_EXCEPTION: type is not a valid metadata type for reading**
Is it a known issue?
Thank in advance for your help

**Comment by paustint** [comment]
It looks like Settings does not appear to be supported with metadata.read (on the Salesforce side)

And I don't think there is a a Tooling object version of settings, so you are going to need to resort to the file-based metadata options.

I think you will need to result to using the file-based metadata api's for working with settings 😭

**Comment by jmsfez** [comment]
Ok, I understand.

Would you be so kind as to tell me **how to retrieve one setting using a Metadata API's file-based call?**

I'm a newbie on both JavaScript and jsforce.

Suppose `conn.metadata.list([{ type: 'Settings', folder: null }])` returns an array with the following element
    `{  "fileName": "settings/FilesConnect.settings", "fullName": "FilesConnect", "type": "Settings"... }`

I would like to synchronously get the details of this metadata in a string.

I tried the following:
```
let metadataDetails = "";
await conn.metadata
    .retrieve({ packageNames: null, singlePackage: true, specificFiles: [  "settings/FilesConnect.settings" ] })
    .stream()
    .on("data", function(data) {
        metadataDetails += data.toString();
    });
```
But it failed with the error
> node:buffer:322
>   throw new ERR_INVALID_ARG_TYPE(
>   ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
>     at new NodeError (node:internal/errors:371:5)
>     at Function.from (node:buffer:322:9)
>     at /Users/jsfez/dev/tools/sftool/node_modules/jsforce/lib/api/metadata.js:774:34
>     at /Users/jsfez/dev/tools/sftool/node_modules/jsforce/lib/promise.js:72:9
>     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
>   code: 'ERR_INVALID_ARG_TYPE'
> }

Then I tried the following which is very similar to what is posted on https://jsforce.github.io/document/#describe-metadata:
```
await conn.metadata
    .retrieve({ packageNames: null, singlePackage: true, specificFiles: [ "settings/FilesConnect.settings" ] })
    .stream()
    .pipe(fs.createWriteStream("./tmp-result.zip"));
```
But it also failed with the same error

Any help would be greatly appreciated

**Comment by paustint** [comment]
Here is an example from my codebase, in typescript, but should give you an idea. `types` is just the result from listMetadata

(Note: this is just the first part, but does not wait for the results to finish).

Salesforce can take anywhere from 1 second to multiple minutes to generate the package.

Assume you have this stored as `types` from a call to `listMetadata` (my code has them stored in a map where the type is the key - but hopefully you can get the gist from my examples)
```json
{
  "Settings": [
    {
      "createdById": "0056g000004tCpaAAE",
      "createdByName": "Austin Turner",
      "createdDate": "1970-01-01T00:00:00.000Z",
      "fileName": "settings/AccountIntelligence.settings",
      "fullName": "AccountIntelligence",
      "id": "",
      "lastModifiedById": "0056g000004tCpaAAE",
      "lastModifiedByName": "Austin Turner",
      "lastModifiedDate": "1970-01-01T00:00:00.000Z",
      "namespacePrefix": "",
      "type": "Settings",
      "manageableState": "unmanaged"
    },
    {
      "createdById": "0056g000004tCpaAAE",
      "createdByName": "Austin Turner",
      "createdDate": "1970-01-01T00:00:00.000Z",
      "fileName": "settings/Account.settings",
      "fullName": "Account",
      "id": "",
      "lastModifiedById": "0056g000004tCpaAAE",
      "lastModifiedByName": "Austin Turner",
      "lastModifiedDate": "1970-01-01T00:00:00.000Z",
      "namespacePrefix": "",
      "type": "Settings",
      "manageableState": "unmanaged"
    }
  ]
}

```

```typescript
export function getRetrieveRequestFromListMetadata(types: MapOf<ListMetadataResult[]>, version: string) {
  // https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieve_request.htm
  const retrieveRequest: RetrieveRequest = {
    apiVersion: version,
    singlePackage: true,
    unpackaged: {
      types: Object.keys(types).map((metadataName) => {
        const members = types[metadataName];
        return {
          members: members.map(({ fullName }) => fullName),
          name: metadataName,
        };
      }),
      version: version,
    },
  };
  return retrieveRequest;
}

const results = await conn.metadata.retrieve(getRetrieveRequestFromListMetadata(types, conn.version));
```

The returned XML is not great for types, I have a simple method I run things through.
This just makes sure that boolean and null are properly structured.

```typescript
export function correctInvalidXmlResponseTypes<T = any>(item: T): T {
  Object.keys(item).forEach((key) => {
    if (isString(item[key]) && (item[key] === 'true' || item[key] === 'false')) {
      item[key] = item[key] === 'true';
    } else if (!Array.isArray(item[key]) && isObject(item[key]) && item[key]['$']) {
      // {$: {"xsi:nil": true}}
      item[key] = null;
    }
  });
  return item;
}

correctInvalidXmlResponseTypes(results)
```

**Comment by jmsfez** [comment]
I got it, thanks a lot for your insights @paustint 😉
