### ISSUE TITLE
Connection "refreshFn" option usage

### ISSUE THREAD

**Issue by Zaporozhec7** [jsforce/jsforce#1213]
I can not find any documentation about "refreshFn" option usage, which is used here - https://github.com/jsforce/jsforce/blob/888edd0ff29d9b4926b16ee5bdacb9b99e773fb8/lib/connection.js#L157 

I have custom OAuth flow because need to have universal implementation for many other OAuth services, additionally to Salesforce,
and this **refreshFn** option seems made exactly for such use cases.

I have tried to get usage from Typescript type defined in "DefinitelyTyped", but it seems to be wrong because the callback signature makes no sense:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a8c15904696a9b95158b0b4160ac825a1c441538/types/jsforce/connection.d.ts#L64

Here seems real signature of callback (I may mistake), but not really clear what should be types of *err* and *res* arguments, especially the last one

https://github.com/jsforce/jsforce/blob/888edd0ff29d9b4926b16ee5bdacb9b99e773fb8/lib/http-api.js#L283

**Comment by mrcampbell** [comment]
Bump!  Stuck here as well

**Comment by GravlLift** [comment]
So as @Zaporozhec7 suspected, it looks like the type definition for `refreshFn`'s callback is wrong. The callback in question gets handled by `SessionRefreshDelegate.refresh`, which in the JS takes as parameters, `err`, `accessToken`, and `res`.

https://github.com/jsforce/jsforce/blob/9cb317cfdbc6c69bfaf9c8497d09dc0af80f5f84/lib/http-api.js#L283-L292

If `err` is falsy, `accessToken` gets set on the connection, and `accessToken` and `refreshToken` will be emitted as a `refresh` event (see @paustint 's post above for an example on handling that event).

So basically, I think the type signature of the `@types/jsforce` package needs to be adjusted from it's current

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0b5cd26be7d5facf78c9d35b0ddc53f9b76ef723/types/jsforce/connection.d.ts#L64
```ts
refreshFn?: ((conn: Connection, callback: Callback<UserInfo>) => Promise<UserInfo>) | undefined;
```
to
```ts
refreshFn?: ((conn: Connection, callback: ((err: Error | null, accessToken: string, res?: unknown) => void)) => Promise<UserInfo>) | undefined;
```
Actually, as far as I can tell, that returned `Promise<UserInfo>` return type [is just dropped and not awaited by the one place in the code that its called](https://github.com/jsforce/jsforce/blob/HEAD/lib/http-api.js#L91), so we could probably get rid of that as well:
```ts
refreshFn?: ((conn: Connection, callback: ((err: Error | null, accessToken: string, res?: unknown) => void)) => unknown) | undefined;
```

**Comment by techieshark** [comment]
Late to the party here but in the example above from @paustint (and from the [JSForce docs](https://jsforce.github.io/document/#access-token-request)) we understand that jsforce can handle the refresh if (and only if) `refreshToken` is given during connection creation. 

However, it seems this is for an Oauth flow involving users. I wonder if the `refreshFn` is still useful when writing server to server code that has no user involvement? (In this case, how does one keep the connection refreshed other than just trying to log in all the time?)

**Comment by cristiand391** [comment]
new session refresh section in docs:
https://jsforce.github.io/document/#session-refresh-handler
