### ISSUE TITLE
EventEmitter is not a constructor

### ISSUE THREAD

**Issue by elchiconube** [jsforce/jsforce#1214]
I just start a project on React and found this error on muy console. Any idea how to fix it?

```
core.js:9 Uncaught TypeError: EventEmitter is not a constructor
    at node_modules/jsforce/lib/core.js (core.js:9:32)
    at __require2 (chunk-U3TMEWQO.js?v=601c5caa:19:44)
    at node_modules/jsforce/lib/browser/jsforce.js (jsforce.js:3:15)
    at __require2 (chunk-U3TMEWQO.js?v=601c5caa:19:44)
    at dep:jsforce:1:16
```

Here's the dependencies on `package.json`
```
  "dependencies": {
    "axios": "^0.25.0",
    "eslint-plugin-jest": "^25.7.0",
    "jsforce": "^1.11.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "styled-components": "^5.3.3"
  },
```

Thanks

**Comment by tehnrd** [comment]
@elchiconube Any luck resolving this? I'm seeing the same thing in a svelte project.

https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

<img width="1128" alt="Screenshot 2024-03-26 at 10 19 50 PM" src="https://github.com/jsforce/jsforce/assets/1007085/d7cf5c8e-46f6-4952-a042-15980ef51b6f">

**Comment by elchiconube** [comment]
> @elchiconube Any luck resolving this? I'm seeing the same thing in a svelte project.
> 
> https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility
> 
> <img alt="Screenshot 2024-03-26 at 10 19 50 PM" width="1128" src="https://private-user-images.githubusercontent.com/1007085/317099056-d7cf5c8e-46f6-4952-a042-15980ef51b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODM4NzYsIm5iZiI6MTcxNjg4MzU3NiwicGF0aCI6Ii8xMDA3MDg1LzMxNzA5OTA1Ni1kN2NmNWM4ZS00NmY2LTQ5NTItYTA0Mi0xNTk4MGVmNTFiNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDgwNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDMzNzFhZDI0YTM3NGE2NTg2ZDRlMDAwYTk2NTEwY2QxY2E0ZDVlZDQ3ZGFkNWVlYWY4ZWJlYmQ3N2I4ODY0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q0dJpkq5LC5uZAOoNlRgGmGkQWVy6wA4cqgUJwG0Jao">

Nop but I've created new projects with last versions and it's fixed.
