### ISSUE TITLE
Importing Jsforce Library causing an error. Uncaught ReferenceError: process is not defined at Object../node_modules/readable-stream/lib/_stream_writable.js

### ISSUE THREAD

**Issue by nirajshelke** [jsforce/jsforce#1222]
Hello,

I am facing an issue **Uncaught ReferenceError: process is not defined at Object../node_modules/readable-stream/lib/_stream_writable.js**  when I am importing jsforce in component. I have attached the Screenshot below

![Screenshot from 2022-02-28 22-38-46](https://user-images.githubusercontent.com/73650079/156027293-df52439e-f18c-4d6f-8d38-d14a3a4c4777.png)

without **import jsforce from 'jsforce'** in code the web page was loading but when I added **import jsforce from 'jsforce'** jsforce library it started throwing this error in browser console and Web page was not loading the content. Kindly help me resolve this issue if anybody is aware of it's reason.

**Comment by jaigupta10** [comment]
I think this issue started occurring with webpack 5. I was able to use JSForce successfully in my previous project but now its not working with the same issue.

This is the part of error I am getting:
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

and suggestion mentioned in below stackoverflow post was not helpful.

https://stackoverflow.com/questions/65894521/webpack-5-node-polyfill-instructions-dont-work

Any help would be appreciated.

**Comment by cristiand391** [comment]
@FeiPengDev can you try setting these polyfills in your webpack config?:
https://github.com/jsforce/jsforce/blob/7c8e6a130a149cc7f310e6628f786f94a98c91b9/webpack.config.js#L5-L11

**NOTE**: those packages should be devDeps in your project.

that webpack config is from the `2.0` branch where we bumped webpack to v5.
