### ISSUE TITLE
Error when upserting entries with umlauts in ID

### ISSUE THREAD

**Issue by ad-si** [jsforce/jsforce#1223]
A few weeks ago upserting Opportunities with a umlaut in its ID stopped working for me.

```js
const upsertResponse = await connection
      .sobject("Opportunity")
      .upsert({Our_ID__c: "with-umlaut-ä"}, "Our_ID__c")
```
 
 yields
 
 ```txt
 ERROR_HTTP_400: Bad Request
at tryCallOne (/workspace/node_modules/promise/lib/core.js:37:12)
at /workspace/node_modules/promise/lib/core.js:123:15
at HttpApi.getError (/workspace/node_modules/jsforce/lib/http-api.js:250:13)
at /workspace/node_modules/jsforce/lib/http-api.js:95:22
at flush (/workspace/node_modules/asap/raw.js:50:29)
at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errorCode: 'ERROR_HTTP_400'
}
```

Directly upserting it on Salesforce with curl works, so it must definitely be something with jsforce.

The only change I can think of that could have caused this are changes in the execution environment (it's running on GCP Cloud Functions). There might have been an upgrade from Node.js 14 to 16 or maybe some other changes?

For the time being I have to switch to manual PATCH requests since I can't get it to work anymore (I also upgraded to jsforce 1.11).

**Comment by cristiand391** [comment]
triaging old issues...

I'm unable to repro this on jsforce v3, `ERROR_HTTP_400: Bad Request` hints it was likely a server error but please open a new issue if this still happens.
