### ISSUE TITLE
http/2 hyperforce cant work with jsforce

### ISSUE THREAD

**Issue by tsabbay** [jsforce/jsforce#1239]
Hi,
This is a heads-up, the new HYPERFORCE is not compatible with the force as it requires http/2.
If one of you wants to maintain the lib let me know as I'm willing to fund this project.

**Comment by stomita** [comment]
@tsabbay Are you using JSforce 1.x ? Try using JSforce 2.0, it should work even in Hyperforce instance (yes I'm using).

**Comment by cristiand391** [comment]
jsforce v2 moved from `request` to `node-fetch` for API requests. On the Salesforce side, we've been using jsforce v2 for ~2 years and haven't heard of any issues from clients on hyperforce.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
