### ISSUE TITLE
Getting empty object on browser for invalid login.

### ISSUE THREAD

**Issue by haani104** [jsforce/jsforce#124]
Hi,

I have implemented Jsforce in nodejs.

I receive an error object on invalid login. On printing that object in console.log(err) results in below o/p in console. 
**Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.**

However when I send this object to client(chrome browser) it shows empty object { }.

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by haydarai** [comment]
@haani104 how did you utilize that code snippet? It always give me `TypeError: err.defineProperty is not a function`

**Comment by cristiand391** [comment]
triaging old issues...

> INVALID_LOGIN: Invalid username, password, security token; or user locked out.

to rule out any Salesforce issue:
1. always set the instanceUrl to your instance domain (not lightning!)
2. if doing username/password login, make sure to append the token to the password.
