### ISSUE TITLE
JWT token authentication doesn't allow subscription for platform events

### ISSUE THREAD

**Issue by anudeepDaliboyina** [jsforce/jsforce#1240]
Our organization is trying to use JSForce's  library for pub/sub implementation with platform events in salesforce. 
We are using JWT certificate based authentication.
We are able to authenticate, get the access token and are able to create a platform event, but not able to subscribe to one using the same authentication means.

We followed all the steps in this documentation:
https://jsforce.github.io/jsforce/doc/Streaming.html#~StreamingMessage

We are able to subscribe using the username, password+security token flow but that isn't something we are looking for.
Is it possible for us to subscribe to a platform using JWT authentication? If yes, how do we do it?

**Comment by stomita** [comment]
@anudeepDaliboyina Yes it should work even in JWT authentication. Just pass the access token and instance url obtained from the token request to the connection instance constructor.

**Comment by cristiand391** [comment]
dup of https://github.com/jsforce/jsforce/issues/1240
