### ISSUE TITLE
Upserting With ExternalId Does Not Set ExternalId

### ISSUE THREAD

**Issue by cwolter97** [jsforce/jsforce#1247]
When calling [upsert(record, extId_Field)](https://jsforce.github.io/jsforce/doc/SObject.html#upsert), the extIdField is not set.

Below is current example. Creating a new record of a custom object, with External ID field EXTID__c. 

The record gets created, but the external id field (EXTID__c) is not set.

```
const newProject = await sfconn.sobject("Project__c").upsert({
            Name: "EXAMPLE",
            RecordTypeId: recordTypeId,
            Account__c: "0016A00000EXAMPLE",
            Lead__c: "0056A00000EXAMPLE",
            EXTID__c: 123456
        }, "EXTID__c")
```

**Comment by cristiand391** [comment]
dup of https://github.com/jsforce/jsforce/issues/1247
