### ISSUE TITLE
*************** Clarity of jsforce future *************** 

### ISSUE THREAD

**Issue by lodossDev** [jsforce/jsforce#1252]
As a community we should get together and look at the current state of jsforce, there are many missing features due to new api's or just bugs @stomita can you clarify what the future is and if you will hand jsforce over?

**Comment by stomita** [comment]
JSforce 2.0 has been in beta for 1.5 years, which almost seems to be ready to be released, but as @amphro noted on #1137 we have several side-works to be officially released (mainly documentation). It takes a lot of human works other than just code-writing. After the release of 2.0, it can be focused to the additional features to be added.

**Comment by cristiand391** [comment]
ref: https://github.com/jsforce/jsforce/issues/1360
