### ISSUE TITLE
errors array contents in response of update?

### ISSUE THREAD

**Issue by haani104** [jsforce/jsforce#126]
Hi,

When updating a single record through 

```
conn.sobject("Lead").update({
    id: 'someId',
    CreatedDt: 'someupdation value'
}, function(err, ret) {
    console.log(rets.errors); //Empty array
});
```

I get ret object which has below format

```
{
    "id": "someId",
    "success": true,
    "errors": []
}
```

On looking into update method definition in connection.js it is given below as

```
noContentResponse: { id : id, success : true, errors : [] }
```

My question is that what could be the content of errors array in case of single record update failure?

**Comment by cristiand391** [comment]
triaging old issues...

the `errors` array will have error objects like in these examples:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/errorcodes.htm?q=error%20handl

jsforce v3 types for those:
https://jsforce.github.io/jsforce/types/types_common.SaveResult.html
