### ISSUE TITLE
ERROR_HTTP_400: Access Declined on jsforce.github.io/document

### ISSUE THREAD

**Issue by Wtrapp** [jsforce/jsforce#1260]
I am getting an error when running a simple requests on the documents page. 

<img width="1396" alt="Screen Shot 2022-07-25 at 3 34 22 PM" src="https://user-images.githubusercontent.com/17165667/180869477-c768a149-792f-4735-94cd-a45327849e01.png">

**Comment by cristiand391** [comment]
I can't repro this, looking at the logs it seems the proxy server was having a bad time.
