### ISSUE TITLE
Trying to get refresh access token 

### ISSUE THREAD

**Issue by ChaudharyRajat** [jsforce/jsforce#1262]
why the code does not pass conn.on('refresh', function(accessToken, result)

 var conn = new jsforce.Connection({
      oauth2: {
        clientId: config.salesforce.clientId,
        clientSecret: config.salesforce.clientSecret,
        redirectUri: config.salesforce.callbackURL
      },
      accessToken: account.salesforce.accessToken.access_token || '',
      instanceUrl: account.salesforce.accessToken.instance_url || '',
      refreshToken: account.salesforce.refreshToken || ''
    });
    // console.log('Connection',conn);
    conn.on('refresh', function(accessToken, result) {
      console.log('Refreshed SFDC Token:', accessToken);
        var newConnection = new jsforce.Connection({
        accessToken: accessToken,
        instanceUrl: result.instance_url
      });

**Comment by IlyaShumyantsev** [comment]
same for me
on "jsforce": "2.0.0-beta.4"
with "jsforce": "1.11.0" it's work fine

**Comment by cristiand391** [comment]
triaging old issues...

expired access tokens are refreshed here (jsforce v3 branch): 
https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/session-refresh-delegate.ts#L55-L57

can someone try setting the logLevel in the connection and see if `Connection refresh completed.` gets logged?
