### ISSUE TITLE
Cannot read properties of undefined (reading '_logger')

### ISSUE THREAD

**Issue by rkrishna-gembrill** [jsforce/jsforce#1265]
When using `batchDescribe` function and if the response has any errors, the error log is failing. Below is the stack trace.
```
TypeError: Cannot read properties of undefined (reading '_logger')
    at /node_modules/jsforce/lib/connection.js:1336:18
    at tryCallOne (node_modules/promise/lib/core.js:37:12)
    at /node_modules/promise/lib/core.js:123:15
    at flush (/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
https://github.com/jsforce/jsforce/blob/9cb317cfdbc6c69bfaf9c8497d09dc0af80f5f84/lib/connection.js#L1336

**Comment by cristiand391** [comment]
triaging old issues...

v1 doesn't receive updates, this method was removed in v2.
