### ISSUE TITLE
Missing where clause whenever it's an object and the value is a jsforce.date

### ISSUE THREAD

**Issue by dhtran91** [jsforce/jsforce#1269]
Missing where clause whenever it's an object and the value is a jsforce.date

`sobject('Account').select('Id, CreatedDate').where({ CreatedDate: jsforce.Date.THIS_WEEK }).toSOQL()`
AND
`sobject('Account').find({ CreatedDate: jsforce.Date.TODAY }, 'Id, CreatedDate').toSOQL()`

## Context
- jsforce v1.11.0

## Expected Behavior
Expected SOQL = "SELECT Id, CreatedDate FROM Account WHERE CreatedDate = TODAY"

## Current Behavior
Actual SOQL ='SELECT Id, CreatedDate FROM Account'

## Failure Information
expression is undefined in soql-builder.js when:
field: 'CreatedDate'
value: { _literal: 'TODAY' }

```
/** @private **/
function createFieldExpression(field, value) {
  // Assume the `$in` operator if value is an array and none was supplied.
  if (_.isArray(value)) {
    return createOpExpression(field, "$in", value);
  }
  // Otherwise, if an object was passed then process the supplied ops.
  else if (_.isObject(value)) {
    var expressions = _.map(value, function (v, k) {
      if (k[0] === "$") return createOpExpression(field, k, v);
    });
    return expressions.join(' AND ');
  }
  // If the value is a scalar, it's an equality condition.
  else return createOpExpression(field, "$eq", value);
}
```

## Possible Solution
```
var expressions = _.map(value, function (v, k) {
  if (k === "_literal") k = "$eq"
  if (k[0] === "$") return createOpExpression(field, k, v);
});
```

## Steps to Reproduce
1. Run command:
    `sobject('Account').select('id,createddate').where({createddate: jsforce.Date.TODAY}).toSOQL()`
    or
    `sobject('Account').find({ createddate: jsforce.Date.TODAY }, 'id,createddate').toSOQL()`

## Workaround
Use any of the $ operator instead.

```
var opMap = {
  $eq: "=",
  $ne: "!=",
  $gt: ">",
  $lt: "<",
  $gte: ">=",
  $lte: "<=",
  $like: "LIKE",
  $nlike: "NOT LIKE",
  $in: "IN",
  $nin: "NOT IN",
  $includes: "INCLUDES",
  $excludes: "EXCLUDES",
  $exists: "EXISTS",
};

sobject('Account')
  .select('id,createddate')
  .where({ createddate: { $eq: jsforce.Date.TODAY }})
  .toSOQL()

sobject('Account')
  .find({createddate: { $eq: jsforce.Date.THIS_WEEK }}, '*')
  .toSOQL()
```

**Comment by cristiand391** [comment]
triaging old issues...

I can't repro this on jsforce v3:

```ts
console.log(await conn.sobject('Account').select('Id, CreatedDate').where({ CreatedDate: jsforce.Date.THIS_WEEK }).toSOQL())
console.log(await conn.sobject('Account').find({ CreatedDate: jsforce.Date.TODAY }, 'Id, CreatedDate').toSOQL())
...
// SELECT Id, CreatedDate FROM Account WHERE CreatedDate = THIS_WEEK
// SELECT Id, CreatedDate FROM Account WHERE CreatedDate = TODAY
```

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
