### ISSUE TITLE
retrieve should allow for specifying fields to retrieve

### ISSUE THREAD

**Issue by kgoerlitz** [jsforce/jsforce#127]
The retrieve function should probably support a fields parameter that takes an array of field names (or a single field name).  If the fields are not specified then all of the fields should be retrieved.

**Comment by techieshark** [comment]
Still useful request.

A work around, with `findOne()`:

```
await connection
      .sobject("Contact")
      .findOne({ Id: idToRetrieve }, {
        Some_Field__c: true,
        Some_BuiltIn_Field: true,
      });
```

or similarly this probably works

```
await connection
      .sobject("Contact")
      .findOne( { Id: idToRetrieve }, ['Some_Field__c', 'Some_BuiltIn_Field'] });
```
