### ISSUE TITLE
Only one error is returned when loading a record

### ISSUE THREAD

**Issue by talbalelty** [jsforce/jsforce#1273]
When I insert records I want to be able to see all the errors that are present in my record's data. It seems the operation moves on to the next record when single error is found.

I plan to provide all the errors on a single record in a single iteration, without having to go back and forth.

![image](https://user-images.githubusercontent.com/46194035/193767260-ead46d7c-886c-42fb-9cfa-af3858e7c4e9.png)

**Comment by cristiand391** [comment]
triaging old issues...

closing this, https://github.com/jsforce/jsforce/issues/861#issuecomment-1275843528

#861 is still valid b/c it's a different API.
