### ISSUE TITLE
This session is not valid for use with the REST API

### ISSUE THREAD

**Issue by matthiaswh** [jsforce/jsforce#1274]
On our sandbox we have started receiving this error message when we try to open a jsforce connection. 

We have tried connecting using both `var conn = new jsforce.Connection({serverUrl : 'https://cs123.salesforce.com', sessionId: '0Dddddd04cT7!AloremipsumLr'});` and `var conn = new jsforce.Connection({serverUrl : 'https://ourdomain--oursandbox.my.salesforce.com', sessionId: '0Dddddd04cT7!AloremipsumLr'});` with the same result.

The same connection code works on production.

My hunch is this might be related to [Enhanced Domains](https://help.salesforce.com/s/articleView?id=sf.domain_name_enhanced.htm&type=5) although we have seemingly done everything required for the actual domain change over.

We get the session ID from a button like so, `https://foo.example.com/sfSession/sessionid={!$Api.Session_ID}/userid={!User.Id}`. Again, this has worked for years on sandbox and continues to work on production.

```
INVALID_SESSION_ID: This session is not valid for use with the REST API
    at HttpApi.getError (/jsforce/node_modules/jsforce/lib/http-api.js:250:13)
    at /jsforce/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/jsforce/node_modules/promise/lib/core.js:37:12)
    at /jsforce/node_modules/promise/lib/core.js:123:15
    at flush (/jsforce/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errorCode: 'INVALID_SESSION_ID'
}
```

**Comment by cristiand391** [comment]
triaging old issues...

please re-open if you can repro with jsforce v3 (looking at the error I think this was an org-related issue, but we did a few changes in the HTTP module so this might have changed).
