### ISSUE TITLE
Streams implementation should be current and interoperable

### ISSUE THREAD

**Issue by curiousercreative** [jsforce/jsforce#1275]
I'd like to wrap a bulk query stream with RxJS, however the stream returned does not conform to the current NodeJS stream implementation. I see we're versioned to [^readable-stream@2.1.0](https://github.com/jsforce/jsforce/blob/master/package.json#L70) which is [more than six years old](https://github.com/nodejs/readable-stream/tree/v2.1.0). Please consider updating.

**Comment by cristiand391** [comment]
triaging old issues...

jsforce >= v2 users the node stream module when running on node and the `stream-browesrify` can be used to polyfill this when running on the browser.
