### ISSUE TITLE
Bulk load method silently fails

### ISSUE THREAD

**Issue by curiousercreative** [jsforce/jsforce#1277]
Code similar to the below never creates a batch. I've tried some variation of function signatures to no avail. Using the more verbose examples from [here](https://github.com/jsforce/jsforce-website/blob/master/src/partials/document/bulk.html.md) does create a batch. Hopefully this saves someone else time.

```javascript 
const accounts = [...];

const batch = conn.bulk.load('Account', 'update', null, accounts);
setTimeout(() => {
  console.info(batch.id); // undefined
}, 5000);

batch.on('queue', console.info); // never emitted
batch.on('error', console.error); // never emitted
batch.on('response', console.info); // never emitted
```

**Comment by cristiand391** [comment]
I'm going to close this, we have an example here showing how you can `await` it to get the records:
https://jsforce.github.io/document/#bulk-api

also tried the code above and got it working on jsforce v3. if someone finds a similar problem please log a new issue.
