### ISSUE TITLE
Where are the latest versions?

### ISSUE THREAD

**Issue by chrisunitt** [jsforce/jsforce#1287]
The latest version of 2.0 in this repository seems to be 2.0.0-beta.9, but the latest SFDX (data plugin 2.1.10) depends on 2.0.0-beta.19

I was looking to grab jsforce to see if I could get PKChunking working for bulk api queries.

Any ideas?

**Comment by riekusr** [comment]
Hi Chris, did you have any luck?  For me it is also unclear how to utilize 2.0 for the BulkAPI V2

**Comment by cristiand391** [comment]
we've automated the release pipeline a while ago, basically each new GH release triggers an npm publish of jsforce so you can  follow https://github.com/jsforce/jsforce/releases.
