### ISSUE TITLE
Upgrade uuid Dependency

### ISSUE THREAD

**Issue by sternam** [jsforce/jsforce#1290]
npm install emits the warning:

npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by cristiand391** [comment]
flagged as `fixed in v3` because `uuid` is no longer a dependency. It does show up as a devDep via request -> jsforce-ajax-proxy, library users don't get jsforce devDeps installed.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
