### ISSUE TITLE
login call succeeds, but the query call is stuck in the 401 loop

### ISSUE THREAD

**Issue by qbert-007** [jsforce/jsforce#1291]
Is there a chance that the login call would succeed but the query will keep returning a 401?
```
const conn = new jsforce.Connection({
  clientId: clientId,
  clientSecret: clientSecret,
  version: "54.0",
  loginUrl: 'https://login.salesforce.com/',
});

conn.login(username, password, function (error, res) {
    if(error){
        console.log('error in login:', error)
    } else{
        conn.query('SELECT Id, Name, OrganizationType FROM Organization', function (err, result){
            if(err){
                console.log('error in query call:', err)
            }else{
                console.log('success')
            }
        })
    }
})
```

We are facing issue in which the login call is successful but the query call fails with a 401, and then another query call is made and a 401 is received; this occurs in a loop. After few hours we receive the below error in callback:
`{ message: 'authentication failure', name: 'invalid_grant', stack: 'invalid_grant: authentication failure\n' + ' at /app/node_modules/jsforce/lib/oauth2.js:198:19\n' + ' at tryCallOne (/app/node_modules/promise/lib/core.js:37:12)\n' } 
`

**Comment by qbert-007** [comment]
Update: We figured out that when `Session Security Level Required at Login` is set to `High Assurance` in the user's profile, the query call gets stuck in a loop and the callback never triggers.

Salesforce throws a `401 Unauthorized` for the above session setting, and there is no handling done for this case in jsforce, and it keeps refreshing tokens here: https://github.com/jsforce/jsforce/blob/master/lib/http-api.js#L90 and never call the callback fn.

**Comment by qbert-007** [comment]
Can this issue be addressed?

**Comment by qbert-007** [comment]
This issue is critically impacting our integration. @stomita Could this please be acknowledged and fixed?

**Comment by samschurter** [comment]
Running into the exact same issue, came to the same conclusion on the same line number. Is this library maintained anymore or is it dead?

**Comment by dtto86** [comment]
Faced similar issue for `describe()` function call when expired credentials were used in `login()` function.

These PR changes https://github.com/jsforce/jsforce/pull/1345 were able to fix the issue related to expired credentials.

Also, tried this PR https://github.com/jsforce/jsforce/pull/1301 changes. They worked as expected when High Assurance session setting was enabled in User's Profile.

@stomita Is it possible to merge these changes in version 1.x.x or they have been addressed in version 2.x.x?

**Comment by cristiand391** [comment]
closing in favor of https://github.com/jsforce/jsforce/issues/1411
