### ISSUE TITLE
Login succeded but on query read ECONNRESET

### ISSUE THREAD

**Issue by NerdyBear90** [jsforce/jsforce#1292]
Since today i got an issue.
The login works Prober, but when it starts to trigger the query I will return 
```
 Error: read ECONNRESET
[1]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
[1]     at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
[1]   errno: -4077,
[1]   code: 'ECONNRESET',
[1]   syscall: 'read'
[1] }
```

using jsforce 1.11.0
and node 16

Here is the sourcecode
```
conn.login(secret.sfUser, secret.sfPass, function (err, result) {
        if (err) {
          return console.error(err);
        }
        console.log("Logged in");
        conn.query(`Select KerberosCustomerId__c, Id, Name, MainIndustry__c, SubIndustry__c FROM Account Where KerberosCustomerId__c='${kerberosId}'`, function (err, result) {
          if (err) {
            return console.error(err);
          }
```

**Comment by FelixHarvey** [comment]
Did you end up finding a resolution for this issue?

**Comment by cristiand391** [comment]
sometimes the org connection is flaky and you get these network errors, jsforce v3 will try on these (5 times by default) to rule out intermittent failures.

If you can repro consistently this issue on v3 please open a new issue, it might be that it's missing the instance URL when instantiating the `Connection` object.
