### ISSUE TITLE
How to delete large numbers / all from Custom object?

### ISSUE THREAD

**Issue by billnbell** [jsforce/jsforce#1300]
I did not see this, and wanted to share with others. You can delete 10,000 at a time using Tooling. This beats 200 at a time and is simpler.

```
const destroyAllBulk = (conn: jsforce.Connection) =>
  new Promise((resolve, reject) => {
    const apexBody =
      'delete [SELECT Id from Object__c LIMIT 10000];';
    conn.tooling.executeAnonymous(apexBody, (err, res) => {
      if (err) {
        console.log(err);
        return reject(err);
      }
      console.log(res);
      return resolve(res);
    });
  });
```

**Comment by cristiand391** [comment]
triaging old issues...

thanks for the example!
for reference, jsforce also supports the bulk v2 API which can be used for big delete operations too:
https://jsforce.github.io/document/#bulk-v2-api
