### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by tarastarchanyn** [jsforce/jsforce#1304]
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at new Buffer (buffer.js:290:17)
    at /root/syncV3-testing/node_modules/jsforce/lib/api/metadata.js:776:27
    at /root/syncV3-testing/node_modules/jsforce/lib/promise.js:72:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
`

Sometimes when calling `metadata.retrieve(anyParams).stream()` above error occurred. After short investigation the root cause was found. 
Extra error check should be done [here](https://github.com/jsforce/jsforce/blob/master/lib/api/metadata.js#L774) 
With current setup if error is thrown it became unreachable for any catch block or `.on('error', (error) => {})` error listener on stream it self.

Please consider to look at the issue

**Comment by DenisBuymistrjuk** [comment]
Facing the same issue

**Comment by LesiaMyronchuk** [comment]
Yes, also experiencing the same.

**Comment by vladdemianiv** [comment]
The same for me, please fix it.

**Comment by cristiand391** [comment]
could someone using jsforce v3 provide a repro or debug logs when this happens?

that error means `result.zipFile`wasn't a string, could be the server that returns something jsforce isn't parsing correctly.

**Comment by cristiand391** [comment]
nvm, closing as dup of https://github.com/jsforce/jsforce/issues/1302
