### ISSUE TITLE
Mismatch API version between jsforce and Flow

### ISSUE THREAD

**Issue by akedalat** [jsforce/jsforce#1305]
When creating a Flow using jsforce, I hard code API v55 in the `version` property when initializing the jsfroce connection, but my flow gets created in API v49. Please see the `version` in the following code: 

```
const jsforce = require('jsforce');

const metadata = {
	fullName: 'someName',
	label: 'someName',
	actionCalls: [
		{
			name: 'someName',
			label: 'someName',
			locationX: 100,
			locationY: 400,
			actionName: 'actionName',
			actionType: 'outboundMessage',
		},
	],
	start: {
		locationX: 50,
		locationY: 50,
		connector: {
			targetReference: 'someName',
		},
		object: input.object,
		recordTriggerType: input.record_trigger_type,
		triggerType: 'RecordAfterSave',
		filterFormula: input.filter_formula,
	},

	status: 'Active',
};

module.exports = input => {
	return new Promise((resolve, reject) => {
		const conn = new jsforce.Connection({
			instanceUrl: input.instance_url,
			accessToken: input.access_token,
			version: '55.0', // ADDED V55
		});
		conn.metadata.create('Flow', metadata, (err, result) => {
			if (err) {
				reject(err);
			} else if (result && result.errors) {
				reject(result);
			} else {
				resolve(result);
			}
		});
	});
};

```

A Flow gets created successfully but when I check the API version on Salesforce, it points to 49 (see screenshot)

<img width="598" alt="Screen Shot 2023-02-08 at 15 38 46" src="https://user-images.githubusercontent.com/32881481/217577600-741eb517-e8bf-4264-8633-70de07130156.png">

How can I create a Flow using the version I defined in my jsforce object?

**Comment by kevintechie** [comment]
Have you tried setting `apiVersion` in the metadata? I don't think that the version in the connection carries over to the default Flow execution context. https://developer.salesforce.com/docs/atlas.en-us.242.0.api_meta.meta/api_meta/meta_visual_workflow.htm

**Comment by akedalat** [comment]
That fixed it! Thanks very much Kevin
