### ISSUE TITLE
Do we have a list of published error code?

### ISSUE THREAD

**Issue by gohlance** [jsforce/jsforce#1309]
Hi All,

I am looking for a list of status error code, can seems to locate it. If anyone can point me in the right direction.

**Comment by cristiand391** [comment]
triaging old issues...
jsforce doesn't have standardization errors across the code, sometimes you get a simple `Error`, sometimes a specific one like this:
https://github.com/jsforce/jsforce/blob/52aeb9a935b8495edbf432efb2b0c1df3b365f30/src/api/bulk2.ts#L140
