### ISSUE TITLE
Changelog out of date.

### ISSUE THREAD

**Issue by genio** [jsforce/jsforce#1314]
Changelogs are the way most of us look through changes to see what might break for us. Any chance you could update the log to make it easier?

**Comment by cristiand391** [comment]
labeling as bug to ensure we re-enable changelog in the release workflow in v3

**Comment by cristiand391** [comment]
closing this, changelog should be updated by the GHA release workflow:
https://github.com/jsforce/jsforce/blob/main/CHANGELOG.md
