### ISSUE TITLE
Vulnerability detected by Snyk: Prototype Pollution in depedency xml2js

### ISSUE THREAD

**Issue by lchnnl** [jsforce/jsforce#1321]
Snyk has identified a _high severity_ vulnerability in package xml2js.

https://security.snyk.io/vuln/SNYK-JS-XML2JS-5414874

---
### Overview

Affected versions of this package are vulnerable to Prototype Pollution due to allowing an external attacker to edit or add new properties to an object. This is possible because the application does not properly validate incoming JSON keys, thus allowing the __proto__ property to be edited.

---
 
Suggested solution is to upgrade xml2js to version 0.5.0 or higher.

I see that version 2.0.0 is already using the suggested version. Could this package be upgraded for v1.11.x?

**Comment by cristiand391** [comment]
Hi @lchnnl.
We'll patch v1 too, see: https://github.com/jsforce/jsforce/issues/1318#issuecomment-1513766100

**Comment by cristiand391** [comment]
@lchnnl just published jsforce v1.11.1 with xml2.js 0.5.0.
