### ISSUE TITLE
Please update xml2js version to 0.5.0 to remove the security vulnerability

### ISSUE THREAD

**Issue by praveendiwakar1** [jsforce/jsforce#1322]
There is a CVE in xml2js@0.4.23 which is getting pulled in via jsforce@1.11.0.
Please update the xml2js version to 0.5.0 [latest] to resolve this issue. Currently it is consuming `xml2js": "^0.4.16"`

**Comment by cristiand391** [comment]
Closing as dup of https://github.com/jsforce/jsforce/issues/1321
