### ISSUE TITLE
[V2] SimpleType not handled well under latest metadata WSDL

### ISSUE THREAD

**Issue by Yoshihisa-Matsumoto** [jsforce/jsforce#1330]
When I execute wsdl2schema.ts (2.0/src/api/wsdl/wsdl2schema.ts) and imported latest metadata WSDL ver58, 
it didn't handle simpleType restriction very well.

I checked the program, and found extractComplexTypes function was root cause.

From: (Line#180)
const rs = simpleType.restriction ?? simpleType['xsd:restriction'];

To:
let rs = simpleType.restriction;
if (rs.$.base.length == 0 || !rs.$.base.includes(':'))
    rs = simpleType['xsd:restriction'];

simpleType.restriction is not empty and simpleType.restrinction.base has empty string 
So original code returned base type as undefined , which caused tons of typescript error on generated file.

**Comment by Yoshihisa-Matsumoto** [comment]
detail :
some simpleType JSON would be as follows.
as you see, restriction.$.base is empty string, so original code always set 'undefined'

{
  '$': { name: 'ID' },
  'xsd:restriction': {
    '$': { base: 'xsd:string' },
    'xsd:length': [Object: null prototype] { '$': [Object: null prototype] },
    'xsd:pattern': [Object: null prototype] { '$': [Object: null prototype] },
    enumeration: [],
    'xsd:enumeration': []
  },
  restriction: { '$': { base: '' }, enumeration: [], 'xsd:enumeration': [] }
}

**Comment by cristiand391** [comment]
for referece:

we haven't touched the wsdl2schema code too much in v3 but created a new Salesforce-owned package that generates these types from the WSDLs maintained in https://github.com/forcedotcom/wsdl, see:

https://github.com/jsforce/jsforce/discussions/1530
