### ISSUE TITLE
v2 tags/releases are no longer created in Github since 2.00-beta.9

### ISSUE THREAD

**Issue by RupertBarrow** [jsforce/jsforce#1333]
Is there a reason ?
We are now on 2.0.0-beta.23, according to commit history and npmjs.com.

**Comment by cristiand391** [comment]
Hey, sorry for the late reply.

Until a few months ago this was a manual process (publish to npm, create GH release, etc), current beta is 2.0.0-beta.27 and it's missing the tags/GH release b/c it was done from a machine (IIRC, Shinichi fixed a regression).

This is automated now with GH actions (see release by the svc-cli-bot-jsforce account): https://github.com/jsforce/jsforce/releases?q=2.0.0-beta&expanded=true

**Comment by RupertBarrow** [comment]
Currently, the latest release is 2.0.0-beta.25, but the latest tag is 2.0.0-beta.27
Is there still a manual operation to release, or another reason ? [asking for a friend interested in CD 😉]
