### ISSUE TITLE
Consolidate the JWT authorization to `Connection#authorize()`

### ISSUE THREAD

**Issue by stomita** [jsforce/jsforce#1334]
@WillieRuemmele 
I recently noticed the code for JWT authorization support in #1249, after I recently added the change of `authorize()` to support grant types other than authorization code (#1331). The code I updated also works for JWT grant, and works as same as your implementation as it doesn't include bearer token generation. I think it is better not to have a special entry point to support each grant types, so I would like to eliminate the `jwtOAuth` implementation from the code. 

As 2.0 is still in beta, and the change was brought in the beta period, I hope we could ignore the compatibility issues, do you have any concerns ?

**Comment by WillieRuemmele** [comment]
Hi @stomita 

I'm not opposed to consolidating methods as long as all functionality will remain the same.

As far as removing it while in the beta period: I think it's _ok_... but I know `sfdx-core` has a few dependencies on this method that would need to be addressed as soon as that new version is released

https://github.com/search?q=repo%3Aforcedotcom%2Fsfdx-core%20jwtOauth&type=code

**Comment by stomita** [comment]
@WillieRuemmele thanks for your comment. I would like to include it in next beta release (beta 23).
