### ISSUE TITLE
ConnectedApp creation via connection.metadata.create() issues

### ISSUE THREAD

**Issue by WillieRuemmele** [jsforce/jsforce#1348]
https://github.com/forcedotcom/cli/issues/2203

**Comment by cristiand391** [comment]
can't repro this 😁 

with `isAdminApproved` set to `true/false`:

![Screenshot 2024-06-07 at 7 15 52 PM](https://github.com/jsforce/jsforce/assets/6853656/181e1850-6855-4877-93c8-ae41ce27a01a)

this was probably fixed in jsforce v2

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
