### ISSUE TITLE
Non-standard login URLs break authentication

### ISSUE THREAD

**Issue by bluelhf** [jsforce/jsforce#1352]
# Issue Description

When the Salesforce instance URL is a subdomain of `lightning.force.com` (a perfectly valid instance URL), HTTP authentication breaks.

## Cause

This issue is caused by JSForce's use of the [`request`](https://www.npmjs.com/package/request) NPM package as a HTTP client, which **has been deprecated for over three years.**

1. Salesforce responds to requests to `lightning.force.com` with a <kbd>302 Found</kbd> redirect.
2. The `request` HTTP client breaks HTTP specification and loses the request method and body after **all non-307 redirects** .
3. Since it's forgot about the request method, `request` makes a GET request to the SOAP login endpoint, to which Salesforce responds with an error.

## Steps to reproduce

1. Set up a Salesforce instance.
2. Attempt to log in to the instance via JSForce using the `lightning.force.com` URL and appropriate credentials
3. See the error response from JSForce:
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 405 Only POST allowed</title>
</head>
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /services/Soap/u/42.0. Reason:
<pre>    Only POST allowed</pre></p><hr /><br/>
<!----- 8< snip ! 8< ----->
```
5. Cry

## Proposed Solution

In `v2`, JSForce will use `node-fetch`. Yay!

For now, a quick hack would be to rewrite the login URL domain from `lightning.force.com` to `my.salesforce.com`.

**Comment by paustint** [comment]
Yes, [enhanced domains](https://help.salesforce.com/s/articleView?id=sf.domain_name_url_format_changes_enable_enhanced.htm&type=5) changed the url structure for accessing salesforce.

**Comment by gmillerd** [comment]
I have never used our domains and instead used just login.salesforce.com and test.salesforce.com and have the login username do the work. Is there a gap in doing this?

**Comment by paustint** [comment]
@gmillerd - there is no gap, but many orgs disable login through these URLs and require going through the custom domain.

And IMO, this ticket is invalid, the login URL for a domain is not the `.lightning` subdomain, it is either `login.salesforce.com` or `test.salesforce.com` or the actual instance domain.

Salesforce calls out the login domain explicitly in the docs https://help.salesforce.com/s/articleView?id=sf.domain_name_url_format_changes_enable_enhanced.htm&type=5

**Comment by cristiand391** [comment]
> And IMO, this ticket is invalid, the login URL for a domain is not the .lightning subdomain, it is either login.salesforce.com or test.salesforce.com or the actual instance domain.

true, in the Salesforce CLI we throw if a user is trying to log in using a lightning domain URL, we can prob do the same in jsforce:
<img width="1792" alt="Screenshot 2023-10-03 at 11 39 25" src="https://github.com/jsforce/jsforce/assets/6853656/06554ef6-395e-4666-a81e-dd2a583a141c">

**Comment by cristiand391** [comment]
labeled as a feature to make jsforce validate and throw if a lightning URL is passed as `instanceUrl`.

W-15748051 (internal Salesforce id to track this)

**Comment by LoganTann** [comment]
Dirty fix (my current implementation) : 
- Open the oauth login popup from the user-provided url (ie. possibly lightning url)
- Redeem the token on both login.salesforce.com and test.salesforce.com
- The login response gives then both the "access_token" and the "instance_url" in my.salesforce.com format, allowing me to fix the final url.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
