### ISSUE TITLE
jsforce.github.io API Reference link is dead

### ISSUE THREAD

**Issue by msouther-lisc** [jsforce/jsforce#1363]
I use the jsforce API Reference a lot. It's linked in the GitHub Pages site nav:

![image](https://github.com/jsforce/jsforce-website/assets/123027648/bd25a3c1-0e71-49f1-8217-25fcc3650ddd)

But the link is dead now 😢:

![image](https://github.com/jsforce/jsforce-website/assets/123027648/5101cc03-88e6-4189-b93b-54d60bb7d9a8)

Is it gone forever? Where can I find it?

**Comment by cristiand391** [comment]
oh sorry, I swapped the branch to test the docs for jsforce v2:
https://jsforce.github.io/jsforce

v1 is here: https://jsforce.github.io/jsforce/v1/ 

but let me revert that until the GA, we'll keep v1 docs under that link 👍🏼
