### ISSUE TITLE
Incomplete type definition for oauth2.requestToken() return value.

### ISSUE THREAD

**Issue by LoganTann** [jsforce/jsforce#1366]
## Context

When working with a developer sandbox, the `instanceUrl` must be in the form of `{yourSandbox}.sandbox.my.salesforce.com` instead of `{yourSandbox}.sandbox.lightning.force.com` (otherwise, any API calls will result in an INVALID_SESSION_ID 401 error).

To avoid this mistake, the `/oauth/token` endpoint returns the access token, but also the `instance_url` property.

## Issue

The `oauth2.requestToken()`'s return type is `TokenResponse`, an interface with the following properties : 

```ts
export interface TokenResponse {
    access_token: string;
    refresh_token: string;
}
```

However, it differs to what Salesforce is really returning.

## Possible fix

I suggest changing the TokenResponse definition type to this : 

```ts
export interface TokenResponse {
    access_token: string;
    refresh_token?: string;
    id_token?: string;
    signature: string;
    scope: string;
    instance_url: string;
    id: string;
    token_type: string;
    issued_at: string;
}
```

It's based on this help article (https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_web_server_flow.htm&type=5), but I couldn't find the real API reference.

## Workaround

Create a custom type, and cast the return value to that type.

**Comment by LoganTann** [comment]
Ooh, I see. 

@cristiand391  Should I keep this issue open then ?

**Comment by cristiand391** [comment]
let's leave it open in case anyone wants to fix it in `@types/jsforce`, I'll close in once jsforce v3 is GA since you'll no longer need `@types/jsforce` 👍🏼

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
