### ISSUE TITLE
Any connection events ?

### ISSUE THREAD

**Issue by bacloud23** [jsforce/jsforce#1372]
I would like to implement a retry mecanism, 
I assume `Jsforce.Connection` is the object to start with.

I see it extends a `EventEmitter`.. So what I'm trying (expecting in a way) is something like this:

```js
connection.on('connection', function () {
  this.logger.log('@@@@@ Connected to Salesforce @@@@');
});

connection.getConnection().on('disconnect', function () {
  this.logger.log('@@@@@ Disconnected from Salesforce @@@@');
});

// there is only 'connection:new' being emitted in the code as far as I searched, but it does not work neither
```

I don't know if these are events proposed by JSForce, these are not typed, 
Furthermore Is this the right way ? to handle reconnections ?

Thanks to everyone in advance.

**Comment by cristiand391** [comment]
hey, sorry for the late reply, triaging old issues.

the `connection:new` event is emitted when creating an instance of `Connection` on the `jsforce` class, not on API requests.
Were you trying to handle network errors? If so, jsforce v3 added support for retrying on common network errors:
https://github.com/jsforce/jsforce/blob/573b869aff8a4ad01d0969c64c1590383326cc6d/src/request.ts#L53

`connection:new`
https://github.com/jsforce/jsforce/blob/573b869aff8a4ad01d0969c64c1590383326cc6d/src/connection.ts#L403
