### ISSUE TITLE
Bulk API v2 - upsert support

### ISSUE THREAD

**Issue by John4tMOS** [jsforce/jsforce#1373]
Hi, wanted to know the eta for supporting `upsert` operation type for bulk api v2.

**Comment by cristiand391** [comment]
Hey @John4tMOS, sorry for the late reply.

jsforce v2 added support for the Bulk API v2, we don't plan to backport it to jsforce v1 as we are working on last details of the next jsforce release (see the pinned issue in the repo).

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
