### ISSUE TITLE
API Reference Documentation Missing

### ISSUE THREAD

**Issue by jsullivanlive** [jsforce/jsforce#1377]
On the main site there is a link for "API Reference" which is currently broken.

On homepage, click this link:
<img width="1320" alt="Screenshot 2023-11-13 at 8 38 38 AM" src="https://github.com/jsforce/jsforce/assets/493648/cf10995e-c6c6-4a68-8907-e9e640af0c3e">

Page not found error:
<img width="1045" alt="image" src="https://github.com/jsforce/jsforce/assets/493648/caaf6245-a2d2-43da-babe-83157f6697d7">

**Comment by cristiand391** [comment]
Hey @jsullivanlive , sorry about that, we switched it to serve docs from the `gh-pages` branch again, https://jsforce.github.io/jsforce/doc/ is up:

dup of: https://github.com/jsforce/jsforce/issues/1363
