### ISSUE TITLE
conn.authorize not getting invoked after upgrading from V1

### ISSUE THREAD

**Issue by jaagaard01** [jsforce/jsforce#1382]
Im trying to do oauth flow that was working perfectly in v1 but im not sure how to migrate to this functionality to newer version. 

Just doing something simple like this 

```
const conn = new jsforce.Connection({ oauth2 })
    return conn.authorize(code, (err, userInfo) => {
      console.log(conn, userInfo, err, 'info')
```

small snippet and it never actually calls the authorize function for me. Never gets the any of the call back values and just times out. 

Any suggestions would be greatly appreciated can provide more code if necessary 

I upgraded to "jsforce": "^2.0.0-beta.29",

**Comment by jaagaard01** [comment]
`   const conn = new jsforce.Connection({
      accessToken: req.headers.tkn,
      instanceUrl: req.headers.instanceurl,
      version: salesforceAPIVersion,
    })
    const [deploymentsData, deploymentsErr] = await conn
      .sobject('PDRI__Deployment_Result__c')
      .find(
        constructFilterQuery({ filterType, filters: parsedFilters }),
        `
          CreatedDate,
          CreatedBy.Email,
          Id,
        `
      )
      .sort({ CreatedDate: -1 })
      .limit(limit)
      .skip((page - 1) * limit)
      .execute((err, records) => {
        console.log(err, records, 'records and error')
        if (err) return [err]
        return [null, records]
      })
    if (deploymentsErr) return res.status(500).send(deploymentsErr)
    return res.status(200).json(deploymentsData)`
    
    also seems to not run execute anymore here and i get returned a single object instead an array of records but never hits my console log inside of the execute callback

**Comment by shijith29** [comment]
I have similar issue in v3 (3.0.0-next.1). 
conn.login(username, password, function(err, userInfo) {
I use above code and this does not return anything

**Comment by pavitra-infocusp** [comment]
Apparently, the APIs now use native Promises. No callback functions. Good move!

**Comment by shijith29** [comment]
Any documentation available on new changes please ?

**Comment by pavitra-infocusp** [comment]
> Any documentation available on new changes please ?

Don't know, I asked here: https://github.com/jsforce/jsforce/issues/1360#issuecomment-1838065565

**Comment by cristiand391** [comment]
sorry for the late reply, jsforce >= 2 removed support for callbacks in most methods.
You can check the jsforce v3 docs with updated examples here:
https://jsforce.github.io/document/#access-token-request
