### ISSUE TITLE
Server-Side Request Forgery in Request & Prototype Pollution vulnerability Issues

### ISSUE THREAD

**Issue by ltechera** [jsforce/jsforce#1394]
If I run npm audit for getting the vulnerabilities report, I get the following:

```
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6        
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request
  jsforce  <=2.0.0-beta.3
  Depends on vulnerable versions of request
  node_modules/jsforce

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
No fix available
node_modules/request/node_modules/tough-cookie
node_modules/tough-cookie
```

Apparently, jsforce uses a vulnerable version of request, which uses a vulnerable version of tough-cookie.
Is this going to be addressed?

See related:
https://github.com/advisories/GHSA-p8p7-x288-28g6   
https://github.com/advisories/GHSA-72xf-g2v4-qvf3
https://github.com/request/request/issues/3142

**Comment by doramar97** [comment]
Facing same issue here
```
jsforce 1.11.1
├─┬ faye 1.4.0
│ └── tough-cookie 4.1.3`
`└─┬ request 2.88.2
  └── tough-cookie 2.5.0
```

**Comment by MoranM** [comment]
same here :\

**Comment by cristiand391** [comment]
Hey all 👋🏼 

this was fixed in jsforce v2 (which has been in beta for a few years, see https://github.com/jsforce/jsforce/issues/1360 for more info).

neither v2 or v3 depends on `request`, closing as dup of:
https://github.com/jsforce/jsforce/issues/999#issuecomment-1750757342

**Comment by aditjain117** [comment]
@cristiand391 jsforce doesn't seem to be leaning on `request` anymore, however, I'm still seeing the vulnerable version of tough-cookie being used by `faye`. I'm on jsforce 3.6.3 (latest GA at the time of writing this message). Is this already being addressed?

<img width="257" alt="image" src="https://github.com/user-attachments/assets/fca3efe6-c7cb-4946-a4aa-890f10e8c942" />

**Comment by cristiand391** [comment]
@aditjain117 I think it's safe to override tough-cookie, we want to get rid of `faye` eventually but it's not in the roadmap yet (we should add support for pub/sub API at least b/c removing `faye` will likely requireq stop supporting the Streaming API).
