### ISSUE TITLE
TypeError: Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by anwbfvr** [jsforce/jsforce#1399]
We experience a bug in node-fetch in relation to minifying code: https://github.com/node-fetch/node-fetch/issues/784 when using @jsforce/jsforce-node@3.0.0-next.1

The bug is fixed in node-fetch@3 (according to https://github.com/node-fetch/node-fetch/issues/784#issuecomment-1286116443), so updating the dependency of node-fetch might help.

**Comment by cristiand391** [comment]
We explored the upgrade path from node-fetch v2 -> v3 for jsforce a few weeks ago and decided we'll stay on node-fetch v2 for jsforce v3.

I'll post the details later post GA, but a few things that blocks us from using node-fetch v3 are:
* [it's an ESM module](https://github.com/node-fetch/node-fetch/blob/main/docs/v3-UPGRADE-GUIDE.md#converted-to-es-module) jsforce is still CJS (there will be an ESM build but we don't plan to keep different branches just for these).
* [dropped support for usage in browsers](https://github.com/node-fetch/node-fetch/blob/main/docs/v3-UPGRADE-GUIDE.md#dropped-the-browser-field-in-packagejson)


Also, now node has native a `fetch` we want to explore dropping node-fetch and just use the native`fetch` in node and browsers (probably in the jsforce v4 roadmap).

**Comment by john-bflow-mcgowan** [comment]
@anwbfvr did any of the workarounds in the linked `node-fetch` issue resolve your issue? I'm also running into this issue deploying my code with jsforce 2.0.0

**Comment by anwbfvr** [comment]
> @anwbfvr did any of the workarounds in the linked `node-fetch` issue resolve your issue? I'm also running into this issue deploying my code with jsforce 2.0.0

Yes, we are now using https://esbuild.github.io/api/#keep-names
