### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by fmoretti** [jsforce/jsforce#1400]
Hi, I’m having this issue that is pretty close to #1270 but without Webpack (I’m using Vite instead).

It’s reproducible with any version of Node.js >= 16.x (I’m currently using 20.x): I guess **it’s something related to Babel**, since I’m able to compile the scripts with Vite and run a development instance of my  Vue 3 application, but it fails to run the `jsforce` module itself.

I get `TypeError: Super expression must either be null or a function` with either `alpha`, `beta`, and `next` versions of the npm package. It’s enough to import the module (I use an ESM import, not a CJS require) to get this error.

I tried to fix the issue by modifying the source code of `package.json` in `node_modules`, but it didn’t work.

Here’s my last configuration:

```
"devDependencies": {
    "@tsconfig/node20": "^20.1.2",
    "@types/jsforce": "^1.11.5",
    "@types/node": "^20.11.24",
    "@types/sass": "^1.45.0",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vue/tsconfig": "^0.5.1",
    "npm-run-all2": "^6.1.2",
    "sass": "^1.71.1",
    "typescript": "~5.3.3",
    "vite": "^5.1.5",
    "vue-tsc": "^2.0.4"
  },
  "dependencies": {
    "jsforce": "^3.0.0-next.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0",
    "vuex": "^4.1.0"
  }
```

And I got this:

```
// node_modules/@babel/runtime-corejs3/helpers/esm/inherits.js
function _inherits(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function");
  }
 [...]
}
```

**Comment by baian1** [comment]
This is caused by missing dependencies of Node.js, use vite-plugin-node-polyfills to solve it.

**Comment by fmoretti** [comment]
Thank you, @baian1: it seems to work as expected.
