### ISSUE TITLE
bulk job.open 'InvalidSessionId' error is never caught and sent to callback

### ISSUE THREAD

**Issue by haoliu119** [jsforce/jsforce#141]
we are using the Bulk.load method with a Salesforce Oauth connection as such:

    SalesforceOauthConnection.bulk.load(type, 'upsert', options, input, function (error, results) {
        if (error && error.code === 'InvalidSessionId') {
             // refresh access token, re-connect, then retry bulk load job
        }
        //................
    });

I traced the code into bulk.js [between line 76 and line 114](https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L76-L114)

on [line 109](https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L109) bulk._request returns err with an error code 'InvalidSessionId' indicating that our access token has expired. However, it seems the error is never caught anywhere, hence our callback is never called with the error object, causing our backend to hang and not knowing to refresh our token.

I implemented a solution at [line 736](https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L736) as such: 

    job.on('error', callback);

The and it returns the error object to our callback. Here's the [pull request](https://github.com/jsforce/jsforce/pull/140).

I wasn't sure if this is the correct place and way in which the error should be caught and return to the callback. I'm not sure if I'm not aware of any cases that this may break.

Please look into this issue. Thanks.

**Comment by stomita** [comment]
This is partially fixed by #132, and there would not be session expiration error when refreshToken is available. There still lies the issue for error handling of job creation when no refresh token is available.
