### ISSUE TITLE
Unable to use bulk api

### ISSUE THREAD

**Issue by no1ipa** [jsforce/jsforce#1410]
When I try to create a bulk job, I get the following error 

> TypeError:Cannot read property 'createJob' of undefined.

```
async function setSalesforceConnection() {
    const conn = new jsforce.Connection({
        loginUrl: process.env.SF_INSTANCE_URL
    });

    const username = process.env.SF_USERNAME;
    const password = process.env.SF_PASSWORD + process.env.SF_SECURITY_TOKEN;
    return await conn.login(username, password);
}

const conn = await setSalesforceConnection();

let job = conn.bulk.createJob(objectName, "upsert", {extIdField: externalIdField});
```

Update: version 1.11.1

**Comment by cristiand391** [comment]
@no1ipa looking at jsforce v1 TS types, `conn.login` returns an object with auth info, not a connection:
https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/connection.js#L1459

try awaiting for the auth to happen then return the connection instance like this:

```diff
async function setSalesforceConnection() {
    const conn = new jsforce.Connection({
        loginUrl: process.env.SF_INSTANCE_URL
    });

    const username = process.env.SF_USERNAME;
    const password = process.env.SF_PASSWORD + process.env.SF_SECURITY_TOKEN;
-   return await conn.login(username, password);
+   await conn.login(username, password);
+   return conn;
}
```

**Comment by no1ipa** [comment]
Thanks @cristiand391 
I apologize for my inattention

**Comment by cristiand391** [comment]
No worries :) 
next jsforce version includes TS types, even if you don't use TS your IDE will do code completion which helps in these cases.
