### ISSUE TITLE
Bulk API Example Request

### ISSUE THREAD

**Issue by jimrae** [jsforce/jsforce#143]
I would appreciate if you could add an example of how to structure a bulk API insert execution that includes one job with multiple batches. My use case is to break up a large csv file and process the chunks with the bulk API. While I can create the single job with multiple batches, I can't figure out how to monitor all of the batches for completion so I can close the job.  I assume it is some type of promise based solution, but I have not implemented anything like that before. Thanks.

**Comment by stomita** [comment]
In JSforce, there are two different level to achieve batch execution. One is low-level which is just mapped to REST API call, and the other is relatively high-level and watching the completion of the batch activity in one async/promise call.
In low-level API, you can create bulk job and batch by `Bulk#createJob()` and `Job#createBatch()`, execute by `Batch#execute()`, then watch each batch completion by `Batch#check()` (or `Batch#poll()`). High-level one is useful in the case you have one batch in one job, and just call one API `Bulk#load()` (or some other convenient synonyms).
In your case it seems you can use low-level API to wait each batch to complete. You can use Promise lib like [q](https://github.com/kriskowal/q) or [bluebird](https://github.com/petkaantonov/bluebird) to wait whole completion of these bulk activity.

**Comment by jimrae** [comment]
Yes, I need to create multiple batches on one Job.  I was hoping to get an example of how to monitor one job with multiple batches.  If if you don't have an example, I will try to get it working, a will provide an example.

**Comment by stomita** [comment]
How about this ? (I've not tried actually, though)

```javascript
var fs = require('fs');
var Promise = require('promise');
var files = [ "acc01.csv", "acc02.csv", "acc03.csv" ];
var job = conn.bulk.createJob("Account", "insert");
Promise.all(
  files.map(function(file) {
     var batch = job.createBatch();
     batch.execute(fs.createReadStream(file));
     batch.poll(5*1000, 30*1000); // poll interval = 5 sec, timeout = 30 sec
     return new Promise(function(resolve, reject) {
       batch.on('response', function(res) { resolve(res); });
       batch.on('error', function(err) { reject(error); });
     });
  });
).then(function(rets) {
  console.log('batch finished');
  console.log(rets);
}, function(err) {
  console.error(err);
});
```

**Comment by jimrae** [comment]
I will check that out, thank you so much!!

**Comment by jimrae** [comment]
This is what I ended up with as my final version.  The full code set also included a filereader that reads in a large CVS file using the HTML5 FileReader, and chunks it into smaller sets of records, which get added to the filearray variable.

```javascript
   var job = conn.bulk.createJob("Account", "insert");    
   Promise.all(
                filearray.map(function(file) {
                    var batch = job.createBatch();
                    batch.execute(file);
                    return new Promise(function(resolve, reject) {
                        batch.on("queue", function(batchInfo) {
                            batchId = batchInfo.id;
                            var batch = job.batch(batchId);
                            batch.on('response', function(res) { resolve(res); });
                            batch.on('error', function(err) { reject(err); });
                            batch.poll(5*1000, 60*1000);
                        });
                    });
                })
            )
            .then(function(rets) {
                  var successrec=0;
                  var errorrec=0;
                  var procrec=0;
                  var errormsg='';
                  for(var i=0;i<rets.length;i++){
                    for(var ii=0;ii<rets[i].length;ii++){
                        procrec++;
                        if(rets[i][ii].success==true){
                            successrec++;
                        }else{
                            errorrec++;
                            if(errormsg.length==0){
                                errormsg=rets[i][ii].errors[0];
                            }else{
                                errormsg='\n'+rets[i][ii].errors[0];
                            }
                        }
                    }
                    document.getElementById("loadresult").innerHTML = 'Processed : '+procrec+' with '+errorrec+' errors '+errormsg;
                  }
                  cursor_clear();
                  job.close();
                }, function(err) {
                  alert(err);
                });
```

**Comment by georgenjthomas** [comment]
I tried this approach but i'm getting an error "batch not started".

Could you please explain me where i need to check whether the batch is running or not?
and how do i find the reason not for batch executing?

**Comment by jimrae** [comment]
Did you try my version or the original version posted by stomita?  My version does account for this issue. I was getting the same "batch not started" error when didn't wait to see if the batches were "queued" before starting the polling.

**Comment by georgenjthomas** [comment]
Thank You:)

Here is the code.

<apex:page showHeader="false" docType="html-5.0">
  <script src="//cdnjs.cloudflare.com/ajax/libs/jsforce/1.3.1/jsforce.min.js"></script>

<script>
function loadfile()
{
    var filearray=[ { Name : 'ACC #1' }, 
                { Name : 'ACC #2'  }, 
                { Name : 'ACC #3'}];
                
    var conn = new jsforce.Connection({ accessToken: '{!$API.Session_Id}' });
    var job = conn.bulk.createJob("Account", "insert");  

   Promise.all(
  filearray.map(function(file) {
     var batch = job.createBatch();
     batch.execute(file);
     console.log('Executed batch');
     batch.poll(5*1000, 30*1000); // poll interval = 5 sec, timeout = 30 sec
     return new Promise(function(resolve, reject) {
       batch.on('response', function(res) { resolve(res); });
       batch.on('error', function(err) { reject(error); });
       batch.on('Batch not started', function(){console.log('not started');});
     });
  })
)
    
    
}
  </script>
  
  <input type="file" id="importfile" onchange="loadfile()"/>
</apex:page>


I checked in back end : Apex jobs, nothing was there.

Could you please share your complete code? Is it possible to insert 10K records via this?

Im not sure if we need to make any config changes.

**Comment by jimrae** [comment]
Your code wasn't posted in the message.  In my version, I am inserting 100,000 records in about 40 seconds.

**Comment by georgenjthomas** [comment]
Thank You:)

Here is the code.
```javascript
<apex:page showHeader="false" docType="html-5.0">
  <script src="//cdnjs.cloudflare.com/ajax/libs/jsforce/1.3.1/jsforce.min.js"></script>

<script>
function loadfile()
{
    var filearray=[ { Name : 'ACC #1' }, 
                { Name : 'ACC #2'  }, 
                { Name : 'ACC #3'}];
                
    var conn = new jsforce.Connection({ accessToken: '{!$API.Session_Id}' });
    var job = conn.bulk.createJob("Account", "insert");  

   Promise.all(
  filearray.map(function(file) {
     var batch = job.createBatch();
     batch.execute(file);
     console.log('Executed batch');
     batch.poll(5*1000, 30*1000); // poll interval = 5 sec, timeout = 30 sec
     return new Promise(function(resolve, reject) {
       batch.on('response', function(res) { resolve(res); });
       batch.on('error', function(err) { reject(error); });
       batch.on('Batch not started', function(){console.log('not started');});
     });
  })
)
    
    
}
  </script>
  <input type="file" id="importfile" onchange="loadfile()"/>
</apex:page>

```
I checked in back end : Apex jobs, nothing was there.

Could you please share your complete code? Is it possible to insert 10K records via this?

Im not sure if we need to make any config changes.

**Comment by georgenjthomas** [comment]
Hello,

This is fixed, i was reading your post https://github.com/jsforce/jsforce/issues/139

I just added the following code and i could see a bulk data load job created 

conn = new jsforce.Connection({ 
                    accessToken: '{!$Api.Session_Id}'
                    ,proxyUrl: '/services/proxy'
                });
