### ISSUE TITLE
Version information is not properly returned on JSforce ver 3.0

### ISSUE THREAD

**Issue by stomita** [jsforce/jsforce#1498]
From CLI, it returns wrong version information:

```shell
$ npx jsforce@3.2.0 --version
2.0.0-beta.8
```

As the above command refers the content of `src/VERSION.ts`, it should be maintained according to the update of version info in package.json.

Note: Formerly (in 1.0 era) it has "prepublish" script to confirm it is synced, so it was possible to notice if there is a difference before publishing as a package.
https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/package.json#L35

**Comment by cristiand391** [comment]
https://github.com/jsforce/jsforce/pull/1499#issuecomment-2189926603
