### ISSUE TITLE
[Error: socket hang up] code: 'ECONNRESET'

### ISSUE THREAD

**Issue by rogah** [jsforce/jsforce#15]
From now and then depending on the number of requests made to create users(see below) I'm getting the following `[Error: socket hang up] code: 'ECONNRESET'` when I'm behind a HTTP proxy. I've made a few researches and it might be related to the fact where the request is not being closed (e.g. req.end()) or some request options you can provide to header (e.g. Content-Length).

```
conn.sobject("User").create(properties, function (err, result) {
  ...
});
```

Any clues?

**Comment by tejasmanohar** [comment]
Why is this necessary?

**Comment by johnbiundo** [comment]
I'm getting this problem sporadically and am not behind a proxy.  What else might be causing it?

**Comment by jangobel** [comment]
Me as well. @johnbiundo do you remember how you solved this?
