### ISSUE TITLE
invalid_grant OAuth 2.0 Username-Password Flow - outdated doc

### ISSUE THREAD

**Issue by AllanOricil** [jsforce/jsforce#1506]
JSForce `Username and Password Login (OAuth2 Resource Owner Password Credential)` flow doc is outdated. 

I believe that the following information must be added as a `WARNING`, because It took me several hours to determine the issue since all indexed community issues pages aren't mentioning this information either.

https://help.salesforce.com/s/articleView?id=release-notes.rn_security_username-password_flow_blocked_by_default.htm&release=244&type=5

<img width="1648" alt="image" src="https://github.com/jsforce/jsforce/assets/55927613/3c2aaea6-1095-4bbb-bf72-258201b2df55">

 I was able to discover the issue after several hours and only after opening the User details page to see the "reason" for failed login attempts.

<img width="1611" alt="image" src="https://github.com/jsforce/jsforce/assets/55927613/6e7111b1-a8a3-4653-a198-ff89f4b062d8">

Even the official OAuth flow doc does not mention this important detail that is required for 2024 orgs

https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_username_password_flow.htm&type=5

### Before enabling Username+password flow

<img width="624" alt="image" src="https://github.com/jsforce/jsforce/assets/55927613/23d34b1c-71d3-4293-b1bc-8c7dca706419">

As you can see, it is difficult to determine the real issue because Salesforce's auth server does not have a detailed error message to indicate the real problem. 

### After enabling Username+password flow

<img width="599" alt="image" src="https://github.com/jsforce/jsforce/assets/55927613/6afa4e2a-10dc-4f76-a9af-2c1a3efc0c44">

**Comment by AllanOricil** [comment]
@cristiand391 which repo has the updated doc?

https://github.com/jsforce/jsforce.github.io

?


Can I add this information there?

**Comment by cristiand391** [comment]
@AllanOricil thanks for the heads up!

https://github.com/jsforce/jsforce.github.io is the correct one, 

> Can I add this information there?

sure, adding a note in these 2 templates should work:
https://github.com/search?q=repo%3Ajsforce%2Fjsforce.github.io+%2FOAuth2+Resource+Owner+Password+Credential%2F&type=code

**Comment by AllanOricil** [comment]
@cristiand391 I added the warning message
