### ISSUE TITLE
TypeError: Only absolute URLs are supported when trying to create a task

### ISSUE THREAD

**Issue by flefloch-payps** [jsforce/jsforce#1508]
Hello,
I'm new to salesforce and jsforce so maybe I'm missing something obvious.
I build a routine to create an account, a contact associated with this account and this is working fine.
But when I try to create a tasj and attach it to this contact I'm receiving this error : TypeError: Only absolute URLs are supported
But I don't send any URL to my new Task object.

Here is how I try to create the task:

const testTask= {
    AccountId: accountId,
    Description: "First connexion",
    Status: "Completed",
    Subject: "LinkedIn message, answer to post",
    TaskSubType: "LinkedIn",
    Type: "Call",
  }
const newTask = await conn.sobject("Task").create(taskData);

I'm using jsforce v3.2.0

Am I missing something?

Thank you.

**Comment by cristiand391** [comment]
👋🏼 
`TypeError: Only absolute URLs are supported` means jsforce is trying to do a request with a relative URL.

Could you share you the `conn` object is being created? Also, you can set the logLevel to `DEBUG` when creating the connection and see more debug logs printed out:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html

**Comment by flefloch-payps** [comment]
Hello @cristiand391 ,

thank you for your help.
Actually the conn object is this one : 

`Connection {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  version: '50.0',
  loginUrl: 'https://login.salesforce.com',
  instanceUrl: '',
  accessToken: undefined,
  refreshToken: undefined,
  userInfo: undefined,
  limitInfo: {},
  oauth2: OAuth2 {
    loginUrl: 'https://login.salesforce.com',
    authzServiceUrl: 'https://login.salesforce.com/services/oauth2/authorize',
    tokenServiceUrl: 'https://login.salesforce.com/services/oauth2/token',
    revokeServiceUrl: 'https://login.salesforce.com/services/oauth2/revoke',
    clientId: undefined,
    clientSecret: undefined,
    redirectUri: undefined,
    codeVerifier: undefined,
    _transport: Transport {}
  },
  sobjects: {},
  cache: Cache { _entries: { describeGlobal: [CacheEntry] } },
  _callOptions: undefined,
  _maxRequest: 10,
  _logger: Logger { _moduleName: 'connection', _logLevel: 1 },
  _logLevel: 'DEBUG',
  _transport: Transport {},
  _sessionType: 'oauth2',
  _refreshDelegate: undefined,
  'describe$': [Function: $fn] { clear: [Function (anonymous)] },
  'describe$$': [Function: $fn] { clear: [Function (anonymous)] },
  describeSObject: [Function: $fn] { clear: [Function (anonymous)] },
  'describeSObject$': [Function: $fn] { clear: [Function (anonymous)] },
  'describeSObject$$': [Function: $fn] { clear: [Function (anonymous)] },
  'describeGlobal$': [Function: $fn] { clear: [Function (anonymous)] },
  'describeGlobal$$': [Function: $fn] { clear: [Function (anonymous)] },
  insert: [AsyncFunction: create],
  delete: [AsyncFunction: destroy],
  del: [AsyncFunction: destroy],
  process: Process {
    rule: ProcessRule { _conn: [Circular *1] },
    approval: ApprovalProcess { _conn: [Circular *1] }
  },
  describe: [Function: $fn] { clear: [Function (anonymous)] },
  describeGlobal: [Function: $fn] { clear: [Function (anonymous)] },
  analytics: [Getter],
  apex: [Getter],
  bulk: [Getter],
  bulk2: [Getter],
  chatter: [Getter],
  metadata: [Getter],
  soap: [Getter],
  streaming: [Getter],
  tooling: [Getter],
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
}`

After changing the logLevel I indeed receive a more detailed error indicating 
`DEBUG	[http-api]  <request> method=POST, url=/services/data/v50.0/sobjects/Task`
which is indeed a relative URL. 
But how can I change this URL to an absolute one? I guess this URL is defined in Jsforce library, or could I add an extra path when creating an object?

Thank you.

**Comment by flefloch-payps** [comment]
I was already setting instanceUrl when creating my connexion..... but after double checking it turns out that the var I was using was empty.
Stupid from my side not to double check this before. Sorry to have bother you and thank you for your help.

**Comment by cristiand391** [comment]
no worries!
I've seen people hit this error a few times, might be a good idea to throw a friendly error from jsforce if we don't have a valid instance URL when doing a request.
