### ISSUE TITLE
Query explain plan support

### ISSUE THREAD

**Issue by stomita** [jsforce/jsforce#151]
For retrieving query performance feedback without executing the query
https://developer.salesforce.com/docs/atlas.en-us.192.0.api_rest.meta/api_rest/resources_query.htm

**Comment by stomita** [comment]
Impled in #154

**Comment by pcon** [comment]
Can you give an example of how to use this?  I thought it would be something like `conn.query.explain('select Id from Contact')` but that obviously doesn't work.
