### ISSUE TITLE
JSForce - sobject('Document').Create is failing with ERROR_HTTP_503: upstream connect error or disconnect/reset before headers. reset reason: remote reset

### ISSUE THREAD

**Issue by npolusf** [jsforce/jsforce#1535]
JSForce sobject('Document').Create is failing with ERROR_HTTP_503: upstream connect error or disconnect/reset before headers. reset reason: remote reset when the file size is around 80 MB

**Sample code :** 

const encodedFile: string = (new Buffer(fs.readFileSync(file.Path))).toString('base64');
        const fileResult = await this.jsforceClient.sobject('Document').create({
            Body: encodedFile,
            ContentType: file.ContentType,
            Description: file.Description,
            DeveloperName: file.DeveloperName,
            FolderId: file.FolderId,
            Name: file.Name,
            Type: file.Type
        });

**Can some one please let me know if there is limitation on file size when using jsforceClient.sobject('Document').create because same piece of code works fine for 1 MB or KB files.**

**Comment by cristiand391** [comment]
It's an API limit:

> Maximum Document Size
You can only create or update documents to a maximum size of 5 MB.

https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_document.htm

**Comment by npolusf** [comment]
@cristiand391 : Thanks for looking into this issue and sharing the link for the documentation. As part of testing I have tried with file size of 6MB and it got uploaded successfully. Any idea may be if the documentation is not up to date or if there are any revised file size limits for maximum document size.

**Comment by cristiand391** [comment]
could be outdated docs, you can test by incrementing the body size to see when it actually fails.
here's the code that does the request:
https://github.com/jsforce/jsforce/blob/38b60d64414929078a3f371c126e63aa383f0744/src/connection.ts#L1016C1-L1029C8

jsforce doesn't do any file size check for `Document` or any specific object.
