### ISSUE TITLE
Filters from v1 not working with v3

### ISSUE THREAD

**Issue by pavitra-infocusp** [jsforce/jsforce#1536]
I used to have a query like this which used to work in v1, but this is no longer working with v3, and this is not mentioned as a breaking change in the migration guide.

```js
const records = await conn.sobject("Opportunity")
    .where({
        Amount: { $gte: 45000, $lte: 75000 },
        OwnerId: ['0055h00000AKFzTAAX']
    })
    .execute();
```

This produces an invalid query string, where the `Amount <= 75000` condition is missing.
```
SELECT Id, LastModifiedDate, CreatedDate, Name, AccountId, OwnerId, Amount, StageName, Probability, ExpectedRevenue, NextStep FROM Opportunity WHERE OwnerId IN ('0055h00000AKFzTAAX') AND Amount >= 45000
```

**Comment by pavitra-infocusp** [comment]
I tried to debug the issue myself, but I couldn't seem to install the dependencies using `npm i` :(

![image](https://github.com/user-attachments/assets/69266d86-8bf5-488c-aac7-5bf0ea064b12)

**Comment by pavitra-infocusp** [comment]
The issue is that when passed as object, it only takes the the first key, not all of them.

https://github.com/jsforce/jsforce/blob/38b60d64414929078a3f371c126e63aa383f0744/src/soql-builder.ts#L108

**Comment by cristiand391** [comment]
> The issue is that when passed as object, it only takes the the first key, not all of them.

@stomita do you remember if this change was on purpose? I think @pavitra-infocusp is right but trying to refactor the query builder to match this breaks some tests:
https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/soql-builder.js#L132-L136

in the meantime, you can pass multiple conditionals as an array:
https://jsforce.github.io/document/#conditionals

```ts
const soql = await conn.sobject('Opportunity')
  .find({
    $and: [
      { Amount: { $gte: 45000 } },
      { Amount: { $lte: 75000 } }
    ],
    'OwnerId': ['0055h00000AKFzTAAX'],
  }, ['AccountId'])
  .toSOQL()
console.log(soql)

// SELECT AccountId FROM Opportunity WHERE (Amount >= 45000 AND Amount <= 75000) AND OwnerId IN ('0055h00000AKFzTAAX')
```
