### ISSUE TITLE
vite:import-analysis Failed to resolve entry for package jsforce

### ISSUE THREAD

**Issue by matindow** [jsforce/jsforce#1553]
When trying to import jsforce in a vite project i am receiving the error:
`vite:import-analysis Failed to resolve entry for package jsforce`

This appears to be the same as this issue https://github.com/vitejs/vite/issues/7725, which is that the path in the `module` field of the `package.json` file must resolve.

In jsforce:
https://github.com/jsforce/jsforce/blob/c83cbd4b0aa4c1706cbe1edaf1eb73ecf64fdf4d/package.json#L26

This path appears to be invalid? I am not familiar with either the project or the intended use of the `module` path, so I'm not really sure what the right resolution is here?

I can tell you that updating the `module` path to (what appears to me to be) the correct entry point `"module": "./index"` seems to correct the issue.

**Comment by schwarmco** [comment]
can confirm the error and the solution by @matindow
