### ISSUE TITLE
INVALID_LOGIN when upgrading to jsforce 3.4.2 from 1.11.10

### ISSUE THREAD

**Issue by mdecock-rep** [jsforce/jsforce#1581]
I tried upgrading jsforce in my repository from 1.11.0 to 3.4.2 but when I try to log in to the connection, I get the following error:

Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.

If I switch back to 1.11.0, everything works again so I know it's not an invalid username, password, token or locked out user.

**Comment by cristiand391** [comment]
Which auth method are you using? Do you have a code example?

**Comment by mdecock-rep** [comment]
this.connection = new jsforce.Connection({
    oauth2: {
        loginUrl: 'https://test.salesforce.com/'
        }
    });

const result = await this.connection.login(username, password);

Looks like I'm using OAuth2. I'm guessing that requires a token in v3? Maybe I just need to disable that. I'll give it a try and report back.

**Comment by mdecock-rep** [comment]
Yep. That was it. I switched my connection to the below and everything seems to be working fine in v3 now. Thank you!

		this.connection = new jsforce.Connection({
			loginUrl: 'https://test.salesforce.com/'
		});
