### ISSUE TITLE
Metadata#retrieve(options) examples

### ISSUE THREAD

**Issue by rogah** [jsforce/jsforce#16]
Could you please provide an example on how to use the `Metadata#retrieve(options)`? Assuming I have a manifest file (e.g. _package.xml_), how do I tell the `Metadata#retrieve(options)` to retrieve the metadata based on the _package.xml_? I'm not quite sure what the `packageNames` stands for in the request options `{ packageNames: [ 'My Test Package' ] }`.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MyCustomObject__c</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>*</members>
        <name>CustomTab</name>
    </types>
    <types>
        <members>Standard</members>
        <name>Profile</name>
    </types>
    <version>30.0</version>
</Package>
```

Thanks in advance!

obs: You could label this as question and not a issue.

**Comment by omniphx** [comment]
Did anyone ever come up with a working example of this?

Essentially what I'm trying to achieve is `jsforce-retrieve -u ###### -p #### -l https://test.salesforce.com -P ./src/package.xml -D ./src`

**Comment by stomita** [comment]
@omniphx if you are using `jsforce-retrieve` the [jsforce/jsforce-metadata-tools](https://github.com/jsforce/jsforce-metadata-tools/) source code includes the live code how to do the retrieve.

**Comment by Krisa** [comment]
For clarity, unpackaged expects the package.XML formatted as JS object (and not as file). That would be a valid request:

```
conn.metadata.retrieve({
    apiVersion: '38.0',
    singlePackage: true,
    unpackaged: {
      types: [{
        'members': ['Account', 'Contact'],
        'name': 'CustomObject'
      }, {
        'members': ['*'],
        'name': 'ApexClass'
      }]
    }
  })
```

**Comment by omniphx** [comment]
Thanks @Krisa! That helps alot

**Comment by gonardfreeman** [comment]
Thanks @Krisa ! Why there is no info about that in docs? How dev need to understand that he could repeat xml structure in js object? Please update docs. Your tool is real powerfull ;)

**Comment by darkacer** [comment]
> For clarity, `unpackaged` expects the package.XML formatted as JS object (and not as file). That would be a valid request:
> 
> ```
> conn.metadata.retrieve({
>     apiVersion: '38.0',
>     singlePackage: true,
>     unpackaged: {
>       types: [{
>         'members': ['Account', 'Contact'],
>         'name': 'CustomObject'
>       }, {
>         'members': ['*'],
>         'name': 'ApexClass'
>       }]
>     }
>   })
> ```

This is not present in the JSforce documentation 
@0cv Thank you for this
