### ISSUE TITLE
Request to resolve dependency security vulnerability for node-fetch

### ISSUE THREAD

**Issue by hshmhshm** [jsforce/jsforce#1601]
Hi, 

We have the following security alerts for the below transitive dependencies, it would be good to see these updated.

node-fetch forwards secure headers to untrusted sites *and* node-fetch Inefficient Regular Expression Complexity:
- Patched version is 3.2.10
- jsforce/jsforce-node@3.4.1 uses node-fetch 2.7.0

Many thanks for the package!

**Comment by cristiand391** [comment]
We can't migrate to node-fetch v3 easily because it dropped support for browsers.

It'll likely be done in a major release (replacing it with native fetch/other lib) but I don't think we'll be doing it in the near future.
