### ISSUE TITLE
jsforce dependency upgrade from 1.9.3 to 3.6.2 is failing on promise.

### ISSUE THREAD

**Issue by mdmehran-qureshi** [jsforce/jsforce#1620]
Hi team, 

We are using jsforce in VBT(https://github.com/vlocityinc/vlocity_build). It is working fine with jsforce 1.9.3 . But as 1.9.3 has some vulnerabilities so we decided to upgrade it to latest version. However after changing version to 3.6.2, It is start failing and unable to resolve Promise( https://github.com/vlocityinc/vlocity_build/blob/master/lib/utilityservice.js#L599) which is being called from [deltaCheck.js:348](https://github.com/vlocityinc/vlocity_build/blob/master/lib/deltacheck.js#L348) and [deltaCheck.js:353](https://github.com/vlocityinc/vlocity_build/blob/master/lib/deltacheck.js#L353). 

If I replace promise with below code, it is working fine:
`try {
        const result = await self.vlocity.jsForceConnection
            .sobject(self.setNamespaceToOrg(sObjectName))
            .describe();
    
        return self.setNamespaceToDefault(result);
    } catch (err) {
        if (!self.vlocity.isOmniStudioInstalled) {
            VlocityUtils.verbose('Describe Not found', sObjectName, err.message);
        }
        throw err;
    }`

  But later it is failing on different location on Promise and async methods. Can you please help us, what is the issue here?

**Comment by cristiand391** [comment]
v3 moved from callback style to promises, there's a migration guide here:
https://github.com/jsforce/jsforce/blob/main/MIGRATING_V1-V3.md
