### ISSUE TITLE
conn.refreshToken missing?

### ISSUE THREAD

**Issue by ColorfullyMe** [jsforce/jsforce#163]
Following the example [Access Token Request](https://jsforce.github.io/document/#access-token-request) from the site (code bellow) I get **conn.refreshToken** = `undefined` what could be the reason for this behavior?

```js
app.get('/oauth2/callback', function(req, res) {
  var conn = new sf.Connection({ oauth2 : oauth2 });
  var code = req.param('code');
  conn.authorize(code, function(err, userInfo) {
    if (err) { return console.error(err); }
    // Now you can get the access token, refresh token, and instance URL information.
    // Save them to establish connection next time.
    console.log(conn.accessToken);
    console.log(conn.refreshToken);
    console.log(conn.instanceUrl);
    console.log("User ID: " + userInfo.id);
    console.log("Org ID: " + userInfo.organizationId);
    // ...
  });
});
```

Help will be appreciated!

**Comment by stomita** [comment]
Have you included "refresh token" scope in your Connected App setting ?

**Comment by ColorfullyMe** [comment]
@stomita No. Thanks this is the missing link ... Thank You!

**Comment by ChandanShankar** [comment]
Hello @stomita,  Even i'm facing the same problem, as you suggested above I have included "refresh token" scope. Even then im not getting the Refresh token. Can You please help me. 

I have selected the following scopes.

Access your basic information (id, profile, email, address, phone)
Access and manage your data (api)
Provide access to your data via the Web (web)
Provide access to custom applications (visualforce)
Perform requests on your behalf at any time (refresh_token, offline_access)
