### ISSUE TITLE
Object conn.limitInfo is empty after login

### ISSUE THREAD

**Issue by goliardico** [jsforce/jsforce#164]
Hi, 
  it's the first time I use this library, I can easily connect to Sf, use CRUD and anything else *BUT* the conn.limitInfo seems empty for me, I can't query ApiUsage limits.
Here's my code:
```javascript
var jsforce = require('jsforce');
var conn = new jsforce.Connection();
conn.login(username,password, function(err, userInfo) {

  if (err) {
        return console.error(err);
  }
  var limitInfo = conn.limitInfo;
  if (Object.getOwnPropertyNames(limitInfo).length == 0) {
    console.log('Empty!');
  }
  //console.log('used: ' + limitInfo.apiUsage.used);
  //console.log('limit: ' + limitInfo.apiUsage.limit);
  console.log('ApiUsage: ' + limitInfo.apiUsage);
});
```

And result is:

    Empty!
    ApiUsage: undefined

#### Software version
node v0.10.32
jsforce v1.3.1

Thank you!

**Comment by stomita** [comment]
The limitInfo requires at least one REST API call before reading information.

**Comment by goliardico** [comment]
Right!
Now it works.
Please update docs to include this info (or if it's already here, I'm sorry).

Thanks!
