### ISSUE TITLE
Cannot execute Bulk hardDelete operation

### ISSUE THREAD

**Issue by mlucci** [jsforce/jsforce#167]
I've been fighting for hours trying to make an hard delete bulk operation to be performed, without success. I noticed later that by changing the operation from "hardDelete" to "delete" the script was working correctly.

Following example code does not create any Bulk Job:
conn.bulk.load('BulkDeleteTestSobject__c', 'hardDelete', [{Id: 'a09240000007Uuj'}]);

If specifying "delete" operation, it works as expected creating a Bulk Delete Job and deleting the record:
conn.bulk.load('BulkDeleteTestSobject__c', 'delete', [{Id: 'a09240000007Uuj'}]);

Am I missing something??? Thanks in advance for helping

**Comment by mlucci** [comment]
My bad - I had missed that a particular system permission was required to submit hard delete Bulk ops, as per Bulk API guide.

**Comment by mlucci** [comment]
I've re-opened the issue as activating the Sys permission seems not to have solved my issue. I was able to create an "Hard Delete" Bulk Job via the Data Loader, but I'm still unable to submit one via JSForce.

**Comment by stomita** [comment]
Fixed hardDelete problem in JSforce. Still needs 'Bulk API hard delete' privilege, though.

**Comment by mlucci** [comment]
@stomita Thank you for coming back on this issue
