### ISSUE TITLE
jsforce.Connection is not a constructor

### ISSUE THREAD

**Issue by georgenjthomas** [jsforce/jsforce#168]
I have copied the code from JSForce and i couldnt even find it working in my developer instance. Could you please help me

I'm getting the following error 
"jsforce.Connection is not a constructor"

I have placed the jsforce.js file as a static resource on server. Please help me, thanks in advance!

<apex:page docType="html-5.0" showHeader="false">
  <apex:includeScript value="{!URLFOR($Resource.JSforce)}" />
  <script>
function jsforce()
{
    var conn = new jsforce.Connection({ accessToken: '{!$Api.Session_Id}' });
    conn.query('SELECT Id, Name FROM Account', function(err, res) 
    {
      if (err) 
      { alert(err);
      }
         alert(res);
    });
}

      </script>
  
<b onClick="jsforce()">Test</b>
</apex:page>

**Comment by stomita** [comment]
Not sure what happened here. Please check you surely loaded jsforce.js in browser's developer tool console.

**Comment by thompsh4** [comment]
I had the same issue when I tries just using the metadata api file, but the problem resolved itself when moved to the all in one library. I wonder if there is a dependency there?

**Comment by ChuckJonas** [comment]
I'm also having this issue when trying to use Metadata.

```const mdapi = new Metadata(conn);```

`Uncaught (in promise) TypeError: jsforce__WEBPACK_IMPORTED_MODULE_11__.Metadata is not a constructor`

This is a typescript/webpack project
