### ISSUE TITLE
What does "raw SOQL WHERE clause string" mean?

### ISSUE THREAD

**Issue by fourq** [jsforce/jsforce#173]
As a param you comment that it can take a "raw SOQL WHERE clause string" but I don't see any tests or examples that utilize this. Is it a string like "WHERE <condition>", or without the WHERE and just the condition?

**Comment by stomita** [comment]
It means a clause without `WHERE` keyword. An example is [here](https://jsforce.github.io/document/#using-query-method-chain) in 3rd example of `Wildcard Fields` section.
