### ISSUE TITLE
Login status for browser not working across different html documents

### ISSUE THREAD

**Issue by mabrin** [jsforce/jsforce#184]
Currently the jsforce browser-client does not support to use the connection across different pages across the same domain. The information like "jsforce0_loggedin" is stored in a cookie. This cookie only works for the same page. Since the callback URL sometimes can be different from the URL where the connection should be used, but is hosted on the same domain, the login does not work. You come across this issue especially when using AngularJS. Routing includes by default anchors (#), which are not allowed in a callback URL by SFDC.

I have patched the client.js file locally to use the local storage here instead, but currently I cannot get the build via grunt working. I did not find any description how to set-up the build correctly. I just did:

npm install
grunt --force

error is: Error: Cannot find module './browsercanvas' from '<local path>/__tmp__/'

**Comment by stomita** [comment]
You can set callback URL without angular in the same domain URL. Cookie is available if it is in the same domain and under the same path, so the callback can accept the tokens. The JSforce website is also using the technique.
Anyway building JSforce is easy. After repository checkout run `npm install' and `grunt build`. If you have any problem please confirm your building environment.
