### ISSUE TITLE
Proxy no longer required

### ISSUE THREAD

**Issue by wesnolte** [jsforce/jsforce#185]
You can now configure CORS from within Salesforce which means you no longer need the proxy.

![screen shot 2015-02-21 at 12 54 33](https://cloud.githubusercontent.com/assets/325493/6314140/fa14c31a-b9c8-11e4-91bf-19e2df957e06.png)

**Comment by stomita** [comment]
Yes, but it is an opt-in mechanism and not always be possible to enable CORS for some reason. Additionally it still racks the support of other APIs like Metadata API.
I have tested and it works fine if you enabled CORS JSforce doesn't require proxy server setting.
