### ISSUE TITLE
CORS Support?

### ISSUE THREAD

**Issue by shawn-edgespring** [jsforce/jsforce#189]
Is CORS supported for general API calls in JSForce 1.4.1? I'm getting:

XMLHttpRequest cannot load https://(mydomain).salesforce.com/services/data/v33.0. No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is for the "GET" request. The preflight "OPTIONS" request succeeds with the appropriate headers:

Access-Control-Allow-Credentials: false
Access-Control-Allow-Headers: accept,authorization
Access-Control-Allow-Methods: HEAD, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Origin: https://(myOrigin)

I'm using OAuth2 and the auth header for GET is being set correctly:

Authorization: Bearer 00DT0000000Dpvc!AQYAQKG.7...

Any ideas?

**Comment by stomita** [comment]
CORS is already supported in JSforce. Have you already enabled the CORS setting in your Salesforce org. ?

**Comment by shawn-edgespring** [comment]
Yes, CORS is enabled, which is why the preflight OPTIONS call works. I just can't figure out why the GET is then failing.

**Comment by chrisjlee** [comment]
CORS is supported for supported via regular objects. Custom REST endpoints aren't supported at the moment.

The documentation here provides some insight regarding this subject: http://www.salesforce.com/us/developer/docs/chatterapi/Content/extend_code_cors.htm

**Comment by thvd** [comment]
:+1: And could you make it also right for the Bulk API?

**Comment by stomita** [comment]
Currently they not accept CORS in bulk API. Not sure in future, too.
