### ISSUE TITLE
Problem to download Document/Attachments

### ISSUE THREAD

**Issue by CreativExit** [jsforce/jsforce#19]
jsforce = require("jsforce")
  conn = new jsforce.Connection({})
  conn.login 'username', 'password', (err, userInfo) ->
    return console.error(err)  if err

```
# Now you can get the access token and instance URL information.
# Save them to establish connection next time.
console.log "Access Token: "+conn.accessToken
#console.log conn.instanceUrl

# logged in user property
console.log "User ID: " + userInfo.id
console.log "Org ID: " + userInfo.organizationId
fs = require "fs" 
fileOut = fs.createWriteStream('./test.pdf') 
docId = 'documentID' 
conn.sobject('Document').record(docId).blob('Body').pipe(fileOut)
```

**Comment by pordonez** [comment]
Hi,  I've asked this question else where but how does one access blob data in the browser where there is not stream to pipe to?  I can see the response data in the client debugger, but I'm not able to access it.  Any help would be greatly appreciated. Thanks, Peter

**Comment by pordonez** [comment]
Got around my issue by using the Connection.request() method instead of blob().

**Comment by juan-ruiz** [comment]
any way you can post your method? i am trying to download attachment from tickets but i have failed miserably

**Comment by pordonez** [comment]
I don't recall the solution but perhaps this link can help:
https://github.com/jsforce/jsforce/issues/223.

**Comment by krishan1kamal** [comment]
I tried below code and it work fine with only images, still i am not able to download other file e.g. pdf, doc etc

conn.sobject('Document').record(docId).blob('Body').pipe(fileOut)
  .on "error", (err) -> console.error err@

Please help me out.

**Comment by mayankagarwal900** [comment]
The code is working fine. but when my attachments in salesforce is very large than how much time will this request will wait.
