### ISSUE TITLE
is {!GETRECORDIDS} supported to use in a visualforce page?

### ISSUE THREAD

**Issue by siddharatha** [jsforce/jsforce#194]
is there a function within jsforce  to access the records selected from a list view button which is redirected to a visualforce?

**Comment by stomita** [comment]
`GETRECORDIDS` is function to get record ids in visualforce page when it can get them from the context. Of course JSforce can deal the information.

```javascript
var ids = {!GETRECORDIDS($ObjectType.MyObj__c)}; 
var conn = new jsforce.Connection({ accessToken: '{!$Api.Session_ID}' });
conn.sobject('MyObj__c').destroy(ids);
```

**Comment by siddharatha** [comment]
I get a console error 
```
Uncaught ReferenceError: getRecordIds is not defined
```

should i include any additional js file in my visualforce page?

**Comment by stomita** [comment]
GETRECORDID works in the environment with standard js files included. It's not JSforce's matter.
