### ISSUE TITLE
Just want to get response of simple REST Get, What should I do?

### ISSUE THREAD

**Issue by xjsender** [jsforce/jsforce#195]
For example, I just want to get the response of ```{instance_url}/services/data/v33.0/sobjects```, what should I do?

Sorry, I didn't find any API on it, can you give the point, thanks?

**Comment by stomita** [comment]
From v1.4, it exposes the method [`Connection#request()`](http://jsforce.github.io/jsforce/doc/Connection.html#request) to access arbitrary resource in REST API. Of course you can use `Connection#describeGlobal()` to get all sobject list.

**Comment by xjsender** [comment]
@stomita ,  [Connection#request()](http://jsforce.github.io/jsforce/doc/Connection.html#request) is what I wanted, thanks.
