### ISSUE TITLE
nodewebkit 

### ISSUE THREAD

**Issue by camilokorea** [jsforce/jsforce#20]
Hello

I'm trying to execute jsforce from node - webkit (https://github.com/rogerwang/node-webkit) trying to create a desktop web app using SalesForce.

The library seems to be installed correctly inside the project folder using npm command.

This is the error that I'm getting executing the following code:

var jsforce = require('jsforce');
var conn = new jsforce.Connection();

conn.login('xxxx@xxxxx', 'xxxxxxxxxxxxxxxxxxx', function(err, res) {
if (err) { return console.error(err); }

conn.query('SELECT Id, Name FROM Account', function(err, res) {
  if (err) { return console.error(err); }
  console.log(res);
});
});

Error:

Uncaught node.js Error 

ReferenceError: XMLHttpRequest is not defined
    at module.exports (C:\GUI2\node_modules\jsforce\lib\browser\request.js:4:17)
    at createRequest (C:\GUI2\node_modules\jsforce\lib\transport.js:65:13)
    at promise.then (C:\GUI2\node_modules\jsforce\lib\transport.js:30:5)
    at Connection.loginBySoap (C:\GUI2\node_modules\jsforce\lib\connection.js:947:6)
    at Connection.login (C:\GUI2\node_modules\jsforce\lib\connection.js:869:17)
    at eval (file:///C:/GUI2/index.html:8:6)

Any clue or example that we would use?
would you reply me to camilo.corea@accenture.com

Thanks

**Comment by alfu32** [comment]
npm install node-salesforce in the same folder where nwjs runtime and package.json are.(you did that)

in your index.html test the first example from https://www.npmjs.com/package/node-salesforce
make sure to fill in the https url to your org, the username and password.
if it doesn't work, login to your salesforce account, go to setup and see under the profile of the username you are attempting to login with if the login attempt has been recorded.
if it does you either need to reset your security token and use the new one for authentication or, if you cannot do that enable ip ranges access with this profile (use the ip you have in the logs)
(a more detailed explanation you'll find here https://help.salesforce.com/HTViewSolution?id=000182450).
once you have succefukky logged in using the second method the security toke will be sent to you in the response.

needles to say I managed to login to my org from nwjs.

make sure that your npm install actually worked

**Comment by alfu32** [comment]
and perhaps you need to let the dom ready-state reach "complete" before you authenticate... though logically it shouldn't have any impact ...

**Comment by camilokorea** [comment]
Ill check it with a new Starting-Project. Ill let you know

**Comment by cristiand391** [comment]
triaging old issues...

I'm going to close this one, we are close to jsforce v3 GA, if anyone hits this problem with node-webkit please file a new issue.
