### ISSUE TITLE
URL issues using tabs

### ISSUE THREAD

**Issue by XavierOlland** [jsforce/jsforce#204]
Hello,

I'm currently developping an webApp on herokuapp which is played inside Salesforce via a tab (and therefore an iFrame).
I'm using the sessionID for the authentication, so users don't need to sign in twice inside salesforce.
The url I get works OK when I use the .query function but fails on identity function.

Any idea on the correct url that should be used for this function ?

**Comment by stomita** [comment]
You may need loginUrl to be set when getting `identity()` call result.

**Comment by XavierOlland** [comment]
Well, after searching and testing a while with my colleague, we have come to the conclusion that in this case (distant app in a tab using sessionid) you need a proxy.
