### ISSUE TITLE
Difference between this jsforce and forcetk

### ISSUE THREAD

**Issue by chrisjlee** [jsforce/jsforce#206]
Is there any differences between jsforce and forcetk? 

From my understanding forcetk is used only for visualforce pages. Is this a correct assumption? Apologies for my ignorance.  I can happily update and write documentation on the jsforce page.

**Comment by stomita** [comment]
Actually, JSforce has different origin from ForceTK. Firstly it was designed for Node.js apps (its former name was "node-salesforce"). Now it is provided as the isomorphic library which runs both on Node.js and web browser.

If you would like to update documentation or add pages in JSforce website, please send pull requests to https://github.com/jsforce/jsforce-website .

**Comment by hdramos** [comment]
forcetk is not only for Visualforce pages; I've used it for some phonegap projects. forcetk is "endorsed" by salesforce but there is not a a lot of documentation for it. I highly recommend you use jsforce instead of forcetk. salesforce does what what forcetk and much more.
