### ISSUE TITLE
Streaming Api fails in test sandboxes

### ISSUE THREAD

**Issue by craigathon** [jsforce/jsforce#208]
I'm using jsforce 1.4.1 in node.js and I have been getting this error when trying to use the Streaming Api in a sandbox. I remember it used to work correctly so I am unsure where this problem is coming from.

https://jsforce.github.io/document/#streaming-api

/node_modules/jsforce/node_modules/faye/node/faye-node.js:616
    uri.protocol = uri.protocol || Faye.ENV.location.protocol;
                                                    ^
TypeError: Cannot read property 'protocol' of undefined

To reiterate production orgs seem to work fine this is only in test. I am setting my loginUrl to 'https://test.salesforce.com'.

**Comment by robertjustjones** [comment]
Does this sandbox use a custom domain by any chance? If so, do other jsforce commands work?

**Comment by craigathon** [comment]
The org has a subdomain set but not a custom domain. Also, I am able to use Apis like Bulk and Metadata within jsforce without issue.

**Comment by craigathon** [comment]
I was also able to test the push topic using https://workbench.developerforce.com/streaming.php and that is working correct so I think I can rule out an issue with salesforce.

**Comment by craigathon** [comment]
This was bad code on my end, I was never falling into logic that would correctly set my loginUrl to 'https://test.salesforce.com'
