### ISSUE TITLE
Is there a way to get field accessibility / access for each field? 

### ISSUE THREAD

**Issue by facultymatt** [jsforce/jsforce#211]
When using the Describe SObject api, I can view all the fields for a subject. But I can't tell which fields are hidden or visible. Is there a way to query this information?  

![Image of hidden](https://www.evernote.com/shard/s2/sh/b2c43921-52ad-4d17-a668-d19b1f7c0ad3/f4b2257d1e777b741f4c89156a2a4a5e/res/320047a9-c46e-4e16-8b6d-aa97e38c1527/skitch.png)

![Image of visible](https://www.evernote.com/shard/s2/sh/f1f86b97-1ba1-443c-98d4-1524e22d8071/e2a91f43911ed76590dde303d3228a2d/res/a9093c4f-d815-44bd-b811-14ea63679692/skitch.png)

**Comment by stomita** [comment]
Metadata API can include the field level security information. Related discussion http://salesforce.stackexchange.com/questions/34521/set-field-level-security-for-profile-using-meta-data-api
