### ISSUE TITLE
Accessing salesforce REST-API through greasemonkey script using jsforce

### ISSUE THREAD

**Issue by Starney** [jsforce/jsforce#212]
Is it possible to query salesforce through its REST-API using a greasemonkey/tampermonkey script only through jsforce ?
If possible, can someone provide me a hint on how to perform this. I have been going through the jsforce documentation, but could not find any substantial resources on this ?

**Comment by stomita** [comment]
I've never tried the greasemonkey yet, but jsforce needs `accessToken` to access the API, which is essentially equivalent to session id. And *.salesforce.com domain has `sid` cookie which stores session id information, which might or might not be useful for establishing connection from these script extensions.

**Comment by bobbymarko** [comment]
@Starney Did you ever figure out how to use jsforce within a Greasemonkey script? I'm attempting to and am encountering the same issues you did.
