### ISSUE TITLE
Could share typescript definition files or coffeescript files?

### ISSUE THREAD

**Issue by SharkleeGitHub** [jsforce/jsforce#214]
For a easy way to use typescript or coffeescript, could you share the typescript definition files or the coffeescript files? Thank's a lot.

**Comment by stomita** [comment]
For CoffeeScript, it simply runs even in CoffeeScript using `require('jsforce')`.
For typescript, The type definition file (.d.ts) file is needed, but not available currently.

The [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) project is useful to share the own-developed type definitions for third-party JS libraries, and I might contribute to it in future, but not having enough time to cope with it currently.

**Comment by iDev0urer** [comment]
Just a quick update on this issue, I am working on transcribing the API into a `jsforce.d.ts` file. Hopefully it won't take too long, but the API is a beast

**Comment by kresho** [comment]
@iDev0urer Do you have anything to share? I'll need to create typings for the API I use and it would be great to share the effort rather than work independently.

**Comment by iDev0urer** [comment]
I have added it as a gist [here](https://gist.github.com/iDev0urer/8889069fb01399f10b73bf9992c8d43f). I didn't want to upload it to DT yet because it is very much not finished yet
