### ISSUE TITLE
upsert function doesnt return id value. Returns only success/error messages in response message

### ISSUE THREAD

**Issue by saparna90** [jsforce/jsforce#216]
I am pointing to jsforce -> lib-> connection.js file where Connection.prototype.upsert  function. Wanted to know if this function would return a id value as response or just success/error messages. If this is as designed, how would upsert doing a create will work - as create would return a id in response. Please let us know the details asap.

**Comment by stomita** [comment]
It will not return id value when it is existing record. This is due to the REST API upsert behavior (which returns only HTTP 204).
https://www.salesforce.com/us/developer/docs/api_rest/Content/dome_upsert.htm
https://github.com/jsforce/jsforce/blob/master/test/connection-crud.test.js#L229-L251

**Comment by saparna90** [comment]
Thanks for the response.But for both the cases - I meant even in the Create case i dont get an id. But normal upsert - Create operation returns an id. 
Pointing to the same doc, 
https://www.salesforce.com/us/developer/docs/api_rest/Content/dome_upsert.htm


Response
    Successful response:

    {
        "id" : "00190000001pPvHAAU",
        "errors" : [ ],
        "success" : true
    }

    The response body is empty. HTTP status code 201 is returned if a new record is created.

But this doesnt happen with jsforce.

**Comment by stomita** [comment]
I'm sure it returns `id` field in the response in the above test code (See that assertion is done in returned record)
https://github.com/jsforce/jsforce/blob/master/test/connection-crud.test.js#L236

Please verify your code or post the code which fails to retrieve the id.

**Comment by saparna90** [comment]
okay. But we are calling https://github.com/jsforce/jsforce/blob/master/lib/sobject.js  -> upsert function -> our assumption is that it internally calls connection.js under https://github.com/jsforce/jsforce/blob/master/lib/connection.js. Please correct if i am wrong. In connection.js upsert function i could not see the response to be different for each. We have even printed console.dir for return(response) for our code but it gives only {success: true} or error messages. It doesnt return an id.

**Comment by saparna90** [comment]
We are trying this ,

self.sfconn.sobject(sObjectName).upsert(data,extIdField, function(err, ret) {
		if (err || !ret.success) { 
			logger.error({"message":"Salesforce Connector error"},{"errorMessage":"Exception occured while getting the connection","error":err});
			callback(err, ret); 
		}else{
			 logger.info({"message":"Salesforce Connector : updateOrCreate Successful"})
			callback(null, ret);
		}
		});
		}.bind(this));

**Comment by saparna90** [comment]
Can you please let me know any update on this ticket.

**Comment by stomita** [comment]
It cannot be said surely from your code but I'm afraid you are updating existing record instead of newly creating the one. Make sure the extIdField of the record is not dup in DB so that insert will happen in the upsert call.
