### ISSUE TITLE
Navigation is broken

### ISSUE THREAD

**Issue by ffxsam** [jsforce/jsforce#218]
![document_-_jsforce](https://cloud.githubusercontent.com/assets/12532733/7874172/dca4acd0-0560-11e5-86ce-05d3c9c5216f.png)

On Mac OS, latest Firefox. The links do nothing.

**Comment by stomita** [comment]
Fixed in https://github.com/jsforce/jsforce-website/commit/749f5f75bc60d304ce80435ba63a2d7f8eef517c
