### ISSUE TITLE
How to connect and fetch lead data, without user intervention?

### ISSUE THREAD

**Issue by ffxsam** [jsforce/jsforce#219]
Is it possible at all to use jsforce to simply connect to our SalesForce install and fetch lead information? I can't have any sort of authentication that the user needs to approve, as this would be a customer just hitting a web page. They expect their information to simply be displayed.

I'm using the browser version of the code. Basically all I want to be able to do is something along these lines:

```javascript
jsforce.browser.init({
  accessToken: '----', //is this the same as security token?
  loginUrl: 'https://test.salesforce.com'
});

jsforce.browser.on('connect', function (conn) {
  console.log('Connected');

  conn.query('select ....', function (error, result) {
    // we've got data
  });
});

jsforce.browser.login();
```

What happens now is, I get bounced to test.salesforce.com with this error:

>error=invalid_client_id&error_description=client%20identifier%20invalid

**Comment by subhog** [comment]
+1

**Comment by stomita** [comment]
First, access token is not same as "security token" - it is a token for API access obtained by OAuth2 authorization flow, and is equivalent to sessionId in Visualforce.

Second, If you are willing to host a web page to capture the visitor's information - who might be your customer but no login account in your Salesforce - exposing such tokens in the web page is not a good way. JSforce in browser cannot be used for such purpose.

I recommend you to host a service which works as a proxy to receive the user's request and post the captured information to Salesforce.
