### ISSUE TITLE
App for Force.com Canvas. Problem with OAuth2 

### ISSUE THREAD

**Issue by zaikin-andrew** [jsforce/jsforce#222]
Hi all. I build Canvas app based on MEAN stack and store on Heroku. I want get access to userInfo and use it for connection and queries to database. 
I have created app into salesforce.com dev account with clientId, clientSecret and then I have used them for user login via [OAuth2](https://jsforce.github.io/document/#oauth2). But when I try to run my app I have "Refused to display 'https://eu5.salesforce.com/setup/secur/RemoteAccessAuthorizationPage.apexp?…&sdtd=1#target_origin=https%3A%2F%2Feu5.salesforce.com&instance_id=_:test2:' in a frame because it set 'X-Frame-Options' to 'DENY'." 
It occurs after redirect from my app to salesforce.com auth page via [getAuthorizationUrl method](http://jsforce.github.io/jsforce/doc/OAuth2.html). 
Where I was wrong?

**Comment by stomita** [comment]
If your app is in Canvas the OAuth2 flow should be in popup window, not by redirect.

**Comment by zaikin-andrew** [comment]
Thanks. I use SignedRequest already :)
