### ISSUE TITLE
How to tell when a streaming api subscription succeeds

### ISSUE THREAD

**Issue by apechimp** [jsforce/jsforce#224]
When I subscribe to a push topic via `connection.streaming.topic('foo').subscribe(function (message {...})` how can I tell whether or not that subscription has succeeded? I made apechimp/jsforce@7622603a43d94827fdd70841084e8d1a79d5caa1 as a workaround, but am wondering if there's another way.

**Comment by stomita** [comment]
I understand the needs of returning Faye's subscription object to make cancel or receive subscription callback. But currently it returns topic object itself for method chaining. I don't know there are users who are using chaining actually, but it should be considered before making breaking change.

**Comment by apechimp** [comment]
Would you like me to clean up my branch and submit a PR?

I agree we'd need to be a little careful with this breaking change. Do you follow semver? It may be appropriate to rev the major version for this.
