### ISSUE TITLE
Bulk API hangs with Node 0.12.x

### ISSUE THREAD

**Issue by stemail23** [jsforce/jsforce#227]
Sorry I don't have time to fully investigate this (I've spent several hours, but can't find a root cause), but I've found that bulk.query() code that works fine on 0.10.x consistently hangs when run on Node v0.12.x.

Raising this mainly to flag the issue for investigation.

**Comment by SamProtas** [comment]
+1

**Comment by apechimp** [comment]
I've seen this happen when using bulk query: If any of the steps to [create the record stream fail](https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L791), the error is not handled. For this case, at least, maybe, an error event can just be emitted on the returned stream.

@stomita, does this sound reasonable?
