### ISSUE TITLE
I get conn.refreshToken = undefined ?

### ISSUE THREAD

**Issue by ChandanShankar** [jsforce/jsforce#242]
As I'm new to Salesforce and Node.js as you suggested in (conn.refreshToken missing?) #163. I have included "refresh token" scope. Even then I'm not getting the Refresh token. Can You please help me. 

I have selected the following scopes.

Access your basic information (id, profile, email, address, phone)
Access and manage your data (api)
Provide access to your data via the Web (web)
Provide access to custom applications (visualforce)
Perform requests on your behalf at any time (refresh_token, offline_access)

This what I'm getting when i try to hit the URL, from browser.
![dftly](https://cloud.githubusercontent.com/assets/10335980/8717569/5b7cf5e2-2bba-11e5-899d-16c2ecb5b20b.jpg). I'm faceing this issue from past 3days.

**Comment by stomita** [comment]
Which type are you using implicit flow or authorization code flow ? The refresh token is only available via authorization code flow.

**Comment by ChandanShankar** [comment]
@stomita, Thank's for the support. I'm using authorization code flow Technic itself, as I'm passing "code" as an parameter, for "req.param('code'); that means i'm following authorization code flow, even than i'm not able to receive Refreshtoken. 

"Please have look at my code sample below and let me know where i have committed the mistake."
 
var oauth2 = new jsforce.OAuth2({
     clientId : '<your Salesforce OAuth2 client ID is here>',
     clientSecret : '<your Salesforce OAuth2 client secret is here>',
     redirectUri : '<callback URI is here>'
});

/* SF OAuth request, redirect to SF login */
app.get('/oauth2/auth', function(req, res) {
      res.redirect(oauth2.getAuthorizationUrl({scope: 'api id web'}));
});
 
/* OAuth callback from SF, pass received auth code and get access token */

app.get('/auth/callback', function(req, res) {
     var conn = new jsforce.Connection({oauth2: oauth2});
     var code = req.param('code');
     conn.authorize(code, function(err, userInfo) {
        if (err) { 
      return console.error(err); 
    }
        req.session.accessToken = conn.accessToken;
        req.session.instanceUrl = conn.instanceUrl;
        req.session.refreshToken = conn.refreshToken;
        console.log(conn.refreshToken);
        var app_json = { "accessToken": req.session.accessToken, "instanceUrl":        req.session.instanceUrl, "OrgID":userInfo.organizationId, "refreshtoken": req.session.refreshToken}; //userInfo.organizationId
        filesystem.appendFile('sfdc_auth_02.txt', JSON.stringify(app_json) + ',', function (err) {
          if (err) throw err;
        });
        URL = "URL which I'm using for oauth"
        res.redirect('/dfty/case');
    });
});

app.get('/dfty/case', function(req, res) {
    // if auth has not been set, redirect to index
         if (typeof req.session == 'undefined' || !req.session.accessToken || !req.session.instanceUrl) {
                 console.log(Date() + ' - ' + run_id + ' - Not yet authorized, so redirecting to auth');
                  res.redirect('/oauth2/auth?f=cases'); 
         } else {
                    var query = 'SELECT CaseNumber, Subject, Origin FROM case LIMIT 10';
               
                 // open connection with client's stored OAuth details
                    var conn = new jsforce.Connection({
                     accessToken: req.session.accessToken,
                     instanceUrl: req.session.instanceUrl
                      });
                        ---
                          ---
                        ---
  }

**Comment by stomita** [comment]
Please try changing

```
res.redirect(oauth2.getAuthorizationUrl({scope: 'api id web'}));
```

to

```
res.redirect(oauth2.getAuthorizationUrl({ scope: 'api id web refresh_token' }));
```

or

```
res.redirect(oauth2.getAuthorizationUrl());
```

**Comment by ChandanShankar** [comment]
@stomita, Thanks a lot finally it worked.

**Comment by mrdeezer** [comment]
Hello guys whenever I am using the above code I get error >>

Cannot get /    on the browser.

Please help me out. When I remove /oauth2/auth from get app.get and leave just '/' there then Its redirecting me to my Heroku App URL I put into redirectURI but my code app.get('/auth/callback', function(req, res) { is not executing. I put console.log there and nothing printed that means the compiler is not even executing that function. I require this help very urgently.
