### ISSUE TITLE
newline character or carriage return

### ISSUE THREAD

**Issue by amit777** [jsforce/jsforce#250]
Hi, I'm trying to do a very simple operation to update the email signature for a user.  However, I cannot seem to get the newline character to appear.  If I update the signature via the web GUI at My Settings->Email Settings , the newline appears.  However when trying to update, I cannot get a newline to work.  I've tried all kinds of combination of escape sequences  such as \n, \r\n, \\n, \\r\\n, <br/>  etc. Here is example of the query:
```
var sig = [
  'Line1'
  'Line2'
].join('\n');

conn.sobject("User").update([{Id: 'objectid', Signature: sig }], function(err, rets){
       console.log(err);
       console.log(rets);
});
```

Any ideas if this is possible?

**Comment by stomita** [comment]
Seems like a problem of Salesforce REST API.
