### ISSUE TITLE
Installation issues on Windows 8 + Vagrant 1.7.2 + VirtualBox 4.3.20

### ISSUE THREAD

**Issue by markgarg** [jsforce/jsforce#253]
"npm install jsforce" (the latest 1.4.1) version on Windows 8 + Vagrant 1.7.2 + VirtualBox 4.3.20 did not work initially because of symlink issues:

    npm ERR! Linux 3.2.0-23-generic
    npm ERR! argv "node" "/home/vagrant/.nvm/v0.10.40/bin/npm" "install"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! path ../coffee-script/bin/coffee
    npm ERR! code UNKNOWN
    npm ERR! errno -1

    npm ERR! UNKNOWN, symlink '../coffee-script/bin/coffee'

"npm install jsforce --no-bin-links" gives me the following error:

    npm ERR! Linux 3.2.0-23-generic
    npm ERR! argv "node" "/root/.nvm/v0.10.40/bin/npm" "install" "--no-bin-links"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! path /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-obj
    ect-property/node_modules/is-property/package.json.4f3fe943fc89778a9375e247e2d52907
    npm ERR! code EPERM
    npm ERR! errno 50

    npm ERR! Error: EPERM, open '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modul
    es/generate-object-property/node_modules/is-property/package.json.4f3fe943fc89778a9375e247e2d52907'
    npm ERR!  { [Error: EPERM, open '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_m
    odules/generate-object-property/node_modules/is-property/package.json.4f3fe943fc89778a9375e247e2d52907']
    npm ERR!   errno: 50,
    npm ERR!   code: 'EPERM',
    npm ERR!   path: '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate
    -object-property/node_modules/is-property/package.json.4f3fe943fc89778a9375e247e2d52907' }
    npm ERR!
    npm ERR! Please try running this command again as root/Administrator.
    npm ERR! Linux 3.2.0-23-generic
    npm ERR! argv "node" "/root/.nvm/v0.10.40/bin/npm" "install" "--no-bin-links"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! path npm-debug.log.65a0fc36c5d0bee259038804e05f4ff6
    npm ERR! code ETXTBSY
    npm ERR! errno 62

When I reverted to 1.3.1, "npm install --no-bin-links" works.

**Comment by markgarg** [comment]
Some part of the npm debug log for the error. Note: I was running this as an administrator.

    5412 info install lodash@3.10.1
	5413 info postinstall lodash@3.10.1
	5414 verbose unlock done using /home/vagrant/.npm/_locks/lodash-a98e8fe50a5e7a9e.lock for /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js/node_modules/xmlbuilder/node_modules/lodash
	5415 verbose about to build /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js/node_modules/xmlbuilder
	5416 info build /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js/node_modules/xmlbuilder
	5417 info install xmlbuilder@2.6.4
	5418 info postinstall xmlbuilder@2.6.4
	5419 verbose unlock done using /home/vagrant/.npm/_locks/xmlbuilder-12a3bec2db53e5dc.lock for /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js/node_modules/xmlbuilder
	5420 verbose about to build /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js
	5421 info build /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js
	5422 info install xml2js@0.4.10
	5423 info postinstall xml2js@0.4.10
	5424 verbose unlock done using /home/vagrant/.npm/_locks/xml2js-35a9b78399b383c1.lock for /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/xml2js
	5425 verbose about to build /vagrant/node-jsforce-test/node_modules/jsforce
	5426 verbose unlock done using /home/vagrant/.npm/_locks/jsforce-60339353e606f450.lock for /vagrant/node-jsforce-test/node_modules/jsforce
	5427 verbose stack Error: EPERM, open '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/package.json.ef9f9152b89a91840d39f65fda99c652'
	5428 verbose cwd /vagrant/node-jsforce-test
	5429 error Linux 3.2.0-23-generic
	5430 error argv "node" "/home/vagrant/.nvm/v0.10.40/bin/npm" "install" "--no-bin-links"
	5431 error node v0.10.40
	5432 error npm  v2.13.3
	5433 error path /vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/package.json.ef9f9152b89a91840d39f65fda99c652
	5434 error code EPERM
	5435 error errno 50
	5436 error Error: EPERM, open '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/package.json.ef9f9152b89a91840d39f65fda99c652'
	5436 error  { [Error: EPERM, open '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/package.json.ef9f9152b89a91840d39f65fda99c652']
	5436 error   errno: 50,
	5436 error   code: 'EPERM',
	5436 error   path: '/vagrant/node-jsforce-test/node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property/package.json.ef9f9152b89a91840d39f65fda99c652' }
	5437 error Please try running this command again as root/Administrator.
	5438 verbose exit [ 50, true ]
	5439 verbose unbuild node_modules/jsforce/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property
	5440 info preuninstall is-property@1.0.2
	5441 info uninstall is-property@1.0.2

**Comment by stomita** [comment]
Do you have your Vagrantfile ?

**Comment by markgarg** [comment]
Here you go (same result without natdnshostresolver1 on too) :

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    Vagrant.configure(2) do |config|
      config.vm.box_url = "http://files.vagrantup.com/precise64.box"
      config.vm.box = "hashicorp/precise64"
      config.vm.network "forwarded_port", guest: 3000, host: 3000
      # For Redis
      config.vm.network "forwarded_port", guest: 6379, host: 6379, auto_correct: true

       config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant-root", "1"]
      end
      
      config.vm.provision "shell", path: "provision/setup.sh"
     
    end

**Comment by stomita** [comment]
I could install JSforce successfully. Please check the node.js version and npm. Setup detail in ubuntu is here. 
https://github.com/joyent/node/wiki/installing-node.js-via-package-manager
