### ISSUE TITLE
v1.5.0 seems to be missing from the cdn 

### ISSUE THREAD

**Issue by icecubed** [jsforce/jsforce#256]
Request URL:https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.5.0/jsforce.min.js
Request Method:GET
Status Code:404 Not Found
Response Headers
cf-cache-status:HIT
cf-ray:214be2a061db02fd-LHR
content-encoding:gzip
content-type:text/html
date:Wed, 12 Aug 2015 11:36:55 GMT
server:cloudflare-nginx
status:404 Not Found
vary:Accept-Encoding
version:HTTP/1.1

**Comment by stomita** [comment]
Now the CDN has been refreshed and 1.5.0 is available from the URL.

**Comment by icecubed** [comment]
thanks @stomita
