### ISSUE TITLE
Mocking/Stubbing

### ISSUE THREAD

**Issue by akatechis** [jsforce/jsforce#26]
Is there anyway to mock/stub a salesforce server so I can write tests that don't reach out to the network?

I'm currently using a stub API server via restify that simply returns stub responses, and pass that URL to the Connection constructor, (for stubbing my custom apexrest endpoints that live on salesforce servers) but I'm not quite clear what endpoints I need to mock in order to simulate the responses JSForce will receive when I execute SObject queries, for example.

**Comment by mwj8410** [comment]
For anyone else hitting this page looking for something similar, I solved for this by stubbing out the individual accessor function after connection as follows:

```javascript
sinon.stub(jsforce.Connection.prototype, 'create', function () {
  arguments[3](null, { success: true });
});
```

For context, I am testing a Node v6.2.0 API using Sails v1.0.0-19. Also, I am using ES6, but usage of arrow functions changes the meaning of `arguments`.

This gives fine grained control of the touch points that my code has with this library. In other words, I can easily introduce an error case with one parameter change to fully exercise every code path my controller expresses. Admittedly, I've not had to work with anything other than the 'tooling' functions, and this approach may not work outside those features.

**Comment by brsanthu** [comment]
We did following and it seems to be working fine.

Stub the jsforce
`sandbox.stub(jsforce)`

Specify what happens when connection is created
```
jsforce.Connection.returns({
  query: (soql) => {
    const result = {
      records: [
        ... your records data
      ],
    };

    return Promise.resolve(result);
  },
});
```

**Comment by bmik7216** [comment]
Has anyone gotten Jest to work with jsforce? I don't think it can automock and I am having trouble trying to mock it manually.

**Comment by pcon** [comment]
If anyone runs across this, I have been able to mock out the connection / login method with Jest doing the following

Under `__mocks__/jsforce.js`

```javascript
const jsforce = jest.createMockFromModule('jsforce');

const __loginMock = jest.fn(function (user, pass, cb) {
    cb();
});

jsforce.Connection = jest.fn().mockImplementation(() => {
    return {
        login: __loginMock
    };
});

jsforce.__loginMock = __loginMock;

module.exports = jsforce;
```

Then in your test

```javascript
const jsforce = require('jsforce');
jest.mock('jsforce');
test('Test', () => {
    expect.assertions(1);
    return callThatDoesLogin().then(function () {
        return new Promise(function (resolve) {
            expect(jsforce.__loginMock.mock.calls.length).toBe(1);
        });
    });
});
```

Now you don't need the whole promise stuff if your `callThatDoesLogin` doesn't handle promises, but you should be able to expand it from there for you use case.  I bound the `fn()` call to `__loginMock` since I don't have access to the returned `Connection` that has an instance of the login on it.

**Comment by vicnguyenqt** [comment]
Can someone provide the fully example how the mocking is gonna work with jsforce?

**Comment by pcon** [comment]
@vicnguyenqt I wrote [this blog post](https://blog.deadlypenguin.com/2022/02/15/mocking-jsforce/) for you.  Hopefully it helps

**Comment by cristiand391** [comment]
Triaging old issues...

FWIW, jsforce >= v2 uses `node-fetch` v2 which allow to mock requests using `nock`:
https://github.com/jsforce/jsforce/blob/3.0/test/http-api.test.ts
