### ISSUE TITLE
Does jsforce support Place Order REST API ?

### ISSUE THREAD

**Issue by liratanak** [jsforce/jsforce#261]
Hi,

As in [Create Order](https://developer.salesforce.com/docs/atlas.en-us.api_placeorder.meta/api_placeorder/sforce_placeorder_rest_api_standalone_post.htm), It seem to work with [Apex.post](http://jsforce.github.io/jsforce/doc/Apex.html#post) with some(bad) change on [apex.js#L22](https://github.com/jsforce/jsforce/blob/1.5.0/lib/api/apex.js#L22) to `return this._conn.instanceUrl;`
It is a better way I can work with the Place Order REST API ?

Sincerely,
Liratanak

**Comment by stomita** [comment]
Place order API is not supported, but you can use `Connection#request()` to make arbitrary REST request.

```javascript
conn.request({
   method: 'post',
   body: { OrderItems: items }
}, function(err, ret) {
  // ...
});
```

**Comment by liratanak** [comment]
Thanks, that's help.
It work for me with small change.

```javascript
connection.request({
	method: 'post',
	url: '/services/data/v30.0/commerce/sale/order',
	headers: {
		'Content-Type': 'application/json'
	},
	body: JSON.stringify({
		"order": [
			// orders
		]
	})
}, function(err, ret) {
	// ...
});
```

**Comment by jpmonette** [comment]
@stomita It's very good to see that we can build our own HTTP requests to the API using this `request` function. It should be added to the documentation!

**Comment by stomita** [comment]
@liratanak Sorry the reply above I didn't tested. Need to call as you presented.

@jpmonette The doc is not available yet, but opened in API reference
http://jsforce.github.io/jsforce/doc/Connection.html#request
