### ISSUE TITLE
promise.done no longer available?

### ISSUE THREAD

**Issue by dangmai** [jsforce/jsforce#262]
Hi, after upgrading to jsforce 1.5.0 my script starts throwing an error - apparently `promise.done` is no longer available, so my code that depends on it no longer runs. Is there plan to bring this method back?

Thanks!

**Comment by stomita** [comment]
We changed the internal promise library.
You can change the `done()` to `then()`, because `done()` is not standard Promise function.

**Comment by JordanBelford** [comment]
The documentation is out of date. It shows done as an available method.
http://jsforce.github.io/jsforce/doc/Promise.html
