### ISSUE TITLE
Logout CORS Error with Proxy

### ISSUE THREAD

**Issue by rbaindourov** [jsforce/jsforce#263]
Hi There,

I am having an issue where the proxy is not used when you try and call jsforce.browser.logout(); I am using jsforce-ajax-proxy and it works great for login, and conn.query.

Should be able to reproduce with this simple code block, but fill in a query and config values please:
```javascript
jsforce.browser.init( {
  "loginUrl": "https://login.salesforce.com",
  "clientId": "",
  "proxyUrl": "https://*/proxy",
  "redirectUri": "https://*/oauthCallback"
});

jsforce.browser.on('connect', function( conn ){
    console.log( 'connect' );

    var queryStr = ""
    console.log('conn.query', queryStr );
    conn.query(queryStr, function(err, result){

      if(err){
        console.error('error', err)
      }else {
        jsforce.browser.logout();
      }

    })
})
```

Thank you!

**Comment by stomita** [comment]
Confirmed that the token revocation request is not using proxy and fails to connect.
