### ISSUE TITLE
Question about CRUD updates

### ISSUE THREAD

**Issue by rdietrick** [jsforce/jsforce#264]
I'm attempting to update several records at once from a browser using jsforce.  Despite the fact that I'm passing 10 records to the update() function, I can see that jsforce is sending 10 separate HTTP requests to the server, each with a single JSON object.  I'm concerned that it is going to put my app in danger of hitting the API call quota.  Is there a better way to do this with jsforce?

**Comment by stomita** [comment]
REST API doesn't support multiple records update in one request as SOAP API does.
You can use `updateBulk()` instead of `update()`, which use bulk API internally.

**Comment by leodutra** [comment]
Is there any documentation for `updateBulk()`?

**Comment by ishantiw** [comment]
@leodutra Did you find any documentation for `updateBulk()`?

**Comment by leodutra** [comment]
Only [API Reference](http://jsforce.github.io/jsforce/doc/Bulk.html), but no solid examples.

Had to dive into the source, linked in the API refs.

**Comment by leblancmeneses** [comment]
```
   const bulkResults = await conn.sobject(table).updateBulk(updates);
```
