### ISSUE TITLE
session could not be mutually authenticated for the use with REST API

### ISSUE THREAD

**Issue by CodisRedding** [jsforce/jsforce#27]
I'm getting the error: "MUTUAL_AUTHENTICATION_FAILED: This session could not be mutually authenticated for the use with REST API" one a previously working node site of mine.

The only reference I've found so far is this from Salesforce: http://docs.releasenotes.salesforce.com/en-us/winter14/release-notes/rn_186_forcecom_security_two_way_mutual_auth.htm Any ideas?

**Comment by iofirag** [comment]
@fourq  thanks, good answare!

**Comment by tggagne** [comment]
@fourq , from your comments it looks like you're using mutual authentication with rest.  Are you getting your token using SOAP or are you able to login using REST and grant_type=password?

**Comment by iofirag** [comment]
the problem in my case it was a expired password like @fourq answered before.
after change it in s.f and in the request - it go back to work
