### ISSUE TITLE
Unable to get refresh token - app is undefined

### ISSUE THREAD

**Issue by sjurgis** [jsforce/jsforce#271]
This relates to #242 as I was using the example from the documentation.

I was trying [this other example](https://jsforce.github.io/document/#authorization-request) as assumption is that I won't be getting refresh token with the implicit flow.

However, what is unclear from the second example is *your app is callbacked from Salesforce with authorization code in URL parameter* with following code `app.get('/oauth2/callback', function(req, res) {`

What should be **app.get** here? Currently it is undefined and throws JavaScript exception. Is this some bower/node specific thing (citing that whole documentation is based on node)? I am trying to run this in the browser.

Many thanks.

**Comment by stomita** [comment]
> What should be app.get here? Currently it is undefined and throws JavaScript exception. Is this some bower/node specific thing (citing that whole documentation is based on node)? I am trying to run this in the browser.

It is the code from [express.js](http://expressjs.com/) framework, one of the most popular web application framework in Node.js world (like Rails or Sinatra in Ruby)
