### ISSUE TITLE
TypeError: Cannot read property 'result' of null(…) in call back function.

### ISSUE THREAD

**Issue by ravikantsaini91** [jsforce/jsforce#277]
In metadata deployment When i did a deployment of zip file in kilobytes it's working. When I deploy a 3mb zip file with it. It's giving me this error in callback function:

"TypeError: Cannot read property 'result' of null(…)"

Here is my code:

conn.metadata.deploy(baseStr, deployOption,handleDetail);
function handleDetail(err, result){
  if(err) 
  {
    console.log(err);
  }
  else
  {
    console.log(result);
  }
}

The deployment is working but I am not able to track result in callback function. 
Is there a solution of it? If there is a solution of it please help me.

**Comment by spawnbean** [comment]
I believe I am having the same issue with this code below. The field gets created but I have no way to confirm or present the results later

    conn.metadata.create('CustomField', metadata, function(err, results) {
      function enableButton() {
            self.disabled = false;
            $(self).html(buttonText);
        }
      if (err) { console.error(err); }
      console.log(results.length); //this is undefined at this point
      for (var i=0; i < results.length; i++) {
        var result = results[i];
        console.log('success ? : ' + result.success); //this is not written to the console at all
        console.log('fullName : ' + result.fullName);
      }
      enableButton(); 
    });
