### ISSUE TITLE
how to use "or" or "includes" in query method chaining?

### ISSUE THREAD

**Issue by jtarre** [jsforce/jsforce#278]
Hi! 

For my Account object, I have an enum, CoPa_Association__c, that categorizes accounts by enum. In the query method chaining, I was wondering how to use an "includes" or "or" on an enum so I do not have to write a call for each enum. Thanks!

          conn.sobject("Account")
              .find(
              {
                CoPa_Association__c : "Company Partner" // would like to say "Company Partner" or "Potential Company Partner"
              },
              "*")
              .execute( function (err, partners) {
...

**Comment by stomita** [comment]
In your proposed case, you can just set the candidate array in value of condition for the field.

```javascript
conn.sobject("Account")
    .find({
        CoPa_Association__c : [ "Company Partner", "Potential Company Partner" ]
    })
    .execute(function (err, partners) {
        // ...
    })
```

Generally, the `$or` operator is the one which works as the logical operator in SOQL.

```javascript
conn.sobject("Account")
    .find({
        $or: [
           { Name : { $like: "ACME%" } },
           { Name : { $like: "Mashmatrix%" } }
        ]
    })
    .execute(function (err, accounts) {
        // ...
    })
```

These query format is much derived from MongoDB's syntax, so checking the [MongoDB's document](http://docs.mongodb.org/manual/tutorial/query-documents/) is helpful.
