### ISSUE TITLE
Can IE9 be supported?

### ISSUE THREAD

**Issue by craigathon** [jsforce/jsforce#283]
In version 1.5.0 of jsforce-core.js, the error is thrown on load:
SCRIPT1010: Expected identifier
jsforce-core.js, line 972 character 6

This project is awesome but we really need to support IE9+

**Comment by colestrode** [comment]
I'd love to get 1.5.1 released so we can get the fix for #247. Anything I can do to help resolve this issue?

**Comment by colestrode** [comment]
The issue is the `.catch()` calls in the promise chain. That can be fixed by doing `promise['catch'](...)`

**Comment by BradRuderman** [comment]
@colestrode  +1
