### ISSUE TITLE
Slim down jsforce-core browser library

### ISSUE THREAD

**Issue by btakita** [jsforce/jsforce#284]
Some dependencies, like underscore.js, can be replaced with something smaller.

**Comment by Krisa** [comment]
It was my concern too. The easiest would be that, all external libraries shouldn't be bundle into the core, at all, so that we can e.g. add our own version of underscore (or lodash according to the package.json?), reused in other parts of the application. Removing it altogether would be obviously better...

**Comment by stomita** [comment]
Now the latest code has been slimed-down like this.

```
-rw-r--r--  1 stomita  staff    2856  3  2 17:59 build/jsforce-api-analytics.min.js
-rw-r--r--  1 stomita  staff    2029  3  2 17:59 build/jsforce-api-apex.min.js
-rw-r--r--  1 stomita  staff   11581  3  2 17:59 build/jsforce-api-bulk.min.js
-rw-r--r--  1 stomita  staff    3391  3  2 17:59 build/jsforce-api-chatter.min.js
-rw-r--r--  1 stomita  staff   28759  3  2 17:59 build/jsforce-api-metadata.min.js
-rw-r--r--  1 stomita  staff    3604  3  2 17:59 build/jsforce-api-soap.min.js
-rw-r--r--  1 stomita  staff   44358  3  2 17:59 build/jsforce-api-streaming.min.js
-rw-r--r--  1 stomita  staff    2708  3  2 17:59 build/jsforce-api-tooling.min.js
-rw-r--r--  1 stomita  staff  219569  3  2 17:59 build/jsforce-core.min.js
-rw-r--r--  1 stomita  staff  289901  3  2 17:59 build/jsforce.min.js
```

The `jsforce.min.js` is 284KB in size and the `jsforce-core.min.js` is 216KB. Usually the size is become rather big because it includes polyfills like Buffer.

It will be published to npm in a few days.
