### ISSUE TITLE
ECONNRESET 

### ISSUE THREAD

**Issue by rbaindourov** [jsforce/jsforce#285]
Hi There,

First, as always I like to say thank you for your hard work on this library.

Recently I wrote a syncer script using jsforce, and I can't help but notice when executing a very large query on a very large table the connection gets reset multiple times.

Now I have built in recovery procedure into the script to handle the problem, but my Project Manager asked me if there was anything I could do to increase the timeout time on my end.

My very simple log file looks like this:

``` sh
starting another job: Task
begin working on job Task
updated job Task status {running:true}
beginSync
{ [Error: socket hang up] code: 'ECONNRESET' }
gotResults
salesforce error: { [Error: socket hang up] code: 'ECONNRESET' }
beginSync
{ [Error: socket hang up] code: 'ECONNRESET' }
gotResults
salesforce error: { [Error: socket hang up] code: 'ECONNRESET' }
beginSync
{ [Error: socket hang up] code: 'ECONNRESET' }
gotResults
salesforce error: { [Error: socket hang up] code: 'ECONNRESET' }
beginSync
gotResults
updating job Task lastDate:2014-11-14T00:37:00.000+0000
continueSync
gotResults
updating job Task lastDate:2014-11-19T19:31:30.000+0000
continueSync
...
```

After three hangups, everything begins to work correctly. This has been a consistent pattern with one table and query.

Please do let me know if there is some setting on my end I can control to extend how long the connection is open for.

Thank you!

**Comment by vikashk1** [comment]
I am having same problem.
Did you find any solution??

**Comment by tejasmanohar** [comment]
Seen similar things.

**Comment by vikashk1** [comment]
# ## ###

**Comment by tejasmanohar** [comment]
@vikashk1 ?

**Comment by Harishgolla** [comment]
Seen similar things? Any idea how to avoid this kind of errors for large queries.

**Comment by tejasmanohar** [comment]
@Harishgolla Haven't had any luck. I think something is wrong with the closing of jobs. I see them sit open from SF console even after they've finished sometimes. Maybe too many open ones leads to ECONNRESET

**Comment by Harishgolla** [comment]
@rbaindourov What kind of retry code you wrote to handle this ?

```Now I have built in recovery procedure into the script to handle the problem,```

**Comment by tejasmanohar** [comment]
just check if err.code == ECONRESET and run it in a loop w/ try catch or .catch()

**Comment by seanfuture** [comment]
We submit a lot of batch jobs to Salesforce on a daily basis and I can tell you 1st hand that we see this error regularly.  We process about 100-200 batch jobs a day.  It's become much more frequent in the past 3-4 months.  I agree with @tejasmanohar in that we get these most commonly when trying to close jobs - As though Salesforce simply can't get the job done at times and so the API call will timeout.  All-in-all their API is extremely unreliable.

Currently forced to issue retries and/or alternative designs that limit the amount of jobs needed just to attempt to avoid the unreliable Salesforce job system.  Suggestions welcome however short of opening a support ticket with Salesforce I believe this is out of jsforce's control.  Please leave this ticket open for now in case a creative solution presents itself.

**Comment by ArcusSimonCull** [comment]
Encountered this issue when sending multiple queries through a Promise.all(). Interestingly the first retry hit an issue where a query returned 0 results (not possible with 'SELECT Id, DeveloperName FROM RecordType'). The next retry succeeded with no issue.  If this is a timeout issue, is there a way to define the timeout for the http.request() to allow more time for SF to complete the request at "busy" times?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
