### ISSUE TITLE
Enhancement: Typescript Definitions for Library

### ISSUE THREAD

**Issue by patnaikshekhar** [jsforce/jsforce#287]
It would be very useful to have Typescript definitions (https://github.com/DefinitelyTyped/DefinitelyTyped) for this awesome library.

**Comment by loganvolkers** [comment]
Typings is the latest and greatest type manager for Typescript and replaced DefinitelyTyped and TSD.

Here's their advice:

> Ask the author

> You can open an issue in the package's repository and ask if they'd be interested in providing a TypeScript definition for their users. If they are, you can link them to [this issue](https://github.com/typings/typings/issues/322) on collaborating, in case they need a hand getting started.

> How?

> There's two way we can collaborate with package authors. **The preferred is that we can help get type definition inside packages**. This means consumers don't even need to install Typings, and things start working immediately after they install a package. The second method is to collaborate with the author in http://github.com/typed-typings, which means consumers will continue to install Typings for now. The least preferred method is what we currently do now, where we contribute independently, unofficially and do not collaborate. The model used is dependent on the package author.

@stomita would you be open to pull requests?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
