### ISSUE TITLE
support for assignment rule headers

### ISSUE THREAD

**Issue by tedjt** [jsforce/jsforce#29]
I'd like to update objects without triggering assignment rules. Typically I would do that using [Assignment Rule headers](http://www.salesforce.com/us/developer/docs/api/Content/sforce_api_header_assignmentruleheader.htm#topic-title), but I don't see support in jsforce for setting the [SForce-Auto-Assign](http://www.salesforce.com/us/developer/docs/api_rest/Content/headers_autoassign.htm) request header, or really any custom headers .

It seems like a fairly major change to plum support for extra headers into all the sobject and connection prototype methods. I've done that locally but am wondering what the best thing to do for a PR is? My solution was to change signature from 

`update(records, callback)` to `update(records, callback, options)`

and options is a kitchen sink like 

``` js
{
  extraHeaders: {
    SForce-Auto-Assign: 'FALSE'
  }
}

```

**Comment by rlbarreto** [comment]
Can i set a header in the insertBulk operation to run the assignment rule?

**Comment by tedjt** [comment]
No - insertBulk doesn't take an options object. It appears bulkload does though, so you it would probably be easy to make a pull request to change the signature.

Looks like you would also need to update the bulk.js load method to accept options for more than just upsert
https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L749
