### ISSUE TITLE
Not possible to autoFetch in bulk update

### ISSUE THREAD

**Issue by pkopac** [jsforce/jsforce#297]
Hi!

I'm using bulk update, but it updates only 10 000 records and stops. I thought there should be some way to set a higher limit, but that's possible only with execute, update lacks that possibility, but maybe I got something wrong.

query = context.connection
            .sobject("Account")
            .find({})
.update(function(record){ //do stuff })

The code above processes only first 10 000 records.

**Comment by stomita** [comment]
Unfortunately the stream update feature in JSforce currently supports only one batch call with bulk API, which is limited to 10,000 records.

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_concepts_limits.htm

We may plan the way to seamlessly call multiple batches without handling such limitation in developer's side.

**Comment by pkopac** [comment]
Thank you for the reply. It would be worth mentioning this in the documentation, though. https://jsforce.github.io/document/#bulk-api

For now I solved it by setting "updated" timestamp to each object and re-executing the batch until all objects are updated.

And thanks for the nice useful library :)
