### ISSUE TITLE
How to set pollTimeout for Bulk job using alternative api method?

### ISSUE THREAD

**Issue by samueleaton** [jsforce/jsforce#298]
these alternative methods were provided in the documentation for doing a bulk job, but it doesn't say how to set the poll timeout option for these method. 

``` javascript
conn.sobject("Account").insertBulk(accounts, function(err, rets) {
  // ...
});
```

``` javascript
conn.sobject("Account").bulkload("insert").execute(accounts, function(err, rets) {
  // ...
});
```

Here is a quick link to the docs: [Bulk API](https://jsforce.github.io/document/#bulk-api)

I'm getting a pollingTimeout error even though my job is very short. I would like to increase the pollTimeout using these methods. 

Even with the polling timeout, the records are all successfully added to salesforce. I just have to go and check manually.

Thank you!

**Comment by stomita** [comment]
You can use the `bulk` object in the connection objet to change the polling timeout/interval of bulk API access.

```js
var conn = new jsforce.Connection({ ... });
conn.bulk.pollInterval = 5000; // 5 sec
conn.bulk.pollTimeout = 60000; // 60 sec
```
Actually, `SObject#insertBulk()` or `SObject#bulkload()` is the shortcut to the `conn.bulk.load()`.

**Comment by rstor1** [comment]
Old but was related and still could use some clarification. I have a batch size of 5000 and `this.connection.bulk.pollTimeout = 1800000` without any pollInterval set. I am getting a polling timeout error and wondering if I need to add a pollInterval variable as well and how would one know at what value to set the pollInterval?

Thanks

**Comment by smohantyCME** [comment]
Can we get some explanation on this?

**Comment by jcwatson11** [comment]
Bumping this question because it seems important. Can we get some explanation from someone on the jsforce team who knows?

**Comment by paulius005** [comment]
Bump on this. We've just switched to the bulk API and are experiencing `PollingTimeout` errors as well. Not quite clear on what's going on, but does setting a `pollingTimeout` solve the issue for y'all?

```javascript
PollingTimeout: Polling time out. Job Id = [xxx] , batch Id = [xxx]
    at Timeout.poll [as _onTimeout] (/usr/local/loom/node_modules/.pnpm/jsforce@1.11.0/node_modules/jsforce/lib/api/bulk.js:573:17)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by cristiand391** [comment]
@paulius005 I see you are on jsforce v1, so:

the default timeout for polling on bulk is 10s:
https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/api/bulk.js#L737

if you are manually using the bulk API methods then you can specify a timeout in `ms` when calling `poll`:
https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/api/bulk.js#L561

if you aren't calling `poll` manually then you probably use some methods that do that under the hood, in those cases you set those via the connection instance, like this:
https://github.com/jsforce/jsforce/blob/e760c2843d8d23fd57331661699dc538784f7a1c/test/bulk.test.ts#L13

**NOTE**: the exampled linked above is from v3 but the logic is the same on v1.

This will be covered in more detail in the new docs.

**Comment by aditya4singla** [comment]
Hi @cristiand391 I work with @paulius005. 

To follow up on our current setup: we are using `upsertBulk` and we have the pollTimeout and pollInterval setup like so:
```
    conn.bulk.pollTimeout = 25000;
    conn.bulk.pollInterval = 5000;
```

However, even with this, we are seeing some some jobs fail with the PollingTimeout error. Currently we don't have much usage so we are only sending 2-5 records in one api call.

Should we be using the manual bulk api methods rather than `upsertBulk` (which seems to be a wrapper)?

> NOTE: the exampled linked above is from v3 but the logic is the same on v1.
I wasn't aware of there being a v3 method. Should we aim to move to v3 or at least v2? Hoping to find a way to resolve this issue so we can reliably use bulk api.

**Comment by cristiand391** [comment]
> However, even with this, we are seeing some some jobs fail with the PollingTimeout error. Currently we don't have much usage so we are only sending 2-5 records in one api call.

With those values it should timeout after 25s, can you confirm it timed out after 25s? could help if you have logs with timestamps to compare. The error doesn't included the timeout so it's hard to tell if it's picking up the value you set, we fixed this in jsforce v2.

> Should we be using the manual bulk api methods rather than upsertBulk (which seems to be a wrapper)?

either is fine, `upsertBulk` is usually easier than having to create the job, upload data and handle polling.

The Bulk API is recommended if you are working with bigger data sets (like a few thousands of records), if that's not your case you will be fine using `upsert` and passing it an array of records:
https://jsforce.github.io/document/#upsert

> I wasn't aware of there being a v3 method. Should we aim to move to v3 or at least v2? Hoping to find a way to resolve this issue so we can reliably use bulk api.

I meant jsforce v3. By looking at the stacktrace provided above I see you are using jsforce v1. Since we are close to v3 GA I would suggest to wait and go straight to v3 (we'll publish a migration guide).

**Comment by aditya4singla** [comment]
> With those values it should timeout after 25s, can you confirm it timed out after 25s?

Yep, checked the logs and there's about 25s b/w the log saying the job has started and the log saying the job has failed. 

> The Bulk API is recommended if you are working with bigger data sets (like a few thousands of records)

Ah I see. So we should aim to only use the bulk API if we have > 100 or so records to send at once? We do expect to have a lot more usage as we ramp up customers onto our integration. 

> I meant jsforce v3. By looking at the stacktrace provided above I see you are using jsforce v1. Since we are close to v3 GA I would suggest to wait and go straight to v3 (we'll publish a migration guide).

Understood, thank you for the help!

**Comment by cristiand391** [comment]
> Ah I see. So we should aim to only use the bulk API if we have > 100 or so records to send at once? We do expect to have a lot more usage as we ramp up customers onto our integration.

Correct, for reference:

if you pass an array of records to `conn.sobject.upsert` it will do 1 API call per record:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm

https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/connection.js#L1002-L1027

check the comment on line 1022, if you are passing a bunch of records it's more likely that you'll end up in a case like that if one request fail (or worse, reach your [daily API limit](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers_api_usage.htm?q=limits))

`conn.sobject.upsertBulk` will use the Bulk API, so fewer requests that could fail

**Comment by paulius005** [comment]
@cristiand391 The main question that we have is why are we receiving that `pollingTimeout` in the first place? Even if we're just pushing 4 records via the bulk API, we're not sure why we would encounter a timeout. 

Is this something that's fixed in v3?

```
export const pushDataToSalesforce = (
  data: AllDataTypes[],
  conn: jsforce.Connection,
  runId: string,
  tools: ServerTools,
  loggerPrefix: string
): Promise<any> => {
  // [FSP-750] Temporarily don't use bulk api due to erratic PollingTimeout errors
  const shouldUseBulk = false;

  if (shouldUseBulk) {
    // Update pollTimeout to 25s to allow for 10,000 rows to be sent to Salesforce (edge case)
    // More information here: https://www.notion.so/loom/Salesforce-rate-limits-5f0704de3d9543b6abdf7367ce2e7a48
    conn.bulk.pollTimeout = POLL_TIMEOUT;
    conn.bulk.pollInterval = POLL_INTERVAL;

    return new Promise((resolve, reject) => {
      // Note: the type for sobject.upsertBulk is wrong in @types/jsforce. It expects upsertBulk to only have (data, callback)
      // whereas in the source code, we can clearly see that it needs (data, extIdField, callback)
      // Source: https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/sobject.js#L328
      (conn.sobject(LOOM_MODEL) as any).upsertBulk(
        data,
        SHARED_LINK_ID_AND_EMAIL,
        upsertCallback(data, runId, tools, loggerPrefix, true, resolve, reject)
      );
    });
  }

  return new Promise((resolve, reject) => {
    conn
      .sobject(LOOM_MODEL)
      .upsert(
        data,
        SHARED_LINK_ID_AND_EMAIL,
        upsertCallback(data, runId, tools, loggerPrefix, true, resolve, reject)
      );
  });
};
```

Here's our entire push function. Let us know what other information we could send over to you that would be useful. We're happy to send you logs to your email if that's helpful.

**Comment by cristiand391** [comment]
@paulius005 jsforce creates the job, ingest the data and then poll for its state until it's complete, if the job didn't complete in that 25s then you get the polling timeout error.

If you grab the job ID in the PollingTimeout error and search for it in your org (Setup > Environments > Jobs > Bulk Data Load Jobs) do you see it completed? status column should say `JobComplete`, you can also check the start and end time, it just be that 25s is not enough.

FWIW, we had to it to 90000ms (1.5m) in our e2e tests and sometimes they still timeout.

**Comment by paulius005** [comment]
@cristiand391 So check this out: We have these 3 jobs that are stuck forever in `In progress`

![CleanShot 2024-02-02 at 12 11 29@2x](https://github.com/jsforce/jsforce/assets/3084367/0b2442bb-39d8-4635-86bb-ec9fb813fb84)
![CleanShot 2024-02-02 at 12 14 28@2x](https://github.com/jsforce/jsforce/assets/3084367/d1507b83-722b-420e-b4a1-be0d6cc48615)
![CleanShot 2024-02-02 at 12 15 41@2x](https://github.com/jsforce/jsforce/assets/3084367/eef9448b-f30b-428a-b17f-d0a590e77833)
![CleanShot 2024-02-02 at 12 16 19@2x](https://github.com/jsforce/jsforce/assets/3084367/02951d0f-70e0-4686-b2f2-7095c636b4fa)

I've verified the payload that failed on 1/29 is the same in our logs as it is in Salesforce. You can see that the `view result` CSV shows all 4 records as created successfully, but the job has just hung. We see this happen consistently with no clear pattern as to why.

**Comment by cristiand391** [comment]
> We have these 3 jobs that are stuck forever in In progress

@paulius005 that's expected, the job isn't closed

**Comment by paulius005** [comment]
>  so at least one reason you get the pollTimeout is that the Bulk API doesn't return the batch state as Complete in those 25s.

Do you know why this would happen for something as small as 4 records?
