### ISSUE TITLE
How does jsforce handle encryption ?

### ISSUE THREAD

**Issue by eelsweb** [jsforce/jsforce#307]
Starting next year,  salesforce is disabling support for anything lower than TLS 1.1. So I was curious about how jsforce handles encryption?

As its user I don't have to do any sort of config for this. Does jsforce handle this under the hood ? Is it using TLS 1.1 ? Do old versions of jsforce do this as well ? 

Where can I find more info on this ?

**Comment by stomita** [comment]
JSforce uses [request](https://www.npmjs.com/package/request) module in Node.js, and the `request` module uses `https` module of Node.js. The `https` module definitely supports TLS over 1.1. So you don't have to worry about it.

**Comment by eelsweb** [comment]
thanks.. just what i wanted to know
