### ISSUE TITLE
Receiving TypeError: Cannot read property 'limit' of undefined while using `conn.limitInfo.apiUsage.limit` 

### ISSUE THREAD

**Issue by RatanPaul** [jsforce/jsforce#308]
Just followed this link https://jsforce.github.io/document/#api-limit-and-usage 

logged in my dev org and try to execute 

console.log("API Limit: " + conn.limitInfo.apiUsage.limit);
console.log("API Used: " + conn.limitInfo.apiUsage.used);

 but getting error TypeError: Cannot read property 'limit' of undefined 
![apilimiterror](https://cloud.githubusercontent.com/assets/8724580/12064285/925b0964-afe5-11e5-988d-da05eef33299.PNG)

**Comment by stomita** [comment]
You should request some api call first. The `limitInfo` object is just for keeping the response header information in API call.
