### ISSUE TITLE
ERROR_HTTP_413: Error: Request Entity Too Large: head

### ISSUE THREAD

**Issue by arupsarkar** [jsforce/jsforce#311]
We are getting this error in few orgs, the version of jsforce lib used is 1.4.1

The rest resource request we are trying to make is the following.

GET /services/data/v32.0/sobjects/rC_Giving__Batch__c/a2e37000000Dzy6AAC 200 146.021 ms - 1577
GET /services/data/v32.0/sobjects/Attachment/find/1?ContentType=application%2Fjson&ParentId=a2e37000000Dzy6AAC 200 364.071 ms - 829
GET /services/data/v32.0/sobjects/Attachment/00P37000001C18VEAS/blob/Body 200 90.772 ms - 393

soon after we are getting the below error

Error:
[ERROR] errors ERROR_HTTP_413: Error: Request Entity Too Large: head
[ERROR] errors print stack ERROR_HTTP_413: Error: Request Entity Too Large: head
    at HttpApi.getError (/Users/ASarkar/Workspace/rc_batchentry/node_modules/jsforce/lib/http-api.js:240:13)
    at /Users/ASarkar/Workspace/rc_batchentry/node_modules/jsforce/lib/http-api.js:85:22
    at /Users/ASarkar/Workspace/rc_batchentry/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/Users/ASarkar/Workspace/rc_batchentry/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:355:11)
[ERROR] req.cookies.SF_ACCESS_TOKEN 00D37000000PmKB!AQQAQHiP_pRHuwE78pmP2oLFwWWrCFVu5Ir6JPnWHYIpVfrqXhIGgKksY0q6yspWdlqKvsIUOoiYi.VtwJLPA0lH_og2EpFp
[ERROR] req.cookies.SF_INSTANCE_URL https://na31.salesforce.com

**Comment by stomita** [comment]
Is there any code which produce this error ?

**Comment by arupsarkar** [comment]
Background : This is a node.js + express + angular app hosted on heroku with backend supported by salesforce, all communication happens via REST API interface between our heroku app and salesforce, authentication is implemented via oauth using jsforce library. We are seeing the following error when trying to access an attachment from salesforce,

[code.zip](https://github.com/jsforce/jsforce/files/90527/code.zip)

I have zipped few js files please take a look at the web.js first which is the starting point of the app, auth.js is where redirection happens for for user authentication, app.remoting.js takes care of all routing. Please feel free to update to ask me anytime for any queries you might have.

**Comment by stomita** [comment]
In REST API "Request Entity Too Large" error typically happens when the SOQL statement becomes too long. Your code seems fetching all fields defined including relationship so it may generate considerably long statement which the platform cannot handle.
