### ISSUE TITLE
"where" clause JSON syntax?

### ISSUE THREAD

**Issue by smhdfdl** [jsforce/jsforce#325]
query.js says for "where" takes "... JSON  (MongoDB-like), or raw SOQL WHERE clause string." Where is the precise definition of the syntax for the Mongo-DB like JSON ?

**Comment by smhdfdl** [comment]
Any plans to support loopback where syntax?
https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Whereclauseforqueries

**Comment by stomita** [comment]
MongoDB query syntax is in [mongodb page](https://docs.mongodb.org/manual/tutorial/query-documents/).

The precise one which JSforce supports is shown in `test` folder. See `test/soql-builder.test.js` which has examples how the query definition JSON is converted to SOQL.

**Comment by smhdfdl** [comment]
Thanks Tomita-san. Any plans to support loopback where syntax?
https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Whereclauseforqueries
