### ISSUE TITLE
"possible EventEmitter memory leak detected" still occurring after upgrading to 1.5.1

### ISSUE THREAD

**Issue by jasonrhodes** [jsforce/jsforce#356]
We are still seeing the memory leak logs mentioned in #247 after upgrading to v1.5.1. They are pretty frequent whenever we are actively using jsforce methods, and usually look something like this:

```
(node) warning: possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at Tooling.initialize (/opt/project/node_modules/jsforce/lib/api/tooling.js:63:36)
    at Connection.initialize (/opt/project/node_modules/jsforce/lib/connection.js:229:18)
    at /opt/project/node_modules/jsforce/lib/connection.js:1073:10
    at /opt/project/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/opt/project/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

This is running on node v4.3.0, and manifested after upgrading from node v0.10... it was also happening in node v0.12 which is why we were aware of it and had upgraded to jsforce@1.5.1, but we still have the error in our logs pretty frequently.

**Comment by stomita** [comment]
Need more information, especially the code which generate the warning.

**Comment by sandromartis** [comment]
I have the same issue. Still occurs in v1.6.0.

```
(node) warning: possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit. 
Trace 
      at addListener (events.js:239:17) 
      at Tooling.initialize (/app/node_modules/jsforce/lib/api/tooling.js:64:36) 
      at Connection.initialize (/app/node_modules/jsforce/lib/connection.js:210:18) 
      at /app/node_modules/jsforce/lib/connection.js:1054:10 
      at tryCallOne (/app/node_modules/jsforce/node_modules/promise/lib/core.js:37:12) 
      at /app/node_modules/jsforce/node_modules/promise/lib/core.js:123:15 
      at flush (/app/node_modules/jsforce/node_modules/promise/node_modules/asap/raw.js:50:29) 
      at doNTCallback0 (node.js:407:9) 
      at process._tickDomainCallback (node.js:377:13) 
      at process.wrappedFunction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:271:51) 
````

Unfortunately I cannot tell exactly which part of the code is generating this, since I don't see that in my logs. I will try to add more logs to narrow this done.

Before every Salesforce API call I do salesforce login:

```
salesforce.login(salesforce_username, salesforce_password + salesforce_token, function(err, userInfo) {
    if (err) {
        logger.error(err);
        return callback(new Error('Could not connect to Salesforce.'));
    }
});
```

Could this be the problem?

**Comment by sandromartis** [comment]
Hey

So I tried to narrow this down and it seems that the EventEmitter warnings are popping up when I'm doing a lot of salesforce API calls in a short period.
It also seems that the warnings show up whenever I do `salesforce.login`.

As stated in my previous comment I'm doing a `salesforce.login` call before every other API call to make sure that I'm still logged in. Is this a bad idea? Could this be causing the EventEmitter leaks?

Is there a better way to handle the login to salesforce?

Thanks,
Sandro

**Comment by justinbeals** [comment]
Jason,

We are seeing a similar issue.  I'm not sure if you found a resolution.  Here is a sample of our logs:

(node) warning: possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at Tooling.initialize (/home/ec2-user/website_wp/node_modules/jsforce/lib/api/tooling.js:63:36)
    at Connection.initialize (/home/ec2-user/website_wp/node_modules/jsforce/lib/connection.js:229:18)
    at /home/ec2-user/website_wp/node_modules/jsforce/lib/connection.js:1073:10
    at /home/ec2-user/website_wp/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/home/ec2-user/website_wp/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:355:11)


This app is built to take api requests from a website and submit them to saleforce.  At times we can have a high volume of api requests.

Thanks,
Justin

**Comment by vinodr** [comment]
I am seeing this issue too. I am not making a lot of API calls but I do have two jsforce connections and seeing this error on the first API call after logging in.

**Comment by JamesGally** [comment]
I was having this issue also, here is what i did to fix:

I had a salesforce.js:

```
var sf = require('jsforce');

var conn = new sf.Connection({
  oauth2 : {
    loginUrl : XXXX,
    clientId : XXXXX,
    clientSecret : XXXXX
  }
});

var sf_create = function(objectName,data,cb){
  conn.login(username, password + security_token, function(err) {
    conn.sobject(objectName).create(data,function(err, records) {
      //check for err here       

     //success stuff here
    });   
  });
};

var sf_query = function(objectName,data,cb){
  conn.login(username, password + security_token, function(err) {

    //do query stuff 

  });
};
```

I moved the connection creation inside my methods....

```
var sf = require('jsforce');

var sf_create = function(objectName,data,cb){

  var conn = new sf.Connection({
    oauth2 : {
       loginUrl : XXXX,
       clientId : XXXXX,
       clientSecret : XXXXX
     }
   });

  conn.login(username, password + security_token, function(err) {
    conn.sobject(objectName).create(data,function(err, records) {
      //check for err here       

     //success stuff here
    });   
  });
};

var sf_query = function(objectName,data,cb){
  
    var conn = new sf.Connection({
    oauth2 : {
       loginUrl : XXXX,
       clientId : XXXXX,
       clientSecret : XXXXX
     }
   });

  conn.login(username, password + security_token, function(err) {

    //do query stuff 

  });
};
```

**Comment by jasonrhodes** [comment]
@stomita so here's what I can figure out. We have an authenticate method in our code that does the `conn.login()` call. It looks like this:
```javascript
salesforce.authenticate = function() {
  // logging in with a valid session will return the current session id, so it is safe to reauthenticate on each request
  return conn.login(salesforceConfig.auth.username, salesforceConfig.auth.password)
    .catch((err) => {
      log.emerg('Cannot establish SalesForce session: ' + err.toString());
      throw err;
    });
};
```
As you can see from the comment there, we assumed when we wrote this that logging in for any request would be fine—and it did work fine in node v0.10.x—but since v0.12 and now in v4.x, it seems like it's not so fine. I can simply call this method a bunch of times in a row and trigger the error:
```
$ node
> var sf = require('./lib/wrappers/salesforce')
undefined
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> sf.authenticate().catch(console.log)
Promise { then: [Function], stream: [Function] }
> (node) warning: possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at Tooling.initialize (/Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/lib/api/tooling.js:63:36)
    at Connection.initialize (/Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/lib/connection.js:229:18)
    at /Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/lib/connection.js:1073:10
    at /Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
(node) warning: possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at Connection.initialize (/Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/lib/connection.js:221:36)
    at /Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/lib/connection.js:1073:10
    at /Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/node_modules/promise/lib/core.js:33:15
    at flush (/Users/jrhodes/src/projects/accounts-api/api/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

somewhere around the 10th call. What I've done to stop the error just now, in my local code, is add some state management:
```javascript
let isConnected = false;

// other code...

salesforce.authenticate = function() {
  if (isConnected) { return q(); }

  return conn.login(salesforceConfig.auth.username, salesforceConfig.auth.password)
    .then(function(connectionDetails) {
      isConnected = connectionDetails;
    })
    .catch((err) => {
      log.emerg('Cannot establish SalesForce session: ' + err.toString());
      throw err;
    });
};
```

Having added that, calling authenticate as many times as I want has no memory leak problem at all, as I guess you would expect since it's the call to `conn.login` that sets the listener and causes the overload.

What I want to know is:
1. What kind of bad things can happen by having this one long-running connection instead of a new login call per request?
1. Is there a better way of managing that connection state, instead of manually keeping track of that `isConnected` toggle?

Thanks!

**Comment by sandromartis** [comment]
I also noticed that the warnings usually pop up when a lot of conn.login() calls are made in a short period.
Are you guys calling conn.logout() after your done with your salesforce updates?

Would this solve the issue? I don't really understand the code in the logout() method, but I saw that it does some cleanup:
```
// Destroy the session bound to this connection
self.accessToken = null;
self.userInfo = null;
self.refreshToken = null;
self.instanceUrl = null;
self.cache.clear();
```

**Comment by stomita** [comment]
The practice of calling `Connection#login()` in parallel in the same connection instance is not the way assumed.
Please create connection instance for each login request, or if you really want to share the instance, don't call it twice. It will leads to the security risk if shared in the different account.

**Comment by jasonrhodes** [comment]
@stomita I'm not sure I know what you mean here:
>It will leads to the security risk if shared in the different accounts.

And just to be clear, you're suggesting doing this for every request, before calling login:
```javascript
let conn = new jsforce.Connection({ /* options */ });
conn.login();
// etc
```
is that correct?

**Comment by stomita** [comment]
@jasonrhodes I mean connection should be for one instance per session. Login call could not be shared in multiple login request which might (or might not be) by different entities.

**Comment by jasonrhodes** [comment]
@stomita ah, yes this is all happening within _one file_, to be honest, so security isn't a concern in the way you're describing. The biggest problem, I think, is that the creation of a new connection object and the act of logging in are separated in the first place, which encourages the pattern of just logging in on every necessary request to ensure you've logged in. If there was a way to check if the connection object is already logged in (a way besides manually managing some kind of outside state like I do in my above example), it'd be a huge help to me and to everyone else in this thread, no doubt.

Otherwise, if I understand what you're suggesting correct, if we have a series of say 1000 query requests to make, we'd need to make 1000 distinct `Connection` objects and then log in with each of them.

Thanks for your help.

**Comment by stomita** [comment]
@jasonrhodes The easiest way to ensure the `login()` call to be run once per session is to use Promise.
```javascript
var conn = new jsforce.Connection();
var loggedIn;

function querySomething(cb) {
  loggedIn = loggedIn || conn.login(usename, password);
  loggedIn.then(function() {
    conn.query('SELECT ...', cb);
  });
}
```

**Comment by Krisa** [comment]
@stomita How can we destroy/delete a connection once we don't need it anymore? I'm leveraging the ability to use the refresh event `connection.on('refresh', fn)` which registers a listener. I'm also having multiple connections hence my need to remove a connection once it's not needed anymore.

**Comment by jasonrhodes** [comment]
**Update**: we pushed code to make sure we only log in once per connection, now I don't get the error when I try to authenticate multiple times. However, the same error is happening in our code anyway, so this did not solve the issue for us. Seems like for us, we're back to square one.

**Comment by stomita** [comment]
I'm not sure what all of you are trying. Our recommendation is to simply create a connection per request. If you have to share the session, you can block the login call and execute query after getting the access token. As far as I understand it doesn't lead to any event emitter leak. The destroying session is not what I concern.

**Comment by stomita** [comment]
When you have a case of event emitter leak even if you are not sharing connection instance, please file it.

**Comment by czerwinskilukasz1** [comment]
Hello, the issue problem still persists. I run into it when I re-login every hour to maintain an active connection with Salesforce before session id expires. After ~10 relogins 2 warnings show up.
Please find stack traces (`node --trace-warnings`).

Stack trace 1:
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at CacheEntry.addListener (events.js:297:10)
    at Tooling.initialize (/home/nodejs/enegive-ocpp-dev/node_modules/node-salesforce/lib/tooling.js:62:36)
    at module.exports.Connection.initialize (/home/nodejs/enegive-ocpp-dev/node_modules/node-salesforce/lib/connection.js:174:16)
    at /home/nodejs/enegive-ocpp-dev/node_modules/node-salesforce/lib/connection.js:851:10
    at _fulfilled (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:760:13)
    at /home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:574:44
    at flush (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

Stack trace 2:
`(node:19516) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:280:19)
    at CacheEntry.addListener (events.js:297:10)
    at module.exports.Connection.initialize (/home/nodejs/enegive-ocpp-dev/node_modules/node-salesforce/lib/connection.js:167:36)
    at /home/nodejs/enegive-ocpp-dev/node_modules/node-salesforce/lib/connection.js:851:10
    at _fulfilled (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:760:13)
    at /home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:574:44
    at flush (/home/nodejs/enegive-ocpp-dev/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

So the issue in both cases is re-adding a listener on 'value' event for 'describeGlobal' key in Cache (jsforce/lib/cache.js). Clearing the cache does NOT remove the listeners because the CacheEntry objects are NOT removed, just their values are deinitialized (`delete this._value`).
The solution proposed here is to remove the previous 'value' event listener just before declaring a new one.
Please check my pull request: https://github.com/jsforce/jsforce/pull/792

**Comment by cristiand391** [comment]
triaging old issues...

Has anyone been able to reproduce this lately? I don't remember seeing this error surface in the last ~3 years in the Salesforce CLI (we've been using jsforce >= v3 for most of that time).

I'll leave this open for a bit in case some can repro on jsforce v3.

**Comment by terrynguyen255** [comment]
Hi @cristiand391 ,
The issue still happens in v3.6.6
If a connection method (e.g connection.metadata.create(...)) fails, the connection instance will abandon its event handles.
Sorry, I don't have time to investigate deeper. This is all I have ATM.
