### ISSUE TITLE
How to get the right credentials for a System's Integration

### ISSUE THREAD

**Issue by franky-continu** [jsforce/jsforce#358]
Hey guys, I've been going over Salesforce documentation for about two weeks while trying to build a prototype for our own Salesforce instance but with intent to provide a service to our customers.

We want to UPSERT (Update or Insert if not present) Salesforce users into our platform. 

I have a node cron job (every 1 minute just for testing purposes) to query all users. 

``` javascript
var cronJob = cron.job("0 */1 * * * *", function() {
    log.info('Scheduled Job ' + name + ' called');
    if (!process.env.SF_USERNAME || !process.env.SF_PASSWORD || !process.env.SF_SECRET_KEY) {
      log.warn('Scheduled Job ' + name + ' is missing environment configuration. This Job WILL NOT BE SCHEDULED');
      return;
    }

    var conn = new jsforce.Connection({
      // you can change loginUrl to connect to sandbox or prerelease env.
      //loginUrl : 'https://test.salesforce.com'
    });
    conn.login(process.env.SF_USERNAME, process.env.SF_PASSWORD + process.env.SF_SECRET_KEY, function(error, userInfo) {
      if (error) {
        return log.error('Error connecting to SF', error);
      }
      // log some info
      log.info(conn.accessToken);
      log.info(conn.instanceUrl);
      // logged in user property
      log.info('User ID: ' + userInfo.id);
      log.info('Org ID: ' + userInfo.organizationId);
      // query users

      conn.query('SELECT User.Id, User.AccountId, User.Name, User.LastName, User.Email, User.CompanyName, User.Department, User.Country, User.LanguageLocaleKey, User.UserRoleId from User', function(error, response) {
        if (error) {
          return log.error('Error executing query.', error);
        }
        log.info(response);
      });
    });

  });
  cronJob.start();
```

I can only get myself and a chatter test user. So I started a Connected App. But I'm not sure I'm in the right place still.

I would love to have something like Slack in which I create an Application that my client installs and then I can have access to their users. 

But if not that, how can I do this? can I get some pointers? 

The idea is a background system process (cron) getting the users every once in awhile, I like this idea the most but I'm open to any other.

Thanks in advance.

**Comment by ra-ryan** [comment]
Does the Salesforce user that you are logging in with have access to all users? I ran your query with an admin user and it worked as expected - returned all users in the system. It seems like your query results are being limited by permissions.

**Comment by franky-continu** [comment]
Yeah, I get the same. 
I can only get myself and a chatter test user when login in with my credentials of course. So I started a Connected App. But I'm not sure I'm in the right place with that.

I need a set of credentials (Maybe like a Slack Application) that my customers using SF can install and I can have access to their data.

Or eventually, would I have to create a user (with cost associated) to do this?

The idea is a background system process (cron) getting the users every once in awhile, I like this idea the most but I'm open to any other.

Do I need to have a user connecting through the API, I would need to ask my clients to create a user for my api, I would imagine that will generate a cost for them.

Is this the only way? I hope I'm making myself clear because I've been going at it for a week and I'm a bit dizzy already.

**Comment by franky-continu** [comment]
Guys Any Help Here?

**Comment by ra-ryan** [comment]
If you want to query for users then you'll need an account that has permission to do that, so either a new account created in the org that can do that or you could use an existing admin account if the client will give you access to that.

There are other options as well, such as setting up a workflow with outbound messaging to send updates to your server whenever a user record is created or updated. Your question isn't really specific to the JSForce library though, so I think this issue can be closed and you might have better luck asking on the Salesforce forums or Salesforce Stack Exchange.

**Comment by franky-continu** [comment]
> If you want to query for users then you'll need an account that has permission to do that, so either a new account created in the org that can do that

YES, I KNOW. I'm trying or asking HOW NOT TU ADD A NEW USER/ACCOUNT which will incur in expenses for our customers. As in a new SF user/account/license = new $$$$$

Is that correct? It is specific to the login method and arguments that need to be provided, maybe a more extensive documentation or examples for the different logins? (APEX, REST, OAuth, etc)
