### ISSUE TITLE
[Error: socket hang up] code: 'ECONNRESET' when running tests asynchronously

### ISSUE THREAD

**Issue by TheWallOfDucks** [jsforce/jsforce#376]
I am pretty consistently getting an error: [Error: socket hang up] code: 'ECONNRESET' when I try to queue apex classes. I would say this happens about 75% of the time I try to do this. Any thoughts on how this can be resolved? I am not running my script behind a proxy as suggested in other solutions. Here is an example of the piece of code that is causing me problems...basically I get a list of all the class IDs I need and then split them into chunks to be run asynchronously.

					chunk = testClassId.slice(counter, chunkSize);

						conn.tooling.runTestsAsynchronous(chunk, function(err, results){
							if (err) { 
								return console.error(err); 
							}

							testResultId = results;
							console.log(testResultId);

						});

**Comment by johnbiundo** [comment]
@TheWallOfDucks Were you able to solve this problem?  If so, could you explain how please?
