### ISSUE TITLE
& in field labels are not encoded to &amp; -  causes metadata requests to fail

### ISSUE THREAD

**Issue by rsievekndy** [jsforce/jsforce#377]
While attempting to create or edit layouts with field labels containing '&', the request fails yielding the error message:

The entity name must immediately follow the '&' in the entity reference.

As a workaround, I can manually encode these prior to sending the request, but this could be done (crudely) as part of the convert function in the various CRUD requests like:

var convert = function(md) {
    var tmpMeta = JSON.stringify(metadata);
    tmpMeta.replace(/&(?!amp;)/g, '&amp;');
    metadata = JSON.parse(tmpMeta);
    md["@xsi:type"] = type;
    return md;
  };

**Comment by stomita** [comment]
Could not find the case to reproduce.
