### ISSUE TITLE
Expose onTick/Poll event

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#379]
Often, for bulk queries, a long time is spent polling for a download to be ready from Salesforce. In many applications, especially those controlled by a parent process, it's necessary to emit events on each poll / tick or every so often to make sure that the child application is staying active. Additionally, a user of this module may want to record each time they poll Salesforce to track API usage and whatnot.

Is there any way I can run a function onTick/onPoll? If not, is this something that you'd think about adding? I'm open to sending PRs, any tips / pointers in the right direction would be great.

**Comment by stomita** [comment]
The Batch instance emits `progress` event when polling.

```javascript
var batch = conn.bulk.load('Account', 'insert', input);
batch.on('progress', function(res) {
  console.log(res);
});
```

**Comment by tejasmanohar** [comment]
Awesome!
