### ISSUE TITLE
Identify compound fields

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#380]
```
{"message":"InvalidBatch : Failed to process query: FUNCTIONALITY_NOT_ENABLED: Selecting compound data not supported in Bulk Query","name":"Error","stack":"Error: InvalidBatch : Failed to process query: FUNCTIONALITY_NOT_ENABLED: Selecting compound data not supported in Bulk Query\n    at /.../node_modules/jsforce/lib/api/bulk.js:579:32
```

I get this error when performing bulk queries on some Salesforce accounts. Is it possible to programmatically determine what fields are "compound" so that I can filter them out from the queries my application dynamically generates? I could not see this information in the output of `describe()` calls.

**Comment by hporter** [comment]
I just spent an hour on the same problem - it's an unfortunate aspect of Salesforce's Bulk API!

I've resorted to the hack of building a custom query based on describe() and filtering out where field type: address or field name suggests it's a geolocation field. Would love some sort of flag - this module is so useful.

I'll raise with Salesforce next time we meet. Worth a try!

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_using_bulk_query.htm

> Bulk API query doesn’t support the following SOQL:
COUNT
ROLLUP
SUM
GROUP BY CUBE
OFFSET
Nested SOQL queries
Relationship fields
Additionally, Bulk API can’t access or query compound address or compound geolocation fields.

**Comment by tejasmanohar** [comment]
That's unfortunate that there's no `type: compound` identifier in Salesforce's Bulk API.

>I've resorted to the hack of building a custom query based on describe() and filtering out where field type: address **or field name suggests it's a geolocation field**.

@hporter I'm doing similar. Would you mind sharing the identifiers you used for the bolded part ^? That would be an exceptional resource for others facing this issue, and I'd really appreciate it personally. I've also been filtering out fields w/ type `address` but am facing an error on a field not of this type and am yet to identify it (if not, I'll likely do a binary search over the col set we're querying, splitting the batch until I find the col(s) that are causing this error).

**Comment by tejasmanohar** [comment]
@stomita Personally, I think this should also be tagged with enhancement. Detection of compound fields would be a great library addition even if it was partial guesswork / based on assumptions.

ping @hporter on how this works--
> or field name suggests it's a geolocation field

**Comment by stomita** [comment]
@tejasmanohar My suggestion for this is to query the fields to filter the desired before querying.

```javascript
conn.sobject('Account').describe(function(ret) {
  var fields = ret.fields.filter(function(f) {
     return f.type !== 'address'; // filter any fields you don't want to include in query.
  }).map(function(f) {
     return f.name;
  });
  var soql = 'SELECT ' + fields.join(', ') + ' FROM Account';
  return conn.bulk.query(soql);
})
```

I'm not sure this is really the matter which we should take care of in JSforce because it can have a simple wrapper like above.

**Comment by tejasmanohar** [comment]
Hey @stomita! Already doing that filter but still getting this error for some customers. Maybe there are other fields that aren't type 'address' that are compound and need to be excluded. As the list needs to be expanded, I think it would be ideal that we maintain a running one in JSForce.

**Comment by stomita** [comment]
@tejasmanohar If you want to filter it out the geolocation field type you can do

```javascript
  var fields = ret.fields.filter(function(f) {
     return f.type !== 'address' && f.type !== 'location';
  }).map(function(f) {
    ...
```

The list of compound field data type is written in [the guide](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/compound_fields.htm). If there were any other compound field types we can't do handle them anyway.

**Comment by tejasmanohar** [comment]
Ah got it. The rest must be custom fields.
