### ISSUE TITLE
Raw response objects?

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#384]
How would I get the raw response object from a JSForce call?

``` js
const sf = new jsforce.Connection();
sf.login(username, password).then(function(res) {
 // ...
}); // api call
```

For example, what if I want to know the `statusCode` of the response of this API call?

**Comment by tejasmanohar** [comment]
PS: Updated title because in Node `http` lib, a `response` object's `request` key points to the `request` object to get things like `pathname` so exposing both is not a concern for the user of this library.

**Comment by stomita** [comment]
The raw response from the server is handled in `http-api.js`. There's no hook of raw response in JSforce connection instance right now.

**Comment by tejasmanohar** [comment]
@stomita Is this a hook you'd be interested in? I'm willing to send a PR. It looks like there is an event emitter containing the HTTP response in the payload [here](https://github.com/jsforce/jsforce/blob/master/lib/http-api.js#L87), but it's on a private object. In terms of usage, what do you think about having each JSForce call that makes an HTTP request expose a `response` event that you can listen on.

```js
const sf = new jsforce.Connection();
const sf.login(username, password).on('response', function(res) {
  // ...
});
```

Or, would you prefer attaching a `rawResponse` key to each object returned by a function that makes an API call? This key would point to a Node HTTP response object.

**Comment by stomita** [comment]
@tejasmanohar Yes, actually HttpApi is an event emitter so you can listen the `response` event for obtaining raw returned response. However the promise object returned from the call is not an event emitter and cannot access to it.

**Comment by tejasmanohar** [comment]
@stomita Right. I understand that. I was asking more from the sense of if I were to send a PR exposing the raw response objects, is there a particular method you'd prefer? I think attaching a `rawResponse` key to the object each function that makes an HTTP call on the JSForce connection returns is the least destructive way of accomplishing this. Thoughts?

**Comment by cristiand391** [comment]
triaging old issues..

closing this in favor of https://github.com/jsforce/jsforce/discussions/1477
