### ISSUE TITLE
Jsforce local app can not login

### ISSUE THREAD

**Issue by bruceyue** [jsforce/jsforce#389]
I create a cordova app in local computer run in http://localhost:8000/index.html
I use jsforce.Connection oauth2  username password flow to login to salesforce, but show the error 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.salesforce.com//services/oauth2/token. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by stomita** [comment]
You need to use [jsforce-ajax-proxy](https://github.com/jsforce/jsforce-ajax-proxy) to connect to Salesforce API within browser app.

**Comment by bruceyue** [comment]
I used proxy and can login. But when call a query, can not work, show the error below

**Comment by stomita** [comment]
It seems you are not correctly setting `proxyUrl` in connection options. By the way, why are you using OAuth2 username/password flow in browser app ? It is insecure because it exposes client secret to public. In browser app, use implicit flow instead.

**Comment by bruceyue** [comment]
Actually I'm building a custom mobile app using html5 and Cordova. So I want to use a custom login page.

Here is my config  

   var conn = new jsforce.Connection({
    oauth2 : {
        // you can change loginUrl to connect to sandbox or prerelease env.
        // loginUrl : 'https://test.salesforce.com',
        loginUrl: 'https://login.salesforce.com/',
        clientId : '..............',
        clientSecret : '.................',
        redirectUri : '.........',
        proxyUrl: 'https://node-salesforce-proxy.herokuapp.com/proxy/'
    }
});

**Comment by stomita** [comment]
The `proxyUrl` is the option passed to Connection instance, not oauth2 property.

**Comment by bruceyue** [comment]
so how should I do? If I remove it, can not login.

**Comment by stomita** [comment]
See http://jsforce.github.io/jsforce/doc/Connection.html#Connection

**Comment by bruceyue** [comment]
it's useless and also I tried all the demos ways from jsforce site, both can not work.

**Comment by bruceyue** [comment]
Can you give me an example?

**Comment by oleghnidets** [comment]
_To Whom It May Concern_

@stomita meant 

```
var conn = new jsforce.Connection({
     oauth2 : {
         loginUrl: 'https://login.salesforce.com/',
         clientId : '..............',
         clientSecret : '.................',
         redirectUri : '.........',
     },
     // MARK: This line should be outside oauth2 
     proxyUrl: 'https://node-salesforce-proxy.herokuapp.com/proxy/'
});
```

Looks like it works with React Native 0.59.8.

**Comment by shuzootani** [comment]
@stomita @oleghnidets I'd really appreciate it if you could share any guideline to integrate jsforce into react native app 🙏

**Comment by oleghnidets** [comment]
@shuzootani You can install it as a usual module. 

`npm install jsforce`

Then create your connection (multiple ways exist):

```
export const connection = new jsforce.Connection({
    loginUrl: "https://test.salesforce.com",
    proxyUrl: "https://node-salesforce-proxy.herokuapp.com/proxy",
    instanceUrl: "// Your instance URL",
    accessToken: "// Access token",
});
```

Check out [documentation](https://jsforce.github.io/document/).

**Comment by shuzootani** [comment]
@stomita 
is there any way by calling REST API or jsforce method to get community members to login themselves in custom browser js app such as spa?
