### ISSUE TITLE
Feature request: Re-cache fields / schema after INVALID_FIELD error

### ISSUE THREAD

**Issue by walling** [jsforce/jsforce#391]
After deleting a field in Salesforce we usually have to restart the application to ensure that the fields are re-cached. It could be nice if jsforce handled this by itself, when it noticed this error. Example error output:

```
INVALID_FIELD:
field1__c, field2__c, deleted_field__c, field3__c
                      ^
                      ERROR at Row:1:Column:42
No such column 'deleted_field__c' on entity 'Example__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

This usually means that we are doing a query using jsforce and it inserts all the field names by itself in the query (when we want the query to return all available fields). However the cache of field names is outdated after the field deletion in Salesforce. It should be purged and reloaded.

**Comment by stomita** [comment]
Are you using `SObject#find()` call without specifying retrieving fields explicitly ? If so, the retrieving fields are automatically retrieved by calling `SObject#describe$()`, which is the cached version of `SObject#describe()`.

The `SObject#describe$()` only fetches the SObject's schema information from server when there is no cache stored in the connection, and then stores the fetched result to the cache. On the other hand, the `SObject#describe()` will always fetch the schema info from server, but it also stores the result to the cache.

So by calling `SObject#describe()` will explicitly update the latest schema information in JSforce connection.

**Comment by walling** [comment]
Ok, I'm not going to re-open the issue, because you made the decision. I just wanted to ask about the approach you suggest:

1. Make a generic function for invoking `SObject#find()`
2. If it returns INVALID_FIELD error, it will invoke `SObject#describe()` and try again once

Anyway, I will try this and see if it improves our process, when changing schemas.

**Comment by yunyu** [comment]
We experienced a breakage today when a customer changed fields we weren't accessing, triggering INVALID_FIELD errors across the board. This was extremely unexpected, and invalidating the cache on this would have fixed it. Just another data point
