### ISSUE TITLE
OAuth 2.0 JWT Bearer Token Flow

### ISSUE THREAD

**Issue by sawuapara** [jsforce/jsforce#393]
Thanks so much for your hard work on jsforce. Do you have any plans to implement [JWT Bearer Token Flow](https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm)?

Thank you!

**Comment by idanblich** [comment]
Hi , 
You can use this package :
https://www.npmjs.com/package/salesforce-jwt

**Comment by sawuapara** [comment]
Thanks @idanblich . I saw [salesforce-jwt](https://github.com/leandrob/node-salesforce-jwt) but it hardcodes the endpoint to https:/login.salesforce.com so we can login to sandboxes that require https://test.salesforce.com.

**Comment by idanblich** [comment]
Change the code, make it Env parameter , and fire PR

**Comment by stomita** [comment]
@sawuapara As an author, as far as there are any alternative ways to work, I recommend to use it. I'm not sure it would be included as a JSforce feature in future but understand the requirement. You can make pull request for it, of course.
