### ISSUE TITLE
Refresh an OAuth token

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#398]
[ref](https://jsforce.github.io/document/#access-token-with-refresh-token)

Is there a way to force / invoke a token refresh? The Salesforce API doesn't seem to only require refresh token (and not access token) to get a new access token so I'd rather work without one and just refresh before my system starts.

**Comment by stomita** [comment]
You can use `OAuth2#refreshToken()` method directly. 

```js
var oauth2 = new jsforce.OAuth2({
  clientId: '<oauth2 client id is here',
  clientSecret: '<oauth2 client secret is here>',
  redirectUri: '<oauth2 redirect uri is here>'
});
oauth2.refreshToken(refreshToken).then(function(ret) {
  var conn = new jsforce.Connection({
     accessToken: ret.access_token,
     instanceUrl: ret.instance_url
  });
  // ...
});

```
See http://jsforce.github.io/jsforce/doc/OAuth2.html#refreshToken
