### ISSUE TITLE
Error in script - [Error: NOT_FOUND: The requested resource does not exist]

### ISSUE THREAD

**Issue by TonyWhiteSMS** [jsforce/jsforce#405]
Hello I am trying to use the tooling api to pull down the test coverage to a CSV so we can track this.  Attached is how far I have gotten with the script so far.  I am finding that I am getting an error of
[Error: NOT_FOUND: The requested resource does not exist]
when it reaches the line:
sfdc_client.tooling.sobject('ApexClass').find({NamespacePrefix:'',Status:'Active'},{Id:1,Name:1,Body:1})

This line works perfectly fine when I run it via jsforce command line.

I am running the attached script via command line using node getTestResults.js
[getTestResults.txt](https://github.com/jsforce/jsforce/files/205938/getTestResults.txt)

Not sure why it works in the command line tool but not via the script, have I missed something or is this a bug?

Note I have borrowed the basis of this script from http://blog.deadlypenguin.com/blog/2015/08/23/coveralls-code-coverage-for-salesforce/

Thanks
Tony

**Comment by stomita** [comment]
@TonyWhiteSMS You need to set version in string, not float number.

```javascript
var sfdc_client = new jsforce.Connection({loginUrl : process.env.SFDC_URL, version: '36.0'});
```

**Comment by TonyWhiteSMS** [comment]
@stomita ah ha, that has resolved the issue!  Thought I had tried it without the version as well but perhaps not.  So it is working getting further along.

Thank you very much.

**Comment by devorbitus** [comment]
I just want to say I had this same issue and this post helped me. I needed to put `version: '49.0'` and I incorrectly had `version: '49'`
