### ISSUE TITLE
startDate before org replication enabled date

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#406]
https://jsforce.github.io/jsforce/doc/sobject.js.html#line403
^ What are the default start/end dates for this function?

Been getting this error-
```json
{
  "message": "startDate before org replication enabled date",
  "name":"INVALID_REPLICATION_DATE",
  // ...
}
```
Any recommendations on handling it without missing out on deleted docs?

**Comment by stomita** [comment]
@tejasmanohar It seems depending to the org environment and cannot be determined simply which date range is always valid for the org.

**Comment by TonyWhiteSMS** [comment]
Couldn't you use the organization created date to ensure you not querying earlier?

`sobject('Organization').find({},{CreatedDate:1});`

**Comment by tejasmanohar** [comment]
@TonyWhiteSMS yeah that seems reasonable. i'll try it out. // cc @stomita
