### ISSUE TITLE
Bulk Query API - OPERATION_TOO_LARGE

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#412]
I'm facing the error in [this StackExchange post](http://salesforce.stackexchange.com/questions/17862/counting-notes-crashes-with-operation-too-large-exceeded-20000-distinct-ids) error except with a regular `SELECT c,o,l,u,m,n,s,...`, not `COUNT(...)` query. Is the recommended approach here to paginate the data? Do we have examples of that?

In the response on that post, a read-only mode is also mentioned ([ref](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_ReadOnly.htm). Is this applicable? How does it work with the Bulk Query API via JSForce?

**Comment by stomita** [comment]
The ReadOnly mode is for Apex-based query access. JSforce is the wrapper of REST/SOAP API and it has different limits from Apex Governors (for example, there is no 50,000 records count limit in APIs).

I'm not sure the reason of `OPERATION_TOO_LARGE` error but as shown in the post it might be affected by the complicated sharing rules.
