### ISSUE TITLE
Entity isn't supported by the Bulk API but is "queryable"

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#413]
Getting an error back from Salesforce API on passing a read-only query (specifically, `SELECT ${cols} FROM ${collection}`) on  `conn#bulk.load` w/ message `Entity '${collection}' is not supported by the Bulk Query API.`

This is odd to me because `conn.sobject(<object>)#describe` returns

``` js
{ activateable: false,
  createable: false,
  custom: false,
  customSetting: false,
  deletable: false,
  deprecatedAndHidden: false,
  feedEnabled: false,
  keyPrefix: null,
  label: 'Recently Viewed',
  labelPlural: 'Recently Viewed',
  layoutable: false,
  mergeable: false,
  name: '...omitted...',
  queryable: true,
  replicateable: false,
  retrieveable: false,
  searchable: false,
  triggerable: false,
  undeletable: false,
  updateable: true,
  urls:
   { rowTemplate: '/services/data/v36.0/sobjects/...omitted.../{ID}',
     defaultValues: '/services/data/v36.0/sobjects/...omitted.../defaultValues?recordTypeId&fields',
     describe: '/services/data/v36.0/sobjects/...omitted.../describe',
     sobject: '/services/data/v36.0/sobjects/...omitted...' } }
```

for this object, which indicates that it is `queryable`. What's the recommend approach for handling this type of error? Is there something else we can filter by in the `#describe` response / potential causes of this?

**Comment by stomita** [comment]
I'm not sure if there is a metadata property in the description of the object which is supported for bulk query call.

**Comment by tejasmanohar** [comment]
@stomita Could you expand on that? Not quite sure where you're seeing "metadata property in the description of the object"? Thanks!

**Comment by stomita** [comment]
@tejasmanohar The describe() result of the sobject I meant.

**Comment by tejasmanohar** [comment]
@stomita Ah, I see. Same problem here. Haven't been able to find a field that indicates this. `queryable` has worked well with most all objects so far but there seem to be some edge cases like this one. By any chance, do you know if this is something the user can configure or is it 100% on Salesforce?

**Comment by cristiand391** [comment]
triaging old issues...

doesn't seem docs mention if an object supports bulk operations or not yet.
