### ISSUE TITLE
Issue creating nested objects with parent child relationship.

### ISSUE THREAD

**Issue by adesotamn** [jsforce/jsforce#417]
Not having a lot of luck finding documentation how to create a nested object with a parent child relationship.

Example 

conn.sobject("Request__c").create(
    {
        Owned_By__c: 'Me',
        Child_Software_Request: {
            Request_Status___c: 'Open',
         }
    },
    function(err, ret){
       console.log(err,ret);
    }
);

Requesting feature to use the Salesforce Rest Api sObject Tree Resource.

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_composite_sobject_tree_create.htm

**Comment by stomita** [comment]
SObject tree resource is not supported in `SObject#create()` method.
Otherwise you can directly call the REST API endpoint by [Connection#requestPost()](https://jsforce.github.io/jsforce/doc/Connection.html#requestPost)

```js
var body = { records: [ ... ] }; // the content of JSON body
conn.requestPost("/composite/tree/Account/", body, function(err, res) {
  //...
});
```

**Comment by DouglasCAyers** [comment]
Confirmed this works, but in my visualforce page (API 39.0) I had to specify a more qualified URL as `/services/data/v39.0/composite/` otherwise I got error about resource could not be found.

Here is example that posts a file then shares it to a record:

```
var conn = new jsforce.Connection({ ... });
conn.requestPost( '/services/data/v39.0/composite/', {
    'allOrNone' : true,
    'compositeRequest' : [
        {
            'method' : 'POST',
            'url' : '/services/data/v39.0/sobjects/ContentVersion',
            'referenceId' : 'newFile',
            'body' : {
                'Title' : filename,
                'PathOnClient' : filename,
                'VersionData' : base64String
            }
        },
        {
            'method' : 'GET',
            'url' : '/services/data/v39.0/sobjects/ContentVersion/@{newFile.id}',
            'referenceId' : 'file'
        },
        {
            'method' : 'POST',
            'url' : '/services/data/v39.0/sobjects/ContentDocumentLink',
            'referenceId' : 'fileLink',
            'body' : {
                'ContentDocumentId' : '@{file.ContentDocumentId}',
                'LinkedEntityId' : recordId,
                'ShareType' : 'I'
            }
        }
    ]
})
```

**Comment by xeektech** [comment]
Any way to update the existing document? Thanks!
