### ISSUE TITLE
@https://jsforce.github.io/js/main.js line 65 > eval:1:1

### ISSUE THREAD

**Issue by MaurizioBella** [jsforce/jsforce#421]
Folks,

I've clicked on API Limit and Usage
[https://jsforce.github.io/document/#api-limit-and-usage]()
and here the error
```
@https://jsforce.github.io/js/main.js line 65 > eval:1:1
@https://jsforce.github.io/js/main.js:65:23
x.event.dispatch@https://jsforce.github.io/asset/jquery/jquery.min.js:5:14077
x.event.add/v.handle@https://jsforce.github.io/asset/jquery/jquery.min.js:5:10849
```
any insight would be appreciate.

**Comment by stomita** [comment]
Do it after some other API call. the apiLimit object is not available before the API call (it is returned by the response header)
