### ISSUE TITLE
INVALID_TYPE - Organization not supported

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#423]
```json
{ "message":"sObject type 'Organization' is not supported.","name":"INVALID_TYPE","stack":"INVALID_TYPE: sObject type 'Organization' is not supported.\n    at HttpApi.getError (/root/dev/src/github.com/segment-sources/salesforce/node_modules/jsforce/lib/http-api.js:250:13)\n }
```

for

```js
jsForceConnection.sobject('Organization').find({}, { CreatedDate: 1 })
```

Looking [here](https://developer.salesforce.com/forums/?id=906F000000091I5IAI), it seems it is possible to view this data with read-only scopes if you use "without sharing" to query SFDC. Does JSForce support that? Any pointers? Thanks!

**Comment by stomita** [comment]
Usually it can query the Org info from JSforce of course. Please check your profile setting has an object access. The `describeGlobal()` result shows the list of which object the user is accessible.

**Comment by tejasmanohar** [comment]
got it
