### ISSUE TITLE
MALFORMED_QUERY when SOQL query contains a reserved character

### ISSUE THREAD

**Issue by ismriv** [jsforce/jsforce#427]
Sending queries containing reserved characters is causing the query to fail a MALFORMED_QUERY error. 

The query looks something like this:

    conn.search('FIND {email@domain-withdash.com} IN EMAIL FIELDS RETURNING Contact(Id, Name, FirstName, LastName)')

I've tried escaping the email address like `FIND {email@domain\-withdash.com}`, and URL encoding the query, but none of these worked.

I have then 2 questions:

1. How should the query be sent?
2. Should jsforce take care of this transparently?

Cheers!

**Comment by stomita** [comment]
You need to double-escape because `\` is the escape char in JavaScript string.

```js
conn.search('FIND {email@domain\\-withdash.com} IN EMAIL FIELDS RETURNING Contact(Id, Name, FirstName, LastName)')
```

**Comment by ismriv** [comment]
Got it @stomita. Thanks!
