### ISSUE TITLE
Does Bulk Query stream include all batches?

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#428]
Does the Bulk Query `.stream()` include all batches? https://jsforce.github.io/document/#bulk-query

```js
var batch = conn.bulk.load("Account", "insert");
// MULTIPLE BATCHES -> ->
batch.on("response", function(rets) { // fired when batch finished and result retrieved
  for (var i=0; i < rets.length; i++) {
    if (rets[i].success) {
      console.log("#" + (i+1) + " loaded successfully, id = " + rets[i].id);
    } else {
      console.log("#" + (i+1) + " error occurred, message = " + rets[i].errors.join(', '));
    }
  }
);
//
// When input stream becomes available, pipe it to batch stream.
//
// -> -> ARE ALL INCLUDED HERE? -> ->
csvFileIn.pipe(batch.stream());
```

Also, is there a spec on what events `batch.stream()` emits?

**Comment by tejasmanohar** [comment]
Also, if you use this style-
```js
conn.bulk.query("SELECT Id, Name, NumberOfEmployees FROM Account")
  .stream().pipe(fs.createWriteStream('./accounts.csv'));
```

How do you get the `.on('progress')` event to know when each poll request is sent out? The stream returned by `.stream()` doesn't seem to expose this.

**Comment by stomita** [comment]
@tejasmanohar Unfortunately the current bulk query implementation (ver 1.6) doesn't handle multiple batch result (of course it should do).

**Comment by tejasmanohar** [comment]
Hmmm so what happens if multiple results come back in the batch query response? is only the first one used? @stomita

**Comment by tejasmanohar** [comment]
oh snap, that is the case ([ref](https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L803)). that should probably be in the docs given that it has the potential to drop data

**Comment by tejasmanohar** [comment]
In what case are multiple batches returned? They can be returned at any time, right? Not specified by the user?
