### ISSUE TITLE
Trade-offs between Query & Bulk Query API?

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#439]
It looks like you can do the same thing in the Query & Bulk Query API except that the Query API returns smaller batches (?) and doesn't use a CSV streaming approach. Is this correct? Are there other trade-offs to consider like rate limits on the Query API?

**Comment by stomita** [comment]
REST API based query fetches the query result synchronously, on the other hand bulk API query does asynchronously so requires polling. REST API returns at most 2,000 records in one fetch, Bulk API can contain over 10,000 records in result.

**Comment by tejasmanohar** [comment]
Makes sense.

**Comment by tejasmanohar** [comment]
> REST API returns at most 2,000 records in one fetch.

In the example with `maxFetch` [here](https://jsforce.github.io/document/#query), the value is set to `4000`, which is odd if the Query API will only return 2k max. Should that be modified, or am I missing something?

```
var records = [];
var query = conn.query("SELECT Id, Name FROM Account")
  .on("record", function(record) {
    records.push(record);
  })
  .on("end", function() {
    console.log("total in database : " + query.totalSize);
    console.log("total fetched : " + query.totalFetched);
  })
  .on("error", function(err) {
    console.error(err);
  })
  .run({ autoFetch : true, maxFetch : 4000 }); // synonym of Query#execute();
```

**Comment by tejasmanohar** [comment]
I also noticed that maxFetch is defaulted to `1000` in the code. How would one override this when using `Connection#query` but not the event-based approach with `Query#run`?
