### ISSUE TITLE
Example of paginating Query API results using `queryMore`

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#440]
@stomita    Is there an example of paignating query reuslts using `queryMore`? The spec for this function doesn't seem to be noted on the /document page on the jsforce website.

```js
var records = [];
conn.query("SELECT Id, Name FROM Account", function(err, result) {
  if (err) { return console.error(err); }
  console.log("total : " + result.totalSize);
  console.log("fetched : " + result.records.length);
  console.log("done ? : " + result.done);
  if (!result.done) {
    // you can use the locator to fetch next records set.
    // Connection#queryMore()
    console.log("next records URL : " + result.nextRecordsUrl);
  }
});
```

https://jsforce.github.io/document/#using-soql

**Comment by tejasmanohar** [comment]
Also, is the `queryAll` method supported so that you can get all objects whether they have been deleted or not?

**Comment by stomita** [comment]
See http://jsforce.github.io/jsforce/doc/Connection.html#queryMore

**Comment by stomita** [comment]
Sobject#find does do queryMore internally to fetch the result when autoFetch is set to true.

**Comment by tejasmanohar** [comment]
@stomita Gotcha. Is there an `autoFetch` option if you pass a SOQL query to #query rather than #find? Also curious about #439 on similar topic.

**Comment by tejasmanohar** [comment]
@stomita Is the "locator" for #queryMore `result.nextRecordsUrl` from #query?

**Comment by stomita** [comment]
@tejasmanohar No autoFetch in Connection#query because it is low level API wrapper. Use nextRecordsUrl in the response it is locator.

**Comment by tejasmanohar** [comment]
@stomita Gotcha. Makes sense.

**Comment by tejasmanohar** [comment]
@stomita What is `result.nextRecordsUrl` when there are no more results to query? Null? Undefined?

**Comment by therazakhan** [comment]
@tejasmanohar if done field is true it means no more records exist, so thats why result.nextRecordsUrl is null.
