### ISSUE TITLE
Concurrent Bulk API Query Limit

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#451]
Are there concurrent request limits for the Salesforce Bulk API? If so, what are they? If I use JSForce, are they handled / are additional requests queued up? Is it common to see `ECONNRESET` errors on an open connection when the limit is reached.

**Comment by stomita** [comment]
`ECONNRESET` is the error thrown in Node.js socket lib and it shows TCP session is closed by the peer. I'm not sure when they (Salesforce) will do it because no manuals says about it AFAIK, but some protection might be working in the provider's side.
