### ISSUE TITLE
How to use Lodash in REPL 

### ISSUE THREAD

**Issue by idanblich** [jsforce/jsforce#470]
Hi , 

[Using REPL the "_" Variable is use to access the latest evaluated result ](https://jsforce.github.io/blog/posts/20140115-jsforce-repl-tips.html). 
[In Jsforce you use the lodash libery](https://github.com/jsforce/jsforce/blob/master/package.json#L63) . 
My question is how can i use the lodash functionality in the REPL. for me it essay to use lodash instead of writhing the functions by myself. 

Love your work.

**Comment by stomita** [comment]
It is the friction commonly known in Node.js REPL (which JSforce REPL is based on). As `_` is always used in the REPL you can assign the lodash/underscore to the variable other than `_` like :
```js
var l_ = require('lodash');
```
