### ISSUE TITLE
This is not an issue rather this is a clarification

### ISSUE THREAD

**Issue by vivinRajagopalan** [jsforce/jsforce#480]
Hi All,
I would like to know whether i can use JSFORCE to do an authorization to salesforce without passing the username and password fields ? I would like the user to type the username and password fields by themselves.

Thanks in advance.......

**Comment by stomita** [comment]
You can use OAuth2 for authorization. See the [doc](https://jsforce.github.io/document/#oauth2).

**Comment by vivinRajagopalan** [comment]
Hi ,
Thanks for the reply. Could you please help me in the below code what does
sf stands for ?

#code
var jsforce = require('jsforce'); // // OAuth2 client information can be
shared with multiple connections. // var oauth2 = new sf.OAuth2({ // you
can change loginUrl to connect to sandbox or prerelease env.


Thanks in advance

**Comment by vivinRajagopalan** [comment]
Hi Stomita,

After i get the Oauth url from oauth2.getAuthorizationUrl(), when i try to post the code to conn.authorize(code, function(err, userInfo) {} , i always get the below error, is there something that am missing ? 


{ [invalid_grant: authentication failure] name: 'invalid_grant' }

**Comment by cristiand391** [comment]
triaging old issues...

oauth docs: https://jsforce.github.io/document/#oauth2

if anyone have more questions please ask in https://github.com/jsforce/jsforce/discussions/categories/q-a
