### ISSUE TITLE
Deploying static resources via the metadata api very slow

### ISSUE THREAD

**Issue by watzon** [jsforce/jsforce#481]
Not sure if this is a jsforce issue or a salesforce issue, I wouldn't be surprised if it were the latter, but deploying static resources via the metadata api is very slow. I am attempting to upload a 2.67 MB file which using Salesforce's own site takes about 15 seconds on my internet connection. However when done via jsforce and the metadata api I am seeing times ranging from 1.3 - 2 minutes. Any ideas on a fix for this? My code is very simple:

``` javascript
SalesforceClient.prototype.deploy = function(zipInput, opts) {
  var self = this;
  return new Promise(function(resolve, reject) {
    self.conn.metadata.deploy(zipInput, opts)
      .complete(true, function(err, result) {
          if (err) {
            reject(err);
          } else {
            resolve(result);
          }
        });
  });
};
```

**Comment by stomita** [comment]
No idea other than the API server temporally issue.
