### ISSUE TITLE
{ [invalid_grant: authentication failure] name: 'invalid_grant' } error while trying to retrieve accesstoken and refreshtoken

### ISSUE THREAD

**Issue by vivinRajagopalan** [jsforce/jsforce#482]
Hi All,

After i get the Oauth url from oauth2.getAuthorizationUrl(), when i try to post the code to conn.authorize(code, function(err, userInfo) {} , i always get the below error, is there something that am missing ? 

{ [invalid_grant: authentication failure] name: 'invalid_grant' }

**Comment by DouglasCAyers** [comment]
@vivinRajagopalan I see you closed this issue, did you resolve the `invalid_grant` problem? I'm facing the same problem. Thanks!

**Comment by Udbhav8** [comment]
@vivinRajagopalan @douglascayers  were you guys able to solve this problem? and if so how?
