### ISSUE TITLE
Wondering how to add a chatter feed to a parent in a community via jsforce?

### ISSUE THREAD

**Issue by srajagopalan1712** [jsforce/jsforce#484]
Edited the example here https://jsforce.github.io/document/#chatter-api

I am trying to follow the example in jsforce document and insert a feed item as a child to a custom object and make it visible in a community. I tried giving parentId for my custom object on whom I need feed for and for community I tried adding networkId or NetworkScope as the sfdc FeedItem api asks for. Neither works. Here is what tried. Will be good to know what my mistake is

`conn.chatter.resource('/feed-elements').create({
body: {
    messageSegments: [{
      type: 'Text',
      text: 'This is new post'
    }]
  },
  feedElementType :'FeedItem',
  subjectId: 'me'
  networkId: '0DB....',
 //networkScope: '0DB..' also fails
}, function(err, result) {
});`

This also fails. See the resource url changed
`conn.chatter.resource('communities/communityId​/feed-elements').create({
  body: {
    messageSegments: [{
      type: 'Text',
      text: 'This is new post'
    }]
  },
  feedElementType : 'FeedItem',
  subjectId: 'me'
}, function(err, result) {
});`

**Comment by GarethSharpe** [comment]
Currently facing the same issue. No ability for a Community User to use the Chatter API. Face with the following error when attempting to use the `feed-elements` resource:

> “The requested API is not available to portal users. You may need to specify a community for portal user access.”

When the resource URL is changed to `communities/communityId​/feed-elements`, Salesforce informs me that the related resource cannot be found.

> "NOT_FOUND: The requested resource does not exist"

@srajagopalan1712, did you ever find a work around for this issue?

**Comment by srajagopalan1712** [comment]
We have not been using this code for a while but this is how I have commented on a feed

var commentsUrl = '/connect/communities/0DB8..Id/chatter/feed-elements/' + feedId + '/capabilities/comments/items';
    return protractor.promise.when(conn.chatter.resource(commentsUrl).create({
      body: {
        messageSegments: [{
          type: 'Text',
          text: 'my comment'
        }]
      }
    }));

**Comment by lms15** [comment]
Good morning, I wanted to inform you of my issues I find coding is too much strain on my eyes with my disability I cannot not practice or key four hours a day. I am checking with my  Doctor to make sure it will or will not cause harm. I have felt discomfort trying to keep up.
I am waiting for his response to my question. Coding may be something I cannot do and may have to give it up at my age. There is many things I need to learn which I am willing to do.
I need to learn Java, Python first and much practice is need. I will get back to you when the
Doctor responses to me today as to what I will decide. Thank you all for your help assisting
Me to learn coding. You all have been so helpful and patient, I very much appreciate your
Help.
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
