### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by jbonigomes** [jsforce/jsforce#487]
Apologies if this is a silly question, I am very new to Salesforce and have a fairly fresh setup.
When invoking the conn.login function, I am getting this error:

    [Error: LOGIN_MUST_USE_SECURITY_TOKEN: Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To get your new security token, log in to Salesforce. From your personal settings, enter Reset My Security Token in the Quick Find box, then select Reset My Security Token.]

My code looks like this:

    var conn = new jsforce.Connection({
      instanceUrl: 'myurlhere', // in the format https://XXX.salesforce.com
      accessToken: 'mytokenhere'
    });
    conn.login('myemailhere', 'mypasswordhere', function(err, res) {
      if (err) { return console.error(err); }
      conn.query('SELECT Id, Name FROM Account', function(err, res) {
        console.log('well, queried');
        if (err) { return console.error(err); }
        console.log(res);
      });
    });

**Comment by cwheikki** [comment]
Are you including your Security Token with your password? Unless your org is configured to allow login without a security token, you will need to include it in the password field of your connection request. So your password entry will be 'passwordXXXXXX', where 'XXXXXX' is your security token. If you don't know your security token, follow the instructions in the error message to reset it.

**Comment by jbonigomes** [comment]
thanks @cwheikki, however, now the error message changed to:

[Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.]

**Comment by jbonigomes** [comment]
thanks @cwheikki, it works perfectly
