### ISSUE TITLE
How to refresh an expired accessToken ?

### ISSUE THREAD

**Issue by vivinRajagopalan** [jsforce/jsforce#488]
Hi,

Currently when we are trying to refresh the expired access token we have to use the  refresh token as grant type .  There are situations when my refresh token has expired (guess this has something to with 5 connections to a connected app in salesforce) and in this scenario how would i get an access token back ?

should the user start from the beginning where he requests an auth code and establish a connection from there ?

Please let me know. Thanks in advance !
@stomita

**Comment by stomita** [comment]
> should the user start from the beginning where he requests an auth code and establish a connection from there ?

When you expire the "refresh token", they should do so.

**Comment by vivinRajagopalan** [comment]
Hi stomata ,
Thanks for the reply.  But I don't expire the refresh token. Sales force
does it and when salesforce expires the refresh token even if I try
refreshing the token using grant type equal to refresh token does not work
as it has already expired.

Please find below the steps i tried :

1)create a connection object in my code :

      var conn = new jsforce.Connection({
          oauth2: oauth2,
          accessToken: accessToken,
          refreshToken: refreshToken,
          instanceUrl: instanceURL,
          id: id
      });

2) trying to search a lead/contact in sales force

  conn.search(searchQuery,function(err, response) {

**Comment by stomita** [comment]
@vivinRajagopalan It doesn't matter who expired the refresh token. The expired refresh token is not useful and you need to ask authorization again by oauth2 flow.

**Comment by vivinRajagopalan** [comment]
Thanks a lot @stomita

**Comment by ChuckJonas** [comment]
what is the default lifetime of refresh tokens in Salesforce?  Mine seems to be expiring after about 1 day (this seems short).  Is it possible to increase this time?

**Comment by SumitCloudAnalogy** [comment]
How to get a new refresh token
