### ISSUE TITLE
Error status code. 

### ISSUE THREAD

**Issue by danrc** [jsforce/jsforce#490]
Is it possible to get error http status code?

**Comment by vuza** [comment]
I was looking for the same feature. Unfortunately the http status code gets removed from the error object in this function, except Salesforce did not return a error in the response body: https://github.com/jsforce/jsforce/blob/a3ce63633f92672edcb536bbc22b6afcf2f592b2/lib/http-api.js#L250

**Comment by cristiand391** [comment]
triaging old issues...

you can see the request status code by setting the log level to debug when creating the connection:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html
https://github.com/jsforce/jsforce/blob/af8a10e84557d95e20a62dae37e9dbf1e4d50fa8/src/http-api.ts#L120

some weird errors might include the status code, IIRC this was added to catch API returning HTML:
https://github.com/jsforce/jsforce/blob/af8a10e84557d95e20a62dae37e9dbf1e4d50fa8/src/http-api.ts#L312C1-L320C13
