### ISSUE TITLE
Can we update activity history of a lead/contact through API ?

### ISSUE THREAD

**Issue by vivinRajagopalan** [jsforce/jsforce#491]
Hi Stomita,

I would love to know whether JSFORCE lets us to update the Activity history of a particular lead/contact and if so what is the necessary function call that i need to make ?

Thanks in advance !
@stomita

**Comment by thataustin** [comment]
I believe you can do so by creating a Task object with a `WhoId` or `WhatId` that represents the object you want to connect it to.  For example, create a Task record with a WhoId that is a contact id if you'd like the Task to show up in the Activity History for that contact.
