### ISSUE TITLE
Invoke custom Apex Rest Endpoints

### ISSUE THREAD

**Issue by tmichels** [jsforce/jsforce#492]
Have the capability to use JsForce to invoke custom Apex Rest Endpoints like:
https://{instance}.salesforce.com/services/apexrest/v1/*

**Comment by cwheikki** [comment]
There are request methods ([Get](https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L333), [Post](https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L355), [Put](https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L378), [Patch](https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L401), [Delete](https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L423)) available on the Connection prototype.

After logging in, you can use the request methods on your established Connection to hit your ApexRest endpoint directly:

```
var options = {
    headers: {
        'Authorization': 'Bearer ' + conn.accessToken
    }
}

conn.requestGet('https://{instance}.salesforce.com/services/apexrest/v1/', options)
    .then(function(result) {
        console.log(result);
    }, function (err) {
        console.log(err);
    });
```

I hope that helps!

Enjoy,
Chris

**Comment by tmichels** [comment]
👍 that helps
