### ISSUE TITLE
runTestsAsynchronous and runTestsSynchronous broken against Summer '16 (v37) API

### ISSUE THREAD

**Issue by alihacks** [jsforce/jsforce#493]
Tooling API v37 requires the calls to these 2 methods to be POST, not GET. When using jsforce, the calls fail with: Error: METHOD_NOT_ALLOWED: HTTP Method 'GET' not allowed. Allowed are POST

Works fine when using API version 36 and before

SFDC Doc:
    In API version 37.0 and later, the GET verb is no longer available for /runTestsAsynchronous/ or /runTestsSynchronous/. GET is still available in API version 36.0 and earlier. In API version 37.0 and later, use only POST.
    In API version 37.0 and later, /runTestsAsynchronous/ takes an optional testLevel parameter. If you don’t provide a testLevel value, we use RunSpecifiedTests.

ref: https://releasenotes.docs.salesforce.com/en-us/summer16/release-notes/rn_api_tooling_behavior.htm

**Comment by Krisa** [comment]
@stomita I think this issue has been closed a bit too early. What about supporting `testLevel`, `maxFailedTests` (and eventually `suiteids`) ?

**Comment by stomita** [comment]
@Krisa could you make a PR for supporting the other parameters ?
