### ISSUE TITLE
Closing Bulk/Batch API job

### ISSUE THREAD

**Issue by tejasmanohar** [jsforce/jsforce#495]
https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_quickstart_close_job.htm

It doesn't appear that JSForce closes Bulk/Batch API jobs after completion. Is this the case, or am I missing something? I think this could potentially cause you to go over the concurrency limit of your Salesforce account and cause connection drops.

**Comment by stomita** [comment]
It closes the job automatically when you do `bulk.load()` call. If you create your own job by `Bulk#createJob()`, and open it by `Job#open()`, you need to do close it explicitly.

**Comment by tejasmanohar** [comment]
Hmm, where's the close call in Bulk#load implementation? Is there a prototype method on `Job` that I can use to close it?

**Comment by tejasmanohar** [comment]
Aha https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L235

**Comment by vswaroop** [comment]
> Hmm, where's the close call in Bulk#load implementation? Is there a prototype method on `Job` that I can use to close it?

Hi Tejas,
Were you able to close bulk job? I wanted to know how do you close it. I mean on which event? Basically we need to be sure that all batches under the job are finished before closing it.

Thanks,
Vishnu

**Comment by vswaroop** [comment]
> Aha https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L235

Hi Tejas,
Were you able to close bulk job? I wanted to know how do you close it. I mean on which event? Basically we need to be sure that all batches under the job are finished before closing it.

Thanks,
Vishnu

**Comment by lms15** [comment]
No I was not able to fix all my bad issues
Mamie Sharrieff

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lms15** [comment]
Good morning, I have to stop my training right now I have a family issue I must resolve and I will return to
training as soon as I can. Thank you all for helping me.
Mamie
