### ISSUE TITLE
resetPassword() and setPassword()

### ISSUE THREAD

**Issue by rogah** [jsforce/jsforce#5]
Is there any chance to add both `conn.resetPassword(ID userID);` and `conn.setPassword(ID userID, string password);` to _jsforce_?

Please do let me know if there's already a way to achieve this thorugh the current version.

**Comment by joost** [comment]
Any suggestion on how to do a `setPassword` from jsforce?

**Comment by joost** [comment]
soap.setPassword(userId, 'pw');

Think issue can be closed.
