### ISSUE TITLE
instanceUrl is overwritten after authorization

### ISSUE THREAD

**Issue by assertnotnull** [jsforce/jsforce#506]
Setting the instanceUrl has no effect because after logging in with oauth2 the value is overwritten by the response.

I was trying to use yakbak for repeatable tests but this makes it impossible

**Comment by stomita** [comment]
instanceUrl is automatically maintained by the oauth authorization flow success, because it always return the correct url of instance url in the response. Changing the instance url is not supported with oauth2 authorization flow.
