### ISSUE TITLE
jsforce Promise should throw errors when not caught

### ISSUE THREAD

**Issue by dcolens** [jsforce/jsforce#510]
Promises that don't have a .catch should throw an unacughtexception or unhandledrejection, the promises of jsforce don't. Example:

```
var promise = conn.login(USER, WRONGPASSWORD);
promise.then(function() {
 // we're logged in
});
```

the above code should throw an unhandled exception, it does not. 
It looks like jsforce catches all exception and does not emit them when it should:

```
var promise = conn.login(USER, WRONGPASSWORD);
promise.then(function() {
 // we're logged in
})
.catch(function(error) {
 throw error
});
```

the above code will also not trigger an uncaught exception.

**Comment by cristiand391** [comment]
triaging old issues...

this is properly handled in jsforce v3.
