### ISSUE TITLE
sobject.Find & Update timeout

### ISSUE THREAD

**Issue by blitzd** [jsforce/jsforce#515]
I'm running into an issue finding and updating a record where it is randomly timing out on the update. I don't see anywhere that I can set a different timeout on the connection or operations, I only see that option for the bulk API. We're processing records one at a time (it's a download/archive scenario for blob attachments) so the bulk API doesn't really work for what we're doing. Can the timeout be set for the Batch API?

**Comment by stomita** [comment]
Are you doing `sobject('SObject__c').find({ ... }).update({ ... })` ? If so, the internal call will invoke bulk API so you should set the timeout value properly to `bulk.pollTimeout`.

If you want to fetch one record, use `sobject('SObject__c').findOne()` and chain it to promise to call the `sobject('SObject__c').update()` call.

**Comment by blitzd** [comment]
@stomita We (co-worker and I) had tried both methods (find/findOne) and I don't think I saw a difference. My co-worker did find the pollTimeout option and that seems to have alleviated a lot of the issues, though we're still running into timeout issues during the day with values of 120000 - this could be more of a salesforce issue though.

**Comment by blitzd** [comment]
This seems to be resolved on our end with a few more adjustments to the timeout. 

It may be helpful in the docs to be more explicit about what is occurring under the covers - we had assumed that the bulk timeout options only applied when directly using those API methods. Thanks for your help!
