### ISSUE TITLE
LoginURL

### ISSUE THREAD

**Issue by taipan-ouch** [jsforce/jsforce#519]
I'm a little confused with the loginURL when using Oauth2 as the force.com connection mechanism.

Connection.oauth2 contains a loginUrl attribute and so does Connection. Which one or both should be populated when build an oauth connection object?

Also if my loginURL host is test.salesforce.com and my instance url is CS41.salesforce.com. Do I need to use CS41 as the loginUrl if my access token token expires? This appears to be the case from the behavior I'm seeing.

Any clarity would be greatly appreciated.

**Comment by stomita** [comment]
Set loginUrl to oauth2 config if you want to use OAuth2 flow for authorization. 
If you are not using OAuth2, and using SOAP based password authentication, set loginUrl in Connection options.

If you are using sandbox, set `test.salesforce.com` as loginUrl, not `cs41.salesforce.com` (which is instance URL)
