### ISSUE TITLE
[Error: Invalid URI "/services/data/v37.0/search?q=FIND%20%7BORD%5C-01796034%7D"]

### ISSUE THREAD

**Issue by cjpuskar** [jsforce/jsforce#523]
I'm having an issue troubleshooting my search API call.....

First some env details:
Im running Node v4.4.4 off of an EC2 server.
Using jsforce v1.7.0

When I run my query on https://jsforce.github.io/document/ everything works as expected.
 
![jsforce](https://cloud.githubusercontent.com/assets/5401197/17781910/0eb4c8ec-6526-11e6-843e-dde63ead6d34.jpg)

However when I run this query off of my node.js server Im getting the invalid uri error. 

In Node.js I've also tried several variations on the query string such as:
 
"ORD\-01796034"

as well as assigning the query to a variable and passing that variable in as an arg, see var searchString

Here is my query code, Im also including the code I use to create the connection to SFDC. When I make the connection to SFDC I'm receiving an SFDC access token so I assume Im making the connection correctly..

**SEARCH QUERY**
SFDC.prototype.query = function (conn, orderName) {
	// var orderName = "ORD\-01796034"
	// var searchString = "FIND {ORD\-01796034}"

	conn.search("FIND {ORD\\-01796034}", function(err, res) {
		if (err) { return console.error(err); }
		console.log(res);
	});
};

**INVOKED AS** 
var objectID = sfdc.query(conn, orderName);

**SFDC CONNECTION**

SFDC.prototype.connection = function () {

	var conn = new sf.Connection({
		oauth2: {
			loginUrl: sfCred.loginUrl,
			clientId: sfCred.clientId,
			clientSecret: sfCred.clientSecret,
			redirectUri: ""
		}
	});

	var password = sfCred.password + sfCred.securityToken;

	conn.login(sfCred.username, password, function(err, userInfo) {
		if (err) { return console.error(err); }

		var sfdcAccessToken = conn.accessToken;
		console.log("sfdcAccessToken: " + sfdcAccessToken);
		console.log("Instance Url: " + conn.instanceUrl);

		// Logged in user property
		console.log("User Id: " + userInfo.id);
		console.log("Org ID: " + userInfo.organizationId);
	});

	return conn;
};

**INVOKED AS**
var conn = sfdc.connection();

Any help I can get would be greatly appreciated. Thanks!

**Comment by rmarius** [comment]
I have this same problem with heroku. It runs fine locally, but I get the error on heroku

**Comment by rmarius** [comment]
I explicitly set the InstanceURL and the problem seems to be gone

**Comment by Muhammadinaam** [comment]
> I explicitly set the InstanceURL and the problem seems to be gone

where do you set InstanceURL explicitly? I am also having this error.
