### ISSUE TITLE
Browser OAuth in the same window

### ISSUE THREAD

**Issue by dirajkumar** [jsforce/jsforce#525]
Hi,

Do you have any examples of doing an OAuth from the same window instead of a popup. I'm working on a react.js app with webpack to do the browser OAuth and having difficulties with the popup window. The following function is never executed and the redirect is not happening.

``` javascript
// This below function is never called. 
jsforce.browser.on('connect', function() {
  browserHistory.push('/home');
});
```

Thoughts?

**Comment by dirajkumar** [comment]
I found this but disabling the "Developer Mode" did not solve the problem. 

http://salesforce.stackexchange.com/questions/51543/jsforce-authentication-popup-dialog-issue?stw=2

**Comment by rodrigoEclipsa** [comment]
Have you found the solution?
