### ISSUE TITLE
Multi-Select data type queries

### ISSUE THREAD

**Issue by cthurston** [jsforce/jsforce#529]
According to: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_querying_multiselect_picklists.htm
one must use the keywords INCLUDES and EXCLUDES to query certain combinations of values when the data type is a multi-select box.  

Can we get them added to the opMap?

````js
var opMap = {
  "="     : "=",
  "$eq"   : "=",
  "!="    : "!=",
  "$ne"   : "!=",
  ">"     : ">",
  "$gt"   : ">",
  "<"     : "<",
  "$lt"   : "<",
  ">="    : ">=",
  "$gte"  : ">=",
  "<="    : "<=",
  "$lte"  : "<=",
  "$like" : "LIKE",
  "$nlike" : "NOT LIKE",
  "$in"   : "IN",
  "$nin"  : "NOT IN",
  "$includes"  : "INCLUDES",
  "$excludes"  : "EXCLUDES",
  "$exists" : "EXISTS"
};
````

**Comment by stomita** [comment]
Sure, you can, please give us the pull request.

**Comment by cthurston** [comment]
Created pull request:
https://github.com/jsforce/jsforce/pull/530
