### ISSUE TITLE
Logout using instance url and access token

### ISSUE THREAD

**Issue by neeraj87** [jsforce/jsforce#531]
I asked this same question on the node-salesforce GitHub account before realizing you had moved everything to jsforce, so sorry for the duplicates. I am logging in the node.js site using HTML login page with salesforce credentials. It returns the instance URL and access token which is saved in my session.

However, in the docs, it is mentioned that we can only log out using session Id and server URL. Can I not log out using the instance URL and access token? I tried doing that but it threw an error. I want the user to log out when they click the logout button.

Great work on the module though, loved it.

**Comment by stomita** [comment]
You need to pass `loginUrl` information in connection options to make the `logout()` work properly.

**Comment by neeraj87** [comment]
I am passing the loginURL in the connection.

This is my code for connection:

```

var username = 'username@sandoxlogin.com';
var password = 'mypassword';
var securityToken = 'mysecuritytoken';
var conn = new jsforce.Connection({
	loginUrl : 'https://test.salesforce.com'
});

conn.login(username, password + securityToken, function(err, userInfo) {
				if (err) { return console.error(err); }
				console.log('AccessToken: ' + conn.accessToken);
				console.log('Instance URL: ' + conn.instanceUrl);
				console.log('User ID: ' + userInfo.id);
				console.log('Org ID: ' + userInfo.organizationId);
				req.session.accessToken = conn.accessToken;
				req.session.instanceUrl = conn.instanceUrl;
				return res.redirect('/dashboard');
			});
```

This is my logout code:

```
app.get('/logout', function(req, res) {
       //logout for the salesforce user
	var conn = new jsforce.Connection({
		instanceUrl: req.session.instanceUrl,
		accessToken: req.session.accessToken
    });

	conn.logout(function(err) {
		if (err) { return console.error(err); }
		// now the session has been expired.
	});
	req.logout(); //passport logout for the node.js site
	req.session.destroy();
	res.redirect('/');
});
```

It gives the following error in the conn.logout method:

> { [ERROR_HTTP_404: Bad_Id] name: 'ERROR_HTTP_404' }

**Comment by songawee** [comment]
@neeraj87 I think you need to add `loginUrl` as a parameter to your logout connection. I had this same issue and adding that parameter worked for me.

**Comment by justinlazaro-iselect** [comment]
anyone have a fixed on this?

**Comment by gouravbhardwaj** [comment]
Your logout code should be :
 let conn = new jsforce.Connection({
        oauth2 : oauth2,     //This is important
        accessToken: req.session.accessToken,
        instanceUrl: req.session.instanceUrl
    });

    conn.logout(function(err) {
      if (err) {  console.log('error',err); }
      console.log('logged out');
      req.session.instanceUrl = '';
      req.session.refreshToken = '';
      // now the session has been expired.
      res.redirect('/');
    });

I was getting the same error but got it fixed by  oauth2 : oauth2, if we don't pass oauth2 details then jsforce library uses default login url causing which is login.salesforce.com which will cause your app to throw an error as your actual loggedin url and login.salesforce.com won't match
