### ISSUE TITLE
timeout and login decline after attempting to create connection while on corporate proxy

### ISSUE THREAD

**Issue by QuantumRich** [jsforce/jsforce#532]
Hello,

I have jsforce-ajax-proxy [(link here)](https://github.com/jsforce/jsforce-ajax-proxy) running in the background, but when I create a connection as such:

```
var conn = new jsforce.Connection({
    loginUrl : 'https://test.salesforce.com',
    proxyUrl : 'http://localhost:3123/proxy/'
});
```

and do a login as such:

```
conn.login(user, (pass+token), function(err, userInfo) {
    console.log("DEBUG");
    if (err) {
        return console.error(err);
    }
}
```

I do not even get my console logging statement as it hangs.  Eventually, after a LONG while, I get a timeout error:

```
POST http://localhost:3123/proxy?(some number here) net::ERR_EMPTY_RESPONSE
DEBUG
Error: Access Declined(…)
```

This does not happen at all when I am not under the proxy (and my app works fine), but I would like this to work behind a proxy.  Is there a setting I can apply to do this, such as setting an http proxy variable?  If it helps, I am behind something that looks like `user:pass@proxy.company.com:port_id`.

**Comment by stomita** [comment]
To be clear, are you using "JSforce Ajax Proxy" behind "HTTP Proxy" ? If so, you should set `HTTP_PROXY` environment variable which points to your "HTTP Proxy" server when you start up the "Ajax Proxy" process.

**Comment by QuantumRich** [comment]
I ended up fixing this by adjusting a proxy parameter in the request in the `proxy.js` file, like so:

'''
var request = require('request');
var debug = require('debug')('jsforce-ajax-proxy');
request.defaults({'proxy': 'http://<user>:<pass>@proxy.company.com:<port>});
'''

**Comment by QuantumRich** [comment]
Hello again,

I am wondering if it is possible to go around a proxy while on an openshift instance.

**Comment by cristiand391** [comment]
triaging old issues...

setting a proxy in jsforce will make all requests to throught it. Use the proxy env vars if you need to switch it when running the app.
