### ISSUE TITLE
Where can I find this function definition?

### ISSUE THREAD

**Issue by vinnyoodles** [jsforce/jsforce#535]
https://github.com/jsforce/jsforce/blob/master/lib/api/bulk.js#L411

I tried looking through the `RecordStream` class but there's no `write` function.

**Comment by stomita** [comment]
The `RecordStream` inherits Node.js [stream.Transform](https://nodejs.org/api/stream.html#stream_class_stream_transform), which has [write()](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback) method.
