### ISSUE TITLE
public visualforce page

### ISSUE THREAD

**Issue by dinnouti** [jsforce/jsforce#536]
I am planning to have a public VisualFoce page with jsforce where it will consume objects from salesforce. 

In my tests, I was able to make a "secure" VisualForce page work with the jsforce.Connection({ accessToken: '{!$API.Session_Id}' }) and Query Stream.

For a **public** visual force page, what is the recommended approach for a public visualforce page to query a SalesForce object? Mostly, how the authentication will play between the public page and the SalesForce object? Do you have examples?

**Comment by stomita** [comment]
The public VF page needs to use OAuth instead of session id.

**Comment by dinnouti** [comment]
@stomita thanks for reply, do you have a sample how to consume objects and put in a guest (public) visual force page using oauth?

**Comment by stomita** [comment]
Just do it like other OAuth2 web integration. Login as a guest user is not possible as the API access doesn't allow that.
