### ISSUE TITLE
Rename a field label with update?

### ISSUE THREAD

**Issue by PhilFrankLee** [jsforce/jsforce#538]
I'm trying to update a field label using the update call but it does nothing. Is this possible? I think rename only applies to api names.

```
var metadata = [{
  fullName: 'TestObject1__c.Myfield10__c',
  label: 'NewName',
}];

conn.metadata.update('CustomField', metadata, function(err, results) {
```

.
.
.

**Comment by stomita** [comment]
I think it will update the label safely. Please check the error message callbacked.
