### ISSUE TITLE
ClientInputError for conn.bulk.query

### ISSUE THREAD

**Issue by gmark-newt** [jsforce/jsforce#545]
I'm getting the following error when trying to use a conn.bulk.query. In other places, I can use the bulk api, and it won't give me this error. But in this particular case, if I remove the 'bulk', and just use conn.query, it will not give me this error. I am not creating anything to upsert, I am only querying in this case. I haven't been able to find out why SalesForce gives me this error.

Error:  { [ClientInputError: Unable to find any data to create batch] name: 'ClientInputError', errorCode: 'ClientInputError' }

**Comment by tjtaill** [comment]
I am seeing this error too any idea what caused it ?

**Comment by arnab-selegic** [comment]
Error [ClientInputError]: Unable to find any data to create a batch

I think these are the possible sol:
Check on the network side if there is any problem.
Check on the Salesforce trust site if there is any performance problem in SF instance.
Check the API limits on the salesforce.

Can any one confirm these! points
