### ISSUE TITLE
replay (streaming api)

### ISSUE THREAD

**Issue by twojoke** [jsforce/jsforce#547]
Any plans on implementing message durability using Replay, where we can pass a replay ID to the client so we can pull all messages that occurred from that ID forward?

For reference: https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/using_streaming_api_durability.htm

**Comment by stomita** [comment]
(The PR #546 is for this enhancement issue I understand)

**Comment by stomita** [comment]
Actually it has already supported the replay channel, but not documented well.

**Comment by sth-fish** [comment]
no support for replay?

**Comment by jatkinson-vivial** [comment]
If replay is already supported how is the replay id set?

In the streaming class the _createClient method sets the endpoint but not the replayId

**Comment by nolson-berry** [comment]
I believe this has been resolved now with: https://github.com/jsforce/jsforce/pull/740
