### ISSUE TITLE
How to perform variable binding in SOQL query?

### ISSUE THREAD

**Issue by neeraj87** [jsforce/jsforce#551]
I have an array of ids of a certain custom object. I need to query all the children of that object records represented in the array. However, it won't do variable binding and gives error saying:

> Bind variables only allowed in Apex code] name: 'MALFORMED_QUERY'

My query looks something like this:

> select Id, field_1__c, field_2__c from Child_Obj__c where Parent_Obj__c in parentObjIdArray

Where parentObjIdArray is an array of ids of the parent object.

Any ideas or suggestions on how to do this?

**Comment by stomita** [comment]
@neeraj87 You can't do the variable binding natively in REST API because it doesn't support right now. However the JSforce's `SObject#find()` do the similar thing to developers. 

```javascript
var parentObjIdArray = [ '', '', '', ... ];
conn.sobject('Child_Obj__c').find({
  ParentObj__c : parentObjIdArray
}, [ 'Id', 'field_1__c', 'field_2__c' ]).then(function(records) {
   // ...
});
```
