### ISSUE TITLE
Retrieving body of Document

### ISSUE THREAD

**Issue by jonathanljames** [jsforce/jsforce#553]
Is there a way to retrieve the body of a Document object?  My code is below:

conn.query("SELECT id, body FROM Document WHERE Name='<DOCUMENT NAME>' LIMIT 1", function(err, res) {
    if (err) { return console.error(err); }
    if(res.totalSize > 0){
         //This is where I need to get the actual content of the file.  I can see an object called "Body" in  
        //the response but I am unsure how to get the actual content.
    }
  });

Thanks!

**Comment by stomita** [comment]
@jonathanljames to fetch the blob data like document body, call like this:
```javascript
var documentId = ' .... '; // get it from the result of queried record 
var fout = fs.createWriteStream('./path/to/document'); // output stream to file
conn.sobject('Document').record(documentId).blob('Body').pipe(fout);
```
