### ISSUE TITLE
Unable to retrieve Settings via Metadata api?

### ISSUE THREAD

**Issue by sfpc2770** [jsforce/jsforce#557]
Is there a known issue using JSForce to pull the Settings type of Metadata from Salesforce?

I've been able to pull almost all the metadata from my org with no troubles.  (Works great!)  But the last piece that I can't get to work is Settings.  I define the exact same unpackaged package with the migration tool or with WSC and it works fine so I know it's supported by Salesforce.  But not with JSForce (or SoapUI using the request that JSForce put together).
`var packageTypes = [];
                        packageTypes.push({ members: ["Account", "Case"],
                                            name: "Settings" });
                        console.log("Calling retrieve with: types=", packageTypes);
                        retResult = status.sfConnection.metadata.retrieve({
                            unpackaged: {
                                types: packageTypes,
                                version: _sfApiVersion
                            }});`

When called, it returns back the zip file containing only the package.xml file:
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account</members>
        <members>Case</members>
        <name>Settings</name>
    </types>
    <version>37.0</version>
</Package>
`
Along with the messages:
  problem: 'Settings type: \'Account\' is unknown' }
  problem: 'Settings type: \'Case\' is unknown' }

Again, I've been able to retrieve the same files using both the Ant migration tool as well as WSC (and other tools).

Any hint of what might be going wrong?

Thanks,
-Sean

**Comment by stomita** [comment]
@sfpc2770 You should do like this:

```
var packageTypes = [];
packageTypes.push({ members: ["Account", "Case"], name: "Settings" });
console.log("Calling retrieve with: types=", packageTypes);
retResult = status.sfConnection.metadata.retrieve({ unpackaged: { types: packageTypes }, apiVersion: "37.0" });
```

**Comment by sfpc2770** [comment]
Ah, thank you very much!  It was the missing apiVersion outside the unpackaged object that was missing.  Funny how the rest of the Metadata types didn't need it.  But I have it all working now.

You're a life saver!

Thanks,
-Sean

**Comment by sfpc2770** [comment]
Ah, thank you very much!  It was the missing apiVersion outside the unpackaged object that was missing.  Funny how the rest of the Metadata types didn't need it.  But I have it all working now.

You're a life saver!

Thanks,
-Sean

**Comment by sfpc2770** [comment]
Ah, thank you very much!  It was the missing apiVersion outside the unpackaged object that was missing.  Funny how the rest of the Metadata types didn't need it.  But I have it all working now.

You're a life saver!

Thanks,
-Sean

**Comment by ChuckJonas** [comment]
> It was the missing apiVersion outside the unpackaged object that was missing. 

Ran into the exact same issue.  So wierd, glad I found this post...
