### ISSUE TITLE
Application using jsforce node module  is getting crashed for batch create process.

### ISSUE THREAD

**Issue by apasrini** [jsforce/jsforce#558]
App which uses jsforce node module gets crashed for batch create for sobject say Account when creating account in bulk using jsforce. 

App is getting crashed with the following exception, 

   ,"err":{"message":"","name":"ERROR_HTTP_404","stack":"ERROR_HTTP_404\n    at HttpApi.getError (/home/vcap/app/node_modules/jsforce/lib/http-api.js:238:13)\n    at /home/vcap/app/node_modules/jsforce/lib/http-api.js:83:22\n    at _fulfilled (/home/vcap/app/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/home/vcap/app/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/home/vcap/app/node_modules/q/q.js:796:13)\n    at /home/vcap/app/node_modules/q/q.js:604:44\n    at runSingle (/home/vcap/app/node_modules/q/q.js:137:13)\n    at flush (/home/vcap/app/node_modules/q/q.js:125:13)\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickDomainCallback (node.js:390:13)"},"msg"

**Comment by apasrini** [comment]
Can someone let me know if this issue is something which is existing with jsforce for bulk operation ? Can some helpout as it is high priority issue.

**Comment by stomita** [comment]
@apasrini 
You need the detail of the code to get the answer or help, not only a crash log.

**Comment by apasrini** [comment]
I see this issue even for normal CREATE operation on objects. When there are multiple login and logout. Log out fails with this issue. The Application crashes with out of memory at the end. Any clue on resolution would be helpful.

**Comment by apasrini** [comment]
I would get a sample code but this happens on bulk working together with multiple login and logout.
