### ISSUE TITLE
[question] Is redirect URI necessary to refresh token?

### ISSUE THREAD

**Issue by wearhere** [jsforce/jsforce#560]
The [refresh token docs](https://jsforce.github.io/document/#access-token-with-refresh-token) show the redirect URI being specified alongside the `clientId` and `clientSecret`. But must we really provide this parameter to have the access token automatically refreshed? It [looks](https://github.com/jsforce/jsforce/blob/38e4e66d021db20b22435f48c9d2b34f48e54c23/lib/connection.js#L141) [like](https://github.com/jsforce/jsforce/blob/38e4e66d021db20b22435f48c9d2b34f48e54c23/lib/oauth2.js#L88) no.

**Comment by wearhere** [comment]
The reason I do not wish to provide this parameter is because I am making a wrapper library around JSForce and I don't want that library to have to know where it's hosted. The service hosting the library will provide the redirect URI and it would be nice to limit the circumstances in which it has to do so.

**Comment by stomita** [comment]
@wearhere the redirect URI is the parameter we need in OAuth2 [authorization code flow](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_web_server_oauth_flow.htm). If you don't need the authz flow and only want to do refresh token it [does not need the redirect URI](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_refresh_token_oauth.htm).

However I cannot understand the case which the developer don't want to pass the redirectURI information to the lib, because it will already have dependencies when passing clientId and clientSecret, which is tightly connected to the redirectURI value.

**Comment by wearhere** [comment]
> It will already have dependencies when passing clientId and clientSecret, which is tightly connected to the redirectURI value.

That's true, but the redirect URI is just one more configuration parameter to pass.

And, the way that I have set my wrapper library, it actually doesn't need to know the redirect URI per se even when performing the authorization code flow. It vends Express middleware that encapsulates as much of the flow as possible:

```js
// My library.
const express = require('express');
const jsforce = require('jsforce');
const urlJoin = require('url-join');

function oauthMiddleware({clientId, clientSecret, rootUrl }) {
  const callbackPath = '/callback';

  return express.Router()
    .get('/', (req, res) => {
      var oauth2 = new jsforce.OAuth2({
        clientId,
        clientSecret,
        redirectUri: urlJoin(rootUrl, req.originalUrl, callbackPath)
      });

      // Details of OAuth state omitted.
      res.redirect(oauth2.getAuthorizationUrl());
    })
    .get(callbackPath, (req, res) => {
      var conn = new jsforce.Connection({
        oauth2: {
          clientId,
          clientSecret,
          redirectUri: urlJoin(rootUrl, req.originalUrl)
        }
      });

      conn.authorize(req.query.code, (err, userInfo) => {
        console.log(err, userInfo);
      });
    });
}
```

```js
// The service using the library, hosted at https://app.mixmax.com.
const oauthMiddleware = require('jsforce-wrapper').oauthMiddleware;

app.get('/_oauth/salesforce', oauthMiddleware({
  clientId: process.env.SALESFORCE_CLIENT_ID,
  clientSecret: process.env.SALESFORCE_CLIENT_SECRET,
  rootUrl: process.env.ROOT_URL // https://app.mixmax.com
});
```

So as you can see, the library doesn't need to be configured with the full redirect URI—it can be agnostic to where it's hosted as long as the host tells it what the root URL is, then the library can dynamically determine the redirect URI during the authorization flow.

**Comment by wearhere** [comment]
Thanks for the info!
