### ISSUE TITLE
How does one Execute an Approval Process?

### ISSUE THREAD

**Issue by couturecraigj** [jsforce/jsforce#561]
This does not seem to be well documented and I am not a java developer as the documentation tends to lean toward classes, methods, and members.  I have created a `jsforce.Connection()` and I want to fire an approval process from the existing connection.  I am using this to create and submit a record and I want to immediately execute an approval process.  Also how would one approve through this plugin?

Thanks in advance

**Comment by couturecraigj** [comment]
Any answer for this?

**Comment by REBELinBLUE** [comment]
Did you ever find the answer to this? There appears to be code to do it in jsforce but there is no mention of it in the documentation

**Comment by couturecraigj** [comment]
Not really, I have been disappointed with the timeliness of responses here.  The best way I could find is to write Apex Code and a Checkbox on the item that you are trying to approve which when checked it runs the Approval Process.

**Comment by REBELinBLUE** [comment]
I think I figured it out 

```javascript
const conn = new jsforce.Connection({
    loginUrl: "http://test.salesforce.com"
});

conn
    .login("user", "password")
    .then((res) => conn.sobject("Custom_object__c").create(data))
    .then((res) => conn.process.approval.submit(
        res.id,
        "Submit for Approval",
        { processDefinitionNameOrId: "Approval_Process_Name" },
        (err, res) => { console.log(res); }
    ));
```

seems to be working for me

**Comment by couturecraigj** [comment]
Great!  At least if somebody else has this issue they have this listed in GitHub.  I will look into this if I need to in the future.  I hate writing Apex so any way around it is appreciated.

**Comment by jrod9904** [comment]
Is there a way to turn off assignment rules when submitting for approval? 
Similar to the create function that accepts headers like so .
create(data, {headers: {'Sforce-Auto-Assign': 'FALSE'}})

**Comment by couturecraigj** [comment]
Approval process should not result in assignment rules firing

**Comment by jrod9904** [comment]
Thank you. Right now it is so that means theres something on salesforce environment causing this?

**Comment by couturecraigj** [comment]
Approvals are basically a separate object where they assign for approvals
but not the object you are going it on... You can trigger workflows which
may be re assigning it out you may have an apex coffee that fires for some
reason and runs the assignment rules

**Comment by jrod9904** [comment]
Thank you

**Comment by xsumit** [comment]
> ```js
> .then((res) => conn.process.approval.submit(
>         res.id,
>         "Submit for Approval",
>         { processDefinitionNameOrId: "Approval_Process_Name" },
>         (err, res) => { console.log(res); }
>     ));
> ```

This can only submit 1 record at a time for approval. How to do it for bulk of records? Can I reject all approvals if any of the record failed to approve?
