### ISSUE TITLE
Refresh token and documentation

### ISSUE THREAD

**Issue by davidedelerma** [jsforce/jsforce#562]
Hi,

I am trying to get the refresh token following the steps written in the documentation, but I can't have it working.
I am using Express.
I also found an error in the documentation (it is reported in the following code).
Can you help me with that please?

Regards,
Davide

`'use strict'
const express = require('express');
const jsforce = require('jsforce');

const app = express();
const path = require('path')

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname + '/client/build/index.html'));
});

//check the documentation: it should be jsforce.OAuth2 not sf.OAuth2

const oauth2 = new jsforce.OAuth2({ 
   // you can change loginUrl to connect to sandbox or prerelease env.
   // loginUrl : 'https://test.salesforce.com',
   clientId : 'My ID', // it is right because it is working for the login part
   clientSecret : 'my client secret',  // it is right because it is working for the login part
   redirectUri : 'https://localhost:3000/'
});

app.get('/oauth2/auth', (req, res) => {
   res.redirect(oauth2.getAuthorizationUrl({ scope : 'api id web refresh_token' }));
});

app.get('/oauth2/callback', function(req, res) {
   var conn = new jsforce.Connection({ oauth2 : oauth2 });
   var code = req.param('code');
   console.log(code);
   conn.authorize(code, function(err, userInfo) {
     if (err) { return console.error(err); }
     // Now you can get the access token, refresh token, and instance URL information.
     // Save them to establish connection next time.
     console.log(conn.accessToken);
     console.log(conn.refreshToken);
     console.log(conn.instanceUrl);
     console.log("User ID: " + userInfo.id);
     console.log("Org ID: " + userInfo.organizationId);
     // ...
   });
 })
`

**Comment by davidedelerma** [comment]
Obviously I added this part as well...

` app.get('/oauth2/callback', function(req, res) {
   var conn = new jsforce.Connection({ oauth2 : oauth2 });
   var code = req.param('code');
   console.log(code);
   conn.authorize(code, function(err, userInfo) {
     if (err) { return console.error(err); }
     // Now you can get the access token, refresh token, and instance URL information.
     // Save them to establish connection next time.
     console.log(conn.accessToken);
     console.log(conn.refreshToken);
     console.log(conn.instanceUrl);
     console.log("User ID: " + userInfo.id);
     console.log("Org ID: " + userInfo.organizationId);
     // ...
   });
 });`

**Comment by davidedelerma** [comment]
When I try the get request using postman, for the path: http://localhost:3000/auth/callback
I get this error: { [invalid_grant: invalid authorization code] name: 'invalid_grant' }
so seems that the problem is here
res.redirect(oauth2.getAuthorizationUrl({ scope : 'api id web refresh_token' }));

**Comment by stomita** [comment]
```javascript
const oauth2 = new jsforce.OAuth2({
// you can change loginUrl to connect to sandbox or prerelease env.
// loginUrl : 'https://test.salesforce.com',
clientId : 'My ID', // it is right because it is working for the login part
clientSecret : 'my client secret', // it is right because it is working for the login part
redirectUri : 'https://localhost:3000/'
});
```
Why the redirectUri is set to `https://localhost:3000/`, not `https://localhost:3000/oauth2/callback` ?
