### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access. The response had HTTP status code 400.

### ISSUE THREAD

**Issue by renatoliveira** [jsforce/jsforce#579]
This error occurs when trying to the bulk API to insert records on a Visualforce page that has no header or sidebar enabled, passing the user's Session Id as the parameter for the connection to be established with Salesforce.

I'm building a custom package, so the URL contains the app's namespace.

The common CRUD methods (create, destroy, update, query) work just fine. But I'm dealing with a huge amount of records.

How can I proceed to solve this issue?

**Comment by stomita** [comment]
The bulk API endpoint is not provided in VF domain so it requires proxy service when calling the bulk API. If you are in VF you can point the AJAX proxy service.

See https://github.com/jsforce/jsforce/issues/139#issuecomment-74491162

**Comment by rdietrick** [comment]
I'm trying to revive an old project that uses the Bulk API.  Previously, I was able to use the `proxyUrl: '/services/proxy'` attribute to successfully access the API from within a visualforce page, but now it's being blocked by the CORS policy and I get the following error:

```
Access to XMLHttpRequest at 'https://XXX-dev-ed.my.salesforce.com/services/async/51.0/job' (redirected from 'https://XXX-dev-ed--c.vf.force.com/services/proxy?1661444829100.8770455799281465') from origin 'https://XXX-dev-ed--c.vf.force.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
request.js:35          GET https://XXX-dev-ed.my.salesforce.com/services/async/51.0/job net::ERR_FAILED 400
```

Is there a workaround for this?

**Comment by cristiand391** [comment]
for reference, see the CORS section in docs:
https://jsforce.github.io/document/#cors
