### ISSUE TITLE
Delete + erase via metadata API?

### ISSUE THREAD

**Issue by arbokrad** [jsforce/jsforce#580]
Is it possible to follow a delete command with an erase to make sure a metadata entity (like a custom field) is actually removed from Salesforce?

Right now running the delete command places the entity in the "recycle bin" for the object. For example:
```
var deferred = Q.defer();
var fieldsToDelete = ['Account.SomeField__c'];
conn.metadata.delete( 'CustomField', fieldsToDelete, function( err, response ) {
    if( err ) {
	deferred.reject( err );
    } else {
        console.log( response );
        deferred.resolve();
    }
});

return deferred.promise;
```

Running this snippet results in the following:
![jsf_destroy_screenshot](https://cloud.githubusercontent.com/assets/15720753/21061565/f25aaef2-be1a-11e6-8331-0a4bc1468cc4.PNG)

I see that there is a way to perform an erase using the deploy(...) command with the purgeOnDelete option. Is there a way this can be done using these one-off delete commands?

**Comment by arbokrad** [comment]
As a followup, I changed the approach I was taking here to not try and do deletes in this one-by-one fashion and instead use the destructiveChanges.xml approach. If anyone else is interested, here is what that code looks like:

```
var sfClient = [assume sfClient is an initialized and properly logged-in jsforce client];

// setup the polling interval and timeout for the deployment
sfClient.metadata.pollTimeout = CONFIG_SETTINGS.pollTimeout;
sfClient.metadata.pollInterval = CONFIG_SETTINGS.pollInterval;

// a deployment of this sort must have the following directory structure:
//    src/
//        destructiveChanges.xml
//        package.xml 					(empty but required)
var zipBuff = [create a zip stream of the destructive bundle using the format above];

// send the deployment package up to salesforce
var deployResult = sfClient.metadata.deploy( zipBuff, { rollbackOnError : true, purgeOnDelete : true } );

// when the deployment is complete, do something
deployResult.complete( function( err, res ) {
    if( err ) {
        // handle the error 
    } else {
        // handle a deployment that may or may not have actually succeeded by inspecting the response
    }
});
```

**Comment by stomita** [comment]
@arbokrad As the `delete()` method in `metadata` is a direct mapping of `deleteMetadata()` in the [metadata API](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deleteMetadata.htm), the deleted definition will always go to trash.  The way you did in `deploy()` is the way to delete them entirely. I hope I can add the same functionality to [jsforce-metadata-tools](https://github.com/jsforce/jsforce-metadata-tools) when supporting the destructive deploy.
