### ISSUE TITLE
Add support for Dashboard related calls

### ISSUE THREAD

**Issue by pcon** [jsforce/jsforce#584]
Add support for the Dashboard objects in the [Analytics API](https://developer.salesforce.com/docs/atlas.en-us.api_analytics.meta/api_analytics/analytics_api_dashboard_resource_reference.htm)

**Comment by pcon** [comment]
@stomita I've started working on this but I've run into a snag while trying to write tests for it.  The default developer sandbox does not have any dashboards on it.  You cannot create a dashboard via the API.  Not sure how you would want me to proceed since it can't be automatically added to the `org-setup` script.

**Comment by stomita** [comment]
@pcon I thought the metadata package could include a dashboard definition. If not, the test might not be the must.

**Comment by pcon** [comment]
@stomita I had completely forgotten that there was a metadata package.  I should be able to add it there.  I'll let you know if it doesn't work.

**Comment by brcline** [comment]
@pcon do you know when the version involving this will be released?

**Comment by pcon** [comment]
@brcline that's all up to @stomita as to when the next release is made.  You can always pull from master and use that.

**Comment by brcline** [comment]
@pcon your code definitely works. I've built a prototype with it. :)
