### ISSUE TITLE
How to get sessionId

### ISSUE THREAD

**Issue by SemenyukPavlo** [jsforce/jsforce#587]
How can I can get sessionId after successful connection?

**Comment by stomita** [comment]
If you established a session in `conn` object, `conn.accessToken` is the one.

**Comment by VladimirDavydko** [comment]
now it's not like that, session Id and access token are different, any thoughts?

**Comment by pardhav** [comment]
@VladimirDavydko the name of the token depends on the context of how you get them. Salesforce has 3 different types of tokens:

- **SESSION_ID**: when the user logs in from the web interface or a SOAP API call the generated token is called SESSION_ID. this is generally bound to user login time and activity and expires after if the user remains idle for a specific time.

- **ACCESS_TOKEN**: When a user tries to login through basic OAuth flow the token generated is called access token and it is 
generally valid for 3600 seconds, according to OAuth 2.0 specifications.

- **SECURITY TOKEN**: this token is an addition to a user's password which allows access to login without IP restrictions.

Both SESSION ID and access token can be used to make an API call.

for more detailed discussion visit [here](https://salesforce.stackexchange.com/questions/18565/security-token-vs-session-id-vs-access-token#:~:text=A%20session%20ID%20identifies%20a,or%20an%20API%2Fintegration%20tool.&text=Session%20ID%20values%20are%20valid,(such%20as%20Chatter%20Mobile))
