### ISSUE TITLE
Approval Process giving Error

### ISSUE THREAD

**Issue by couturecraigj** [jsforce/jsforce#591]
I am getting the following Error when attempting to use the Approval Process
`Error: Invalid URI "/services/data/v37.0/process/approvals"`

What am I doing wrong?  I am attempting to use this Server Side as I do not want to reveal this to the client as best I can.
```
const jsforceCon = new jsforce.Connection()
jsforceCon .process.approval.list(res => console.log(res))
```

Please assist I would like to build a process where users to submit things for approval and this would be a major step in doing that.

**Comment by shubhamr** [comment]
putting some time before calling the next method after creating connection worked for me . Don't know if it is the right solution to do this . But you can give it a shot .

**Comment by couturecraigj** [comment]
That seems to have been it.  I need to make sure that everything is connected and Authenticated before performing an approval... I was being silly and trying to do this outside of the routes and that does not seem to allow enough time to be authenticated.
