### ISSUE TITLE
HTTP access control (CORS)

### ISSUE THREAD

**Issue by jeremywhittington** [jsforce/jsforce#595]
When I was using the ajax toolkit I was able to natively use their ajax proxy they have built into the toolkit.

https://developer.salesforce.com/docs/atlas.en-us.ajax.meta/ajax/sforce_api_ajax_proxy.htm

The AJAX proxy is part of the AJAX Toolkit. Access it using remoteFunction defined in connection.js. You can specify any HTTP method in remoteFucntion, for example HTTP GET or POST, and it will be forwarded to the external service.

Now that Salesforce CPQ has moved to jsforce I am having problems making calls to a custom service.

I can no longer use sforce.connection.remoteFunction() and am trying to use conn.request() and xmlhttprequest directly.

`var xmlhttp;
	var url = "URL"; 
	
	if (window.XMLHttpRequest) {
		// code for IE7+, Firefox, Chrome, Opera, Safari
		xmlhttp=new XMLHttpRequest();
	}
	else {
		// code for IE6, IE5
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}

	xmlhttp.open("POST",url,false);
	xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
	xmlhttp.send();`

Im getting the error 'XMLHttpRequest cannot load **APIURL***. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '***ORIGINURL***' is therefore not allowed access.'

Does jsforce have an AJAX Proxy like the AJAX Toolkit that I can use?

I dont have another server to run the jsforce-ajax-proxy application.

**Comment by stomita** [comment]
Actually the `jsforce-ajax-proxy` is a standalone server program whose interface is compatible to Salesforce's AJAX proxy endpoint. The AJAX Toolkit's `remoteFunction` is the browser client implementation for the endpoint, which jsforce does not include. In jsforce the proxy is used to call to Salesforce API endpoint, not the external service.
