### ISSUE TITLE
Uncaught Exception: Quoted field not terminated

### ISSUE THREAD

**Issue by mlim1972** [jsforce/jsforce#596]
Recently, I've seen an uncaught exception surfacing when doing Bulk Query.  It seems that csv-parser is reading the stream mid-way in and not finding an end of quote on a field.  The error is not consistent or easily replicateable since it can succeed the next time the same query is issued.  Have anyone else seen this issue?

UncaughtException stack:
```
Sat, 11 Feb 2017 04:45:18 GMT uncaughtException: Quoted field not terminated at line 807775
Error: Quoted field not terminated at line 807775
    at Parser._flush (/home/ubuntu/my-node/node_modules/csv-parse/lib/index.js:185:26)
    at null.<anonymous> (_stream_transform.js:118:12)
    at g (events.js:273:16)
    at emitNone (events.js:80:13)
    at emit (events.js:179:7)
    at prefinish (_stream_writable.js:471:12)
    at finishMaybe (_stream_writable.js:479:7)
    at endWritable (_stream_writable.js:491:3)
    at Writable.end (_stream_writable.js:456:5)
    at PassThrough.onend (/home/ubuntu/my-node/node_modules/readable-stream/lib/_stream_readable.js:504:10)
```
Unfortunately, there is no line number on jsforce code since this is an asynch call.

**Comment by jsec516** [comment]
Facing the same issue. have you found any workaround @mlim1972 ?

**Comment by mlim1972** [comment]
@jsec516, unfortunately, I could not resolve or work around it.  It is happening on and on for me.  The only thing I could do is retry the process again since I can pick up from the last completed data.    I still get this error daily.  I might spend some time at later on and try to create a different transformer for it.

**Comment by cristiand391** [comment]
triaging old issues...

I'm not sure there's much we can do here, the csv parser has an option to skip these errors:
https://csv.js.org/parse/options/skip_records_with_error/

but I don't think it's a good idea to enable it here, even handling the `skip` event in jsforce to surface the failures should make it throw instead of just returning incomplete errors.
