### ISSUE TITLE
XML list parsing issue under LockerService

### ISSUE THREAD

**Issue by jeffhube** [jsforce/jsforce#601]
So now that the Spring 17 release is out with CSP Trusted Sites, I'm looking at trying to use the Metadata API from Lightning (through jsforce-ajax-proxy).

When LockerService is active and I make a call that returns a list of results, such as listMetadata(), I instead get a list that looks like this: [[[[A, B], C], D], E]. It works fine if I disable LockerService, or if there are no more than 2 items being returned.

The issue seems to be with xml2js used by parseXML() in http-api.js.

**Comment by jeffhube** [comment]
I'll do some more investigation later, but after a quick glance this line seems likely to be the cause https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/src/parser.coffee#L61

**Comment by jeffhube** [comment]
I have confirmed that after this change everything works as expected
https://github.com/jeffhube/node-xml2js/commit/8e79dc2935c451bd73e73dd74b37ddd4afacaef7

**Comment by cristiand391** [comment]
triaging old issues...

jsforce v3 still uses xml2js but there's been a few updates since this issue was logged, I'm going to close this but please open a new one (with repro if possible) if it's still happen.
