### ISSUE TITLE
How to get all data using api ?

### ISSUE THREAD

**Issue by nitishxp** [jsforce/jsforce#602]
Like simple_salesforce query_all is there any function which get all data in one go so there will be no need to parse nextresulturl url ?

**Comment by gmillerd** [comment]
Parse? Just don't apply a limit.

https://jsforce.github.io/document/#search

**Comment by cristiand391** [comment]
triaging old issues...

you can pass `autoFetch: true` to `connection.query` so that it paginates over the query results:
https://jsforce.github.io/document/#query
