### ISSUE TITLE
How to fetch all records and save it to another database

### ISSUE THREAD

**Issue by nitishxp** [jsforce/jsforce#603]
var query = conn.query(d)
			.on("record", function(record) {
				count +=1
				var values = [];
				console.log(count)
			records.push(record);
			total = query.totalSize
			console.log(record['Name'])
			var cs = new pgp.helpers.ColumnSet(table[c], {table: c});
			// for (var r in records){
			// 	console.log(r['Name'])
			// }
			// console.log(cs)
			})
			.on("end", function() {
			console.log("total in database : " + query.totalSize);
		    console.log("total fetched : " + query.totalFetched);
		    // res.send(records)
		})
			.on("error", function(err) {
			console.error(err);
			})
			.run({ autoFetch : true, maxFetch : 100000000000000});
    }
I am using this code for passing my query to fetch all records from salesforce but i am confused in which event i should save my data ? i can't save in end because the resultant object can be very large since my salesforce contain more than 20 Millions records ? so what it the efficient way to save the data ?

**Comment by siddharatha** [comment]
why aren't you using a bulk query ?
```
var records = [];
conn.bulk.query('your query')
.on('record',function(record){
records.push(record);
if(records.length===1000){
//fire insert here 
//and flush the list 
records=[];
}
})
.on('error',function(err){})
.on('done',function(){

});

**Comment by cristiand391** [comment]
triaging old issues...

when working with a bunch of objects it's better to use the Bulk API, you can use node streams to handle these efficiently
https://jsforce.github.io/document/#bulk-v2-api
