### ISSUE TITLE
jsforceAjaxProxy always returns 503 for Update and Create commands.

### ISSUE THREAD

**Issue by Ejrnst** [jsforce/jsforce#604]
Hi,

when I try to to update or create a record with jsForce, using my own jsforce-ajax-proxy (hosted on heroku) it always returns 503 (Service Unavailable) after about 30s. Querying Salesforce works like a charm.
If I replace my proxy with "https://node-salesforce-proxy.herokuapp.com/proxy/" everything works fine. But I don't want to depend on a page I cannot control.

Here's the code I use to to include the proxy functionality in my express.js server:

>     app.all("/proxy/?*", jsforceAjaxProxy({ enableCORS: true }));
> 
>     // load tasks
>     app.get("/api/tasks", function (req, res) {
>         // My server dode
>     });

**Comment by cristiand391** [comment]
triaging old issues...

we've been using the ajax proxy in e2e test and haven't seen this, please reopen with a repro if possible if anyone still gets this error.
