### ISSUE TITLE
connection.identity() failing due to strict MIME type checking 

### ISSUE THREAD

**Issue by pixel9** [jsforce/jsforce#611]
First of all, thank you so much for a library that's a pleasure to use! The documentation makes this the nicest option for working with Salesforce that I've seen.

I currently have a React/Electron app that has been working great for half a year and I haven't made any code changes for the past month. Last week I started getting the following error when making an `identity()` call after successfully logging in:

`Refused to execute script from 'https://login.salesforce.com/id/...&callback=_jsforce_jsonpCallback_1' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

followed by:

`JSONP call time out.`

I've been using jsforce 1.7.1 this entire time and have made no code changes recently so I'm suspecting Salesforce has subtly changed some behavior that I'm unaware of. The response from the `identity()` call contains the `X-Content-Type-Options: nosniff` header so the error makes sense. I just don't know if this is new behavior and why it's breaking now. If this is new Salesforce behavior it may be causing unexpected headaches for `jsforce`.

Adding `jsforce-ajax-proxy` and configuring the `proxyUrl` option doesn't seem to remedy this issue since `jsforce` is making direct calls to Salesforce for `identity()`. 

Here's the simplest code snippet that reproduces the error:
```
var conn = new Connection({
  proxyUrl: 'http://localhost:3030/proxy/',
  loginUrl: 'https://login.salesforce.com'
});

conn.login(username, password, function(err) {
  conn.identity(function(err, res) {
    if (err) return console.error(err);
    console.log('never gets here');
  });
});
```
The proxy is identical to the middleware example you've provided here (again, thank you for your wonderful documentation!): https://github.com/jsforce/jsforce-ajax-proxy

I'm out of ideas and I would like to continue using `jsforce` if at all possible. Any assistance is greatly appreciated!

**Comment by pixel9** [comment]
So it looks like this was the breaking change for Electron support: https://github.com/jsforce/jsforce/pull/375

It coincides with the last time my app was working and is consistent with the `identity()` call failing due to a JSONP error. I have verified the call succeeds when JSONP is not used.

Would you consider a change like this to help detect the Electron environment?
https://github.com/Liquidframeworks/jsforce/commit/3932c4743c482383fafd471d31530488a985abbc

**Comment by githubbob42** [comment]
I'm experiencing the same thing too.  In fact, if you click the "Run" button for the "Identity" method on the Docs page (https://jsforce.github.io/document/#identity), it returns the same error:
```
Error: JSONP call time out.
    at https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.7.0/jsforce.min.js:2:5873
```

**Comment by edwinabt** [comment]
I am writing a chrome extension and it returns that error too... Doing a quick search found this post: https://success.salesforce.com/issues_view?id=a1p3A000000et4XQAQ but since I am using the jsforce library I dont see how can I change the dataType.

**Comment by pixel9** [comment]
@edwinabt One way to get around this is to not use JSONP but that requires a change in `jsforce`. I have a branch that disables JSONP support within an Electron environment, but this obviously won't fix the native browser behavior.

It seems using JSONP was a deliberate change to support Visual Force pages (https://github.com/jsforce/jsforce/pull/375). It's unfortunate that it breaks normal usage in a browser environment.

**Comment by edwinabt** [comment]
@pixel9 cool, can you give the link to the branch?

**Comment by pixel9** [comment]
@edwinabt here you go: https://github.com/Liquidframeworks/jsforce/commit/3932c4743c482383fafd471d31530488a985abbc

It's specifically for disabling JSONP in Electron environments so the actual change probably won't help you. At least you'll have a place to start looking!

**Comment by edwinabt** [comment]
@pixel9 appreciate the help.

**Comment by mrjasonroy** [comment]
Any fixes for this? Breaking in the browser for us.

**Comment by aguynamedben** [comment]
+1 this is breaking for me too in Electron. I'm not sure, but it seems like the change made in #375, where XHR is altered to JSONP, is a deviation from jsforce's usual call mechanics. I wasn't expecting jsforce to use JSONP at all.

Maybe jsforce could have an option? Or there could be an option in the .identity() method that lets you toggle XHR or JSONP?

**Comment by aguynamedben** [comment]
I didn't realize at first that the Identity URL services requires an additional scope requested: `id`. See https://help.salesforce.com/articleView?id=remoteaccess_oauth_scopes.htm&type=5. I haven't tested yet though because it's a PITA to change scope for an already deployed Connected App (you have to go through security review, request Push Updates, etc.)

**Comment by aguynamedben** [comment]
I just learned there's a UserInfo endpoint: https://help.salesforce.com/articleView?id=remoteaccess_using_userinfo_endpoint.htm&type=5

Example that works for me: 
```
$ curl 'https://login.salesforce.com/services/oauth2/userinfo?oauth_token=1234...'
```

Props to [this StackOverflow answer](https://salesforce.stackexchange.com/a/104891). I don't think this endpoint is supported in jsforce yet.

**Comment by cristiand391** [comment]
looks like this was fixed here:
https://github.com/jsforce/jsforce/commit/689e8359a0724c41c75b42d802583a1745e3470f

closing this but please reopen if you see this on jsforce v3.

**Comment by demkantor** [comment]
@cristiand391 i am seeing this in jsforce v3 - just for some users which is very strange. we can call conn.identity() if the server is on a localhost but always fails with some users in production server. trying to see what is different about these users but dont have an exact reason why this is happening yet other than the failure is on the identity call
