### ISSUE TITLE
Need to understand how to use JSON as a where clause query

### ISSUE THREAD

**Issue by apasrini** [jsforce/jsforce#612]
Trying to use WHERE clause which would be in JSON format. 

filter = {"where":{"id":"0032800000v6gn8AAA"}}

This when mapped as filter.where -- {"id":"0032800000v6gn8AAA"} JSON. This JSON works.

But when tried with multiple where -- {"where":{"id":"0032800000v6gn8AAA","firstName":"Fname"}}  -- This operation doesnt work.

Can some one point out how to use JSON object as where clause along with usage of AND and OR operators. This is right now not there in the documentation and even in code comments. 

I also want to understand if loopback Where clause support is present with jsforce ?
https://loopback.io/doc/en/lb2/Where-filter.html

**Comment by ishidas** [comment]
I have the same issue.. did you figured it out by any chance?

**Comment by cristiand391** [comment]
triaging old issues....

If I understood the question, conditionals should be passed an array like this:
https://github.com/jsforce/jsforce/issues/1112#issuecomment-2134108857

docs will be updated, if anyone have questions please post in https://github.com/jsforce/jsforce/discussions/categories/q-a
