### ISSUE TITLE
Problem with Tooling query

### ISSUE THREAD

**Issue by nochum** [jsforce/jsforce#614]
I'm able to successfully query the Tooling API with curl:

`curl https://security-playground.my.salesforce.com/services/data/v39.0/tooling/query?q=SELECT%20Score%20FROM%20SecurityHealthCheck -H 'Authorization: Bearer ...'
`

However the following jsforce code fails trying to do the same:

`conn.tooling.query('SELECT Score FROM SecurityHealthCheck', function(err, res) {`
    `if (err) { return console.error(err); }`
    `console.log(res);`
`});`

The stack trace returned is:

`Error: Invalid URI "/services/data/v39.0/tooling/query?q=SELECT%2BScore%2BFROM%2BSecurityHealthCheck"`

        `at Request.init (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/request/request.js:276:31)`
        `at new Request (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/request/request.js:130:8)`
        `at request (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/request/index.js:54:10)`
        `at /Users/nklein/projects/node.js/cross-org-health-check/node_modules/request/index.js:101:12`
        `at createRequest (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/jsforce/lib/transport.js:84:13)`
        `at Promise.promise.then (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/jsforce/lib/transport.js:43:5)`
        `at HttpApi.request (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/jsforce/lib/http-api.js:82:47)`
        `at Connection.request (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/jsforce/lib/connection.js:318:18)`
        `at Tooling.request (/Users/nklein/projects/node.js/cross-org-health-check/node_modules/jsforce/lib/api/tooling.js:83:29)`
        `at /Users/nklein/projects/node.js/cross-org-health-check/node_modules/jsforce/lib/query.js:407:23`

What am I doing wrong?  Accessing the Health Check scores via the Tooling API is available as of the [Summer '16 Release](https://releasenotes.docs.salesforce.com/en-us/summer16/release-notes/rn_security_ps_hcheck_api.htm).

**Comment by vmarasow** [comment]
I'm having the same issue running a query from the CLI 
command: `tooling.query('SELECT Id FROM WorkflowAlert')`
result: `Error: Invalid URI "/services/data/v42.0/tooling/query?q=SELECT%20Id%20FROM%20WorkflowAlert"`

When I paste the URI into the workbench rest explorer I get the expected result.

**Comment by vmarasow** [comment]
Seems like any queries against the tooling api are failing with the above message

**Comment by cristiand391** [comment]
triaging old issues...

this error is very likely because the connection object is missing the instance url.
https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/request.js#L261

https://jsforce.github.io/document/#connection
