### ISSUE TITLE
Error: "toString()" failed during downloading large files (>256MB)

### ISSUE THREAD

**Issue by hysh** [jsforce/jsforce#615]
I tried to download a file with the following.

```
 let fileOut = fs.createWriteStream('FILENAME');
 conn.sobject('ContentVersion').record(RecordId).blob('VersionData').pipe(fileOut)
```

The code does not work if the files is larger thand 256MB and raised this Error.
Do we have a quick workaround for this issue?

```
Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Request.<anonymous> (/home/node_modules/request/request.js:1147:39)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
The error is comming from request trying to do toString() for a large Buffer.
https://github.com/request/request/blob/master/request.js#L1137

The restriction is comming from kMaxLength upper limit for a buffer.
https://github.com/nodejs/node/pull/4394

Looking at the following post in request, if callback is passed, request tries to return the body.

https://github.com/request/request/issues/2270#issuecomment-234407653
> request will try to save all response data in the memory.
> so, when pipe large files, just do not supply the callback parameter will resolve this

I guess jsforce is passing callbacks in Transport.prototype.httpRequest around here.
https://github.com/jsforce/jsforce/blob/master/lib/transport.js#L84

**Comment by dev-usa** [comment]
So, after spending couple of hours trying to resolve this issue and reading through possible solutions suggested at https://stackoverflow.com/a/43493057/829542 and trying few csv parsers which did not help in resolution.. I finally took a look at what was going on in jsForce's bulk.js and tried calling the SFDC Bulk API REST interface directly...  and this has resolved my issue. For anyone else, trying the jsForce bulk api to download the results as a file and failing... below is the working code I used to resolve this.

Using the connection object as "conn" 

    var baseUrl = [ conn.instanceUrl, "services/async", conn.version ].join('/');
    let requestPath = "/job/" + jobId + "/batch/" + batchId + "/result/" + retrievedBatchResultId;
    let requestUrl = baseUrl + requestPath;
    var options = {
    				url: requestUrl,
    				headers: {
    				"X-SFDC-SESSION" : conn.accessToken,
    				"responseType" : "application/octet-stream"
    				}
    			};
    let writeableStream = fs.createWriteStream('./result'+'-'+retrievedBatchResultId+'.csv');
    require('request')(options).pipe(writeableStream);

Thanks.

**Comment by vtomenko** [comment]
Such a cool library, yet this issue prevents from messing with batch/job/result ids manually...
Would be really nice to fix it.
Many thanks to @hysh for investigation and @dev-usa for the workaround.

**Comment by cristiand391** [comment]
triaging old issues...

jsforce v2 moved from `request` to `node-fetch`, is anyone able to repro this error on latest jsforce?
