### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by bvellacott** [jsforce/jsforce#616]
Hi guys

I've been experiencing problems with the bulk api using jsforce. It's an encoding issue. I'm pushing data from a salesforce web page. Encoding on the salesforce instance is UTF-8 as it is on the page (checked with desgribeGlobal() and document.charset). Basically the pound signs in a text field are converted to Â£'s.

Reproducing the error:

Create an object called TestObj__c, add a field to it called ShortTextField__c and give it a length of 10. Then use jsforce to execute the following (in a UTF-8 encoded salesforce page). 

```
var data = "Name,extid__c,ShortTextField__c\nsome name,extid_1,££££££££££";

var conn = new jsforce.Connection({ accessToken: '{!$API.Session_Id}' });
var job = conn.bulk.createJob('TestObj__c', 'upsert', { extIdField: 'extid__c' });

job.open()
.then(jobInfo => {
  return new Promise((resolve, reject) => {
    var batch = job.createBatch();
    batch.on('queue', info => {
      console.log(info);
      batch.poll(1000, 200000);
    })
    .on('response', resolve)
    .on('error', reject);

    batch.execute(data);
  });
})
.then(res => {
  console.info(res);
  job.close();
})
.catch(err => {
  console.error(err);
  job.close();
});

```

You should get an error in the errors array saying 
`"STRING_TOO_LONG:ShortTextField: data value too large: Â£Â£Â£Â£Â£Â£Â£Â£Â£Â£ (max length=10):ShortTextField__c --"`

Cheers

**Comment by bvellacott** [comment]
... looking at the request payload it is leaving the browser looking like this: `Name,extid__c,ShortTextField__c
some name,extid_1,Â£Â£Â£Â£Â£Â£Â£Â£Â£Â£` which must mean the 'bug' is either in how I'm using the library or in the library itself.

**Comment by bvellacott** [comment]
... ok so changing line 469 in bulk.js
`this._dataStream.write(data, 'utf8');` to `this._dataStream.write(data, 'ascii');` fixes the example scenario. I'm not sure if this is a bug or expected. I would have expected that the stream encodes the string into utf8 and sends it over with the content type 'utf-8' and then the receiver knows to handle the data as utf8. This suggests all has to go through as ascii??

**Comment by klercker** [comment]
We are experiencing similar issues, fortunately not in any critical code path.

**Comment by exiahuang** [comment]
I have a same bug about Bulk API.
I ran the code and I got the accounts as below.
 `Account #1`
`ãã¹ã #2`
`ä¸­æ#3`

How can I fix the bug ?

```
// Provide records
var accounts = [
  { Name : 'Account #1' },
  { Name : 'テスト日本語#2' },
  { Name : '中文#3' },
];
// Create job and batch
var job = conn.bulk.createJob("Account", "insert");
var batch = job.createBatch();
// start job
batch.execute(accounts);
// listen for events
batch.on("error", function(batchInfo) { // fired when batch request is queued in server.
  console.log('Error, batchInfo:', batchInfo);
});
batch.on("queue", function(batchInfo) { // fired when batch request is queued in server.
  console.log('queue, batchInfo:', batchInfo);
  batch.poll(1000 /* interval(ms) */, 20000 /* timeout(ms) */); // start polling - Do not poll until the batch has started
});
batch.on("response", function(rets) { // fired when batch finished and result retrieved
  for (var i=0; i < rets.length; i++) {
    if (rets[i].success) {
      console.log("#" + (i+1) + " loaded successfully, id = " + rets[i].id);
    } else {
      console.log("#" + (i+1) + " error occurred, message = " + rets[i].errors.join(', '));
    }
  }
  // ...
});
```

**Comment by bvellacott** [comment]
@exiahuang Have you tried editing the code like I suggested? I would be interested to know if it fixes the issue for you? That would suggest a bug in the library. If that's the case then I can submit a change request for the fix.

**Comment by fengjw6** [comment]
> I have a same bug about Bulk API.
> I ran the code and I got the accounts as below.
> `Account #1`
> `ã��ã�¹ã�� #2`
> `ä¸­æ��#3`
> 
> How can I fix the bug ?
> 
> ```
> // Provide records
> var accounts = [
>   { Name : 'Account #1' },
>   { Name : 'テスト日本語#2' },
>   { Name : '中文#3' },
> ];
> // Create job and batch
> var job = conn.bulk.createJob("Account", "insert");
> var batch = job.createBatch();
> // start job
> batch.execute(accounts);
> // listen for events
> batch.on("error", function(batchInfo) { // fired when batch request is queued in server.
>   console.log('Error, batchInfo:', batchInfo);
> });
> batch.on("queue", function(batchInfo) { // fired when batch request is queued in server.
>   console.log('queue, batchInfo:', batchInfo);
>   batch.poll(1000 /* interval(ms) */, 20000 /* timeout(ms) */); // start polling - Do not poll until the batch has started
> });
> batch.on("response", function(rets) { // fired when batch finished and result retrieved
>   for (var i=0; i < rets.length; i++) {
>     if (rets[i].success) {
>       console.log("#" + (i+1) + " loaded successfully, id = " + rets[i].id);
>     } else {
>       console.log("#" + (i+1) + " error occurred, message = " + rets[i].errors.join(', '));
>     }
>   }
>   // ...
> });
> ```

I have the same issue with Japanese characters in this way (records uploading instead of csv).
But if I use `require('fs').createReadStream()` to upload it is working. (but I can't use this mode in web page)
Can anyone help?

**Comment by bvellacott** [comment]
@fengjw6 

The original issue is an encoding issue between `utf8` and `ascii`. 

Also, if you want to use streams in the browser you'll need to use a bundler like browserify, webpack, gulp, grunt or broccoli to bundle your javascript and import a browser stream library like stream, blob-stream or other using npm.

**Comment by fengjw6** [comment]
@bvellacott 
thanks for reply!

I tried with ascii but it is not working for Japanese characters.

**Comment by bvellacott** [comment]
I think your solution is to try and make sure all encoding is in utf8 at every stage.
