### ISSUE TITLE
Callback is not being called for setPassword

### ISSUE THREAD

**Issue by kurunve** [jsforce/jsforce#617]
Hello everyone

Recently  I found one interesting behaviour of setPassword function -- callback is not being called at all.
Documentation says next [here](http://jsforce.github.io/jsforce/doc/SoapApi.html):
`setPassword(userId, password, callbackopt) → {Promise.<String>}`

Steps to reproduce:
```
var jsforce = require('jsforce');
var conn = new jsforce.Connection({loginUrl:'https://login.salesforce.com'});
conn.login('mylogin@example.com','mypwd',function(err) { if (err) { console.log('ERROR: ' + err); } } );
// next line does not show anything in the console
conn.soap.setPassword('userid','mynewpwd',function(res){console.log('DONE:' + res);});
```

**Comment by jeffprinty** [comment]
I'm having this same problem, did you figure out a solution?

**Comment by engPabloMartinez** [comment]
Hi did you figure out a solution? I'm having the same problem.

**Comment by stomita** [comment]
It seems not working currently. Use promise instead.
```javascript
conn.soap.setPassword(userId, newPwd).then(function() {
  // ...
}).catch(function() {
  // ...
});
```

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
