### ISSUE TITLE
.toString() Error Piping to CSV for Large Queries

### ISSUE THREAD

**Issue by Rob-ModernAnalytics** [jsforce/jsforce#620]
I've read older threads about this issue and thought that it had been resolved.  I am receiving this error when piping data to a CSV.  It only happens to me when writing more than a million records but I'm not sure if it has to do with the number of columns selected as well.  For smaller query results everything seems fine.

Please inform.

Thanks,

Rob

**Comment by Rob-ModernAnalytics** [comment]
I forgot to mention that I am using the SalesForce conn.bulk.query operation.

Does anyone have any information on this?  My project is falling behind with no option at this point.  Yikes!

**Comment by dev-usa** [comment]
Faced something similar.Please see https://github.com/jsforce/jsforce/issues/615#issuecomment-304396624

**Comment by cristiand391** [comment]
closing this in favor of #615
