### ISSUE TITLE
bulk api authorization with cloudforce.com domain (trialforce org)

### ISSUE THREAD

**Issue by dccatl** [jsforce/jsforce#622]
We have an integration that uses jsForce and the Bulk API to import some custom object records into our subscribers' orgs.  The import works fine if the org was not installed via trialforce (does not have a *.cloudforce.com instance) but if using a trialforce org with the domain mycompany-1717.cloudforce.com the bulk api fails with an HTTP 411 error and the cryptic message: "We are down for maintenance."

my jsForce connection consructor is:

`
var conn = new jsforce.Connection({
     instanceUrl: data.instance_url,
     accessToken: data.access_token
});
`

where data.instance_url and data.access_token are retrieved from an upstream oAuth login.

If I replace the instanceUrl with the hardcoded SF instance obtained from the trust.salesforce.com My Domain look up tool (in this case 'https://na35.salesforce.com/') then the bulk data load works as expected.

Is there an issue with bulk API and cloudforce.com domains or am I missing something in my jsForce code.

Thanks in advance,
David

**Comment by cristiand391** [comment]
triaging old issues...

you should always use the "my domain" URL when establishing a connection to your org.
