### ISSUE TITLE
Ionic 2: Error during WebSocket handshake: Unexpected response code: 302

### ISSUE THREAD

**Issue by 32xnabin** [jsforce/jsforce#624]
I am simply trying to subscribe a topic from salesforce in my ionic2 app it even allows rest api call but gives an error while subscribing topic:

 Error during WebSocket handshake: Unexpected response code: 405
here is the full code:

import { Component } from '@angular/core';

import { NavController, Platform} from 'ionic-angular';

import * as jsforce from "jsforce";

declare var window: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private platform: Platform) {

    
    var conn = new jsforce.Connection({

         loginUrl : 'https://login.salesforce.com'
      });

      var username ='XXXXXXXXXXX';
      var password ='XXXXXXXXXXXXXXXXX';

      conn.login(username, password, function(err, userInfo) {
        if (err) { return console.error(err); }

            console.log(conn.accessToken);
            console.log(conn.instanceUrl);

           //this part of code works
            conn.query("SELECT Id, Name FROM Account", function(err, result) {
              if (err) { return console.error(err); }
              console.log("total : " + result.totalSize);
              console.log("fetched : " + result.records.length);
            });

           // this part of codes doesn't work
            conn.streaming.topic("InvoiceStatementUpdates").subscribe(function(message) {
              console.log('Event Type : ' + message.event.type);
              console.log('Event Created : ' + message.event.createdDate);
              console.log('Object Id : ' + message.sobject.Id);
            });

            // logged in user property
            console.log("User ID: " + userInfo.id);
            console.log("Org ID: " + userInfo.organizationId);

      });

  

  }

 

}

**Comment by cristiand391** [comment]
triaging old issues...

302 and 405 are for different scenarios, please re-open if can repro on latest jsforce
