### ISSUE TITLE
HTTPS_PROXY support

### ISSUE THREAD

**Issue by tnoonan-salesforce** [jsforce/jsforce#626]
@stomita I see support for setting the HTTP_PROXY environment variable and having it honored by jsforce. However, I'm not seeing support for HTTPS_PROXY. 

Are there technical reasons for this not being supported? Is it just time/resources?

**Comment by tnoonan-salesforce** [comment]
@stomita Poke.

**Comment by stomita** [comment]
HTTP_PROXY can be used for SSL, too.

**Comment by tnoonan-salesforce** [comment]
If HTTPS_PROXY points to a different url than HTTP_PROXY would't that be an issue? We understand that the underlying "request" library that JSforce uses allows them both to be set. So why does JSForce even need to do anything with those env variables?

https://github.com/request/request#proxies

**Comment by stomita** [comment]
As the SF endpoint is always being SSL, why u need distinguish the http/https ?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
