### ISSUE TITLE
batch api authorization error

### ISSUE THREAD

**Issue by rdietrick** [jsforce/jsforce#63]
Hi,

I'm able to use the metadata API without any problems from a VisualForce page.  When I try to use the batch API (in the same page), however, I get the following error:
XMLHttpRequest cannot load https://na15.salesforce.com/services/async/30.0/job. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://c.na15.visual.force.com' is therefore not allowed access.

It seems the batch endpoint is in a different domain than the one I'm authenticating on (and using for the metadata API calls).  Has anyone else experienced this?  Is there a workaround?

JSForce is pretty awesome, btw.

**Comment by sureshshamanth** [comment]
Well, this didn't really work for me, still getting the same error
