### ISSUE TITLE
Need a way to control JSForce Bulk API batch size

### ISSUE THREAD

**Issue by achinni** [jsforce/jsforce#634]
Currently the batch size of the **Bulk API** is **1 record per batch**.
Need a way to specify/control the batch size limit if we are using Bulk API.
Having this option would be helpful when we're dealing with large sets.

**Comment by paustint** [comment]
Are you sure you are calling the API correctly and not using the SObject rows API, which does call 1 per record? I am not seeing 1 record per batch, but am able to get up to 10K records per batch. Reviewing the SFDC native API docs, there is no option to control a "batch size" and it is just based on however many records you include in the batch.

From docs:
```
var job = conn.bulk.createJob("Account", "insert");
var batch = job.createBatch();

batch.execute(accounts);
batch.on("queue", function(batchInfo) { // fired when batch request is queued in server.
  batchId = batchInfo.id);
  jobId = batchInfo.jobId);
  // ...
});
```

Aside from PKChunking, I don't think there are any other unimplemented features for the Bulk API request.  Chunking just sets the number of records that are chunked together (e.x. how many will be sent to a trigger at the same time) - this defaults to 200.

**Comment by achinni** [comment]
Thanks for the info.
You're right. It is creating one batch, and the default batch size is not 1.
Since you said that we can't control batch size, I assume we have to do the chunking in our application while building the data set.
This is what we're using:
```
conn.bulk.load("Lead", "insert", cleanLeads_jso, function(err, rets) {
  if (err) {
     return console.error(err);
  }
  for (var i=0; i < rets.length; i++) {
    if (rets[i].success) {
      console.log("#" + (i+1) + " loaded successfully, id = " + rets[i].id);
    } else {
      console.log("#" + (i+1) + " error occurred, message = " + rets[i].errors.join(', '));
    }
  }
}
```
