### ISSUE TITLE
Promises based API 

### ISSUE THREAD

**Issue by fxfactorial** [jsforce/jsforce#639]
Can you provide a Promises API. 

End users like me are wrapping the cbs in Promises, but might as well have the lib provide that

**Comment by paustint** [comment]
Take a look at the API docs, you will notice most functions do indeed
return promises as well as calling the callback function, so you could use
either.

https://jsforce.github.io/jsforce/doc/Connection.html#query

**Comment by fxfactorial** [comment]
@paustint nice, thanks!
