### ISSUE TITLE
How to retrieve XML file or package using JSforce?

### ISSUE THREAD

**Issue by TonyRenHK** [jsforce/jsforce#644]
How to retrieve XML file or package using JSforce?
I want to input as Json format like this:

var metadata = [{
  fullName: 'TestObject1__c',
  label: 'Test Object 1',
  pluralLabel: 'Test Object 1',
  nameField: {
    type: 'Text',
    label: 'Test Object Name'
  },
  deploymentStatus: 'Deployed',
  sharingModel: 'ReadWrite'
}, {
  fullName: 'TestObject2__c',
  label: 'Test Object 2',
  pluralLabel: 'Test Object 2',
  nameField: {
    type: 'AutoNumber',
    label: 'Test Object #'
  },
  deploymentStatus: 'InDevelopment',
  sharingModel: 'Private'
}];

and output as XML format or package, any idea?

**Comment by siddharatha** [comment]
If you want to work on package and deploy features you should use the metadata tools provided by jsforce.
https://github.com/jsforce/jsforce-metadata-tools

**Comment by cristiand391** [comment]
triaging old issues...

checkout :https://jsforce.github.io/document/#retrieve-deploy-metadata-file-based-

https://github.com/jsforce/jsforce/blob/af8a10e84557d95e20a62dae37e9dbf1e4d50fa8/src/api/metadata.ts#L320
