### ISSUE TITLE
NodeJS crashed

### ISSUE THREAD

**Issue by dieffrei** [jsforce/jsforce#648]
All my nodejs scripts using JSFORCE, stopped to login in to salesforce sandbox.
It has been started tomorrow.

Error: INVALID_LOGIN:
node_modules/jsforce/lib/connection.js:1071:13
I tried a lot of times to reset user and security key but the errors

**Comment by cristiand391** [comment]
triaging old issues....

if anyone get this error please open a new issue with a code example.
