### ISSUE TITLE
Support for Deploy Recent Validation

### ISSUE THREAD

**Issue by AWillForAWay** [jsforce/jsforce#650]
Would love to know if there are plans to support deployRecentValidation as mentioned here: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deployRecentValidation.htm

Doing two deployments, one for validation and one to do the actual deployment of files, works but is not ideal. Unless I completely missed where it has already been added.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
