### ISSUE TITLE
How to get 'CustomObjectTranslation' metadata using jsforce?

### ISSUE THREAD

**Issue by TonyRenHK** [jsforce/jsforce#652]
Hi,

How to get 'CustomObjectTranslation' metadata using jsforce? do you have some example?

Thanks

**Comment by vpetrovych** [comment]
Something like this:
```
conn.metadata.read('CustomObjectTranslation', ['Account-en_US'], function(err, translations) {
	if (err) { return console.log(err); }
	console.log(translations);
});
```

**Comment by vlamic** [comment]
@vpetrovych this seem to fail for objects installed with a package. See #853. Any recommendations?

**Comment by cristiand391** [comment]
closing as dup of #853
