### ISSUE TITLE
Custom Objects Layout Support?

### ISSUE THREAD

**Issue by orcaman** [jsforce/jsforce#653]
Hey guys,

I'm using jsforce to clone custom objects. My method is basically retrieving the source object's metadata, changing it's name all across, and then creating a new custom object with the changed metadata. 

This works quite well except that the layout from the source object isn't created on the target object. I checked out the metadata response and it seems that it doesn't contain any reference to the object's page layouts. 

Is page layout supported by jsforce?

Thanks

**Comment by paustint** [comment]
How are you getting the source data? (What API)

You will likely need to use the metadata API using the Layout type as
references here: -
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_layouts.htm

**Comment by orcaman** [comment]
@paustint Thanks. The thing is, I'm not getting anything related to layouts when asking for *all* of an objects metadata. My code looks roughly like so:

```javascript
    conn.metadata.read('CustomObject', objName, function (err, meta) {
...
...
```

The response object (`meta`) doesn't contain any mention of layouts. Any idea?

**Comment by idanblich** [comment]
@orcaman 
you can use the layout rest api : 
`../services/data/v39.0/sobjects/{sObject}/describe/layouts`
see : [https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_layouts.htm](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_layouts.htm)

**Comment by orcaman** [comment]
@idanblich Thanks. I know that it's possible using SF API, my question is regarding page layout metadata support on jsforce.

**Comment by paustint** [comment]
I had the same problem with metadta API's - some API's say the version is optional, but it is only option if you specified the version in the connection object initially (I think).  Here are some examples from my application and I have had consistent results returned **(Note: These examples are in Typescript)**

You can start with the `list` call to get a list of all metadata.

```javascript
export function getMetadata(conn, type, fullNames) {
  fullNames = Array.isArray ? fullNames : [fullNames];
  return new Promise((resolve, reject) => {
    conn.metadata.read(type, fullNames, (err, metadata) => {
      if (err) { return reject(err); }
      resolve(metadata);
    });
  });
}
```

```javascript
// Here is the shape of the "queries" variable in the next example.
interface ListMetadataQuery {
  type: string,
  folder?: string;
}

export function listMetadata(conn, types: string | string[], version: string = '39.0') {
  return new Promise((resolve, reject) => {
    let typesArr: string[] = <string[]>(_.isArray(types) ? types : [types]);
    const queries: ListMetadataQuery[] = typesArr.map(type => {return {type: type}});
    conn.metadata.list(queries, version, (err, fileProperties: FileProperties) => {
      if (err) { return reject(err); }
      resolve(fileProperties);
    });
  });
}
```

```javascript
interface DescribeMetadataResult {
  metadataObjects: [{childXmlNames: string[], directoryName: string, inFolder: boolean, metaFile: boolean, suffix: string, xmlName: string}];
  organizationNamespace: string;
  partialSaveAllowed: boolean;
  testRequired: boolean;
}

/**
 * Get metadata for any type
 * 
 * @param {any} type
 * @param {any} apiNames
 * @returns
 */
export function describeMetadata(conn, version: string = '37.0') {
  return new Promise((resolve, reject) => {
    conn.metadata.describe(version, (err, metadataResults: DescribeMetadataResult) => {
      if (err) { return reject(err); }
      resolve(metadataResults);
    });
  });
}
```

```javascript
export function readMetadata(conn, metadataType: string, fullNames: string | string[]) {
  return new Promise((resolve, reject) => {
    conn.lo
    conn.metadata.read(metadataType, fullNames, (err, metadataResults) => {
      if (err) { return reject(err); }
      resolve(Array.isArray(metadataResults) ? metadataResults : [metadataResults]);
    });
  });
}

export function retrieveMetadata(conn, options: any) {
  return new Promise((resolve, reject) => {
    conn.metadata.retrieve(options, (err, retrieveResult) => {
      if (err) { return reject(err); }
      resolve(retrieveResult);
    });
  });
}

export function checkRetrieveStatus(conn, id: string) {
  return new Promise((resolve, reject) => {
    conn.metadata.checkRetrieveStatus(id, (err, retrieveResult) => {
      if (err) { return reject(err); }
      resolve(retrieveResult);
    });
  });
}
```
