### ISSUE TITLE
updateBulk not updating

### ISSUE THREAD

**Issue by ishantiw** [jsforce/jsforce#654]
I'm using below format to update bulk records, but I'm not getting any results and also no update in salesforce. Is it the right syntax for bulk update operation?
```
 conn.sobject('Performance_Data__c').updateBulk(rec, extId, (err, rets) => {
      if (err) {
        return console.error(err)
      }
```

**Comment by paustint** [comment]
I also had issues with the examples as well, I was able to get it working like this:

```javascript
export function bulkDelete(conn, sobject, records) {
  return new Promise((resolve, reject) => {
    var job = conn.bulk.createJob(sobject, 'delete');
    var batch = job.createBatch();
    batch.execute(records);
    batch.on("error", function(err) {
      reject(err);
    });
    batch.on("queue", function(batchInfo) {
      batch.poll(1000 /* interval(ms) */, 120000 /* timeout(ms) */) // start polling
      batch.on("response", function(results) {
        resolve({results, batchInfo});
      })
    });

  });
}
```

**Comment by ishantiw** [comment]
@paustint Thanks, I tested this and it is working. I think the syntax which I'm using doesn't support update.

**Comment by lms15** [comment]
Ok, thank you for your help I had a family member hospitalized and it got me off track

**Comment by lms15** [comment]
Hello everyone, I want to apologize I am not igoring you. There was a family emergency and I ended up baby sitting becaue the kinds cannot atten day care. The pink eye which they caught it there. A big problem for me. I have a 8 month old and a two year old. hopefully I can continue next week. I cannot focus with the babies. They are my great grands so I have to help them. i hope all is forgiven under the circumstance. See I have to go. the babie 
Mamie
