### ISSUE TITLE
Is there a way to fetch the contact image(PhotoURL) from the salesforce Org and convert to base24 format? 

### ISSUE THREAD

**Issue by ChandanShankar** [jsforce/jsforce#655]
Can anyone help me solving this, I'm trying to fetch contact image from the salesforce DB and how can i download and convert it to base24 format..?
```
var queryString = "Select PhotoUrl from Contact where Id = '" contactid + "'";
	return conn.query (queryString)
	.then (function(resultSet) {
		var cont_act = resultSet.records;
               return conn.chatter.resource(cont_act[0].PhotoUrl).retrieve();
	}) .then(function(result){
          //return some encrypted data how do I decrypt this
      })
```

**Comment by shershen08** [comment]
I've been struggling with a similar problem.
```
conn.chatter.resource('/services/images/photo/003o0000XXXXX')
  .retrieve(function(err, response) {
    console.log(response);
    //outputs some binary data like 
    //�PNG
    //IHDR-:��sRGB����IDATX
    //...
});
```
I've tried to read it as a Buffer but it didn't work

**Comment by ChandanShankar** [comment]
@shershen08, Please let me know if you solve this problem/issue.

**Comment by shershen08** [comment]
@ChandanShankar in my case it was solved in the Sf DB side by adding proper field that contained normal string witb absolute image url link

**Comment by ChandanShankar** [comment]
@shershen08, Created a fieldname photourl on contact and tried accessing it on SOQL.

```
queryString = "select vfs__PhotoUrl__c from Contact where Id = '" + contactid + "'";
	return conn.query (queryString)
	.then (function(resultSet) {
		var cont_act = resultSet.records;
		debugger;
		photoUrl = cont_act[0].PhotoUrl;
		//return = s_box.url +""+photoUrl;
		return conn.chatter.resource(cont_act[0].vfs__PhotoUrl__c).retrieve();
        }) 
```

Even after this i'm getting the same output. can you please share your code.

**Comment by siddharatha** [comment]
The photo url will only contain the url ,you have to use the request module to make a call and get the image .

https://github.com/siddharatha/downloadUserPictures
Might help

**Comment by ChandanShankar** [comment]
@siddharatha  Thank you, it worked.

**Comment by ChandanShankar** [comment]
@siddharatha is there a way to upload/update contact profile image?
