### ISSUE TITLE
Is there a way to upload/update profile photo on contact/Account photoUrl field?

### ISSUE THREAD

**Issue by ChandanShankar** [jsforce/jsforce#657]
I'm trying to Update/Upload Image on contact (using PhotoUrl field), I don't find away to upload the Contact/Account profile pic. Can anyone please help me solving this?

**Comment by Smadger1** [comment]
Did you find any solution to this @ChandanShankar

**Comment by cristiand391** [comment]
triaging old issues...

the `PhotoUrl` field is expected to be an URL, not a blob.
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_account.htm
