### ISSUE TITLE
Expose status code as part of the error object

### ISSUE THREAD

**Issue by ccnixon** [jsforce/jsforce#658]
Thanks so much for your excellent work. I was wondering if there was a way to pass the statusCode from the http response as part of the returned error object. Likely an additional property added here:

https://github.com/jsforce/jsforce/blob/master/lib/http-api.js#L251

Is it possible to access this currently?

Thanks!

**Comment by cristiand391** [comment]
https://github.com/jsforce/jsforce/issues/490#issuecomment-2127711394
