### ISSUE TITLE
warning: possible EventEmitter memory leak detected. 11 value listeners added.

### ISSUE THREAD

**Issue by svanweelden** [jsforce/jsforce#661]
When I start my Node app, I see this warning seeming to come from JSForce

![image](https://user-images.githubusercontent.com/21185458/28081049-ce718bc2-6622-11e7-8b4e-dfa67059324a.png)

**Comment by jasonrhodes** [comment]
This has been an oft-reported issue and we've seen it in our code for a very long time, despite doing all of the things recommended in other issues.

See: #247 and #356 for example

We've tried limiting our authenticate calls and memoizing certain parts of the flow, but still see this error in our logs regularly.

**Comment by svanweelden** [comment]
@jasonrhodes I'm not sure if it'll help, but this is a pretty recent thing that just started showing up when adding more to my project. I wonder if you get to a certain point/size/complexity and then it starts showing up.

It seems like if I were to do some state management of login status upon inititalization, or only log in and log out on each actual call I need, I might be better off. I'll try that.

**Comment by cristiand391** [comment]
triaing old issues...

closing this in favor of https://github.com/jsforce/jsforce/issues/356
