### ISSUE TITLE
Question: How would I specify parent record external field for lookups when I insert child

### ISSUE THREAD

**Issue by srajagopalan1712** [jsforce/jsforce#673]
If I want to insert a child record and there is a lookup relationship it has with a parent. Assume parent has an external id which can be used for upsert. In the example in tutorial I see that to upsert a record you use one external field. In my case I need to insert child and use parent's external id to fill in parent info

Tutorial example: 
conn.sobject("UpsertTable__c").upsert({ 
  Name : 'Record #1',
  ExtId__c : 'ID-0000001'
}, 'ExtId__c', function(err, ret) {

In my case I am wondering what the format would be to pass in 2 external id fields? In data loader we have 2 steps where we pick both ext ids.

conn.sobject("child__c").upsert({ 
  Name : 'Record #1',
  ExtId__c : 'ID-0000001'
}, 'ExtId__c', parent_extid__c?? function(err, ret) { --> I am looking to see if something like this is possible?

**Comment by srajagopalan1712** [comment]
@stomita please see if you can help here

**Comment by ArcusSimonCull** [comment]
You'll want to look at the [Composite API](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite.htm). Construct a JSON composite POST then use [conn.requestPost()](https://github.com/jsforce/jsforce/issues/417#issuecomment-305314674) to insert/update the objects

**Comment by dogenzenji8** [comment]
Ever find a solution for this @srajagopalan1712?

**Comment by srajagopalan1712** [comment]
I did! And built and entire integration to move data over using this. Here is an example

```
conn.sobject("child__c").upsert({
  Name : 'Record #1',
  ExtId__c : 'ID-0000001',
  parentRelationshipName__r: {type: 'parentObjName__c', parentExtIdValue: 'xxxxxx'}
}, function(err, ret) { 
```

Hope this helps. You can find parent relationship name when you describe the child object.

**Comment by JyotsnaShinde** [comment]
@srajagopalan1712  I am also looking for same solution. I tried your solution mentioned above. 

But it is giving me error 'Provided external ID field does not exist or is not accessible'. I think this error is because for upsert function after record parameter there is no 'external_id' field parameter present.
Below is my code:

res.then((value) => {
            console.log("connection established: ",value);
            conn.sobject("Contact").upsert({
                LastName: 'GaryTeng',
                ExternalId__c: '21',
                Account: {type:'Account',ExternalId__c: '1'}
            }).then((value1) => {
                console.log("upsert result with parent child: ", value1);
            }).catch(function (error) {
                console.log("error is: ",error);
                throw error
            });
        }).catch(function (error) {
            throw error
        });

Could you please help me here?
