### ISSUE TITLE
Getting SalesForce Profile for Current User

### ISSUE THREAD

**Issue by Rob-ModernAnalytics** [jsforce/jsforce#674]
Hi,

Is there a way to get the user profile assigned to the current user logged into the connection object?  I'm actually trying to add custom field permissions for a custom field I'm adding with metaData.create('CustomField', 'Lead.My_Score__c').  I would just like to make the custom field visible in the API so I can access it further.  My thought was to get the user profile and add a Field Level Security entry for this field in the Lead object.  Does anyone know if this is possible with JSForce?

Thanks,

Rob

**Comment by Rob-ModernAnalytics** [comment]
I figured it all out.  Thanks!

**Comment by JamesMarino** [comment]
Hi @Rob-ModernAnalytics, What did you end up doing to get the user profile assigned to the current user logged into the connection object?

Thanks,
James

**Comment by Rob-ModernAnalytics** [comment]
James,

Sorry for the promise chain - I haven't re-written this in async/await yet.  Let me know if you have any questions.

Rob

module.exports.CreateCustomField = function (clientID, clientSecret, redirectUri, instanceUrl, accessToken, refreshToken, objectName, fieldName, type, length, precision, scale, label) {
	return new Promise( (resolve, reject) => {
		try {
			var connection = getConnection(clientID, clientSecret, redirectUri, instanceUrl, accessToken, refreshToken);

			var metaData = {
				fullName: objectName + '.' + fieldName,
				label: label,
			};

			if (type != null) {
				metaData.type = type;
			}
			if (length != null) {
				metaData.length = length;
			}
			if (precision != null) {
				metaData.precision = precision;
			}
			if (scale != null) {
				metaData.scale = scale;
			}

			$scope = {};

			connection.metadata.create('CustomField', metaData)
				.then( result => {
					if (result.success == false) {
						console.log('error message', result.errors.message);
						throw new Error(result.errors.message);
					}
					else {
						return connection.identity();
					}
				})
				.then( identity => {
					var query = "select ProfileId from User where id = '" + identity.user_id + "'";
					return executeQuery(connection, query);
				})
				.then( result => {
					var profileId = result.records[0].ProfileId;
					console.log('profileId', profileId);
					$scope.profileId = profileId;
					return connection.metadata.list([{type: 'Profile', folder: null}], connection.version);
				})
				.then( profiles => {
					console.log('Profiles', profiles);
					var userProfile = profiles.find( profile => { return profile.id == $scope.profileId } );
					console.log('userProfile', userProfile);
					return connection.metadata.read('Profile', [userProfile.fullName]);
				})
				.then( profile => {
					$scope.profile = profile;
					var fieldPermissions = profile.fieldPermissions;
					var customFieldPermissions = fieldPermissions.find( fieldPermission => { return fieldPermission.field.toLowerCase() == (objectName + '.' + fieldName).toLowerCase() } );
					console.log('field Permissions', customFieldPermissions);
					return new Promise( (resolve, reject) => { return resolve(customFieldPermissions) } );
				})
				.then( customFieldPermissions => {
					if (customFieldPermissions.readable.toLowerCase() == 'true') {
						console.log('permissions already set - skipping update');
						return new Promise( (resolve, reject) => { return resolve(true) } );
					}
					else {
						console.log('updating custom field permissions in profile');
						customFieldPermissions.readable = true;
						return connection.metadata.update('Profile', $scope.profile);
					}
				})
				.then( () => {
					return resolve(true);
				})
				.catch( err => {
					console.log(new Date().toLocaleString(), 'salesForce.CreateCustomField error', err);
					return reject(err);
				})
			;
		}
		catch (err)
		{
			console.log(new Date().toLocaleString(), 'salesForce.CreateCustomField error', err);
			return reject(err);
		}
	});
}

**Comment by JamesMarino** [comment]
Thanks for the help @Rob-ModernAnalytics, the below code example worked a treat when connecting using an OAuth2 Access Token

```javascript
const connection = new JSForce.Connection({
    instanceUrl,
    accessToken,
});

const currentUser = await connection.identity();
```

**Comment by DrewMurr2** [comment]
@Rob-ModernAnalytics Thank you for your service. That code above I had a massive impact on my project.

**Comment by Rob-ModernAnalytics** [comment]
Thank you for the kind words.  A rewrite using async/await would significantly simplify the code.

Good luck with your eadeavors.

**Comment by danielmhanover** [comment]
@Rob-ModernAnalytics this was incredibly helpful!

A simpler version for anyone else who stumbles on this:
```
await Promise.all([
                'Standard',
                'ReadOnly',
                'Admin'
            ].map(async (fullName) =>
                conn.metadata.update('Profile', {
                    fullName,
                    fieldPermissions: {
                        field: `LabsContractPreset__c.${fieldApiName}__c`,
                        readable: true,
                        editable: true
                    },
                })
            ))
```

**Comment by Rob-ModernAnalytics** [comment]
Hi Daniel,

Thanks for promisifying the code – good work!

Rob

**Comment by lms15** [comment]
Ok thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
