### ISSUE TITLE
Updating an array of records throws on any record error

### ISSUE THREAD

**Issue by jordanbtucker** [jsforce/jsforce#680]
```js
const accounts = [
  validAccount1,
  validAccount2,
  invalidAccount1,
  invalidAccount2,
]

conn
  .sobject('Account')
  .update(accounts)
  .then(results => {
    // This code doesn't get called.
  })
  .catch(err => {
    // err is only the first error returned by update().
    // There is no way to tell which accounts were updated
    // and which ones had errors.
  })
```

This is because `update` returns a `Promise.all` of an array of `requests`, but `Promise.all` rejects on the first error.

Instead, `update` should return a `Promise.all` of result objects.

From just reviewing the code, it looks like you can add a `catch` to the end of [this code] so it would be:

```js
return self.request({
  method : 'PATCH',
  url : url,
  body : JSON.stringify(record),
  headers : _.defaults(options.headers || {}, {
    "Content-Type" : "application/json"
  })
}, {
  noContentResponse: { id : id, success : true, errors : [] }
})
.catch(err => { id : id, success : false, errors : [err] });
```

Of course, this would be a breaking change, so you'd probably want this behavior enabled with an option like `{ dontThrow : true }` or something.

Let me know what you think.

[this code]: https://github.com/jsforce/jsforce/blob/a99a38b55346388f53a47d8b2e5afcace43c232b/lib/connection.js#L698-L707

**Comment by cristiand391** [comment]
this was fixed in v3:

https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/connection.ts#L1170C1-L1177C12

note that this code is used only if you are below API 42:
https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/connection.ts#L1126

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
