### ISSUE TITLE
Error logging should be disabled by default

### ISSUE THREAD

**Issue by jordanbtucker** [jsforce/jsforce#681]
jsforce is a library and so it shouldn't be logging to the console by default.

Consider the following examples:

```js
const jsforce = require('jsforce')
const conn = new jsforce.Connection()

// Example 1
conn.identity((err, info) => {
	if (err) {
		// ignore error
	} else {
		console.log(info)
	}
})

// Example 2
conn.identity()
	.then(info => console.log(info))
	.catch(err => {
		// ignore error
	})

// Example 3
async function logInfo () {
	try {
		const info = await conn.identity()
		console.log(info)
	} catch (err) {
		// ignore error
	}
}

logInfo()
```

Because I haven't logged in, the call to `identity()` in each example should throw. However, all three examples **also write the error to the console** even though my code silently handles the error.

I'm aware that I can disable this by setting the `logLevel` option, however, I shouldn't have to do this. In a library, when an error occurs, it should be handled by code or crash the app, but not logged to console.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
