### ISSUE TITLE
metadata deploy not supported in browsers

### ISSUE THREAD

**Issue by rdietrick** [jsforce/jsforce#69]
I am retrieving (successfully) zipped metadata, modifying it, and then trying to redeploy it -- all from a browser.  I can retrieve and modify the metadata XML files, but when I then try to redeploy it in zip format, it fails because the Metadata.deploy function depends on the zipInput parameter being either a Stream or a Buffer.  Both of these seem to be Node classes that aren't available in the browser.  It would be great if the deploy method allowed zip input as a base64 encoded string as well.  This would remove all Node dependencies.

**Comment by rsievekndy** [comment]
I'm trying to utilize this feature to run deployments from the browser but i'm having some issues with passing the zip data.

Here's a trimmed down version of what I'm doing. Assume JSZip and JSForce are resources on the  page.

var apexContent = 'public class sampleClass { public string mystring;}';
		var pkgXml = '<?xml version="1.0" encoding="UTF-8"?>' + 
							'<Package xmlns="http://soap.sforce.com/2006/04/metadata">' + 
				    			'<types>' + 
				        			'<members>sampleClass</members>' +
				        			'<name>ApexClass</name>' + 
				    			'</types>' + 
				    			'<version>35.0</version>' + 
							'</Package>';	
		var metadataDetail = '<?xml version="1.0" encoding="UTF-8"?>' +
							'<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">' +
							    '<apiVersion>35.0</apiVersion>' + 
							    '<status>Active</status>' +
							'</ApexClass>';
							
		var zip = new JSZip();
		zip.file("package.xml", pkgXml);
		zip.file("classes/sampleClass.cls-meta.xml", metadataDetail);
		zip.file("classes/sampleClass.cls", apexContent);

		var content = zip.generate({type:"base64"});
		var contentPrefix = 'data:application/zip;base64,' + content;

		conn.metadata.deploy(content, {runAllTests : false})
		  .complete(function(err, result) {
		    if (err) { console.error(err); }
		    console.log('done ? :' + result.done);
		    console.log('success ? : ' + result.true);
		    console.log('state : ' + result.state);
		    console.log('component errors: ' + result.numberComponentErrors);
		    console.log('components deployed: ' + result.numberComponentsDeployed);
		    console.log('tests completed: ' + result.numberTestsCompleted);
		  });


I'm not having any luck with the base64 file, with or without the prefix.

Without the prefix, I get a Payload Error, stating no Package.xml is found. With the prefix, the deployment runs successfully, but has no components inside (0/0 deployed successfully).

**Comment by rsievekndy** [comment]
I figured out the issue, posting back here to help anyone else with this problem. This approach requires the singlePackage attribute in the deploy options to be set to true ({runAlltests: false, singlePackage: true}). Without this set, the default is to look for multiple packages.

**Comment by mattgoldspink** [comment]
Posting this here in case others hit issues doing this in a browser.

`
var zip = new window.JSZip();
zip.file('package.xml', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><Package xmlns=\"http://soap.sforce.com/2006/04/metadata\"><types><members>*</members><name>CustomLabels</name></types><types><members>pl</members><name>Translations</name></types><version>42.0</version></Package>');
zip.file('translations/pl.translation', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><Translations xmlns=\"http://soap.sforce.com/2006/04/metadata\"><customLabels><label>Nowy</label><name>New</name></customLabels></Translations>');
 
zip.generateAsync({type: 'base64'})
                    .then(function(content) {
                        window.conn.metadata.deploy(zipStream, {
                                singlePackage: true
                            })
                            .complete(function(err, deployResult) {
                                if (err) {
                                    reject(err);
                                } else if (deployResult.success === false) {
                                    window.conn.metadata.checkDeployStatus(deployResult.id, true, 
                                            function(err, deployResult) {
                                                console.log(err);
                                                console.log(deployResult);
                                            });
                                    reject(deployResult);
                                } else {
                                    resolve(deployResult);
                                }
                            });
                    });
`

I'm using JSZip like ryan in the browser. The main difference is that I'm not prefixing 'data:application/zip;base64,' to the base64 output of JSZip. When I had the prefix it caused Salesforce to report errors about "No package.xml found".
