### ISSUE TITLE
Check if connection is still valid

### ISSUE THREAD

**Issue by sattarab** [jsforce/jsforce#699]
How can we check if the connection object with the cached access tokens and instance url is still valid to determine if we need to re-login?

FYI: I am implementing the entire salesforce login flow on the server side without any Web Interface

**Comment by mcbergsma** [comment]
Did you ever figure this out?

**Comment by cristiand391** [comment]
closing this...
The only way to know if the cached access token is valid is to do a request (the API will return a `403`/`INVALID_SESSION_ID` response), but you shouldn't need to worry about it if a session refresh handler is set:
https://jsforce.github.io/document/#session-refresh-handler
