### ISSUE TITLE
Cannot subscribe to a push topic.

### ISSUE THREAD

**Issue by Shrikant9** [jsforce/jsforce#703]
Folks, 

I am trying to subscribe to a push topic I have created in SFDC. 

```
var conn = new jsforce.Connection(xxxx);
conn.login(xxxx, xxxx, function (err, userInfo) {
if (err) {
  logger.error(err);
  throw new Error(err);
}

console.log('Authenticated.')
console.log('Connecting to push topic');
conn.streaming.topic("InvoiceStatementUpdates").subscribe(function(message) {
  console.log('Event Type : ' + message.event.type);
  console.log('Event Created : ' + message.event.createdDate);
  console.log('Object Id : ' + message.sobject.Id);
});
```

I have just copied and pasted the code from documentation. 
I am able to authenticate properly, but not abl to connect to the push topic. 
Am I doing something wrong? Is there any way I can debug this?

Console Output: 
```
    Authenticated.
    Connecting to push topic
```

Any thoughts?

**Comment by Chiragsorathiya** [comment]
i have same issue

**Comment by cristiand391** [comment]
triaging old issues...

if anyone experience this please open a new issue, you can set `logLevel` in the conn to get debug logs:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html#__type.logLevel
