### ISSUE TITLE
Error unsupported_grant_type when login

### ISSUE THREAD

**Issue by lusianawijayanti** [jsforce/jsforce#706]
I've tried tutorial from this website --> https://jsforce.github.io/ however,
whenever I tried to login, I got an error 'unsupported_grant_type' as following:
`{ unsupported_grant_type: grant type not supported
    at C:\Users\lusiana.wijayanti\Documents\mycustomapp\app\api\node_modules\jsforce\lib\oauth2.js:195:19
    at tryCallOne (C:\Users\lusiana.wijayanti\Documents\mycustomapp\app\api\node_modules\promise\lib\core.js:37:12)
    at C:\Users\lusiana.wijayanti\Documents\mycustomapp\app\api\node_modules\promise\lib\core.js:123:15
    at flush (C:\Users\lusiana.wijayanti\Documents\mycustomapp\app\api\node_modules\asap\raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) name: 'unsupported_grant_type' }`

Does anyone ever come across the same issue? If yes, some advice will be very helpful.

**Comment by jbouhier** [comment]
I have the same error as you with oauth2.
Did you manage to solve this by chance ?

**Comment by strictlyd** [comment]
If you can include some code snippets, it'd be much easier to help debug.

**Comment by dyarbrough93** [comment]
I am having the same issue a year later. Judging by the lack of response here I will probably have to use something else but it's worth a shot. I'm following this tutorial: https://medium.com/netscape/first-time-dev-building-a-fullstack-js-app-for-salesforce-with-oauth-login-jsforce-react-redux-ca5962fb7fe3. My code is as follows:

```
const oauth2 = new jsforce.OAuth2({
    loginUrl: 'loginUrl',
    clientId: 'clientId',
    clientSecret: 'clientSecret',
    redirectUri: `http://localhost:${PORT}/token`
  })
  router.get('/auth/login', (req, res) => {
    // Redirect to Salesforce login/authorization page
    res.redirect(oauth2.getAuthorizationUrl({ scope: 'api id web refresh_token' }))
  })
  
  router.get('/token', function(req, res) {
    const conn = new jsforce.Connection({ oauth2 })
    const code = req.query.code
    
    conn.authorize(code, function(err, userInfo) {
      if (err) { return console.error("This error is in the auth callback: " + err) }
      console.log('Access Token: ' + conn.accessToken)
      console.log('Instance URL: ' + conn.instanceUrl)
      console.log('refreshToken: ' + conn.refreshToken)
      console.log('User ID: ' + userInfo.id)
      console.log('Org ID: ' + userInfo.organizationId)
      req.session.accessToken = conn.accessToken
      req.session.instanceUrl = conn.instanceUrl
      req.session.refreshToken = conn.refreshToken

      var string = encodeURIComponent('true')
      //res.redirect('http://localhost:3000/?valid=' + string)
    })
  })
```

Which returns "unsupported_grant_type: grant type not supported"

**Comment by nimish-gupta** [comment]
Hey @lusianawijayanti, have you got the solution for this one?

**Comment by AtticusRains** [comment]
Hey @dyarbrough93 where you able to solve this issue?

**Comment by dyarbrough93** [comment]
@atticusrains unfortunately no. I am now using nforce which works great.

**Comment by AtticusRains** [comment]
@dyarbrough93 I'll check it out, thanks for the suggestion :)

**Comment by tgentet-obrien** [comment]
Has there been any movement on this? I am currently hitting the same issue -_-

**Comment by photz** [comment]
All of a sudden I am also seeing this error. Have any of you solved this?

**Comment by jbouhier** [comment]
Nope

**Comment by strictlyd** [comment]
Oh that seems to ring a bell, sandbox orgs should be using the test endpoint. It's been a while since I touched this stuff, but I can help take a look.

**Comment by cdnicoll** [comment]
I was in the same boat as @photz trying to auth against a clients sandbox, using https://test.salesforce.com worked for me.

**Comment by bhuvaneswary** [comment]
I have with https://test.salesforce.com for my sandbox org. It is failing with **invalid_client_id: client identifier invalid** error. It is happening during conn.authorize call. I am getting authorisation code succeffully.

**Comment by zilurrane** [comment]
I am also having same issue. Anyone ever found solution?

**Comment by Myrko-SM** [comment]
You can try to remove the loginUrl param from the oAuth connection options, worked for me:

SALESFORCE_OAUTH: new jsforce.OAuth2({
    **// loginUrl : process.env.SALESFORCE_LOGIN_URL,** 
    clientId : process.env.SALESFORCE_CONSUMER_KEY,
    clientSecret : process.env.SALESFORCE_CONSUMER_SECRET,
    redirectUri : process.env.SALESFORCE_OAUTH_REDIRECT
  })

**Comment by cristiand391** [comment]
triaging old issues...

this error can happen on multiple scenarios, for reference:
the default `loginUrl` if you dont't specify it is `https://login.salesforce.com` which usually is prod, when working on a sandbox you **need** to pass `loginUrl: "https://test.salesforce.com"`

for anyone else who get these errors, please open a new issue.
