### ISSUE TITLE
Support for Bulk API 2.0 

### ISSUE THREAD

**Issue by snarjuna** [jsforce/jsforce#707]
From the latest salesforce release, Bulk API 2.0 is newly introduced where OAuth 2.0 is supported. Currently, jsforce supporting bulk api 1.0. 

Is there any plan to support bulk api 2.0 in near future.

However, with existing jsforce implementation I am able to use bulk apis using oAuth 2 access token? Is this supported approach or is this working unintended?

**Comment by snarjuna** [comment]
@stomita Can you please provide your comments on this issue

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
