### ISSUE TITLE
Bulk API : Close the job

### ISSUE THREAD

**Issue by apasrini** [jsforce/jsforce#711]
wanted to know how does one close the job using jsforce bulk api ?
There seem to be no api reference for closing a job in bulk api. wanted to know how closing a job is handled in bulk api v1. 

There is only api for batch status but not for job status.

**Comment by mtuchi** [comment]
Hello 👋🏽 , I am facing a challenge using bulk v1, the job are not closed despite using `job.close()`. @apasrini can you share how you have achieved closing the job ?

**Comment by cristiand391** [comment]
@mtuchi can you share the code where you call `job.close`?

**Comment by mtuchi** [comment]
@cristiand391 i found the problem, `job.close()` is promise function and i was calling it without `await`. 
So i have updated my implementation to use async/await. [See L418-L439 of our salesforce adaptor](https://github.com/OpenFn/adaptors/blob/main/packages/salesforce/src/Adaptor.js#L418-L439)
