### ISSUE TITLE
Is it possible to create a batch with job id alone ?

### ISSUE THREAD

**Issue by apasrini** [jsforce/jsforce#712]
Wanted to know if there is a way to create a batch with job id?

Steps:
1. create a job in one .js file
2. get the info on the job - job id basically
3. use this info in another js file to create a batch?

Trying to understand if this is possible Add a Batch to a Job: https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_batches_create.htm

**Comment by cristiand391** [comment]
triaging old issues...

this can be done by creating a `job` instance using `conn.bulk.job(<job-id>)`:
https://jsforce.github.io/document/#bulk-api
