### ISSUE TITLE
False boolean values in update are ignored

### ISSUE THREAD

**Issue by amakk** [jsforce/jsforce#714]
When running `conn.sobject('Custom_Object__c').find({ Id: { $in: ['objectid'] } }).update({ Flag__c: false })`, `Flag__c` isn't getting updated when boolean value is false. When it's true, or a string it does get updated. It looks like a similar issue was fixed in #627 but looks like it didn't fix all cases

**Comment by dland512** [comment]
I can second that I'm seeing this behavior as well. If you use `false.toString()` it works fine but just `false` has not effect.

**Comment by cristiand391** [comment]
triaging old issues...

this works on jsforce v3:

```ts
const contact = conn.sobject('Contact');

const currentCon = await contact.find({
  Name: 'John Doe'
}, ['Name', 'bool__c'])
console.log(currentCon)

const res = await contact.find({
  Name: 'John Doe'
}).update({
  bool__c: false
})
console.log(res)

const updatedCon = await contact.find({
  Name: 'John Doe'
}, ['Name', 'bool__c'])
console.log(updatedCon)
```

🔽 

```
[
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v60.0/sobjects/Contact/0038N00000JmwqsQAB'
    },
    Name: 'John Doe',
    bool__c: 'true'
  }
]
[ { id: '0038N00000JmwqsQAB', success: true, errors: [] } ]
[
  {
    attributes: {
      type: 'Contact',
      url: '/services/data/v60.0/sobjects/Contact/0038N00000JmwqsQAB'
    },
    Name: 'John Doe',
    bool__c: 'false'
  }
]
```

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
