### ISSUE TITLE
Having Issue with CRUD

### ISSUE THREAD

**Issue by Chetu-S-A** [jsforce/jsforce#717]
Hi, 
I am trying to use JSForce API with my salesforce instance. When trying to create a record, I get this issue.

[Error: Invalid URI "/services/data/v39.0/sobjects/Admin"]

I need help with this ASAP. Is there something I need to configure on my salesforce or is it because of the changes in the salesforce itself?

PS:
My instance was setup on Jan 10 2018.

**Comment by liveyourheart** [comment]
Assuming Admin is a custom object you created, you might try adding the __c postfix, i.e. `conn.sobject('Admin__c')`

**Comment by Chetu-S-A** [comment]
Thank you! That solved my problem.
