### ISSUE TITLE
How to tunn off caching

### ISSUE THREAD

**Issue by Varun-garg** [jsforce/jsforce#741]
Sometimes when I load an object, which I just updated using jsforce I still get old copy. On further investigation, I found out the problem is with browser caching. I also use it in a cordova application but that shouldn't be the issue.

![cache](https://user-images.githubusercontent.com/5960246/38658240-f0b8ef5c-3e41-11e8-8b2e-61ea6fa06865.png)

As it can be seen in screenshot, last sObject (0016A00000OLnT2QAL) is loaded from the cache which seems to be the issue.

`connection.cache.clear()` or ` $.ajaxSetup({ cache: false }); ` or using meta tags for disabling caching did not work.

In reponse headers, I can see `Cache-Control: private`

### User Agent
`Mozilla/5.0 (Linux; Android 8.1.0; ONE A2003 Build/OPM1.171019.021; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36.`

**Comment by dbhoot** [comment]
Click the disable cache checkbox (it's present in the screenshot you attached).

https://www.technipages.com/google-chrome-how-to-completely-disable-cache

**Comment by DanielGM** [comment]
@Varun-garg did you find a solution to this? I'm having the same issue
