### ISSUE TITLE
Composite requests support

### ISSUE THREAD

**Issue by MeuhMeuh** [jsforce/jsforce#742]
Hello,

I'm studying the possibility to migrate a project using the Salesforce REST API. This project would be using Node.js, so I'm looking at the possibility to use a third party package to ease the Salesforce integration.
In our project, we make a heavy use of Composite requests ( see https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_composite.htm ). It doesn't seem like it's implemented in this library. Am I right ? If not, is there anything planned to support it ?

Thank you !

**Comment by stomita** [comment]
Yes we have a plan but if you want to use it currently use `requestPost()` method which will send a raw api request using json body.

**Comment by MeuhMeuh** [comment]
Sounds good, thank you for your answer.

**Comment by jonathanwiesel** [comment]
Any news on this?

**Comment by MeuhMeuh** [comment]
FYI using `requestPost()` directly did the trick for me @jonathanwiesel .
