### ISSUE TITLE
API vs libs

### ISSUE THREAD

**Issue by dolanmiu** [jsforce/jsforce#745]
What is the difference between the `lib` folder, and the `api` folder, is there a meaning behind this design decision for this code base, or is it from legacy code?

https://github.com/jsforce/jsforce/tree/master/lib

https://github.com/jsforce/jsforce/tree/master/lib/api

**Comment by cristiand391** [comment]
triaging old issues...

`lib` contains the library code, `lib/api` contains most of the API wrappers which are then imported in the connection object.
