### ISSUE TITLE
Tooling.runTestsSynchronous incorrect body

### ISSUE THREAD

**Issue by benvogler** [jsforce/jsforce#747]
Per salesforce [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/intro_rest_resources.htm), the body of a request to /runTestsSynchronous/ should look like

```
{
    "tests": [
        {
            "className": "YourClassName1",
            "testMethods": [
                "testMethod1",
                "testMethod2",
                "testMethod3"
            ]
        },
        {
            "className": "YourClassName2"
        },
        {
            "maxFailedTests": "2"
        }
    ]
}
```

jsforce currently sends the a body like this
```
{
    "classnames": [
        "YourClassName1",
        "YourClassName2"
    ]
}
```

This request always returns null. Changing the body to the correct format successfully returns test results

**Comment by dancrew32** [comment]
@benvogler sorry to bother several years later, but did you manage to resolve this? I get a similar null response when sending my class name(s). It's also definitely not resulting in the code-coverage percentage updating that you can get when running tests from the apex debug tool. Thanks for any info you might be able to provide.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
