### ISSUE TITLE
Delete a Subscriber?

### ISSUE THREAD

**Issue by rjmohammad** [jsforce/jsforce#748]
Hello,

I am new to all of this so pardon my lack of experience! 

I was just wondering if this library support subscriber deletion? I saw basic CRUD operations with the name of the *sobject*. But I am referring to this particular request.
https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/deleting_a_subscriber.htm

Any help or suggestion is greatly appreciated. 
Thanks

**Comment by cristiand391** [comment]
triaging old issues...

there's no MC-specific support in jsforce yet.
https://github.com/jsforce/jsforce/discussions/1455?converting=1
