### ISSUE TITLE
jsforce relies on vulnerable version of `open` dependency

### ISSUE THREAD

**Issue by zmillman** [jsforce/jsforce#751]
The Node Security Platform flagged `open` as a critically vulnerable library: https://nodesecurity.io/advisories/663

It's currently [used for making requests from the CLI](https://github.com/jsforce/jsforce/blob/38e4e66d021db20b22435f48c9d2b34f48e54c23/lib/cli/cli.js#L11), and could probably be replaced by a normal `http` request.

In the meantime, this is causing any services depending on `jsforce` to fail their security checks.

**Comment by jaan** [comment]
Even `sshpk` package is highly vulnerable. Posting the `npm audit` result below:

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ **High**          │ Regular Expression Denial of Service          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ **Package**       │ sshpk          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jsforce-metadata-tools [dev]          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jsforce-metadata-tools > jsforce > request > http-signature  │
│               │ > sshpk          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/606          │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ **Critical**      │ Command Injection          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ **Package**       │ open          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jsforce-metadata-tools [dev]          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jsforce-metadata-tools > jsforce > open          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/663          │
└───────────────┴──────────────────────────────
