### ISSUE TITLE
Property 'search' does not exist on type 'Connection'

### ISSUE THREAD

**Issue by pritisolanki** [jsforce/jsforce#753]
Hi there,

`  conn.search("FIND {Un*} IN ALL FIELDS RETURNING Account(Id, Name), Lead(Id, Name)", function (err, ret) {
                if (err) {
                    return reject(err);
                }
                console.log(ret);
}`

It throws - Property 'search' does not exist on type 'Connection'.

Any idea what might be wrong.

**Comment by pritisolanki** [comment]
I resolved this as below
` (conn as any).search(searchOpts, function (err, ret) {`

Not sure if this is a right or wrong way. thoughts?

**Comment by cristiand391** [comment]
triaging old issues...

this was likely types from `@types/jsforce` being wrong.
