### ISSUE TITLE
Caching Describe methods should return promise

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [jsforce/jsforce#756]
All of the async describe methods return promises, however the caching versions of these methods (describe$, describeGlobal$, layouts$, etc), return a value from the cache. An error is thrown if a callback isn't passed to the caching version and a value doesn't exist in the cache.

Preferably the caching methods should have the same signature as the non-caching ones: i.e. the caching method returns an immediately resolved promise if the value exists in the cache, otherwise the original method is called and its promise returned.

**Comment by timendez** [comment]
For those of you who also want to avoid mixing callbacks with promises, you can do this:

```javascript
import util from 'util'
...
const meta = await util.promisify(conn.sobject('Salesforce_Object__c').describe$)()
```

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
