### ISSUE TITLE
 Command Injection Error during installation 

### ISSUE THREAD

**Issue by karthikkornalies** [jsforce/jsforce#758]
Hello Team,
I'm trying to install jsforce (via npm) and fails due to related path jsforce -> Open.  Can you please advise on what am I missing here.

Node version : v6.11.1
NPM Version : 6.1.0

# npm install jsforce --save

npm WARN noderest@1.0.0 No repository field.

+ jsforce@1.8.4
updated 1 package, moved 1 package and audited 1587 packages in 4.44s
found 1 critical severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ open                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jsforce                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jsforce > open                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/663                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by WhiteAbeLincoln** [comment]
This is an issue with a dependency of the cli module. There is an open pull request #752 which should fix the problem so that users don't see this warning any more.

**Comment by sfryffdc** [comment]
It would be great to get this published as it shows up as a vulnerability with retire, nsp etc. Is there a roadmap for publishing to npm?

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
