### ISSUE TITLE
Tooling Api Query example fails with Malformed Query Error

### ISSUE THREAD

**Issue by pogilvie** [jsforce/jsforce#763]
This seems to happen in cases where we receive more than one record.

![image](https://user-images.githubusercontent.com/628688/41513465-aae11164-7251-11e8-85e6-50191a89d482.png)

**Comment by cristiand391** [comment]
triaging old issues...

I can't repro this on jsforce v3. For reference, you can call `toSoql()` to print the SOQL query generated by jsforce:
```ts
await conn.tooling.sobject('ApexTrigger').find({
    TableEnumOrId: "Contact"
  }).toSOQL()
```
