### ISSUE TITLE
Consume lots of API limit if batch status is Not Processed

### ISSUE THREAD

**Issue by AvanishKumar008** [jsforce/jsforce#765]
When the batch status is not completed then it will try to hit API and API limit exceed. It calls in every one second because in bulk.js they set up hardcoded value for the interval.

I am using this API and it exceeds my limit 100K in 4-5 Hours.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
