### ISSUE TITLE
question : how to use convertLead()

### ISSUE THREAD

**Issue by pritisolanki** [jsforce/jsforce#768]
I am trying to call leadConvert function via jsforce lib 

import { SoapApi } from "jsforce";
const soapApi = await new SoapApi(conn);
conn.soap.convertLead //has no exported member 'SoapApi'.

Following the documentation - https://jsforce.github.io/blog/posts/20150816-jsforce15-released.html. I am setting up connection like below

 connection = new Connection({ loginUrl : this.loginUrl});        
 userInfo = await connection.login(this.user, this.password);

and then,

conn.soap.convertLead(leadConverts, function(err, res) {}
Property 'soap' does not exist on type 'Connection'.

Any clue? how to solve this.

**Comment by joelwatson** [comment]
Per my comment to your SO question, it seems to work just as expected for me:
https://stackoverflow.com/questions/50958561/how-to-call-convertlead-via-jsforce

Are you able to establish the connection successfully? Do other operations work as you expect them to?
