### ISSUE TITLE
High Vulnerability issue reported by WhiteSource due to dependency : open-0.0.5.tgz

### ISSUE THREAD

**Issue by anupamabalahara** [jsforce/jsforce#772]
Hi All,

There is a high vulnerability issue reported on jsforce due to open-0.0.5.tgz dependency. 

https://github.com/pwnall/node-open/issues/67

Are there any plans to remove this dependency ?

Regards
Anu

**Comment by ajmcgarry** [comment]
We have the same issue reported with Snyk https://snyk.io/vuln/npm:open:20180512

**Comment by stomita** [comment]
@anupamabalahara The patches are provided in #752 and already merged. I will do the release immediately ASAP.

**Comment by joshprice** [comment]
@stomita looks like this issue should be closed now?
