### ISSUE TITLE
Using promises with bulk api batches

### ISSUE THREAD

**Issue by dland512** [jsforce/jsforce#776]
Is it valid to use promises or async/await when working with the bulk api? I have some code that looks like this:

```
const batch = job.createBatch();
await batch.execute();
```

But it just hangs waiting for `batch.execute()`, which seems to indicate that it's not returning a promise.

The [documentation for the Batch class](http://jsforce.github.io/jsforce/doc/Bulk-Batch.html) lists a function called `then()` but I'm not sure how to use it:

> then()
> Promise/A+ interface http://promises-aplus.github.io/promises-spec/ Delegate to deferred promise, return promise instance for batch result

I also see that `batch.execute()` takes a callback function. When is that called? After the request for the batch has been submitted?

**Comment by cristiand391** [comment]
execute no longer takes a callback in jsforce >= v2.

You can also `await conn.bulk.load` on last versions.
https://jsforce.github.io/document/#bulk-api

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
