### ISSUE TITLE
Question : When does queryMore() returns the deleted records as well and when it do not return.

### ISSUE THREAD

**Issue by nidhiag** [jsforce/jsforce#779]
My scenario is i need to fetch deleted records as well based on the flag. I can achieve that using the queryAll or q.scanAll(true) but the only thing confusing me is the queryMore . When does it returns the deleted records and when it does not ?

**Comment by stomita** [comment]
`queryMore()` is using the cursor returned by the previous query execution. If the previous query execution holds deleted record in the target, `queryMore()` will also return it.
(Actually I didn't test this but it is the natural consequence.)
