### ISSUE TITLE
Missing Prototype Functions such as createSingle

### ISSUE THREAD

**Issue by MGarfOppLoans** [jsforce/jsforce#797]
Keep getting the following error when i run the three code blocks :
error TypeError: this._createSingle is not a function
extension.js:65
    at Tooling.Connection.insert.Connection.create (/Users/michaelgarfinkel/Documents/forcecompiler/node_modules/jsforce/lib/connection.js:727:12)
    at compile (/Users/******/Documents/*******/extension.js:58:29)
    at /Users/michaelgarfinkel/Documents/forcecompiler/extension.js:126:17
    at /Users/michaelgarfinkel/Documents/forcecompiler/node_modules/jsforce/lib/promise.js:72:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

I run this first
```
        conn = new jsforce.Connection({
            // you can change loginUrl to connect to sandbox or prerelease env.
            loginUrl: 'https://test.salesforce.com',
            version: '43.0'
        });
```

this second
```
  conn.login(username, password, function (err, userInfo) {
            if (err) {
                console.error(err);
                reject(err);
            } else {
                // Now you can get the access token and instance URL information.
                // Save them to establish connection next time.
                console.log(conn.accessToken);
                console.log(conn.instanceUrl);
                // logged in user property
                console.log("User ID: " + userInfo.id);
                console.log("Org ID: " + userInfo.organizationId);
                // ...
                console.log('conn', conn);            
}
        });
```
And this third
```
        return conn.tooling.sobject('ApexClass').create({
            body: apexBody
        }, function (err, res) {
            if (err) { return console.error(err); }
            console.log(res);
        });
```

**Comment by daishi4u** [comment]
Same issue here!

**Comment by pixel9** [comment]
I'm running into the same issue.

It seems all the 'private' methods (`_createSingle`, `_createParallel`, etc...) on the `Connection` prototype are missing when going through the `tooling` API. It feels like an unintended omission but I haven't looked at it any further to determine if this is a limitation of the tooling API.

**Comment by lms15** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MGarfOppLoans** [comment]
@stomita still getting 

`this._createSingle is not a function`  after the PR merge.

**Comment by MoshikEilon** [comment]
@stomita Hi, I'm still getting these errors as well

Error: TypeError: this._createSingle is not a function
At: Tooling.Connection.insert.Connection.create

Example code:
`    if (!err) {
        const apexBody = [
            "public class TestApex {",
            "  public string sayHello() {",
            "    return 'Hello';",
            "  }",
            "}"].join('\n');
        conn.tooling.sobject('ApexClass').create({
            body: apexBody
          }, function(err, res) {
            if (err) { return console.error(err); }
            console.log(res);
          });
    }`

**Comment by aust1nz** [comment]
I had the same issue with JSforce v 1.9.1. I downgraded to 1.8.5 and was able to use the Tooling API as expected.

**Comment by tnoonan-salesforce** [comment]
@stomita We had the same problem with sfdx and had to downgrade to 1.8.5.

**Comment by DavidKerrHighRoads** [comment]
> @stomita We had the same problem with sfdx and had to downgrade to 1.8.5.



> I had the same issue with JSforce v 1.9.1. I downgraded to 1.8.5 and was able to use the Tooling API as expected.

What is the procedure for doing this?  I tried yarn add jsforce@1.8.5 but I get the same createSingle error.

**Comment by jacksonStone** [comment]
So it seems this issue should not be closed, right?
