### ISSUE TITLE
howto: detect a broken connection

### ISSUE THREAD

**Issue by cdaringe** [jsforce/jsforce#798]
# problem

if my salesforce connection dies, i want to be able to handle & respond to that event.  is this possible?

# discussion

i get a `connection` object after logging in.  is there any such event that is emitted?  `connection.on('disconnect|error|whatever', ...)` i can hook into?

thanks!

**Comment by kerloom** [comment]
bump!

**Comment by cristiand391** [comment]
triaging old issues...

the only event the connection emits is `refresh` here:
https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/session-refresh-delegate.ts#L57

When using OAuth, jsforce will refresh the access token if it does an API with with and it's expired so you don't need to handle those scenarios.

If not using oauth, jsforce just throws when using an expired token.
