### ISSUE TITLE
How to add Custom Field to 'Account'?

### ISSUE THREAD

**Issue by webdev522** [jsforce/jsforce#800]
Hi JSForce Team,

I'd like to add a Custom Field to my 'Account', not to Custom Object, but I can't find any snippet for that.
Let me know if you have a solution for it.

Regards,
webdev522

**Comment by cristiand391** [comment]
triaging old issues...

`metadata.create` can be used for this:
https://jsforce.github.io/document/#create-metadata

the `medatata.update` example shows how to update a custom field, the syntax is the same for both methods
https://jsforce.github.io/document/#update-metadata

API:
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_createMetadata.htm
