### ISSUE TITLE
Bug: _toSaveResult error

### ISSUE THREAD

**Issue by staufman** [jsforce/jsforce#801]
I'm seeing an issue with some methods in the `Connection` class where `_toSaveResult` is not found. In my particular case, I was using the `upsert` method and forgot to pass in the `extIdField`. The API was, rightfully, returning an error but when it went to run the `catch` block, it referenced the _toSaveResult` method which is nowhere to be found. Is this a dead reference?

```
connection.js:987
.catch(function(err) {
        // be aware that `allOrNone` option in upsert method will not revert the other successful requests
        // it only raises error when met at least one failed request.
        if (!isArray || options.allOrNone || !err.errorCode) { throw err; }
        return this._toSaveResult(null, err);
      })
```

**Comment by vlamic** [comment]
Any plans to release the fix?
