### ISSUE TITLE
REST API - upsert on collections with { allOrNone: false } does not return array of errors

### ISSUE THREAD

**Issue by maciejsimm** [jsforce/jsforce#813]
I'm using upsert with option `allOrNone: true`, I'd expect that in return I'd receive an array of objects simillar to `Database.SaveResult[]`.

In case some record fails in the collection I'm getting a JSForce exception instead:

```
TypeError: Cannot read property '_toRecordResult' of undefined
    at /Users/maciejsimm/Documents/Workspaces/Salesforce/Enxoo/enxooProductMigrator/node_modules/jsforce/lib/connection.js:992:21
    at tryCallOne (/Users/maciejsimm/Documents/Workspaces/Salesforce/Enxoo/enxooProductMigrator/node_modules/promise/lib/core.js:37:12)
    at /Users/maciejsimm/Documents/Workspaces/Salesforce/Enxoo/enxooProductMigrator/node_modules/promise/lib/core.js:123:15
    at flush (/Users/maciejsimm/Documents/Workspaces/Salesforce/Enxoo/enxooProductMigrator/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

I've checked and it's not the case for insert operation - which properly returns array of errors that can be individually handled.

My code is below (`data` is an array of sObjects). I'd like to upsert records, and in case individual ones have error -> log it to console, but still allow the upsert on correct records.

```
conn.sobject("enxCPQ__Attribute__c").upsert(data, "enxCPQ__TECH_External_Id__c", { allOrNone: false, allowRecursive: true }, function(err, rets) {
    if (err) {
        reject('error creating attributes: ' + err);
        return;
    }
    let errorsCount = 0;
    for (let i = 0; i < rets.length; i++) {
        if (!rets[i].success) {
            console.log('----- !!! - success: ' + rets[i].success + ' errors: ' + JSON.stringify(rets[i].errors));
            errorsCount++;
        }
    }
    console.log("--- upserted attributes: " + rets.length + ", errors: " + errorsCount);
    resolve();
});
```

**Comment by borys-kupar** [comment]
The same bug with context is in 3 more places: https://github.com/borys-kupar/jsforce/commit/00acfda1bf07569b5ac6270b58634a3b5295dd96

**Comment by stefangoor** [comment]
> The same bug with context is in 3 more places: [borys-kupar@00acfda](https://github.com/borys-kupar/jsforce/commit/00acfda1bf07569b5ac6270b58634a3b5295dd96)

PR for these changes available here: https://github.com/jsforce/jsforce/pull/985

Thanks @borys-kupar

**Comment by cristiand391** [comment]
triaging old issues...

this should be fixed in jsforce v3, that helper is just a function now:
https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/connection.ts#L212

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
