### ISSUE TITLE
Confusion on refresh token flow

### ISSUE THREAD

**Issue by kylesimmonds** [jsforce/jsforce#824]
I'm looking at this code in the jsforce docs about the access/refresh token flow:

```
var conn = new jsforce.Connection({
  oauth2 : {
    clientId : '<your Salesforce OAuth2 client ID is here>',
    clientSecret : '<your Salesforce OAuth2 client secret is here>',
    redirectUri : '<your Salesforce OAuth2 redirect URI is here>'
  },
  instanceUrl : '<your Salesforce server URL (e.g. https://na1.salesforce.com) is here>',
  accessToken : '<your Salesforrce OAuth2 access token is here>',
  refreshToken : '<your Salesforce OAuth2 refresh token is here>'
});

conn.on("refresh", function(accessToken, res) {
  // Refresh event will be fired when renewed access token
  // to store it in your storage for next request
});
```

Does jsforce automatically catch expired access tokens and refresh them? Or does my connection need some extra catch when it makes a `query()`? Should I manually call `conn.refreshToken()` every time I make a connection?

The reason I ask is because I periodically receive errors from jsforce about expired access tokens and invalid grants. With the code above, are those just notifications to be aware of, or are they actual errors caused by users being unable to refresh their access tokens? jsforce doesn't make it clear when it's actually validating and refreshing tokens.

Sorry if that's a little vague, I'm still trying to wrap my head around how this needs to be structured within express and my client-side app

**Comment by stomita** [comment]
> Does jsforce automatically catch expired access tokens and refresh them

Yes, if refreshToken and oauth2 client/secret information is given in constructor.

> does my connection need some extra catch when it makes a query()?

No.

> Should I manually call conn.refreshToken() every time I make a connection?

No.

The `refresh` event of the connection is typically used for updating the access token information which is usually kept in some persistent store. It is automatically called when the access token becomes invalid and refresh token flow is completed, with the newly obtained access token information in the argument.

You don't have to implement the event handler, but without it, it would always run refresh token flow in the first API access, because the access token initially obtained quickly becomes obsolete within a few hours.

**Comment by kylesimmonds** [comment]
@stomita thanks for the quick response. That makes sense to me.

What's the proper way to catch an expired refresh token? I know Salesforce returns the error `invalid_grant: expired access/refresh token` but it doesn't differentiate between access or refresh.

One way I thought of is adding middleware before each Salesforce request that tries a connection to validate it (example below), but that might be overkill.

```
router.use(async (req, res, next) => {
  try {
    const conn = new jsforce.Connection({
      logLevel: 'ERROR',
      oauth2: {
        loginUrl: '[loginUrl]',
        clientId: '[clientId]',
        clientSecret: '[clientSecret]',
        redirectUri: '[redirectUri]',
      },
      instanceUrl: '[instanceUrl]',
      accessToken: '[accessToken]',
      refreshToken: '[refreshToken]',
    });

    /** Resave the updated access token */
    conn.on('refresh', (newAccessToken, res) => {
      console.log('Access token refreshed');
      req.session.accessToken = newAccessToken;
    });
    
    /** HERE */
    /** Try to validate the access/refresh token */
    conn.initialize();

    /** Make the connection accessible to the next middleware */
    req.sfConn = conn;

    return next();
  } catch (error) {
    next(error);
  }
});
```

**Comment by kylesimmonds** [comment]
Got it, thanks!

**Comment by keanedawg** [comment]
One more thing, if you are using a sandbox URL, you are going to need to explicitly set the loginURL (inside OAuth2 object) to `https://test.salesforce.com`. Otherwise JSFORCE will default to using `https://login.salesforce.com/`.
