### ISSUE TITLE
Transaction management in Rest API SOQL

### ISSUE THREAD

**Issue by joydeep9** [jsforce/jsforce#825]
I am unable to find any transaction management options when using Rest API using SOQL.
In my use case -
I am using 1 insert and then one update. If update fails then insert operation should be rolled back.
But after insert is done even after update is failed I am not able to roll back insert.
Can anyone please suggest how an insert (using SOQL ) can be rolled back.

Thanks in Advance!

**Comment by stomita** [comment]
I believe no long-running transaction (= transaction spread across several API calls) is available when using REST / (or even SOAP) API. Use Apex instead.

**Comment by joydeep9** [comment]
Thank you for reply.
I have these two operations in one single API. First insert and then
update. So i was wondering if it is possible to achieve in an api.

**Comment by stomita** [comment]
Maybe the [composite resource](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_composite_record_manipulation.htm) might suit to your use case.
There is not special support in JSforce for composite request right now, but you can call the endpoint by `Connection.request()`.

```javascript
conn.requestPost('/composite/', {
    "allOrNone" : true,
    "compositeRequest" : [{
        "method" : "POST",
        "url" : "/services/data/v38.0/sobjects/Account",
        "referenceId" : "NewAccount",
        "body" : {  
            "Name" : "Salesforce",
            "BillingStreet" : "Landmark @ 1 Market Street",
            "BillingCity" : "San Francisco",
            "BillingState" : "California",
             "Industry" : "Technology"
        }
    },{
        "method" : "GET",
        "referenceId" : "NewAccountInfo",
        "url" : "/services/data/v38.0/sobjects/Account/@{NewAccount.id}"
    },{
        "method" : "POST",
        "referenceId" : "NewContact",
        "url" : "/services/data/v38.0/sobjects/Contact",
        "body" : {  
            "lastname" : "John Doe",
            "Title" : "CTO of @{NewAccountInfo.Name}",
            "MailingStreet" : "@{NewAccountInfo.BillingStreet}",
            "MailingCity" : "@{NewAccountInfo.BillingAddress.city}",
            "MailingState" : "@{NewAccountInfo.BillingState}",
            "AccountId" : "@{NewAccountInfo.Id}",
            "Email" : "jdoe@salesforce.com",
            "Phone" : "1234567890"
        }
    },{
        "method" : "GET",
        "referenceId" : "NewAccountOwner",
        "url" : "/services/data/v38.0/sobjects/User/@{NewAccountInfo.OwnerId}?fields=Name,companyName,Title,City,State"
    },{
        "method" : "GET",
        "referenceId" : "AccountMetadata",
        "url" : "/services/data/v38.0/sobjects/Account/describe",
        "httpHeaders" : {
            "If-Modified-Since" : "Tue, 31 May 2016 18:13:37 GMT"
        }
    }]
})
```

**Comment by joydeep9** [comment]
Thank you very much. Will try and update you.
