### ISSUE TITLE
OAuth Popup Doesn't Close

### ISSUE THREAD

**Issue by jmiller-io** [jsforce/jsforce#827]
I am building a Vue app and am trying to add Salesforce OAuth and I have not been able to fix this issue I'm experiencing with the OAuth popup window. 

What is occurring is, a user clicks a login button, the Salesforce OAuth window pops up, they log in. Upon successful Salesforce login, within the popup window they are redirected back to my app and the popup never closes. The initial page where the user clicked login, is still open and does not change.

I expect that upon successful login the popup would close and the original application would be redirected.

Is there a solution to resolve this issue? Can we disable the popup window and perform the OAuth within the same window of the app?

Thank you

**Comment by lms15** [comment]
Yes, Jake, my system crashed again last night and I do not have git hub on anymore. Sorry, but my wins 10 is corrupted.
Mamie

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lms15** [comment]
I have so many issues with my new computer right now. Still working with dell about to call them again.
Mamie
thank Jake

**Comment by cristiand391** [comment]
triaging old issues...

jsforce have a handler to close the popup. If anyone experience this please open a new issue with how jsforce is being called.
