### ISSUE TITLE
conn.on("refresh") Looping

### ISSUE THREAD

**Issue by madskunker** [jsforce/jsforce#830]
var conn = new jsforce.Connection({
    oauth2: {
        clientId: process.env.SALESFORCE_CLIENT_ID,
        clientSecret: process.env.SALESFORCE_CLIENT_SECRET
    },
    refreshToken: refreshToken,
    instanceUrl: instanceUrl
});
conn.on('refresh', function(newAccessToken, res) {
    console.log('Refresh Occurred :', newAccessToken);
});

This Loops Forever until you get a MaxListenersExceededWarning

every 200ms the "refresh" event fires.

Why is this happening.  I have never seen this before and I am stumped

Jeff

**Comment by hitesh22b** [comment]
i am facing the same issue, did you find the solution to this?

**Comment by cristiand391** [comment]
this might be related to https://github.com/jsforce/jsforce/issues/1411

closing it because we can't tell if the org info was correct. Please open a new issue if someone can repro.
