### ISSUE TITLE
Create Promise Returning Early

### ISSUE THREAD

**Issue by rjott0309** [jsforce/jsforce#831]
When trying to create records via sobject, it appears that the create promise is returning before my callback code is called. The following example and the output shows the issue. The output should be A B C D but is instead A B D C. Query promises are working fine.

```
function createAccountsAndSendResults(conn) {
  console.log('A Create Accounts Starting')
  createAccounts(conn)
    .then((results) => {
      console.log('D Results from then: ' + results)
    })
}

function createAccounts(conn) {
  console.log('B Creating Accounts')
  return conn.sobject('Account').create([{Name: "Account1"}, {Name: "Account2"}], (err, results) => {
    console.log('C Accounts Created')
    if (err) return console.log(err)
    return('Retrieved ' + results.length + ' results')
  })
}
```

Output
```
A Create Accounts Starting
B Creating Accounts
D Results from then: [object Object],[object Object]
C Accounts Created
```

**Comment by stomita** [comment]
Actually it is not assumed the callback is used with promise, so no order guarantees. If you would like to the order to be within promise chain, use `.then()` or `.catch()` instead of callback.

**Comment by rjott0309** [comment]
Thanks for the clarification. ---- On Wed, 31 Oct 2018 20:44:54 -0500 Shinichi Tomita <notifications@github.com> wrote ---- Actually it is not assumed the callback is used with promise, so no order guarantees. If you would like to the order to be within promise chain, use .then() or .catch() instead of callback. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lms15** [comment]
Hope I did the pull correctly?
