### ISSUE TITLE
Calling describeGlobal$ when a "refresh" is needed causes hanging

### ISSUE THREAD

**Issue by newhouse** [jsforce/jsforce#836]
I've noticed that if:
1. I'm using OAuth2 authentication
2. My `accessToken` is expired
AND
3. My first call is to a `describeGlobal$` (perhaps all cached calls)

...the library just hangs.

The `on('refresh', ...)` code fires, but my code never resumes from where the `describeGlobal$` call was made. Looks like it could be related to https://github.com/jsforce/jsforce/issues/756 as the cached calls are not returning the right thing. Bummer!

**Comment by cristiand391** [comment]
triaging old issues...

I did a quick test and can't repro this, but also not sure how OP was calling `describeGlobal$`.
Please re-open if it's reproducible in jsforce v3.
