### ISSUE TITLE
Questions on bulk Api : storing sf Id in local db

### ISSUE THREAD

**Issue by sushicodeur** [jsforce/jsforce#837]
Hello,

I've got a question to be sure to do things the right way. In this code sample from the documentation (https://jsforce.github.io/document/#load-from-records) 

```
// Provide records
var accounts = [
  { Name : 'Account #1' },
  { Name : 'Account #2' },
  { Name : 'Account #3' },
];
// Create job and batch
var job = conn.bulk.createJob("Account", "insert");
var batch = job.createBatch();
// start job
batch.execute(accounts);
// listen for events
batch.on("error", function(batchInfo) { // fired when batch request is queued in server.
  console.log('Error, batchInfo:', batchInfo);
});
batch.on("queue", function(batchInfo) { // fired when batch request is queued in server.
  console.log('queue, batchInfo:', batchInfo);
  batch.poll(1000 /* interval(ms) */, 20000 /* timeout(ms) */); // start polling - Do not poll until the batch has started
});
batch.on("response", function(rets) { // fired when batch finished and result retrieved
  for (var i=0; i < rets.length; i++) {
    if (rets[i].success) {
      console.log("#" + (i+1) + " loaded successfully, id = " + rets[i].id);
    } else {
      console.log("#" + (i+1) + " error occurred, message = " + rets[i].errors.join(', '));
    }
  }
  // ...
});
```

Are we guaranteed that the index of inserted datas in `rets` correlates to the index of objects as they are sent in `accounts` ?

If not how can I update my local db records to store the salesforce Id ?

**Comment by cristiand391** [comment]
Triaging some old issues here...

For anyone else curious, I can't tell from the API docs if the order of records in the matches the order of the data ingested for the the original Bulk API (`conn.bulk`), but the Bulk 2.0 docs note that the order isn't guaranteed:

https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/get_job_successful_results.htm
