### ISSUE TITLE
CORS issue - Metadata create call

### ISSUE THREAD

**Issue by manpuriasudip** [jsforce/jsforce#840]
Hi 

I am trying to use jsforce on a canvas app inside a developer edition salesforce org.

`
    this.jsForceConn.metadata.createSync('ApexPage', metadata, (err: any, results: any) => {
      console.log('Page creation request called.' , err , results);
    });
`

I have added my canvas url - 'https://canvas-url' to the CORS whitelist on salesforce.

`
Access to XMLHttpRequest at 'sfdc-instance' from origin 'https://canvas-url' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

console.log result - Page creation request called. Error: Access Declined

`

Please help me out.

**Comment by cristiand391** [comment]
triaging old issues...

`conn.metadata` uses mostly the SOAP API which doesn't support CORS. You'll need to set up a CORS proxy like this:
https://github.com/jsforce/jsforce-ajax-proxy/
