### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by timendez** [jsforce/jsforce#843]
On [this page](https://jsforce.github.io/document/#access-token-with-refresh-token), the access token's description has two r's in Salesforce:

```
...
  accessToken : '<your Salesforrce OAuth2 access token is here>',
...
```

**Comment by CognitiveClouds-Prasad** [comment]
Actually, I am having a hard time reading documentation. (No. I am not meaning two r in Salesforce)
The main example mentioned in https://jsforce.github.io/ for Web-browser itself does not work properly. It leads to INVALID_SESSION_ID. There are no complete examples. Documentation mentioned in https://jsforce.github.io/document/ refers to Node only. So, I really do not know how I can use this in my web-browser.

**Comment by timendez** [comment]
@CognitiveClouds-Prasad Your issue is entirely different from issue #843. Please open a new one.

**Comment by lms15** [comment]
Hello Tim, I have to stop now I have a family issue and cannot continue right now
Thanks for all your assistance, too much going on right now.
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lms15** [comment]
Hello, I have to stop now I have some family issue and cannot continue
Right now. Thanks for all your assistance
Mamie


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by techieshark** [comment]
PR is here: https://github.com/jsforce/jsforce-website/pull/14

**Comment by cristiand391** [comment]
ref: https://github.com/jsforce/jsforce-website/pull/14#issuecomment-2192549145
