### ISSUE TITLE
jsforce.browser.on is not returning the connection. Nothing is returned in console.log when calling from finesse server.

### ISSUE THREAD

**Issue by mamoonrasheed** [jsforce/jsforce#844]
I have written this code inside finnese gadget which is hosted on finesse server but it does not return anything to console.

Code is given below --

var jsForceConn;
        jsforce.browser.init({
			clientId: "my Client Id",
			//clientSecret : 'my Client Secret',
            redirectUri: "http://addressToFinesseServer/callback.html",
            //proxyUrl: "https://node-salesforce-proxy.herokuapp.com/proxy/"
        });
		
        jsforce.browser.on('connect', function(conn) {
			var phone = 'xxxxxxx';
			var queryString = "SELECT Id,Name,Account.Name,Account.Industry FROM Contact WHERE phone = '" + phone + "'";
            conn.query(queryString, function(err, res) {
                if (err) {
                    return console.error(err);
                }
                console.log(res); -- **nothing is returned here.**	 	
            });
			jsForceConn = conn;
        });
		
But when I execute the same code from my local server it gets executed. @stomita

**Comment by mamoonrasheed** [comment]
Please assist @stomita

**Comment by cristiand391** [comment]
closing this, if someone hits  a similar scenario (jsforce not returning something), make sure to set `logLevel` when creating the connection and see the debug logs in the console to ensure auth happened.
