### ISSUE TITLE
Metadata Read for Profile is failing with sf:UNKNOWN_EXCEPTION: UNKNOWN_EXCEPTION: java.lang.NullPointerException

### ISSUE THREAD

**Issue by v15h9** [jsforce/jsforce#845]
In a handful of Sandboxes I'm able to authenticate but am not able to read Profile via conn.metadata.read. This is true when I use jsForce Documentation as well. 

The response I receive is as follows: 
`{"statusCode":500,"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:sf=\"http://soap.sforce.com/2006/04/metadata\"><soapenv:Body><soapenv:Fault><faultcode>sf:UNKNOWN_EXCEPTION</faultcode><faultstring>UNKNOWN_EXCEPTION: java.lang.NullPointerException</faultstring></soapenv:Fault></soapenv:Body></soapenv:Envelope>","headers":{"date":"Thu, 06 Dec 2018 16:56:01 GMT","cache-control":"no-cache,must-revalidate,max-age=0,no-store,private","set-cookie":["BrowserId=fDtDidoKQbWtrA5etRU-Rw;Path=/;Domain=.salesforce.com;Expires=Mon, 04-Feb-2019 16:56:01 GMT;Max-Age=5184000"],"expires":"Thu, 01 Jan 1970 00:00:00 GMT","content-type":"text/xml; charset=utf-8","transfer-encoding":"chunked","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"ceo--ceofull.cs90.my.salesforce.com","port":443,"hostname":"ceo--ceofull.cs90.my.salesforce.com","hash":null,"search":null,"query":null,"pathname":"/services/Soap/m/39.0","path":"/services/Soap/m/39.0","href":"https://ceo--ceofull.cs90.my.salesforce.com/services/Soap/m/39.0"},"method":"POST","headers":{"Content-Type":"text/xml","SOAPAction":"\"\"","content-length":784}}}`

Has anyone faced this issue? How can I debug Metadata API calls in Salesforce?

**Comment by cristiand391** [comment]
triaging old issues...

this seems like one of those intermittent server errors, we've seen a few on the Salesforce CLI from time to time.
For debuggin jsforce you usually set the log level when creating the connection, other than that it might require a Salesforce case for folks to look at the failure.
