### ISSUE TITLE
How to query VersionData from ContentVersion?

### ISSUE THREAD

**Issue by ringoyip0901** [jsforce/jsforce#852]
Hello, 

First, thanks for reading this post. Appreciate your time. 

I would like to export images from the ContentVersion object through "VersionData". I tried the following ways but didn't have any luck. What are the right ways to retrieve the blob data from the VersionData record? All my images are stored in the ContentVersion Object. Thank you!  

1.) conn.apex.get(
      "/services/data/v42.0/sobjects/ContentVersion/{id}",
      body,
      (err, res) => {
        if (err) console.error(err);
        req.blob = res;
      }
    );

2.)conn.sobject("ContentVersion").record("j0918230dsa").blob("VersionData").pipe(writeFile).on("error", err => console.error(err));

**Comment by EliranMoveo** [comment]
Did you find a way to do that?

**Comment by jsonpoindexter** [comment]
@EliranMoveo here is what I did
`     const fileData = await new Promise((resolve, reject) => {
          const writableStream = new Stream.Writable()
          let data = ''
          writableStream._write = (chunk, encoding, next) => {
            data += chunk
            next()
          }
          writableStream._final = (err) => {
            if (err) console.log(err())
            resolve(data)
          }
          sfApi.jsforceConn
            .sobject('ContentVersion')
            .record('*recordId*')
            .blob('VersionData')
            .pipe(writableStream)
        })`

**Comment by ddxxtony** [comment]
Hi @EliranMoveo ,@ringoyip0901 , , has anyone found a way to achieve this?
