### ISSUE TITLE
CustomObjectTranslation - metadata read doesn't return data for objects from package

### ISSUE THREAD

**Issue by vlamic** [jsforce/jsforce#853]
Hi!

I can successfully read using the Metadata API `CustomObjectTranslation` objects for standard and custom objects. However, only fullName is returned for objects installed with a package. 

The following works:
```
connection.metadata.read("CustomObjectTranslation", [ "Lead-en_US" ]);
```

And the following works:
```
connection.metadata.read("CustomObjectTranslation", [ "MyObject__c-en_US" ]);
```

This example doesn't return any data (I've verified the data exist within salesforce; the data is also returned via `retrieve` method). The `read` method fails:
```
connection.metadata.read("CustomObjectTranslation", [ "PKG__MyObjectFromPackage__c-en_US" ]);
```

Any recommendation what I'm doing wrong? Thank you!

**Comment by bucholcm** [comment]
Same issue for CPQ package with jsforce v.1.9.1

**Comment by cristiand391** [comment]
per API docs:

>The full names must match one or more full names returned by the listMetadata() call, which includes namespace prefixes. If you obtain the fullName from a package manifest file, and the component has a namespace prefix, prepend the namespace prefix to the fullName

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_readMetadata.htm?q=readMetadata

if anyone still experience this, can you share what `connection.metadata.list` returns for that type?
