### ISSUE TITLE
Typescript error with JSforce

### ISSUE THREAD

**Issue by pritisolanki** [jsforce/jsforce#854]
Hi There,

I just started getting error - error TS2559: Type '(err: Error, ret: any) => void' has no properties in common with type 'ExecuteOptions'.

`conn.query(emailquery,(err : Error, ret:any)`

I am not able to find any info on ExecuteOptions in the document. Can someone help me around on this.

**Comment by paustint** [comment]
Looking at the type definitions, it appears that the signature is not the same as the JSForce documentation.

Here is the type definitions (which, I agree, are incorrect)
```typescript
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsforce/query.d.ts
query<T>(soql: string, options?: ExecuteOptions, callback?: (err: Error, result: QueryResult<T>) => void): Query<QueryResult<T>>;

// Here is the interface I found in the type definition
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsforce/query.d.ts
export interface ExecuteOptions {
    autoFetch?: boolean;
    maxFetch?: number;
    headers?: object;
    scanAll?: boolean;
}

// here is the data structure of the result of the query
interface QueryResult<T> {
    done: boolean;
    nextRecordsUrl?: string;
    totalSize: number;
    records: T[];
}

```
I would recommend to file a bug with DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/issues.

What you can do instead is to use a promise instead of the callback and ignore the second and third parameters.  Most (not all) JSForce functions allow either a callback or a promise.

Examples:
```typescript
await conn.query("SELECT Id FROM Email");

// Alternatively you can add types, as the function is generic
interface Email {
  Id: string;
  Name: string;
  recipient: string;
  some_custom_field__c: string;
}

const results = await conn.query<Email>("SELECT Id FROM Email");

// If you are not using async await
conn.query<Email>("SELECT Id FROM Email")
.then(results => {
  // handle result
})
.catch(err => {
  // handle me
})
```

**Comment by snps-swwang** [comment]
I got same error when calling "find" function, any idea how to resolve this?

conn
        .sobject("Engagement__c")
        .find(
          // conditions in JSON object
          {
            Name: { $like: "%" + inputEngagement + "%" },
            "project__r.name": { $like: "%" + inputProject + "%" },
            "project__r.logo__r.name ": { $like: "%" + inputLogo + "%" },
            "Sales_Material__r.Tier_1__c": {
              $like: "%" + inputTier1 + "%",
            },
            "Sales_Material__r.Tier_2_Product_Group__c": {
              $like: "%" + inputTier2 + "%",
            },
            "Sales_Material__r.Tier_3_Product_Category__c": {
              $like: "%" + inputTier3 + "%",
            },
          },
          // fields in JSON object
          {
            Id: 1,
            Name: 1,
            "project__r.logo__r.name ": 1,
            "project__r.name": 1,
            "Sales_Material__r.Tier_1__c": 1,
            "Sales_Material__r.Tier_2_Product_Group__c": 1,
            "Sales_Material__r.Tier_3_Product_Category__c": 1,
          }
        )
        // .sort({ CreatedDate: -1, Name: 1 })
        // .limit(5)
        // .skip(10)
        .execute(function (
          err: Error,
          records: [
            {
              // length: string;
              Id: string;
              Name: string;
              Project__r: { Name: string; Logo__r: { Name: string } };
              Sales_Material__r: {
                Tier_1__c: string;
                Tier_2_Product_Group__c: string;
                Tier_3_Product_Category__c: string;
              };
            }
          ]

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
