### ISSUE TITLE
How to refresh an expired refresh token ?

### ISSUE THREAD

**Issue by saichandesh** [jsforce/jsforce#855]
I'm establishing the connection using username and password + security token. Below is my piece of code.

 try {
&emsp; const connection = new jsforce.Connection({
       &emsp; &emsp;              oauth2: {
         &emsp;   &emsp;    &emsp;           loginUrl : loginUrl,
         &emsp;   &emsp;    &emsp;           clientId: consumerKey,
        &emsp;     &emsp;     &emsp;         clientSecret: consumerSecret,
           &emsp;   &emsp;         &emsp;    redirectUri: callbackUrl,
        &emsp;         &emsp;     },
       &emsp;          });
         &emsp;        await connection.loginByOAuth2(user, password + securityToken);
} catch(err) {
  &emsp;   console.log(err)
}

Recently I started getting error `invalid_grant: expired access/refresh token`. This seems that my refresh token or access token is expired.

Questions : 

1. Will jsforce automatically refresh the access token and refresh token?
2. If jsforce can't refresh the tokens, how should I do that. ( I have seen couple of examples which says I should pass a refresh token to the Connection object. But how should I get a refresh token ? `console.log(connection.refreshToken); // undefined ` ).

**Comment by tcampb** [comment]
I ran into a similar issue and it appears that a refresh token cannot be used with the username-password OAuth flow - https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_username_password_oauth_flow.htm.

You can use the Web Server OAuth flow to retrieve a refresh token - https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_web_server_oauth_flow.htm.

**Comment by lms15** [comment]
Ok thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
