### ISSUE TITLE
[bug] Jsforce redirects to APEX with a wrong method

### ISSUE THREAD

**Issue by ivawzh** [jsforce/jsforce#858]
## Context
I am trying to hit APEX backend with `POST` method through `conn.post`. Since `conn` has only stored instance URL of visualforce address, we are relying VisualForce to redirect us to APEX. 

However, in real life somehow the `post` method forwards us to the APEX endpoint with a wrong method - `GET` instead.

## Suspicion 
I have looked into the source code, Jsfource uses library `request` behind the scenes at https://github.com/jsforce/jsforce/blob/master/lib/api/apex.js#L85 with the whitelisted options https://github.com/jsforce/jsforce/blob/master/lib/api/apex.js#L30-L46 .

The `request` library has a way to handle following redirect URL with original method with option:

> `followOriginalHttpMethod` - by default we redirect to HTTP method GET. you can enable this property to redirect to the original HTTP method (default: false)

Therefore, I would suggest Jsforce to try allow passing a new boolean option `followOriginalHttpMethod` to support calling APEX with non-get methods.

**Comment by cristiand391** [comment]
triaging old issues...

jsforce v2 moved from `request` to `node-fetch` for API calls, can someone confirm if this still happens with jsforce >= 2?
