### ISSUE TITLE
Raise combined error object when multiple errors are found

### ISSUE THREAD

**Issue by stomita** [jsforce/jsforce#861]
When multiple errors occurred during creating/updating a record (e.g. matching multiple validation rules or multiple addError() in trigger), the REST API returns an array of errors. Currently JSforce only picks and reports the first one and abandons the rest.

To handle whole errors in applications, it is required to raise a combined error with details in array of errors.

```json
{
  "name": "MULTIPLE_ERRORS",
  "message": "Multiple errors returned",
  "errors": [{
    "errorCode": "FIELD_CUSTOM_VALIDATION_EXCEPTION",
    "message": "Invalid value passed to CloseDate",
    "fields": ["CloseDate"]
  }, {
    "errorCode": "FIELD_CUSTOM_VALIDATION_EXCEPTION",
    "message": "Invalid value passed to Amount",
    "fields": ["Amount"]
  }]
}
```

**Comment by stomita** [comment]
This is applied only when the `create()`/`update()` call is made in single record. When passed records in array the errors will be returned each SaveResult entry

**Comment by talbalelty** [comment]
When I perform bluk.load I need to collect all the errors that are related to a single record, in the rets[i].errors array. Only the first error is returned for each record. And solution?

**Comment by rcbevans** [comment]
I'm seeing this issue where the error from an invalid update is only providing one error message, despite multiple validation failures.

**Comment by talbalelty** [comment]
After investigating, I found that if you try to insert a record from Apex it will also throw a single error message.
This seems to be a Salesforce limitation.

**Comment by cristiand391** [comment]
this still happen in jsforce v3, the API returns 2 validation rules errors but jsforce only prints the first one:

```
response.body: [{"message":"bool value should be: &quot;true&quot;","errorCode":"FIELD_CUSTOM_VALIDATION_EXCEPTION","fields":[]},{"message":"wrong extId, it should be &qu
ot;123&quot;","errorCode":"FIELD_CUSTOM_VALIDATION_EXCEPTION","fields":[]}]


/Users/cdominguez/code/gh/jsforce/lib/http-api.js:280
        return new HttpApiError(error.message, error.errorCode);
               ^

FIELD_CUSTOM_VALIDATION_EXCEPTION: bool value should be: &quot;true&quot;
    at HttpApi.getError (/Users/cdominguez/code/gh/jsforce/lib/http-api.js:280:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/cdominguez/code/gh/jsforce/lib/http-api.js:127:33
    at async Connection.create (/Users/cdominguez/code/gh/jsforce/lib/connection.js:722:15)
    at async /Users/cdominguez/code/gh/jsforce/lala.js:12:22 {
  errorCode: 'FIELD_CUSTOM_VALIDATION_EXCEPTION',
  content: undefined
}
```
