### ISSUE TITLE
Retrieving package does not work.

### ISSUE THREAD

**Issue by VitalyGaiduchok** [jsforce/jsforce#865]
**jsforce version 1.9.1
jsforce-retrieve version 1.3.1**

I am trying retrieve package data for cyclr__Cyclr package and it does not work for me.

![screen shot 2019-02-21 at 13 09 31](https://user-images.githubusercontent.com/31094841/53164952-1e5c0300-35da-11e9-8405-43bd6bb4ae46.png)

command that I run: 
----------------------------------------------
jsforce-retrieve --sandbox -u myUser@test.com -p passSecurityToken --pollTimeout 1500000  --packageNames "cyclr__Cyclr" --zipFile cyclrPackage.zip ./retrieved

Also I tried retrieve this package without namespace, and that also did not help me.

**With all other packages that works fine for me**

output: 
----------------------------------------------
Logged in as: myUser@test.com
Retrieving from server...

Retrieve Failed.
UNKNOWN_EXCEPTION: More than 1 installed package named 'cyclr__Cyclr' exists in this organization.  Use <namespace_prefix>__<pkg_name> to uniquely identify managed installed packages

Id: 09SJobId
Status: Failed
Success: false
Done: true

No output files generated.

I was trying do the same thing with node js and get next error stack trace:
----------------------------------------------
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
buffer.js:202
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)
    at /myDir/node_modules/jsforce/lib/api/metadata.js:774:27
    at /myDir/node_modules/jsforce/lib/promise.js:72:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) 

failed object `{
  "done": "true",
  "errorMessage": "More than 1 installed package named 'cyclr__Cyclr' exists in this organization.  Use <namespace_prefix>__<pkg_name> to uniquely identify managed installed packages",
  "errorStatusCode": "UNKNOWN_EXCEPTION",
  "id": "09SJobId",
  "status": "Failed",
  "success": "false",
  "zipFile": {
    "$": {
      "xsi:nil": "true"
    }
  }
}`

**Comment by lms15** [comment]
Hello, thanks for your help, but I got so confused can I start over from the start I received several emails to  help me
Then I got confused.
Mamie


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jsullivanlive** [comment]
Might be related to this open issue:
https://trailblazer.salesforce.com/issues_view?id=a1p3A0000008gcuQAA

**Comment by rzinnatullin** [comment]
Getting the same error when using `Ant Migration Tool`:
![image](https://user-images.githubusercontent.com/11244866/144192178-86bf3ba6-237c-40e8-97d8-2fc00af3e4d3.png)


> Might be related to this open issue: https://trailblazer.salesforce.com/issues_view?id=a1p3A0000008gcuQAA

Yep, but the workaround suggested there does not work.
