### ISSUE TITLE
Ability to pass `rejectUnauthorized: false` to request to allow self-signed SSL certificates for certain Connection instances

### ISSUE THREAD

**Issue by aguynamedben** [jsforce/jsforce#867]
Thanks for the work you do on this library, we like it a lot. 🙏

I'm building an Electron app that connects to Salesforce. Certain customers see the following error when jsforce tries to call the Salesforce API:

```
self signed certificate in certificate chain
```
I believe this is because these employees are behind a corporate firewall that is terminating SSL with a corporate self-signed SSL certificate (i.e. basically a [corporately approved MITM "attack" on employees for Salesforce traffic](https://stackoverflow.com/questions/39639860/dealing-with-corporate-firewall-adding-self-signed-certificates)). When this case is detected, ideally I'd show some UI to the user that says "Allow self-signed certificate when calling Salesforce?", they'd click "Allow", and our app would re-create the jsforce `Connection` instance with the underlying `request` instance having `strictSSL: false` (or `rejectUnauthorized: false`).

I see [in the jsforce code](https://github.com/jsforce/jsforce/blob/master/lib/transport.js#L15) that I can set `request.defaults`, but I don't want to do this for EVERY `request` object in my app, just certain jsforce `Connection` instances. Ideally `Connection` would allow for `options.requestLibOptions` and I could set `options.requestLibOptions.strictSSL = false` if I wanted to.

Is that somehow do-able with the current jsforce library? From my read of the code, it'd require a pull request to allow custom options for the `request` library. Probably a branch [around here](https://github.com/jsforce/jsforce/blob/master/lib/connection.js#L81) to detect for `options.requestLibOptions` and pass them to `new Transport()`?

There's another hacky option to set `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;` for the entire process, but that's heavy-handed and unnecessary if I can just tweak how jsforce is using request.

I'm happy to submit a PR to allow `request` to be configured per-Connection if that makes sense and there are no current workarounds.

**Comment by cristiand391** [comment]
triaging old issues...

jsforce v2 moved from `request` to `node-fetch` which doesn't seem to have a similar option like `strictFalse`.
Also, we are trying to minimize custom changes to the current node-fetch wrapper as we aren't sure we'll keep in future jsforce versions.
