### ISSUE TITLE
metadata.list can return an object instead of an array

### ISSUE THREAD

**Issue by mshanemc** [jsforce/jsforce#871]
When a metadata.list call returns only one item, it's coming as a single object, rather than a single object in an array.  This creates an edge case where anyone using jsforce depending on an array has to check that it is an array or convert that single object type to an array.  It'd be nice if jsforce ALWAYS returned an array (per the typedef for this function).

example issue: https://github.com/mshanemc/shane-sfdx-plugins/issues/23
example workaround: https://github.com/mshanemc/shane-sfdx-plugins/commit/8c4873030b93ae40b310e1cf51984c98e5ab0fc6#diff-af7cc77113d5c3316801d9402059e477

**Comment by DougMidgley** [comment]
Noticed as well when looking at typing. Issue relates to xml2js trying to convert to array or object depending on number of elements.  For me this was getting test failures, where one result would be object, while multiple would be array. 
https://www.npmjs.com/package/xml2js doesnt seem to have much flexibility in this, but fast-xml-parser does (https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#isarray). 
Not sure if changing lib would help, or if there is something which allows for TS definition based conversion?

**Comment by cristiand391** [comment]
Hey Shane 😉 

I'm unable to repro this on jsforce v3:

```ts
const results = await conn.metadata.list({ type: 'ApexClass' });
console.log(results)
```

with 1 class:
```
  console.log
    [
      {
        createdById: '0055200000BjPHrAAN',
        createdByName: 'User User',
        createdDate: '2024-05-23T16:52:14.000Z',
        fileName: 'classes/JSforceTestUtil.cls',
        fullName: 'JSforceTestUtil',
        id: '01p5200000c0SHDAA2',
        lastModifiedById: '0055200000BjPHrAAN',
        lastModifiedByName: 'User User',
        lastModifiedDate: '2024-05-23T16:52:14.000Z',
        manageableState: 'unmanaged',
        type: 'ApexClass'
      }
```

with 2 or more:
```
  console.log
    [
      {
        createdById: '0055200000BjPHrAAN',
        createdByName: 'User User',
        createdDate: '2024-05-23T16:52:14.000Z',
        fileName: 'classes/JSforceTestUtil.cls',
        fullName: 'JSforceTestUtil',
        id: '01p5200000c0SHDAA2',
        lastModifiedById: '0055200000BjPHrAAN',
        lastModifiedByName: 'User User',
        lastModifiedDate: '2024-05-23T16:52:14.000Z',
        manageableState: 'unmanaged',
        type: 'ApexClass'
      },
      {
        createdById: '0055200000BjPHrAAN',
        createdByName: 'User User',
        createdDate: '2024-05-23T16:52:14.000Z',
        fileName: 'classes/JSforceTestUserPool.cls',
        fullName: 'JSforceTestUserPool',
        id: '01p5200000c0SHCAA2',
        lastModifiedById: '0055200000BjPHrAAN',
        lastModifiedByName: 'User User',
        lastModifiedDate: '2024-05-23T16:52:14.000Z',
        manageableState: 'unmanaged',
        type: 'ApexClass'
      }

```


the server response didn't change but jsforce v2 started casting the response if you pass a schema (`conn.list`) does, so you always have an array:
https://github.com/jsforce/jsforce/blob/af8a10e84557d95e20a62dae37e9dbf1e4d50fa8/src/soap.ts#L231
