### ISSUE TITLE
Please add support of v45.0 for signed requests

### ISSUE THREAD

**Issue by evgemar** [jsforce/jsforce#872]
Signed request of canvas application returns links for v45.0 but JSforce ignore it and trying to use v42.0 urls that is wrong.

**Comment by lms15** [comment]
Ok everything I do is wrong, I will keep trying
Mamie

**Comment by cristiand391** [comment]
triaging old issues...

the default API version used in jsforce v3 is `50.0`, you can also specify it when creating a connection and it will be used for all requests.
