### ISSUE TITLE
how to logout from salesforce

### ISSUE THREAD

**Issue by sumanthhg** [jsforce/jsforce#877]
by using below code i am able to expire session but not logut from salesforce.

var conn = new jsforce.Connection({
    sessionId : req.session.accessToken,
    serverUrl : req.session.instanceUrl,
  });
  conn.logout(function(err) {
    if (err) { return console.error(err); }
    // now the session has been expired.
    console.log('done!!!');
  });

**Comment by lms15** [comment]
Good morning, the visual instructions are going to fast, my eyes have to have time
To focus on where to pointer is touching is there a way to slow down visuals
To allow me a chance to focus where you are touching. I going to speak to my
Ophthalmologist to see if this is good for me to do just to stay busy and use my brain
Lol.
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lms15** [comment]
Oh! I coped down what to key in but does package have to load terminal
To type? in where I typed turns red so it must be wrong but I get line numbers
mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lms15** [comment]
Hello, I need to study atom to learn how to use it to benefit me
And I want to choose the right package and theme. Let me review
Some videos to better understand your guidance. I am stuck again
My project he not showing and I did not know what was next.
Pull push merge it seems to be incorrect lol I see your OOOOps
Thanks for all your assistance I thank you all for your patience with
Me.
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lms15** [comment]
Hello, I got lost again and I need to learn how to use atom and the functions. Let me spend some
time on using atom and it does make things easier for me. 
Thanks for all your assistance, just review Travis setup on Atom in youtube
Thanks
Mamie
