### ISSUE TITLE
conn.login not working when hosted on AWS Lambda with Node8.10

### ISSUE THREAD

**Issue by ALB5** [jsforce/jsforce#878]
Hello everyone,

I am currently running a script on AWS Lambda using jsforce. I need to update the runtime from Node6.10 to 8.10. 
However, while I manage to make the script work locally with the 8.10 version, it is not working on AWS Lambda. 

For some reasons, this piece of code is not working anymore on AWS Lambda. 

```
let connnection = new jsforce.Connection( { loginUrl: 'https://eu16.salesforce.com' } );
connnection.login( config.get( 'salesforce_login' ), config.get( 'salesforce_password' ), function( err ) {
        if ( err ) { return logger.error( err, true ); }
        instance = connnection.instanceUrl;
        token = connnection.accessToken;
} );
```

Any idea about what could be the issue ?

**Comment by lms15** [comment]
Thanks you I have some issues with eyes

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by paustint** [comment]
Are you appending the API token to your password? If the AWS ip is not
whitelisted, then bother the password and API token must be provided.

**Comment by ALB5** [comment]
Yes, I am appending the API token. 
What is totally weird is that it is currently working with Nodejs6.10 in Lambda, and Nodejs8.10 but locally only, without changing anything.

**Comment by ALB5** [comment]
After further investigation, it sounds like it is blocked in `connection.js` class. I can get some logs in `Connection.prototype.loginBySoap` but this is not returning any response:
```
return this._transport.httpRequest({
    method : 'POST',
    url : soapLoginEndpoint,
    body : body,
    headers : {
      "Content-Type" : "text/xml",
      "SOAPAction" : '""'
    }
  })
```

If I dig deeper, I end up in transport.js. class. I noticed that Transport.prototype.httpRequest method is currently using `Promise.defer()` which is supposed to be deprecated. Could this be the issue?

**Comment by lms15** [comment]
Hello, I have some family issues and cannot continue at this time. Thanks for all your
Assistance.
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by timendez** [comment]
Hi Mamie, these emails you are receiving aren't specifically directed to you, but to a large mailing list that you are on. Go ahead and press the unsubscribe button as these emails don't seem to pertain to what you are working on.

**Comment by dhenard** [comment]
Did you find a solution?  I'm trying with Node.js 10.x on AWS and what works locally to login is not working on AWS lambda.

**Comment by cmcmd4377** [comment]
Same. Did anyone figure this out. Same issue with Node 12.13.1.

**Comment by maan6050** [comment]
You should use **Username**, **Password** and **Security Token** for authentication. Here is my code and it works fine:
```
var jsforceConn = new jsforce.Connection({
    // you can change loginUrl to connect to sandbox.
    // loginUrl : 'https://test.salesforce.com'
});
jsforceConn.login("[SalesForceUsername]", "[SalesForcePassword][SalesForceToken]", function(err, user) {
    if (err) { return console.error(err); }
    console.log(jsforceConn.accessToken);
    console.log(jsforceConn.instanceUrl);
    console.log(user.id);
    console.log(user.organizationId);

    jsforceConn.query("SELECT Id, Name FROM Account", function(err, result) {
        if (err) { return console.error(err); }
        console.log("total : " + result.totalSize);
        console.log("fetched : " + result.records.length);
    });
});
```

**Comment by shresthaankit7** [comment]
I'm getting the same issue of not invoking `login` method  in AWS lambda for node JS 10.x or 12.x.
The function `login` is not working and also, if I tried the Oauth2 method (which i have already made callbacks) the `authorize` method is not invoking(for OAuth2, I can handle if login works, basically issue is same).

Here is my index.js (i'm using `lambda-api` and `jsForce`dependencies for my work)
Code snippet here:

```
// Require the framework and instantiate it
const api = require('lambda-api')()
const jsForce = require('jsforce')


api.get('/', async (req, res) => {
    console.log("I am on main end-point!!! / Slash called")
    res.redirect(jsForce.getAuthorizationUrl({ scope : 'api id web' }));
});

api.get('/login', async (req,res) => {
  console.log("Login Called!!")

  var conn = new jsForce.Connection({
    // you can change loginUrl to connect to sandbox or prerelease env.
    loginUrl : 'https://XXXXXX--testing.my.salesforce.com'
  });

  console.log("RUNNING async");

  try{
    conn.login("UserName", "Password and Security token")
    .then(userInfo =>{
        // Now you can get the access token and instance URL information.
        // Save them to establish connection next time.
        console.log(conn.accessToken);
        console.log(conn.instanceUrl);
        // logged in user property
        console.log("User ID: " + userInfo.id);
        console.log("Org ID: " + userInfo.organizationId);

        return { status: 'ok' }
    }).catch(err=>{
        console.log("ERRORR !!!!!");
        return console.error(err); 
    });
  }catch(e){
    console.log("E>>>>>>>>");
    console.log(e);
  }
});

api.get('/oauth2/callback', async (req,res) => {
  console.log("Callback url called !!")
  return { status: "Oauth is here now"}
});

// Define a route
api.get('/status', async (req,res) => {
    console.log("HI!!!>> Status called")
  return { status: 'ok' }
})
 
// Declare your Lambda handler
exports.handler = async (event, context) => {
  
  return await api.run(event, context)
}
```
