### ISSUE TITLE
Ip restricted oauth and heroku

### ISSUE THREAD

**Issue by jeremym148** [jsforce/jsforce#884]
Hi 

Im trying to connect with a specific profile that has restricted ip with the OAuth 2 from node js on heroku, 
On heroku Im using proxy quotaguard in order to have an ip fix and so connect using jsforce but when I did it using proxyUrl, but  it is not working...

router.get('/salesforce', (req, res) => {
    oauth2 = new jsforce.OAuth2({
        proxyUrl: keys.QUOTAGUARDSTATIC_URL,
        loginUrl: keys.SF_LOGIN_URL,
        clientId: keys.SF_CLIENT_ID,
        clientSecret: keys.SF_CLIENT_SECRET,
        redirectUri: keys.SF_AUTH_CALLBACK}
    });

    res.redirect(oauth2.getAuthorizationUrl({
        scope: 'id',
        prompt: 'login',
        grant_type: 'authorization_code'
    }));
});

**Comment by lms15** [comment]
Hello, I have a family issue and was unable to respond
Mamie

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
