### ISSUE TITLE
AccessToken undefined

### ISSUE THREAD

**Issue by gitcryptocoin42** [jsforce/jsforce#887]
Hi,

Since i've changed my password of my SF account (and so refresh my securityToken by the way), JSforce connection returns error 'Cannot read property 'id' of undefined'. 
Console displays conn.instanceUrl and conn.accessToken are undefined.
But yet, Apex API connexion appears on SF historical connexion and state is 'active'. 

SOAP Partner | France | IP | 11:18 | Other Apex API | Session active

Before this change, all was ok since 3 years. On JS FILE, i've just changed password + securityToken like my SF account. No more change. 

API Version : 37.0
I've tried on 42.0, same problem

Thanks for your help

**Comment by dvera12** [comment]
Hi,
Can you please share your code in order to help you?

**Comment by sundariragavan** [comment]
Hi, 
 I have implemented salesforce login in react project using jsforce.  Its working fine and returning the value (access token)
 ` jsforce.browser.init({
      clientId: "client id",
      redirectUri: "https://localhost:3000/salesforce",
    });

    jsforce.browser.login();

    jsforce.browser.on("connect", function(conn) {
   // access token
    });`

But i want to implement the salesforce login in outlook Add Ins ( React ). Unable to get the access token.  
`jsforce.browser.init({
      clientId: "client id",
      redirectUri: "https://localhost:3000/taskpane.html",
    });
    jsforce.browser.login();
    jsforce.browser.on("connect", function(conn) {
    // access token
    });`
In outlook react add ins unable to get the data. Please help me to solve the issue
Thanks
