### ISSUE TITLE
CORS error on logout

### ISSUE THREAD

**Issue by joelabair** [jsforce/jsforce#890]
calling `jsforce.browser.logout();` produces the following errors in the js console

Access to XMLHttpRequest at 'https://na42.salesforce.com/services/oauth2/revoke?token=####' (redirected from 'https://xxx.xxx/jsforce-proxy?###') from origin 'https://xxx.xxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by kharatps02** [comment]
I'm also getting the same error.

**Comment by cristiand391** [comment]
triaging old issues...

see: https://github.com/jsforce/jsforce/issues/980#issuecomment-574195234
