### ISSUE TITLE
Creating records in Salesforce which share a master-detail relationship.

### ISSUE THREAD

**Issue by anupamabalahara** [jsforce/jsforce#895]
Is there a way to create records in SF objects which share a master-detail relationship?

Say I have 100 Master records with 600 Details records which need creation in SF.

One solution is to use
1. .sObject.create call to create 100 Master records
2. Use .find to locate their IDs
3. Later use their IDs to create 600 Detail records

Is there any other better way to achieve the same using jsforce ?
Because I believe the above would result in a large number of API calls.

**Comment by paustint** [comment]
You probably want to use the bulk API if your volume is that high. Check out the docs for examples of chaining logic together.

 In addition, the ID is included in the response from the first insert, so you do not need to make more API calls just to find the id of the master record, as you already have that.

Finally, you can use the composite API as another option to handle this operation with fewer round trips, but this might be more work to setup. (Look at sfdc docs for examples of how it works, then use conn.request to invoke those apis)

**Comment by anupamabalahara** [comment]
Thank you @paustint for your response.

I can see that the ID is included in the first insert, but I was planning to use the allowRecursive in the Step1 of create.

**Comment by anupamabalahara** [comment]
Would you be able to provide me any examples of using the composite API using jsforce. Would like to try that as it shall be fewer API calls to SF. @paustint

**Comment by stomita** [comment]
JSforce's create/insert call is now using SObject collection API which has 200 records limit at one op call. You can use bulk API for much larger amount of records, but if you like to do it in sync the `allowRecursive` option will do it for you. Here is an example:

```js
// Create 1000 accounts, more than SObject Collection limit (200)
var accounts = [];
for (var i=0; i<1000; i++) {
  accounts.push({ Name: 'Account #' + (i+1) });
}
// Internally dividing records in chunks,
// and recursively sending requests to SObject Collection API
conn.sobject('Account')
  .create(accounts, { allowRecursive: true }).then((rets) => {
    console.log('processed: ' + rets.length);
  });
```

**Comment by stomita** [comment]
Approximate API call num:

> 1. .sObject.create call to create 100 Master records

--> 1 API call

> 2. Use .find to locate their IDs

--> 1 API call

> 3. Later use their IDs to create 600 Detail records

--> 3 API calls

In total: 5 API calls

**Comment by anupamabalahara** [comment]
Thanks @stomita and @paustint .

I looked at both the options:
1. Composite 
2. Using sObject.create, find 

I am still unsure which shall be best to handle large number of records and will give me fewer API calls.

Need you assistance.

I have a JSON like so:
[{ parentNo: '1', parentName: 'One', childNo: 'a', childName: 'aa'}
{ parentNo: '1', parentName: 'One', childNo: 'b', childName: 'bb'}
{ parentNo: '2', parentName: 'Two', childNo: 'c', childName: 'cc'}]
{ parentNo: '3', parentName: 'Three', childNo: 'd', childName: 'dd'}]
{ parentNo: '3', parentName: 'Three', childNo: 'e', childName: 'ee'}]
{ parentNo: '3', parentName: 'Three', childNo: 'f', childName: 'ff'}]
{ parentNo: '4', parentName: 'Four', childNo: 'g', childName: 'gg'}]


I want the above to be inserted in a master detail relationship objects like so

ParentObject - fields: parentNo, parentName
ChildObject - fields: childNo, childName

SF records result
4 records in ParentObject
7 records in ChildObject

Now I can use jsforce sObject API calls like mentioned above:
1. create the 4 records in ParentObject _(single api call)_
2. find records created = TODAY //Unsure if this is the correct way, but how else can i find the ids of the records created above _(single api call)_
3. create the 7 records in ChildObject _(single api call)_
In the above scenario, there would be I believe JSON manupulation to get the input which gets fed into the 1st and the 3rd calls. Also, using the where clause in find is (seems) unsafe, as there can be anything else in the system which was created TODAY.
I believe you understand the issue here, **chaining** seems to be the issue.

However looking at Composite API , chaining seems simple.
One can create something like below:
connection.requestPost('/services/data/v45.0/composite/tree/ParentObject/', {
              'records' : [
                 {
                     'attributes' : {'type' : 'ParentObject', 'referenceId' : 'newFile'},                    
                     'parentNo' : '1'
                     'parentName' : 'One'
                     'ChildObject' : {
                         'records': [
                             {
                            'attributes' : {'type' : 'ChildObject', 'referenceId' : 'ref1'},                        
                               'childNo' : '1'
                               'childName' : 'One'                             },
                             {
                                'attributes' : {'type' : 'ChildObject', 'referenceId' : 'ref2'},                        
                               'childNo' : '2'
                               'childName' : 'Two'                                }]
                    }
                 }]}, function( err, records) {
             });
in a single API call.
But what the above gives me a single API call for each ParentObject-ChildObject creation which for the above example would total 4 API calls. And this number will increase if my ParentObject number increases.

Is my thinking correct?
Is there a solution which gives me fewer API calls and reduces the chaining?

The above a create logic I am working on. 
Next an update logic is also need to be worked upon which will include update existing ParentObject - find ChildObjects for the updated Parent - delete ChildObjects for the updated Parent and then recreate them for the Updated Parent. More chaining required.

**Comment by cristiand391** [comment]
triaging old issues...

as mentioned above, bulk API is likely the solution, bulk v2 examples:
https://jsforce.github.io/document/#bulk-v2-api

an insert job will return IDs of created records which then can be used for child objects.
