### ISSUE TITLE
this._updateSingle is not a function.

### ISSUE THREAD

**Issue by nerdybeast** [jsforce/jsforce#897]
Upgrading from version 1.8.5 to one of the 1.9.x versions throws a `this._updateSingle is not a function.` error in the `Connection.prototype.update` function inside connection.js.

I am calling `tooling.sobject("TraceFlag").update({...})` when the error is thrown. 

I clearly see `Connection.prototype._updateSingle` defined in that file so I'm not really sure what's going on... 

I'm running node: 10.15.1

I can repro this error by installing jsforce globally, logging into a sandbox via the jsforce repl, and running this command:
```
tooling.sobject('TraceFlag').update({ Id: 'xxxxxxxxxxxxxx' });

TypeError: this._updateSingle is not a function
    at Tooling.Connection.update (C:\Users\michael.penrod\AppData\Roaming\npm\node_modules\jsforce\lib\connection.js:841:14)
    at module.exports.SObject.update (C:\Users\michael.penrod\AppData\Roaming\npm\node_modules\jsforce\lib\sobject.js:94:21)
```

**Update**
Calling the non-tooling version of an sobject update works just fine:
```
sobject('Account').update({ Id: 'xxxxxxxxxxxx' })
```
So it appears the issue only exists with the tooling connection instance.

Rolling back to version 1.8.5 temporarily fixes the issue for me.

**Comment by cristiand391** [comment]
triaging old issues...

I can't repro this on jsforce v3, if anyone sees this again please file a new issue.
