### ISSUE TITLE
Records fetch limit decreases after several requests

### ISSUE THREAD

**Issue by calmeeee** [jsforce/jsforce#898]
Hello.
I'm trying to fetch records from my org.
For first several requests it returns the amount, as the same SOQL in Develop Console, e.g. 1500
But then, after several requests it begins to return only maximum 1000 records.
Firstly, I queried al through query chain, and this happened.
Then, I switched to single string, and again, after 10-15 successful responses, SF became to return maximum 1000 records with same conditions.
Is there a way not to use OFFSET? Maybe it happens because of limits of requests from concrete IP or what?

**Comment by paustint** [comment]
Salesforce will return a different number of records based on how expensive the dataset is. E.x. if you have a subquery in your SOQL and all records have related child recs, that will return fewer records.

This is not something that can be controlled and it is how the SFDC API works and is not related to JSForce. I have seen as few as 100 records be returned or as many as 2000 records being returned from any individual query.

**Comment by calmeee** [comment]
> Salesforce will return a different number of records based on how expensive the dataset is. E.x. if you have a subquery in your SOQL and all records have related child recs, that will return fewer records.
> 
> This is not something that can be controlled and it is how the SFDC API works and is not related to JSForce. I have seen as few as 100 records be returned or as many as 2000 records being returned from any individual query.

Thanks for the answer, paustint.
But still, why it used to return full set of records with same conditions at several early responses?
