### ISSUE TITLE
How many API call would the following query use?

### ISSUE THREAD

**Issue by thomas-33across** [jsforce/jsforce#899]
Hello
I have a questions in regard to the query call to the SF api and want to know how many API call would the following query use?
let's say the total records in SF is around 17,000 records, and we are doing the streaming of the data that's return from the API call

```
sfConnection
          .query('SELECT id from Opportunity')
          .run({ autoFetch : true, maxFetch:999999 })
          .pipe(saveData)
          .on('finish', resolve)
```

Thank you

**Comment by paustint** [comment]
@thomas-33across - this all depends on how expensive the API calls are. Salesforce returns a variable amount of records based on the fields/relationships/subqueries included in the query AND depending on what data is populated in the records.

For example, in an org I have here is my results:
**Query all fields on accounts** - 200 at a time out of of 54,196 records
**SELECT ID FROM Account** - 2,000 of 54,196 records

I have also seen where individual datasets returned can vary (usually if you have a subquery where many records don't have the child records, then other segments of the data where lots of records have the related child records).

**Here is my take on this**:
1. You probably don't need to be concerned about the number of API calls made unless you have a process that is extremely high volume
1. I have an application where we auto-download records if the user asks us to, and many users have downloaded 80K+ records, plus tons of other calls and never hit API limits
1. `.run({ autoFetch : true, maxFetch:999999 })` --> for some reason I always had problems with autoFetch - it never seemed to work, so I built my own system to do this.
1. While 17K records is not very high volume, you will gain a lot of performance by using the bulk API. ou will need to poll for changes (which takes multiple API calls - but again, you probably do not need to be concerned with this) and then you can download the results.
