### ISSUE TITLE
Property 'extIdField' is missing - For BulkOptions - bulk.d.ts issue

### ISSUE THREAD

**Issue by toddhalfpenny** [jsforce/jsforce#900]
It looks like the _bulk.d.ts_ file is incorrect, and I believe the `extIdField` is optional for the `BulkOptions` (based upon what I think is the case in the source).

I'm unsure how to raise a PR for this, as I think the _bulk.d.ts_ is in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jsforce). Is it the case that I can fork DefinitelyTyped and submit a PR to that project? Thanks

**Comment by combizs** [comment]
@toddhalfpenny seems to be in the [source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5c50029a816d86e094146003c7e815e07da9d95b/types/jsforce/bulk.d.ts#L10) now

good to close, @mdonnalley?

**Comment by cristiand391** [comment]
closing as it was added (not as optional tho) in `@types/jsforce` (types for jsforce v1).
`extIdField` is an optional prop since jsforce v2.
