### ISSUE TITLE
Can someone explain what pollTimeout and pollInterval do together?

### ISSUE THREAD

**Issue by rstor1** [jsforce/jsforce#901]
It is not clear to me what these do together to help with the Bulk API. I have a batch size of 5000 and `this.connection.bulk.pollTimeout = 1800000` without any pollInterval set. I am getting a polling timeout error and wondering if I need to add a pollInterval variable as well and how would one know at what value to set the pollInterval? 

Thanks

**Comment by rstor1** [comment]
Added my question here: https://github.com/jsforce/jsforce/issues/298

**Comment by rstor1** [comment]
Opened this back up because I was not sure if closed questions get reviewed if commented on...

**Comment by keanedawg** [comment]
I am interested in this as well

**Comment by cristiand391** [comment]
closing this, updated bulk v1/v2 docs:
https://jsforce.github.io/document/#bulk-v2-api
