### ISSUE TITLE
SQLBuilder feature

### ISSUE THREAD

**Issue by anupamabalahara** [jsforce/jsforce#903]
Hello, seeing unexplained behaviour when trying to use the SQLBuilder option in jsforce. Below is my lines of code. I would expect the jsforce query to return only two rows; however I observe details of all the users are logged out. Seems like the condition is not being applied at all. Is the feature available to use ?

```
         var queryConfig = {
            fields: [ "Name", "Profile.Name" ],
            table: "User",
            condition: {
                $or: [
                    { Id: '005D0000003d8xS' },
                    { Id: '005L0000003djbr' }
                  ]
              }
        };

        connection.query(queryConfig).on("record", function(record) {
            console.log(record);
          }).execute();
```

**Comment by douglascayers** [comment]
Hi @anupamabalahara,

You have a typo in your query config. `condition` should be `conditions` with an 's'.
