### ISSUE TITLE
lodash version is subject to high severity Prototype pollution security vulnerability

### ISSUE THREAD

**Issue by doubleminus** [jsforce/jsforce#904]
jsforce is currently using lodash 4.11.1.

Thus it is vulnerable to this issue: https://github.com/lodash/lodash/pull/4336

So lodash needs to be updated to version >=4.17.13 to resolve this.

**Comment by stomita** [comment]
The vulnerable version is removed and updated to the latest in #905.
Also released ver 1.9.2.
