### ISSUE TITLE
ERROR_HTTP_400

### ISSUE THREAD

**Issue by karpikdima** [jsforce/jsforce#916]
`this.connection
.query(thread.query)
.on("record", function(record) {
self.onRetrieveRecord(record,thread);
})
.on("end", function(result) {
self.onRetrieveEnd(result,thread);
})
.on("error", function(err) {
self.onRetrieveError(err);
})
.run({ autoFetch : false});`

When querying "Attachment" I get an error:
![Screenshot from 2019-08-06 15-03-56](https://user-images.githubusercontent.com/28755320/62538679-10363200-b85c-11e9-9cd7-0d5f2620feb3.png)

**Comment by paustint** [comment]
Assumption: you are using Heroku to proxy your connection.

Heroku has a time limit of 30 seconds before Heroku terminates the connection. This seems like you made a very expensive query that is exceeding the 30 second window.

I am not 100% positive on this, but it seems like a place to investigate: https://devcenter.heroku.com/articles/request-timeout

**Comment by karpikdima** [comment]
Thanks for your reply. Could you tell me if there is any way to fix this?

вс, 27 окт. 2019 г. в 21:28, Austin Turner <notifications@github.com>:

**Comment by paustint** [comment]
If that is for sure the issue, then you will need to reduce your query
complexity so that it returns sooner or use the bulk api.

You might want to test locally without using the proxy to see if that makes
a difference to confirm it is the cause.
