### ISSUE TITLE
Query objects produce improper unhandled promise rejections in some cases

### ISSUE THREAD

**Issue by ethanresnick** [jsforce/jsforce#920]
Jsforce Query objects have a dual identity as thenables and readable streams, which means there should be two ways to handle errors (in addition to the callback style):

```js
query
  .on("record", () => { /* ... */ })
  .on("error", () => { /* ... */ })
  .run({  /* ... */  })
```

or 

```js
query
  .run({  /* ... */  })
  .catch () => { /* ... */ })
```

Right now, though, someone using the first form will get an unhandled promise rejection error in the event that the query fails. The issue seems to be that jsForce assumes that the Query is being used as a Promise because `run` isn't given a callback, so it rejects the underlying deferred (producing the error), without having accounted for this "used as a stream with error listener" case.

There's also a related error, which is that, if the Query is used with CPS error handling, but the callback throws, that also causes the Promise to reject, triggering the unhandled rejection error. This feels incorrect to me — a callback throwing could/should trigger an uncaught exception error, but it probably shouldn't trigger the rejection of a promise that the user didn't intend to exist when they called `run()` with a callback. (Also, the return value from the callback — likely undefined — is being used as the resolution value of the deferred which, on the off-chance anyone is listening, is very weird.)

I think all these issues can be fixed by changing [promiseCallback](https://github.com/jsforce/jsforce/blob/b6bebda5a5b9d963413649f4553a6cd382bed4a9/lib/query.js#L334) to be something like:

```js
var promiseCallback = function(err, res) {
  if (_.isFunction(callback)) {
    callback(err, res);
  } 
  // Detect that query isn't used as an event emitter before settling the deferred. 
  // Technically, this should look if the user's registered _any_ listeners (not just an 
  // error listener), but this code is just an example. There might also be an off-by-one 
  // error in this check, since I haven't tested + don't know exactly when `once`
  // listeners  are removed (i.e., before or after running the listener callback),
  // but you get the idea. If the Query is being used as a event emitter, we
  // don't have to do anything 
  else if(this.listenerCount('error') === 0) {
    if (err) {
      deferred.reject(err);
    } else {
      deferred.resolve(res);
    }
  } 
};
```

**Comment by cristiand391** [comment]
triaging old issues...

I think this is fixed in jsforce v3.
`Query` catches the errors here and emits `error`:
https://github.com/jsforce/jsforce/blob/b661afdd21729812974f1056e392f2f58fc21096/src/query.ts#L575

which is can be handled by the `error` handler defined by the user.

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
