### ISSUE TITLE
Not able to set the oauth2 loginUrl in a dynamic way

### ISSUE THREAD

**Issue by PRF-IPA** [jsforce/jsforce#921]
Hi,

I am trying to sign in using oauth2, I would want to have the option between going to either 
`https://test.salesforce.com OR https://login.salesforce.com`

My oauth2 object looks like this:

```
let oauth2 = new jsforce.OAuth2({
  loginUrl: null,
  clientId: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET,
  redirectUri: process.env.REDIRECT_URI
});
```
It seems using it like this without having a defined loginURL will cause it to crash the server.

In my application I have something like this code snippet for both sandbox and production environment and this is how i set the url for the loginURL.

```
router.post("/salesforce-sandbox", (req, res, next) => {
  if (req.session.currentUser) {
    res.redirect("/dashboard");
  } else {
    oauth2.loginUrl = "https://test.salesforce.com";
    console.log(oauth2);
    res.redirect("/auth");
  }
});
```

the console.log prints out the following information, it would lead me to think that I've set the loginUrl correctly for the oauth2 object. Any idea how I can do this without the server crashing?

```
{
  loginUrl: 'https://test.salesforce.com',
  authzServiceUrl: 'https://test.salesforce.com/services/oauth2/authorize',
  tokenServiceUrl: 'https://test.salesforce.com/services/oauth2/token',
  revokeServiceUrl: 'https://test.salesforce.com/services/oauth2/revoke',
  clientId: 'clientid here',
  clientSecret: 'secret here',
  redirectUri: 'http://localhost:3000/auth/token',
  _transport: {}
}
```

it seems to crash when it reaches this code snippet:

```
router.get("/", (req, res, next) => {
  if (req.session.currentUser) {
    res.redirect("/dashboard");
  } else {
    res.redirect(
      oauth2.getAuthorizationUrl({ scope: "api id web refresh_token" })
    );
  }
});
```

**Comment by paustint** [comment]
Your best option here would be to create two different `conn` objects - one for prod and another for test instead of trying to change the URL on the fly.

For authorization, 

I have an app where every user is using a different org on any SFDC environment they might wish to use.

To authenticate when a user wants to connect a new org, I do something like this:
```javascript
const oauth2 = new jsforce.OAuth2({
    loginUrl: loginUrl,
    clientId: process.env.clientId,
    clientSecret: process.env.clientSecret,
    redirectUri: process.env.redirectUri,
  })
const conn = new jsforce.Connection({ oauth2 });

conn.authorize(code, function(err, userInfo) {
...
});
```

Then, in the future when a new request comes in, I create a new `conn` instance just for the request which can be garbage collected once the request is done - I do this in middleware (Express):
_Note: I tried to re-use a conn object across users but I ran into lots of issues and I would strongly discourage sharing conn across users_
```javascript
   // This could be pulled from a DB or the client could store and send to you etc..
    const authInfo = {
      loginUrl: req.get('loginUrl'),
      instanceUrl: req.get('instanceUrl'),
      accessToken: req.get('accessToken'),
      refreshToken: req.get('refreshToken'),
    };
  const connData = {
    oauth2: getOAth2(null, authInfo.loginUrl),
    instanceUrl: authInfo.instanceUrl,
    accessToken: authInfo.accessToken,
    refreshToken: authInfo.refreshToken,
    version, // I omitted where this is coming from
  };

req['sfdcConnection'] = new jsforce.Connection(connData);

```

**Comment by fredrikhogstrom** [comment]
> Your best option here would be to create two different `conn` objects - one for prod and another for test instead of trying to change the URL on the fly.
> 
> For authorization,
> 
> I have an app where every user is using a different org on any SFDC environment they might wish to use.
> 
> To authenticate when a user wants to connect a new org, I do something like this:
> 
> ```js
> const oauth2 = new jsforce.OAuth2({
>     loginUrl: loginUrl,
>     clientId: process.env.clientId,
>     clientSecret: process.env.clientSecret,
>     redirectUri: process.env.redirectUri,
>   })
> const conn = new jsforce.Connection({ oauth2 });
> 
> conn.authorize(code, function(err, userInfo) {
> ...
> });
> ```
> 
> Then, in the future when a new request comes in, I create a new `conn` instance just for the request which can be garbage collected once the request is done - I do this in middleware (Express):
> _Note: I tried to re-use a conn object across users but I ran into lots of issues and I would strongly discourage sharing conn across users_
> 
> ```js
>    // This could be pulled from a DB or the client could store and send to you etc..
>     const authInfo = {
>       loginUrl: req.get('loginUrl'),
>       instanceUrl: req.get('instanceUrl'),
>       accessToken: req.get('accessToken'),
>       refreshToken: req.get('refreshToken'),
>     };
>   const connData = {
>     oauth2: getOAth2(null, authInfo.loginUrl),
>     instanceUrl: authInfo.instanceUrl,
>     accessToken: authInfo.accessToken,
>     refreshToken: authInfo.refreshToken,
>     version, // I omitted where this is coming from
>   };
> 
> req['sfdcConnection'] = new jsforce.Connection(connData);
> ```

Thanks for the reply, got it fixed (I think, at least it works locally).
