### ISSUE TITLE
How to get expire time of access token and how to refresh token in oauth2 authorization

### ISSUE THREAD

**Issue by SumitCloudAnalogy** [jsforce/jsforce#932]
Here is my code
const conn = new jsforce.Connection({oauth2: oauth2});
const code = req.query.code;
conn.authorize(code, function (err, userInfo) {
if (err) {
return console.error("This error is in the auth callback: " + err);
}
let data = {
accessToken: conn.accessToken,
refreshToken: conn.refreshToken,
instanceUrl: conn.instanceUrl,
id: userInfo.id,
organizationId: userInfo.organizationId
};
console.log(conn);
console.log(userInfo

**Comment by SumitCloudAnalogy** [comment]
Here is my code 
const conn = new jsforce.Connection({oauth2: oauth2});
    const code = req.query.code;
    conn.authorize(code, function (err, userInfo) {
        if (err) {
            return console.error("This error is in the auth callback: " + err);
        }
        let data = {
            accessToken: conn.accessToken,
            refreshToken: conn.refreshToken,
            instanceUrl: conn.instanceUrl,
            id: userInfo.id,
            organizationId: userInfo.organizationId
        };
        console.log(conn);
        console.log(userInfo);

**Comment by cristiand391** [comment]
triaging old issues...

jsforce automatically refreshes expired access tokens for you if using oauth:
https://jsforce.github.io/document/#access-token-with-refresh-token
