### ISSUE TITLE
Dependency Audit - csv-parse Vulnerability

### ISSUE THREAD

**Issue by ghost** [jsforce/jsforce#938]
Your dependency, csv-parse, at the version you are using, causes a dos vulnerability, at its current version of 1.3.3. This has been patched in version >=4.4.6 of that package. 

`=== npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ csv-parse                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jsforce                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jsforce > csv-parse                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/1171                      │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 285284 scanned packages
  1 vulnerability requires manual review. See the full report for details.`

**Comment by createthis** [comment]
dupe of #925

**Comment by acrosman** [comment]
Fixed by #930

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
