### ISSUE TITLE
Cannot upload binary content using Apex REST

### ISSUE THREAD

**Issue by pozil** [jsforce/jsforce#946]
I'm uploading binary content (a JPEG file) to a custom Apex REST endpoint. I added a `'Content-Type': 'image/jpeg'` request header but I noticed that I'm not getting the right data on Salesforce side:
- request body is in JSON
- content type is `application/json`

My apex endpoint works because I can upload images with Postman. So my guess is that jsforce is doing something wrong.

Here's my client code:
```js
const options = {
    headers: {
        'Content-Type': 'image/jpeg'
    }
};
jsforce.apex.post(
    `/myEndpoint`,
    pictureBinaryData,
    options,
    (error, result) => {
        if (error) {
            console.error('Failed to upload image ', error);
        } else {
            console.info('Successfully uploaded image');
        }
    }
);
```

I found that when posting to Apex REST, the request body is always serialized to JSON regardless of content type:
https://github.com/jsforce/jsforce/blob/f043799c29e274e550d952777db404b982cb81f9/lib/api/apex.js#L44

**Comment by pozil** [comment]
Here's a workaround if someone bumps into this:
```js
const request = {
    url: `/services/apexrest/myEndpoint`,
    method: 'POST',
    headers: {
        'Content-Type': 'image/jpeg'
    },
    body: pictureBinaryData
};
jsforce.request(request);
```

**Comment by danbrycefairsailcom** [comment]
Same problem with Content-Type: `application/octet-stream`.

The base64 request body gets wrapped in double-quotes, and Salesforce returns:

> Got error response: APEX_ERROR: System.StringException: Unrecognized base64 character: "

**Comment by pozil** [comment]
Fixed by https://github.com/jsforce/jsforce/pull/947
