### ISSUE TITLE
Bulk query cannot build inner object with more than one property

### ISSUE THREAD

**Issue by adrianlukaszek1992** [jsforce/jsforce#948]
jsforce: v1.9.3
node: v10.17.0

When trying to query Product2.Name, Product2.tech_id, someOtherStuff FROM PricebookEntry conn.bulk.query resolves Product2 objects with just Name property or just tech_id.

**Comment by cristiand391** [comment]
triaging old issues...

hopefully this was org-related, if anyone experience this please file a new issue.
