### ISSUE TITLE
Where Is the Release Note For 1.9.3?

### ISSUE THREAD

**Issue by Jacob-Friesen** [jsforce/jsforce#951]
This new version seems to have fixed a vulnerability found by `npm audit` (https://github.com/jsforce/jsforce/issues/925) and shows up in NPM: https://www.npmjs.com/package/jsforce. There was a merged PR here: https://github.com/jsforce/jsforce/pull/942, but I cannot find any overview of what was changed in the releases section: https://github.com/jsforce/jsforce/releases

**Comment by stomita** [comment]
Sorry not having notes. I've just created
https://github.com/jsforce/jsforce/releases/tag/1.9.3
