### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by gohlance** [jsforce/jsforce#953]
Seems like the code is not handling concurrent calling. Anyone have thoughts around pull all fields regarding a bunch of sobject using tooling api?

connect ETIMEDOUT 13.110.34.175:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.110.34.175',
  port: 443

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529
