### ISSUE TITLE
Can I use jsforce on the Marketing Cloud's Custom activity to view Accounts or Contacts in the Marketing Cloud?

### ISSUE THREAD

**Issue by chanhos0626** [jsforce/jsforce#958]
I am currently creating a Custom Activity in the Marketing Cloud.
By the way, upload the screen of the Activity to the Heroku is in progress to operate the function.
However, I can't import the data registered in Marketing Cloud from Custom Activity, so I want to know if jsforce is available because I know jsforce.
I would be grateful if you could let me know if I just change the url to mc.exetarget.com.

**Comment by cristiand391** [comment]
closing as dup of https://github.com/jsforce/jsforce/discussions/1455
