### ISSUE TITLE
response issue.

### ISSUE THREAD

**Issue by mayankagarwal900** [jsforce/jsforce#976]
I am using this to fetch the file from salesforce using node.js.

conn.sobject('ContentVersion').record('contentVersionId').blob('VersionData').pipe(fileOut);
My files are downloading but i am not able to send response can anyone pls how we can find the response for this request.

Thanks in advance.

**Comment by cristiand391** [comment]
triaging old issues...

if you meant API requests, you can set the logLevel when creating the connection and see the URLs in the logs:
https://jsforce.github.io/jsforce/types/connection.ConnectionConfig.html
