### ISSUE TITLE
Failed to Compile after making connection

### ISSUE THREAD

**Issue by salahsaleh** [jsforce/jsforce#977]
Hello,

I am new to Salesforce and Heroku so I think I am doing something wrong. 

I installed jsforce package stating `npm i jsforce` after that I am trying to make connection to my test portal 

`public conn = new jsForce.Connection({
    loginUrl: "https://test.salesforce.com/"
  });`

When I write above code I get compiler error stating module not found. Check below error:

`Failed to compile.
./node_modules/jsforce/lib/csv.js
Module not found: Can't resolve 'core-js/modules/es6.array.filter' in 'D:\clientProjects\newTest\mynewapp\node_modules\jsforce\lib'`

When I remove connection code, application work fine. The moment I add connection code back, application throw error.

Can anyone know where I am going wrong. Below is my package.json file.

`
{
  "name": "mynewapp",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "npm": "6.4.1",
    "node": "8.11.3"
  },
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/jquery": "^2.0.54",
    "@types/jqueryui": "^1.12.10",
    "alertifyjs": "^1.13.1",
    "axios": "^0.19.0",
    "bufferutil": "^4.0.1",
    "core-js": "^3.6.1",
    "express": "^4.17.1",
    "heroku-client": "^3.1.0",
    "jquery": "^3.4.1",
    "jqueryui": "^1.11.1",
    "jsforce": "^2.0.0-alpha.7",
    "office-ui-fabric-react": "^7.78.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0",
    "typescript": "^3.7.4",
    "utf-8-validate": "^5.0.2",
    "ws": "^7.2.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/runtime-corejs2": "^7.7.7"
  }
}

`

**Comment by stomita** [comment]
@salahsaleh sorry this is caused by mistakenly published alpha version. Install ver 1.x by `npm install jsforce@1.9.4`.

**Comment by salahsaleh** [comment]
> @salahsaleh sorry this is caused by mistakenly published alpha version. Install ver 1.x by `npm install jsforce@1.9.3`.

Thanks, I realized it and installed 1.9.2. 
Working fine now.
