### ISSUE TITLE
Lambda - cannot find user home directory to store configuration files

### ISSUE THREAD

**Issue by dylandechant** [jsforce/jsforce#979]
trying to get a lambda function up and running but am running into an error just importing it into a file (not even using or calling the library)
here is the error
```json
{
    "errorType": "Error",
    "errorMessage": "cannot find user home directory to store configuration files",
    "stack": [
        "Error: cannot find user home directory to store configuration files",
        "    at getDefaultConfigFilePath (/var/task/node_modules/jsforce/lib/registry/file.js:42:11)",
        "    at new FileRegistry (/var/task/node_modules/jsforce/lib/registry/file.js:64:47)",
        "    at Object.<anonymous> (/var/task/node_modules/jsforce/lib/registry/index.js:47:98)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Module.require (internal/modules/cjs/loader.js:849:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/node_modules/jsforce/lib/jsforce.js:38:40)"
    ]
}
```

i understand the cli saves to `~/.jsforce/config.json`, but that doesn't seem to be required for non-cli usage. is there anyway to override this check?

**Comment by dylandechant** [comment]
solved:

to fix this add an environment variable to your lambda function that points it to `/tmp`
`HOME=/tmp`

**Comment by lms15** [comment]
OK thanks glad it was solved

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mayrbenjamin92** [comment]
This might not be the solution for all users of this module! The default should actually be something in the "node_modules" folder itself. What if I can't set an ENV variable?

**Comment by olup** [comment]
This is very wrong and require hacking the env variables, especially when having also a local setup. Could it be allowed to pass this path directly in some jsforce initialization params ?

**Comment by dohomi** [comment]
I also bumped into this issue while trying to use Vercel hosting. Any solution out there?

**Comment by genk1** [comment]
I solved by overriding process.env.JSFORCE_CONNECTION_REGISTRY before importing salefoce library

```
process.env.JSFORCE_CONNECTION_REGISTRY = "sfdx"
```

**Comment by NotoriousPyro** [comment]
I worked around this by creating a new `lib/jsforce/index.ts` and within it:
```typescript
import * as jsf from 'jsforce'
import { FileRegistry } from 'jsforce/lib/registry';

const jsforce = jsf.default;
(jsforce.registry as FileRegistry) = new FileRegistry({configFilePath: "/tmp/.jsforce"});

export default jsforce;
export {jsforce}

//// @ts-ignore
export * from 'jsforce'
```

Then import jsforce from it and use it:
```typescript
import jsforce from '../../../lib/jsforce'
jsforce.registry.saveConnectionConfig(...)
```

The file is created:
```
[craig.crawford@fedora salesforce-demo]$ ls -lsa /tmp | grep .jsforce
4 -rw-------.  1 craig.crawford craig.crawford  308 Oct 17 17:16 .jsforce
```

**Comment by RupertBarrow** [comment]
Hi @dohomi , did you fix this for Vercel hosting ?

**Comment by dohomi** [comment]
its too long ago 

> Hi @dohomi , did you fix this for Vercel hosting ?

I am not sure its too long ago..

**Comment by cristiand391** [comment]
this should be fixed in v3:

for reference:
#1336 fixed this and added a `console.error` for the original failure (`cannot find user home directory to store configuration files`).

**Comment by talbalelty** [comment]
For anyone working with Lambda Docker Container running Nodejs Express,
I had the same issue and I solved it by copying the package.json and not mounting.

my working dockerfile

`
FROM public.ecr.aws/lambda/nodejs:${NODE_VERSION} 

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json .

RUN npm ci --include=dev

COPY . .

CMD [ "index.handler" ]

`

**Comment by cristiand391** [comment]
This should be fixed in v3, see: https://github.com/jsforce/jsforce/discussions/1529

**Comment by watanabeshuji** [comment]
@cristiand391 
this issue is solved.
But we still see error log.
I think it is not working.

**Comment by cristiand391** [comment]
@watanabeshuji what exactly are you seeing? is your code just failing because of this?

**Comment by watanabeshuji** [comment]
@cristiand391 I run on AWS Lambda.
Process is not failed.
But I see error log at CloudWatch Logs.

`console.log()` is not good at this line.
https://github.com/jsforce/jsforce/blob/main/src/registry/index.ts#L13

![スクリーンショット 2024-07-18 6 04 42](https://github.com/user-attachments/assets/459d6e06-1cd3-49d7-b73f-8307959f6665)

**Comment by cristiand391** [comment]
@watanabeshuji got it, feel free to open a PR to make it use logger if that would solve your issue, here are some examples:
https://github.com/search?q=repo%3Ajsforce%2Fjsforce%20%2FgetLogger%2F&type=code

**Comment by watanabeshuji** [comment]
@cristiand391  Is the module name of Logger 'registry' ?

**Comment by cristiand391** [comment]
> @cristiand391  Is the module name of Logger 'registry' ?

@watanabeshuji yes
