### ISSUE TITLE
JSForce subscriptions to Platform Events failing in Spring 20 Sandboxes

### ISSUE THREAD

**Issue by GreenerPasturesConsulting** [jsforce/jsforce#982]
I noticed something strange and was hoping somebody else has seen it.  My team is using jsforce 1.9.2 in a node v12.13.0 app.  We subscribe to multiple platform events.  Code working fine in Winter '20 salesforce environments but not working in any Spring '20 salesforce sandboxes.  Anybody else can confirm this behavior?  Are we maybe on a dated version of jsforce and need to upgrade or is this as it seems an issue with how subscriptions to platform events are working only on Spring '20

conn.streaming.topic("/event/Building_Created__e").subscribe(function(message){
    var buildingId = message.payload.Building_ID__c;
    console.log("Building ID", buildingId);
  });

**Comment by bpetty-formfast** [comment]
I logged a similar ticket: https://github.com/jsforce/jsforce/issues/1058
How are you authenticating?  If you are using access tokens, could you try username/pwd?  I wonder if these issues are related.

**Comment by cristiand391** [comment]
I'm going to close this in favor of #1058, please follow that issue for updates.
