### ISSUE TITLE
Is jsforce not usable in CORS?

### ISSUE THREAD

**Issue by TakedaShouhei** [jsforce/jsforce#988]
CORS was applied suddenly in Salesforce.
Thereafter, I cannot use jsforce.
So I am in trouble.
I want you to help me.
I use bulk API.

An error below occurred.
"Access to XMLHttpRequest at 'https://XXX --develop.my.salesforce.com/services/async/42.0/job' (redirected from 'https://supporttools--develop--c.visualforce.com/services/proxy? 1579566867647.12334047822591554') from origin 'https://supporttools--develop--c.visualforce.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Is setting of Salesforce bad?
Is setting of jsforce bad?
Is jsforce not usable in CORS?

Setting of Salesforce
 1. CORS
　https://*.salesforce.com
　https://XXX--develop--c.visualforce.com
    https://XXX--develop.lightning.force.com
    https://XXX--develop.my.salesforce.com
    https://*.visual.force.com

 2. Setting of the remote site
     XXX
     XXX_mydomain

     XXX is my domain

Stting of jsforce
let conn = new jsforce.Connection({ accessToken: '{!$Api.Session_Id}', proxyUrl: '/services/proxy' });
let job = conn.bulk.createJob( object_name, bulkOp );
let batch = job.createBatch();
batch.execute( SendData );

**Comment by ChandanShankar** [comment]
Even I'm facing the same problem, did u find the solution to fix the above issue.?

**Comment by cristiand391** [comment]
Some REST APIs support CORS (you have to setup in your org), but SOAP APIs doesn't.

You can host a CORS proxy like jsforce-ajax-proxy, see: https://github.com/jsforce/jsforce-ajax-proxy

We'll add a section about this in docs.

**Comment by cristiand391** [comment]
ref: https://jsforce.github.io/document/#cors
