### ISSUE TITLE
Uploading PDF Atachment to work order

### ISSUE THREAD

**Issue by Jafesu** [jsforce/jsforce#997]
I am trying to use JSForce to upload a PDF file to a WorkOrder in SalesForce.
Here is the code I am trying to use, just don't know how to attach it to a work order ID

```
fs.readFile(pdfPath, function (err, filedata) {
                    if (err) {
                        console.error(err);
                    }
                    else {
                        var base64data = new Buffer(filedata).toString('base64');
                        jsForceConn.sobject('Attachment').create({
                            ParentId: wo,
                            Name: pdfName,
                            Body: base64data,
                            ContentType: fileType,
                        },
                            function (err, ret) {
                                if (err || !ret.success) { return console.error(err, ret); }
                                console.log('PDF Uploaded Successfully : ' + ret.id);
                                
                            });
                    }
                });

```

I feel like it is not as simple as setting the `ParentId` to the workorder id

Need help with this ASAP. Thanks

**Comment by euclas** [comment]
Hi!
Solve this?
I need the some solution.
In sequence, post email with the .PDF.

Euclides.

**Comment by ganesh2109** [comment]
@Jafesu @euclas It works for me if I do where accountId is the salesforce id of the account:
connection.sobject("Attachment").create({
        Name: 'demoAttachment.pdf',
        Body: pdfBase64,
        parentId: accountId
        }, function(err, ret) {
            if (err || !ret.success) { 
                return console.error(err, ret); 
            }
            console.log("Created record id : " + ret.id);
        });

What error are you getting?
